// UNBTECH_204B.c
// Generated by decompiling UNBTECH.exe
// using Reko decompiler version 0.12.2.0.

#include "UNBTECH.h"

struct seg204B_t * g_ptr204B0 = &g_t2657; // 000204B0
word16 g_w000E = 0x00; // 204B:000E
word16 g_w0010 = 0x00; // 204B:0010
Eq_94242 g_t0012 = // 204B:0012
	{
		0x00
	};
word16 g_w0014 = 0x00; // 204B:0014
word16 g_w0016 = 0x00; // 204B:0016
struct Eq_94258 * g_ptr0018 = null; // 204B:0018
// 204B:0048: void fn204B_0048()
// Called from:
//      fn0800_476D
void fn204B_0048()
{
	selector seg204B;
	seg204B->t0012.u1 = 0000:0020;
	seg204B->w0014 = (word16) 0000:0022;
	seg204B->w0010 = 0x10;
	seg204B->w000E = 0x00;
	seg204B->w0016 = 0x0186;
	struct Eq_94258 * cs;
	seg204B->ptr0018 = cs;
	msdos_set_interrupt_vector(0x08, &cs->t0020);
	__out<byte>(0x43, 0x36);
	__out<byte>(0x40, ~0x00);
	__out<byte>(0x40, 0x0F);
}

// 204B:0091: void fn204B_0091()
// Called from:
//      fn0800_476D
void fn204B_0091()
{
	selector seg204B;
	msdos_set_interrupt_vector(0x08, seg204B->t0012);
	__out<byte>(0x43, 0x36);
	__out<byte>(0x40, ~0x00);
	__out<byte>(0x40, ~0x00);
}

// 204B:00BD: void fn204B_00BD()
// Called from:
//      fn204B_02E4
//      fn204B_0306
void fn204B_00BD()
{
	__out<byte>(0x61, __in<byte>(0x61) | 0x03);
}

// 204B:02E4: void fn204B_02E4(Stack Eq_5 wArg04)
// Called from:
//      fn0800_476D
void fn204B_02E4(Eq_5 wArg04)
{
	struct Eq_94324 seg204B_t::* bx_20;
	if (wArg04 < 0x0D)
	{
		fn204B_00BD();
		selector seg204B;
		(seg204B->*((((&(seg204B->t0328).a0000))[0].ptr0000))[wArg04].ptr0000)();
		word16 ax_24 = (0x204B->*bx_20).w032A;
		seg204B->w0016 = ax_24;
	}
}

// 204B:0306: void fn204B_0306(Stack Eq_5 wArg04)
// Called from:
//      fn0800_476D
void fn204B_0306(Eq_5 wArg04)
{
	struct Eq_94341 seg204B_t::* bx_20;
	if (wArg04 < 0x0D)
	{
		fn204B_00BD();
		selector seg204B;
		(seg204B->*((((&(seg204B->t0332).a0000))[0].ptr0000))[wArg04].ptr0000)();
		word16 ax_24 = (0x204B->*bx_20).w0334;
		seg204B->w0016 = ax_24;
	}
}

Eq_94318 g_t0328 = // 204B:0328
	{
		
		{
		},
	};
Eq_94335 g_t0332 = // 204B:0332
	{
		
		{
		},
	};
// 204B:033C: Register word16 fn204B_033C()
// Called from:
//      fn0800_476D
word16 fn204B_033C()
{
	selector seg204B;
	if ((seg204B->w0016 ^ 0x0186) == 0x00)
		return 0x01;
	return 0x00;
}

