// UNBTECH_1F3D.c
// Generated by decompiling UNBTECH.exe
// using Reko decompiler version 0.12.2.0.

#include "UNBTECH.h"

// 1F3D:0006: Register Eq_5 fn1F3D_0006(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Register out word16 diOut, Register out (ptr16 Eq_266) dsOut)
// Called from:
//      fn0800_0000
//      fn0800_1AFD
//      fn0800_3FAE
//      fn0800_48B7
//      main
//      fn0DAB_04F9
//      fn0DAB_1AFE
//      fn0FDC_0629
//      fn11B8_16B2
//      fn135D_0004
//      fn135D_0AB6
//      fn1631_1DCC
//      fn1AE8_12C7
//      fn1CD3_0004
//      fn1F3D_0259
//      fn1F3D_086A
Eq_5 fn1F3D_0006(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, word16 & diOut, struct Eq_266 & dsOut)
{
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_25;
	word16 di_22;
	struct Eq_266 * ds_23;
	fn207F_2FDC(0x00, fp - 2, si, di, ds, wLoc06, wLoc04, out si_25, out di_22, out ds_23);
	while (true)
	{
		--wArg04;
		if (wArg04 == 0x00)
			break;
		fn207F_0B40(Mem36[ds_23:22254:selector]->t32AC);
	}
	diOut = di_22;
	dsOut = ds_23;
	return si_25;
}

// 1F3D:002F: Register word16 fn1F3D_002F(Register Eq_36 bp, Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Register out int16 siOut, Register out int16 diOut, Register out Eq_5 dsOut)
// Called from:
//      fn0800_0000
//      fn0800_2A2B
//      fn0800_3FAE
//      fn0800_476D
//      fn0800_50C8
//      main
//      fn0DAB_1AFE
//      fn0FDC_0629
//      fn11B8_0D58
//      fn183B_000A
word16 fn1F3D_002F(Eq_36 bp, Eq_5 si, Eq_5 di, Eq_5 ds, int16 & siOut, int16 & diOut, union Eq_5 & dsOut)
{
	word16 wLoc04;
	cup16 wLoc02;
	int16 si_23;
	int16 di_20;
	Eq_5 ds_21;
	fn207F_2FDC(0x00, bp, si, di, ds, wLoc04, wLoc02, out si_23, out di_20, out ds_21);
	word16 ax_42;
	if (fn207F_3BDC(ds_21) == 0x00 && Mem0[ds_21:22256:selector]->w3938 == 0x00)
		ax_42 = 0x00;
	else
		ax_42 = 0x01;
	siOut = si_23;
	diOut = di_20;
	dsOut = ds_21;
	return ax_42;
}

// 1F3D:0053: Register Eq_5 fn1F3D_0053(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Register out word16 diOut, Register out (ptr16 Eq_14786) dsOut)
// Called from:
//      fn0800_378D
//      fn0DAB_0002
//      fn0DAB_094B
//      fn0FDC_13DE
//      fn11B8_0002
//      fn11B8_0925
//      fn11B8_1762
//      fn135D_03AA
//      fn183B_000A
//      fn183B_1C1F
//      fn1CD3_0004
Eq_5 fn1F3D_0053(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, word16 & diOut, struct Eq_14786 & dsOut)
{
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	word16 si_101;
	word16 di_102;
	selector ds_103;
	fn207F_2FDC(0x00, fp - 2, si, di, ds, wLoc06, wLoc04, out si_101, out di_102, out ds_103);
	selector seg3092;
	Eq_5 si_52;
	Eq_5 di_48;
	Eq_5 ds_49;
	fn207F_3BB6(0x00, wArg04, &seg3092->t0012, 0x0A, out si_52, out di_48, out ds_49);
	Eq_5 si_73;
	word16 di_69;
	struct Eq_14786 * ds_70;
	fn1E56_03F5(si_52, di_48, ds_49, &seg3092->t0012, out si_73, out di_69, out ds_70);
	diOut = di_69;
	dsOut = ds_70;
	return si_73;
}

// 1F3D:0086: Register Eq_5 fn1F3D_0086(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Stack Eq_5 wArg06, Stack Eq_5 wArg08, Stack Eq_5 wArg0A, Stack Eq_5 wArg0C, Stack Eq_5 wArg0E, Register out word16 diOut, Register out (ptr16 Eq_5823) dsOut)
// Called from:
//      fn0800_1AFD
//      fn0800_46A7
//      main
//      fn0DAB_1AFE
//      fn1467_08A8
//      fn1CD3_0004
Eq_5 fn1F3D_0086(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, Eq_5 wArg06, Eq_5 wArg08, Eq_5 wArg0A, Eq_5 wArg0C, Eq_5 wArg0E, word16 & diOut, struct Eq_5823 & dsOut)
{
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_25;
	word16 di_22;
	struct Eq_5823 * ds_23;
	fn207F_2FDC(0x00, fp - 2, si, di, ds, wLoc06, wLoc04, out si_25, out di_22, out ds_23);
	if (ds_23->w4FBA != 0x02)
		fn207F_200E(wArg04, wArg06, wArg08, wArg0A, wArg0C, wArg0E);
	else
		fn207F_245C(0x00, 0xA800, 0x00, 0xA000, wArg08, wArg0A, wArg0C, wArg0E);
	diOut = di_22;
	dsOut = ds_23;
	return si_25;
}

// 1F3D:00D5: Register byte fn1F3D_00D5(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 dwArg04, Stack Eq_5 wArg08, Stack Eq_5 wArg0A, Stack Eq_5 wArg0C, Stack Eq_5 wArg0E, Register out cui16 siOut, Register out word16 diOut, Register out (ptr16 Eq_16609) dsOut)
// Called from:
//      fn0800_3FAE
//      fn0800_4AA6
//      fn0800_4CAC
//      fn0DAB_1AFE
//      fn1467_08A8
//      fn1543_07CB
//      fn183B_1774
//      fn1CD3_0004
//      fn1E56_07CB
//      fn1F3D_05BC
byte fn1F3D_00D5(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 dwArg04, Eq_5 wArg08, Eq_5 wArg0A, Eq_5 wArg0C, Eq_5 wArg0E, cui16 & siOut, word16 & diOut, struct Eq_16609 & dsOut)
{
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	cui16 si_22;
	word16 di_19;
	struct Eq_16609 * ds_20;
	fn207F_2FDC(0x0E, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	selector ss;
	ss->*((word32) sp_18 - 2) = wArg0E;
	ss->*((word32) sp_18 - 4) = wArg0C;
	fn207F_2127(ss->*((word32) sp_18 - 4), ss->*((word32) sp_18 - 2));
	Eq_5 wLoc0C_250 = wArg0A *s16 0x0140;
	Eq_5 ptrLoc06_255 = dwArg04;
	if (ds_20->w4FBA == 0x03)
		wLoc0C_250 = wArg0A *s16 0x0A00;
	byte ah_227 = SLICE(wArg08, byte, 8);
	Eq_5 wArg08_261 = wArg08;
	word16 bx_69;
	while (true)
	{
		word16 wLoc06_258 = (word16) ptrLoc06_255;
		word16 wLoc04_281 = SLICE(ptrLoc06_255, word16, 16);
		bx_69 = (word16) ptrLoc06_255;
		byte al_70 = *ptrLoc06_255.u5;
		if (al_70 == 0x00)
			break;
		if (al_70 == 0x0D)
		{
			Eq_5 v21_211;
			v21_211.u5 = (word16) wLoc0C_250.u2 + 320;
			ah_227 = SLICE(wArg08, byte, 8);
			wArg08_261 = wArg08;
			wLoc0C_250 = v21_211;
			if (ds_20->w4FBA == 0x03)
				wLoc0C_250.u5 = (word16) v21_211.u2 + 2240;
			ptrLoc06_255 = SEQ(wLoc04_281, wLoc06_258 + 0x01);
		}
		else
		{
			ui16 ax_92 = (SEQ(ah_227, *ptrLoc06_255.u5) & 0x7F) << 0x03;
			ptrLoc06_255 = SEQ(wLoc04_281, wLoc06_258 + 0x01);
			if (wArg08_261 > ds_20->w4FB8 - 0x01)
			{
				++ds_20->w4FBE;
				Eq_5 v27_103;
				v27_103.u5 = (word16) wLoc0C_250.u2 + 320;
				wArg08_261 = wArg08;
				wLoc0C_250 = v27_103;
				if (ds_20->w4FBA == 0x03)
					wLoc0C_250.u5 = (word16) v27_103.u2 + 2240;
			}
			wArg08_261.u5 = (word32) wArg08_261 + 1;
			if (ds_20->w4FBA == 0x00)
			{
				ss->*((word32) sp_18 - 2) = wArg08_261 << 0x01;
				ss->*((word32) sp_18 - 4) = wLoc0C_250;
				(ss->*((word32) sp_18 - 6)).u5 = ax_92 << 0x01;
				fn207F_2209(ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4), ss->*((word32) sp_18 - 2));
			}
			else if (ds_20->w4FBA == 0x01)
			{
				ss->*((word32) sp_18 - 2) = wArg08_261 << 0x02;
				ss->*((word32) sp_18 - 4) = wLoc0C_250;
				(ss->*((word32) sp_18 - 6)).u5 = ax_92 << 0x02;
				fn207F_21A8(ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4), ss->*((word32) sp_18 - 2));
			}
			else if (ds_20->w4FBA == 0x02)
			{
				ss->*((word32) sp_18 - 2) = wArg08_261;
				ss->*((word32) sp_18 - 4) = wLoc0C_250;
				(ss->*((word32) sp_18 - 6)).u5 = ax_92;
				fn207F_2251(ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4), ss->*((word32) sp_18 - 2));
			}
			else
			{
				ss->*((word32) sp_18 - 2) = wArg08_261 << 0x03;
				ss->*((word32) sp_18 - 4) = wLoc0C_250;
				(ss->*((word32) sp_18 - 6)).u5 = ax_92;
				fn207F_22A5(ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4), ss->*((word32) sp_18 - 2));
			}
			ah_227 = 0x00;
		}
	}
	siOut = si_22;
	diOut = di_19;
	dsOut = ds_20;
	return SLICE(bx_69, byte, 8);
}

// 1F3D:01FB: Register Eq_5 fn1F3D_01FB(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Stack Eq_5 wArg06, Stack Eq_5 wArg08, Stack Eq_5 wArg0A, Stack Eq_5 wArg0C, Register out Eq_5 diOut, Register out Eq_5 dsOut)
// Called from:
//      fn0800_3FAE
//      fn0800_4AA6
//      fn0800_4BC1
//      fn0DAB_174C
//      fn0DAB_1858
//      fn1467_08A8
//      fn1543_07CB
//      fn1543_0CDE
//      fn1E56_0388
//      fn1E56_07CB
Eq_5 fn1F3D_01FB(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, Eq_5 wArg06, Eq_5 wArg08, Eq_5 wArg0A, Eq_5 wArg0C, union Eq_5 & diOut, union Eq_5 & dsOut)
{
	byte bArg04 = (byte) wArg04;
	byte bArg08 = (byte) wArg08;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_108;
	Eq_5 di_104;
	Eq_5 ds_105;
	fn207F_2FDC(0x00, fp - 2, si, di, ds, wLoc06, wLoc04, out si_108, out di_104, out ds_105);
	if ((bArg04 & 0x01) == 0x00 && ((bArg08 & 0x01) != 0x00 && Mem7[ds_105:20410:word16] == 0x01))
		fn207F_08A1(wArg04, wArg06, wArg08 - wArg04 >> 0x01, wArg0A - wArg06, wArg0C);
	else
	{
		while (wArg0A >= wArg06)
		{
			wArg06.u5 = (word32) wArg06 + 1;
			si_108 = fn1F3D_03EB(si_108, di_104, ds_105, wArg06, wArg04, wArg08, wArg0C, out di_104, out ds_105);
		}
	}
	diOut = di_104;
	dsOut = ds_105;
	return si_108;
}

// 1F3D:0259: Register int16 fn1F3D_0259(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Register out Eq_5 siOut, Register out Eq_5 diOut, Register out Eq_5 dsOut)
// Called from:
//      fn0800_0000
//      fn0800_1A13
//      fn0800_2913
//      fn0800_2A2B
//      fn0800_2A4F
//      fn0800_32B3
//      fn0800_35D3
//      fn0800_378D
//      fn0800_3FAE
//      fn0800_4D57
//      main
//      fn0DAB_094B
//      fn0DAB_18E8
//      fn0DAB_1AFE
//      fn0FDC_0008
//      fn0FDC_01C0
//      fn0FDC_0629
//      fn0FDC_13DE
//      fn0FDC_15E6
//      fn0FDC_17B9
//      fn11B8_0002
//      fn11B8_0925
//      fn11B8_0D58
//      fn11B8_1762
//      fn135D_01E9
//      fn135D_02A8
//      fn135D_02D2
//      fn135D_03AA
//      fn135D_04AB
//      fn135D_055A
//      fn135D_079C
//      fn135D_0980
//      fn135D_0AB6
//      fn1431_000A
//      fn1467_0002
//      fn1467_08A8
//      fn1543_0004
//      fn1543_0CDE
//      fn1631_1057
//      fn1631_1DCC
//      fn183B_000A
//      fn183B_1C1F
//      fn183B_2231
//      fn183B_2591
//      fn1AE8_12C7
//      fn1CD3_0004
//      fn1E56_0B5E
//      fn1F3D_05BC
int16 fn1F3D_0259(Eq_5 si, Eq_5 di, Eq_5 ds, union Eq_5 & siOut, union Eq_5 & diOut, union Eq_5 & dsOut)
{
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_100;
	Eq_5 di_184;
	Eq_5 ds_188;
	fn207F_2FDC(0x04, fp - 2, si, di, ds, wLoc06, wLoc04, out si_100, out di_184, out ds_188);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	int16 ax_112;
	int16 wLoc06_153;
	if (Mem7[ds_188:22256:selector]->w3938 == 0x00)
	{
		do
		{
			ax_112 = fn207F_0B8A();
			if (Mem119[ds_188:22258:selector]->w458C == 0x00)
				goto l1F3D_0318;
			if (ax_112 == 0x68)
				ax_112 = 0x48;
			selector es_132 = Mem129[ds_188:22260:selector];
			struct Eq_90806 Eq_90817::* bx_133 = es_132->ptr39F8;
			es_132->ptr39F8 = (struct Eq_90806 Eq_90817::*) ((char *) es_132->ptr39F8 + 1);
			(Mem135[ds_188:22262:selector]->*bx_133).b00A0 = (byte) ax_112;
			wLoc06_153 = ax_112;
		} while (ax_112 == 0x48);
	}
	else
	{
		int16 ax_39;
		selector ss;
		while (true)
		{
			selector es_33 = Mem32[ds_188:22260:selector];
			struct Eq_90806 Eq_90817::* bx_34 = es_33->ptr39F8;
			es_33->ptr39F8 = (struct Eq_90806 Eq_90817::*) ((char *) es_33->ptr39F8 + 1);
			ax_39 = (int16) (Mem36[ds_188:22262:selector]->*bx_34).b00A0;
			wLoc06_153 = ax_39;
			if (ax_39 != 0x48)
				break;
			(ss->*((word32) sp_18 - 2)).u0 = 0x1E;
			si_100 = fn1F3D_0006(si_100, di_184, ds_188, ss->*((word32) sp_18 - 2), out di_184, out ds_188);
		}
		if (fn207F_3BDC(ds_188) != 0x00)
		{
			Mem42[ds_188:22264:selector]->w0152 = 0x01;
			fn207F_0B8A();
		}
		(ss->*((word32) sp_18 - 2)).u0 = 0x01;
		si_100 = fn1F3D_0006(si_100, di_184, ds_188, ss->*((word32) sp_18 - 2), out di_184, out ds_188);
		if (ax_39 == 0x50)
			Mem88[ds_188:22264:selector]->w0152 = 0x01;
	}
	ax_112 = wLoc06_153;
l1F3D_0318:
	siOut = si_100;
	diOut = di_184;
	dsOut = ds_188;
	return ax_112;
}

// 1F3D:031C: Register Eq_5 fn1F3D_031C(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Stack Eq_5 wArg06, Stack Eq_5 wArg08, Stack Eq_5 wArg0A, Stack Eq_5 wArg0C, Register out Eq_5 diOut, Register out Eq_5 dsOut)
// Called from:
//      fn0800_4BC1
//      fn1467_08A8
//      fn1AE8_12C7
Eq_5 fn1F3D_031C(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, Eq_5 wArg06, Eq_5 wArg08, Eq_5 wArg0A, Eq_5 wArg0C, union Eq_5 & diOut, union Eq_5 & dsOut)
{
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_173;
	Eq_5 di_169;
	Eq_5 ds_170;
	fn207F_2FDC(0x02, fp - 2, si, di, ds, wLoc06, wLoc04, out si_173, out di_169, out ds_170);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	if (wArg08 < wArg04)
	{
		wArg04 = wArg08;
		wArg08 = wArg04;
	}
	if (wArg0A < wArg06)
	{
		wArg06 = wArg0A;
		wArg0A = wArg06;
	}
	if (wArg04 < 0x00)
		wArg04.u0 = 0x00;
	if (wArg06 < 0x00)
		wArg06.u0 = 0x00;
	if (wArg08 < 0x00)
		wArg08.u0 = 0x00;
	if (wArg0A < 0x00)
		wArg0A.u0 = 0x00;
	if (wArg04 > 0x013F)
		wArg04.u0 = 0x013F;
	if (wArg08 > 0x013F)
		wArg08.u0 = 0x013F;
	if (wArg06 > 199)
		wArg06.u0 = 199;
	if (wArg0A > 199)
		wArg0A.u0 = 199;
	selector ss;
	if (wArg04 == wArg08)
	{
		ss->*((word32) sp_18 - 2) = wArg0C;
		ss->*((word32) sp_18 - 4) = wArg0A;
		ss->*((word32) sp_18 - 6) = wArg06;
		ss->*((word32) sp_18 - 8) = wArg04;
		fn207F_05D0(ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4), ss->*((word32) sp_18 - 2));
	}
	else
	{
		if (wArg06 != wArg0A)
			goto l1F3D_03E7;
		ss->*((word32) sp_18 - 2) = wArg0C;
		ss->*((word32) sp_18 - 4) = wArg08;
		ss->*((word32) sp_18 - 6) = wArg04;
		ss->*((word32) sp_18 - 8) = wArg06;
		si_173 = fn1F3D_03EB(si_173, di_169, ds_170, ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4), ss->*((word32) sp_18 - 2), out di_169, out ds_170);
	}
l1F3D_03E7:
	diOut = di_169;
	dsOut = ds_170;
	return si_173;
}

// 1F3D:03EB: Register Eq_5 fn1F3D_03EB(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Stack Eq_5 wArg06, Stack Eq_5 wArg08, Stack Eq_5 wArg0A, Register out word16 diOut, Register out (ptr16 Eq_90773) dsOut)
// Called from:
//      fn1F3D_01FB
//      fn1F3D_031C
Eq_5 fn1F3D_03EB(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, Eq_5 wArg06, Eq_5 wArg08, Eq_5 wArg0A, word16 & diOut, struct Eq_90773 & dsOut)
{
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	word16 di_19;
	struct Eq_90773 * ds_20;
	fn207F_2FDC(0x04, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	cui16 ax_31 = ds_20->a4FC4[0][ds_20->w4FBA];
	selector ss;
	while ((wArg06 & ax_31) != 0x00 && wArg06 <= wArg08)
	{
		ss->*((word32) sp_18 - 2) = wArg0A;
		ss->*((word32) sp_18 - 4) = wArg04;
		ss->*((word32) sp_18 - 6) = wArg04;
		ss->*((word32) sp_18 - 8) = wArg06;
		fn207F_05D0(ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4), ss->*((word32) sp_18 - 2));
		wArg06.u5 = (word32) wArg06 + 1;
	}
	if (wArg06 < wArg08)
	{
		Eq_5 ax_77 = wArg08 - wArg06;
		Eq_5 wLoc04_180 = ax_77;
		if (ds_20->w4FBA != 0x03)
			wLoc04_180 = ax_77 >> ((((ds_20->a4FD4))[0].b0000))[ds_20->w4FBA].b0000;
		if (wLoc04_180 != 0x00)
		{
			ss->*((word32) sp_18 - 2) = wArg0A;
			ss->*((word32) sp_18 - 4) = wLoc04_180;
			ss->*((word32) sp_18 - 6) = wArg04;
			ss->*((word32) sp_18 - 8) = wArg06;
			fn207F_0780(ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4), ss->*((word32) sp_18 - 2));
		}
		wArg06 = ds_20->a4FCC[0][ds_20->w4FBA] & wArg08;
	}
	while (wArg06 <= wArg08)
	{
		ss->*((word32) sp_18 - 2) = wArg0A;
		ss->*((word32) sp_18 - 4) = wArg04;
		ss->*((word32) sp_18 - 6) = wArg04;
		ss->*((word32) sp_18 - 8) = wArg06;
		fn207F_05D0(ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4), ss->*((word32) sp_18 - 2));
		wArg06.u5 = (word32) wArg06 + 1;
	}
	diOut = di_19;
	dsOut = ds_20;
	return si_22;
}

// 1F3D:049D: Register Eq_5 fn1F3D_049D(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 ptrArg04, Stack Eq_5 wArg08, Stack Eq_5 wArg0A, Register out word16 diOut, Register out (ptr16 Eq_10542) dsOut)
// Called from:
//      fn0800_2DA8
//      fn0800_320B
//      fn0800_4621
//      fn0800_46A7
//      main
//      fn0DAB_1AFE
//      fn135D_0004
//      fn135D_055A
//      fn135D_079C
//      fn1467_08A8
//      fn1CD3_0004
Eq_5 fn1F3D_049D(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 ptrArg04, Eq_5 wArg08, Eq_5 wArg0A, word16 & diOut, struct Eq_10542 & dsOut)
{
	Eq_5 wArg06_150;
	wArg06_150.u5 = SLICE(ptrArg04, word16, 16);
	word16 wArg04_146 = (word16) ptrArg04;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	word16 di_19;
	struct Eq_10542 * ds_20;
	fn207F_2FDC(0x04, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	Eq_5 es_31;
	es_31.u5 = SLICE(ptrArg04, selector, 16);
	selector ss;
	if (*ptrArg04.u5 == 0x01)
	{
		ss->*((word32) sp_18 - 2) = wArg0A;
		ss->*((word32) sp_18 - 4) = wArg08;
		ss->*((word32) sp_18 - 6) = es_31;
		ss->*((word32) sp_18 - 8) = wArg04_146 + 0x01;
		fn207F_22F8(ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4), ss->*((word32) sp_18 - 2));
	}
	else
	{
		ss->*((word32) sp_18 - 2) = wArg0A;
		ss->*((word32) sp_18 - 4) = wArg08;
		ss->*((word32) sp_18 - 6) = wArg06_150;
		ss->*((word32) sp_18 - 8) = wArg04_146 + 0x01;
		fn207F_2368(ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4), ss->*((word32) sp_18 - 2));
	}
	if (ds_20->w4FBA == 0x00)
	{
		Eq_5 wLoc06_151;
		wLoc06_151.u0 = 0x50;
		if (ds_20->w4FBC != 0x00)
			wLoc06_151.u0 = 0x04;
		(ss->*((word32) sp_18 - 2)).u0 = 16000;
		ss->*((word32) sp_18 - 4) = wLoc06_151;
		ss->*((word32) sp_18 - 6) = wArg0A;
		ss->*((word32) sp_18 - 8) = wArg08;
		ss->*((word32) sp_18 - 0x0A) = wArg0A;
		ss->*((word32) sp_18 - 0x0C) = wArg08;
		fn207F_0163(ss->*((word32) sp_18 - 0x0C), ss->*((word32) sp_18 - 0x0A), ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 + 4), ss->*((word32) sp_18 - 2));
		if (ds_20->w4FBC != 0x00)
		{
			ss->*((word32) sp_18 - 2) = wArg0A;
			ss->*((word32) sp_18 - 4) = wArg08;
			fn207F_01D7(ss->*((word32) sp_18 - 4), ss->*((word32) sp_18 - 2));
		}
	}
	diOut = di_19;
	dsOut = ds_20;
	return si_22;
}

// 1F3D:0525: Register Eq_5 fn1F3D_0525(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 ptrArg04, Register out word16 diOut, Register out (ptr16 Eq_18017) dsOut)
// Called from:
//      fn0800_46A7
//      main
//      fn0DAB_1AFE
//      fn1CD3_0004
Eq_5 fn1F3D_0525(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 ptrArg04, word16 & diOut, struct Eq_18017 & dsOut)
{
	Eq_90348 wArg06 = SLICE(ptrArg04, word16, 16);
	Eq_91405 wArg04 = (word16) ptrArg04;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	word16 di_19;
	struct Eq_18017 * ds_20;
	fn207F_2FDC(0x04, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	selector ss;
	ss->*((word32) sp_18 - 2) = si_22;
	if (ds_20->w4FBA != 0x01)
	{
		if (ds_20->w4FBA == 0x02)
		{
			(ss->*((word32) sp_18 - 4)).u5 = Mem29[ds_20:22254:selector]->t32AC;
			fn207F_0B40(ss->*((word32) sp_18 - 4));
			Eq_91405 wLoc04_153;
			wLoc04_153.u0 = 0x00;
			while (wLoc04_153 < 0x10)
			{
				Eq_90348 ax_75 = (int16) ptrArg04.u5[(uipr32) wLoc04_153];
				Eq_90348 wLoc06_156 = ax_75;
				if (ax_75 > 0x07)
					wLoc06_156 = (word16) ax_75 + 8;
				(ss->*((word32) sp_18 - 4)).u5 = wLoc06_156;
				(ss->*((word32) sp_18 - 6)).u5 = wLoc04_153;
				fn207F_022A(ss->*((word32) sp_18 + 6), ss->*((word32) sp_18 + 4));
				wLoc04_153 = (word16) wLoc04_153.u0 + 1;
			}
		}
		else if (ds_20->w4FBA == 0x03)
		{
			(ss->*((word32) sp_18 - 4)).u5 = wArg06;
			(ss->*((word32) sp_18 - 6)).u5 = wArg04;
			fn207F_0FEE();
l1F3D_05B4:
			goto l1F3D_05B7;
		}
l1F3D_05B7:
		Eq_5 si_142 = ss->*((word32) sp_18 - 2);
		diOut = di_19;
		dsOut = ds_20;
		return si_142;
	}
	else
	{
		(ss->*((word32) sp_18 - 4)).u5 = Mem29[ds_20:22254:selector]->t32AC;
		fn207F_0B40(ss->*((word32) sp_18 - 4));
		(ss->*((word32) sp_18 - 4)).u5 = wArg06;
		(ss->*((word32) sp_18 - 6)).u5 = wArg04;
		fn207F_2B45(ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4));
		goto l1F3D_05B4;
	}
}

// 1F3D:05BC: Sequence Eq_91548 fn1F3D_05BC(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Stack Eq_5 wArg06, Register out Eq_5 siOut, Register out Eq_5 diOut, Register out Eq_5 dsOut)
// Called from:
//      fn1E56_0AE5
//      fn1F3D_070A
Eq_91548 fn1F3D_05BC(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, Eq_5 wArg06, union Eq_5 & siOut, union Eq_5 & diOut, union Eq_5 & dsOut)
{
	Eq_91548 dwLoc08;
	word16 wLoc06 = SLICE(dwLoc08, word16, 16);
	mp16 fp;
	cup16 wLoc04;
	Eq_5 si_102;
	Eq_5 di_140;
	Eq_5 ds_134;
	fn207F_2FDC(0x06, fp - 2, si, di, ds, wLoc06, wLoc04, out si_102, out di_140, out ds_134);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	selector ss;
	Eq_91548 dwLoc08_224;
	if (wArg06 >= 0x00 && (wArg06 > 0x00 || wArg04 > ~0x00))
	{
		(ss->*((word32) sp_18 - 2)).u0 = 0x00;
		(ss->*((word32) sp_18 - 4)).u0 = 0x0F;
		(ss->*((word32) sp_18 - 6)).u0 = 0x0A;
		(ss->*((word32) sp_18 - 8)).u0 = 0x00;
		ss->*((word32) sp_18 - 0x0A) = ds_134;
		(ss->*((word32) sp_18 - 0x0C)).u0 = 20442;
		Eq_5 si_87;
		Eq_5 di_83;
		Eq_5 ds_84;
		fn1F3D_00D5(si_102, di_140, ds_134, ss->*((word32) sp_18 - 0x0C), ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4), ss->*((word32) sp_18 - 2), out si_87, out di_83, out ds_84);
		fn1F3D_0259(si_87, di_83, ds_84, out si_102, out di_140, out ds_134);
		dwLoc08_224 = dwLoc08;
	}
	else
	{
		ss->*((word32) sp_18 - 2) = wArg04;
		word16 dx_46;
		dwLoc08_224 = SEQ(dx_46, fn207F_3835(ds_134, ss->*((word32) sp_18 - 2), out dx_46));
	}
	if (dwLoc08_224 == 0x00)
	{
		(ss->*((word32) sp_18 - 2)).u0 = 0x00;
		(ss->*((word32) sp_18 - 4)).u0 = 0x0F;
		(ss->*((word32) sp_18 - 6)).u0 = 0x0A;
		(ss->*((word32) sp_18 - 8)).u0 = 0x00;
		ss->*((word32) sp_18 - 0x0A) = ds_134;
		(ss->*((word32) sp_18 - 0x0C)).u0 = 0x4FE9;
		Eq_5 si_151;
		Eq_5 di_147;
		Eq_5 ds_148;
		fn1F3D_00D5(si_102, di_140, ds_134, ss->*((word32) sp_18 - 0x0C), ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4), ss->*((word32) sp_18 - 2), out si_151, out di_147, out ds_148);
		fn1F3D_0259(si_151, di_147, ds_148, out si_102, out di_140, out ds_134);
	}
	siOut = si_102;
	diOut = di_140;
	dsOut = ds_134;
	return dwLoc08_224;
}

// 1F3D:063B: Register word16 fn1F3D_063B(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Register out Eq_5 siOut, Register out Eq_5 diOut, Register out Eq_5 dsOut)
// Called from:
//      fn0800_2DA8
//      fn0800_320B
//      fn0800_4621
//      fn0800_46A7
//      main
//      fn0DAB_1AFE
//      fn0FDC_1D30
//      fn135D_0004
//      fn135D_055A
//      fn135D_079C
//      fn1467_08A8
//      fn1CD3_0004
word16 fn1F3D_063B(Eq_5 si, Eq_5 di, Eq_5 ds, union Eq_5 & siOut, union Eq_5 & diOut, union Eq_5 & dsOut)
{
	struct Eq_91826 Eq_91735::* bp_93;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_130;
	Eq_5 di_132;
	Eq_5 ds_139;
	fn207F_2FDC(0x06, fp - 2, si, di, ds, wLoc06, wLoc04, out si_130, out di_132, out ds_139);
	Eq_36 bp_109 = fp - 2;
	Eq_5 sp_159;
	sp_159.u0 = <invalid>;
	struct Eq_91735 * ss;
	do
	{
		ss->*((word16) bp_109 - 4) = 0x00;
		struct Eq_91741 Eq_91735::* sp_33 = sp_159 - 2;
		(ss->*sp_33).t0000.u0 = 0x8000;
		(ss->*sp_33).ptrFFFFFFFE = (struct Eq_91735 *) (ss->*((word16) bp_109 + 8));
		(ss->*sp_33).tFFFFFFFC.u0 = (wchar_t) (ss->*((word16) bp_109 + 6));
		Eq_5 ax_42 = fn207F_33D0(ds_139, (ss->*sp_33).tFFFFFFFC.u5, (ss->*sp_33).t0000.u0, (ss->*sp_33).t0002.u0, out bp_109);
		ss->*((word16) bp_109 - 6) = ax_42;
		Eq_5 sp_116;
		sp_116.u5 = &sp_33->t0002.u0;
		if (ax_42 != ~0x00)
		{
			(ss->*sp_33).t0000.u0 = 0x02;
			(ss->*sp_33).ptrFFFFFFFE = ss;
			(ss->*sp_33).tFFFFFFFC.u0 = (wchar_t) (bp_109 - 2);
			(ss->*sp_33).tFFFFFFFA.u0 = (wchar_t) (ss->*((word16) bp_109 - 6));
			struct Eq_91777 Eq_91735::* bp_69;
			fn207F_3580(ds_139, (ss->*sp_33).tFFFFFFFA.u0, (ss->*sp_33).tFFFFFFFC.u5, (ss->*sp_33).t0000.u0, out bp_69);
			Eq_5 sp_73;
			sp_73.u0 = <invalid>;
			(ss->*sp_73.u7).ptr0006 = (struct Eq_104903 Eq_5::*) (ss->*bp_69).tFFFFFFFE.u0;
			(ss->*((word32) sp_73 + 4)).u5 = (ss->*bp_69).w000C;
			(ss->*sp_73.u7).w0002 = (ss->*bp_69).t000A.u0;
			(ss->*sp_73.u7).t0000.u1 = (ss->*bp_69).tFFFFFFFA.u0;
			uint8 al_107 = fn207F_3580(ds_139, (ss->*sp_73.u7).t0000.u1, ss->*((word32) sp_73 + 2), (ss->*sp_73.u7).ptr0006, out bp_93);
			Eq_5 sp_97;
			sp_97.u0 = <invalid>;
			(ss->*sp_97.u7).ptr0006 = (struct Eq_104903 Eq_5::*) (ss->*bp_93).tFFFFFFFA.u0;
			bp_109 = fn207F_3336(al_107, ds_139, (ss->*sp_97.u7).ptr0006);
			sp_116.u5 = &sp_97.u7->t0008.u0;
		}
		else
			ss->*((word16) bp_109 - 4) = 0x01;
		if (ss->*((word16) bp_109 - 4) != 0x00)
		{
			struct Eq_91860 Eq_91735::* sp_127 = sp_116 - 2;
			(ss->*sp_127).t0000.u0 = (wchar_t) Mem120[ds_139:22266:selector]->t014E;
			si_130 = fn0800_2913(si_130, di_132, ds_139, (ss->*sp_127).t0000.u0, out di_132, out ds_139);
		}
		sp_159 = sp_116;
	} while (ss->*((word16) bp_109 - 4) != 0x00);
	word16 bp_157 = (word16) (ss->*bp_109);
	siOut = si_130;
	diOut = di_132;
	dsOut = ds_139;
	return bp_157;
}

// 1F3D:06C3: Register Eq_5 fn1F3D_06C3(Register Eq_36 bp, Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Register out Eq_1167 diOut, Register out (ptr16 Eq_1169) dsOut)
// Called from:
//      fn0800_0000
//      fn0800_2C50
//      fn0800_3D40
//      fn0FDC_0629
//      fn0FDC_134B
//      fn135D_0004
//      fn135D_01E9
//      fn135D_055A
//      fn135D_079C
//      fn135D_0AB6
//      fn1631_032F
//      fn183B_000A
//      fn183B_1774
//      fn1AE8_000C
//      fn1AE8_12C7
//      fn1CD3_0004
Eq_5 fn1F3D_06C3(Eq_36 bp, Eq_5 si, Eq_5 di, Eq_5 ds, union Eq_1167 & diOut, struct Eq_1169 & dsOut)
{
	word16 wLoc04;
	cup16 wLoc02;
	Eq_5 si_23;
	Eq_1167 di_20;
	struct Eq_1169 * ds_21;
	fn207F_2FDC(0x00, bp, si, di, ds, wLoc04, wLoc02, out si_23, out di_20, out ds_21);
	switch (ds_21->w4FBA)
	{
	case 0x02:
		fn207F_245C(0x00, 0xAC00, 0x00, 0xA000, 0x0D, 0x00, 0x1B, 200);
		break;
	case 0x03:
		fn207F_1D3A();
		break;
	default:
		fn207F_1CB8();
		break;
	}
	diOut = di_20;
	dsOut = ds_21;
	return si_23;
}

// 1F3D:070A: Register Eq_5 fn1F3D_070A(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Stack Eq_5 wArg06, Stack Eq_5 wArg08, Stack Eq_5 wArg0A, Stack Eq_5 wArg0C, Register out word16 diOut, Register out (ptr16 Eq_22606) dsOut)
// Called from:
//      main
Eq_5 fn1F3D_070A(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, Eq_5 wArg06, Eq_5 wArg08, Eq_5 wArg0A, Eq_5 wArg0C, word16 & diOut, struct Eq_22606 & dsOut)
{
	struct Eq_22606 * ds_48;
	word16 di_47;
	word16 si_262;
	byte bArg0A_208 = (byte) wArg0A;
	byte bArg0C_207 = (byte) wArg0C;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	Eq_5 di_19;
	Eq_5 ds_20;
	fn207F_2FDC(0x08, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	selector ss;
	ss->*((word32) sp_18 - 2) = si_22;
	(ss->*((word32) sp_18 - 4)).u0 = 0x00;
	Eq_92003 ax_33 = wArg0C *s16 wArg0A;
	ss->*((word32) sp_18 - 6) = ax_33 * 0x04 + 0x04;
	Eq_89810 dx_ax_259 = fn1F3D_05BC(si_22, di_19, ds_20, ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4), out si_262, out di_47, out ds_48);
	(*((char *) ds_48->ptr56FC + 14842))[wArg04].u1 = (struct Eq_110640 *) dx_ax_259;
	struct Eq_92038 * dx_49 = SLICE(dx_ax_259, word16, 16);
	word16 ax_44 = (word16) dx_ax_259;
	if (dx_ax_259 != 0x00)
	{
		dx_ax_259.u1->b0001 = bArg0C_207 - 0x01;
		dx_ax_259.u1->b0002 = bArg0A_208;
		Eq_5 wArg0A_214 = wArg0A;
		ui16 wArg06_210;
		int16 wArg08_212;
		word16 wLoc0A_216;
		if (ds_48->w4FBA == 0x00)
		{
			wArg06_210 = wArg06 << 0x01;
			wArg08_212 = wArg08 *s16 0x50;
			wLoc0A_216 = 0x50;
		}
		else
		{
			wArg06_210 = wArg06 << 0x02;
			wArg08_212 = wArg08 *s16 0xA0;
			wArg0A_214 = wArg0A << 0x01;
			wLoc0A_216 = 0xA0;
		}
		ss->*((word32) sp_18 - 4) = wLoc0A_216 - (wArg0A_214 << 0x01);
		ss->*((word32) sp_18 - 6) = wArg0C;
		ss->*((word32) sp_18 - 8) = wArg0A_214;
		(ss->*((word32) sp_18 - 0x0A)).u5 = dx_49;
		(ss->*((word32) sp_18 - 0x0C)).u4 = ax_44 + 0x04;
		(ss->*((word32) sp_18 - 0x0E)).u0 = 0x246C;
		(ss->*((word32) sp_18 - 16)).u5 = wArg06_210 + 0x244B + wArg08_212;
		fn207F_0931(ss->*((word32) sp_18 - 16), ss->*((word32) sp_18 - 0x0E), ss->*((word32) sp_18 - 0x0C), ss->*((word32) sp_18 - 0x0A), (ss->*sp_18.u7).t0008.u1, ss->*((word32) sp_18 + 6), ss->*((word32) sp_18 - 4));
		if (ds_48->w4FBA == 0x00)
		{
			ss->*((word32) sp_18 - 4) = wLoc0A_216 - (wArg0A_214 << 0x01);
			ss->*((word32) sp_18 - 6) = wArg0C;
			ss->*((word32) sp_18 - 8) = wArg0A_214;
			(ss->*((word32) sp_18 - 0x0A)).u5 = dx_49;
			(ss->*((word32) sp_18 - 0x0C)).u4 = (ax_33 * 0x04 >> 0x01) + ax_44 + 0x04;
			(ss->*((word32) sp_18 - 0x0E)).u0 = 0x3092;
			(ss->*((word32) sp_18 - 16)).u5 = wArg06_210 + 0x4614 + wArg08_212;
			fn207F_0931(ss->*((word32) sp_18 - 16), ss->*((word32) sp_18 - 0x0E), ss->*((word32) sp_18 - 0x0C), ss->*((word32) sp_18 - 0x0A), (ss->*sp_18.u7).t0008.u1, ss->*((word32) sp_18 + 6), ss->*((word32) sp_18 - 4));
		}
	}
	Eq_5 si_191 = ss->*((word32) sp_18 - 2);
	diOut = di_47;
	dsOut = ds_48;
	return si_191;
}

// 1F3D:0814: Register word16 fn1F3D_0814(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Register out Eq_5 siOut, Register out Eq_5 diOut, Register out Eq_5 dsOut)
// Called from:
//      fn0800_48B7
//      fn0800_50C8
//      fn11B8_16B2
//      fn135D_055A
word16 fn1F3D_0814(Eq_5 si, Eq_5 di, Eq_5 ds, union Eq_5 & siOut, union Eq_5 & diOut, union Eq_5 & dsOut)
{
	struct Eq_92352 Eq_91735::* bp_92;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	Eq_5 di_19;
	Eq_5 ds_20;
	fn207F_2FDC(0x02, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	struct Eq_92242 Eq_91735::* bp_33 = fp - 2;
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	selector ss;
	while (true)
	{
		(ss->*((word32) sp_18 - 2)).u0 = 0x8000;
		(ss->*((word32) sp_18 - 4)).u5 = (ss->*bp_33).ptr0008;
		(ss->*((word32) sp_18 - 6)).u0 = (ss->*bp_33).t0006.u0;
		Eq_5 ax_41 = fn207F_33D0(ds_20, ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 2), (ss->*sp_18.u7).t0000.u1, out bp_33);
		(ss->*bp_33).tFFFFFFFE.u0 = (wchar_t) ax_41;
		if (ax_41 != ~0x00)
			break;
		ss->*((word32) sp_18 - 2) = Mem53[ds_20:22266:selector]->t014E;
		si_22 = fn0800_2913(si_22, di_19, ds_20, ss->*((word32) sp_18 - 2), out di_19, out ds_20);
	}
	(ss->*((word32) sp_18 - 2)).u0 = (ss->*bp_33).t000E.u0;
	(ss->*((word32) sp_18 - 4)).u5 = (ss->*bp_33).ptr000C;
	(ss->*((word32) sp_18 - 6)).u0 = (ss->*bp_33).t000A.u0;
	(ss->*((word32) sp_18 - 8)).u0 = (ss->*bp_33).tFFFFFFFE.u0;
	uint8 al_106 = fn207F_3580(ds_20, ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 2), out bp_92);
	Eq_5 sp_96;
	sp_96.u0 = <invalid>;
	(ss->*sp_96.u7).ptr0006 = (struct Eq_104903 Eq_5::*) (ss->*bp_92).tFFFFFFFE.u0;
	word16 bp_116 = (word16) (ss->*fn207F_3336(al_106, ds_20, (ss->*sp_96.u7).ptr0006));
	siOut = si_22;
	diOut = di_19;
	dsOut = ds_20;
	return bp_116;
}

// 1F3D:086A: Register Eq_5 fn1F3D_086A(Register Eq_36 bp, Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Register out word16 diOut, Register out (ptr16 Eq_14313) dsOut)
// Called from:
//      fn0800_378D
//      fn0DAB_094B
//      fn0DAB_18E8
//      fn0FDC_01C0
//      fn0FDC_0629
//      fn0FDC_13DE
//      fn0FDC_15E6
//      fn135D_0AB6
//      fn1431_000A
//      fn1467_0002
//      fn183B_000A
//      fn1CD3_0004
//      fn1CD3_17EA
Eq_5 fn1F3D_086A(Eq_36 bp, Eq_5 si, Eq_5 di, Eq_5 ds, word16 & diOut, struct Eq_14313 & dsOut)
{
	struct Eq_14313 * ds_51;
	word16 di_50;
	Eq_5 ds_36;
	Eq_5 di_35;
	word16 wLoc04;
	cup16 wLoc02;
	Eq_5 si_23;
	Eq_5 di_20;
	Eq_5 ds_21;
	fn207F_2FDC(0x00, bp, si, di, ds, wLoc04, wLoc02, out si_23, out di_20, out ds_21);
	Eq_5 sp_19;
	sp_19.u0 = <invalid>;
	selector ss;
	(ss->*((word32) sp_19 - 2)).u0 = 0x32;
	Eq_5 si_54 = fn0800_2A2B(bp, fn1F3D_0006(si_23, di_20, ds_21, ss->*((word32) sp_19 - 2), out di_35, out ds_36), di_35, ds_36, out di_50, out ds_51);
	diOut = di_50;
	dsOut = ds_51;
	return si_54;
}

