// UNBTECH_135D.c
// Generated by decompiling UNBTECH.exe
// using Reko decompiler version 0.12.2.0.

#include "UNBTECH.h"

// 135D:0004: Register Eq_28 fn135D_0004(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Register out Eq_5 siOut, Register out Eq_5 diOut, Register out Eq_5 dsOut)
// Called from:
//      fn0800_32B3
//      fn0FDC_0008
Eq_28 fn135D_0004(Eq_5 si, Eq_5 di, Eq_5 ds, union Eq_5 & siOut, union Eq_5 & diOut, union Eq_5 & dsOut)
{
	Eq_5 ds_338;
	Eq_5 di_337;
	Eq_5 ds_314;
	Eq_5 di_313;
	Eq_5 ds_298;
	Eq_5 di_297;
	Eq_5 ds_215;
	Eq_5 di_214;
	Eq_5 ds_187;
	Eq_5 di_186;
	Eq_5 si_190;
	Eq_5 ds_140;
	Eq_5 di_139;
	Eq_5 si_143;
	Eq_5 ds_102;
	Eq_5 di_101;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	Eq_5 di_19;
	Eq_5 ds_20;
	fn207F_2FDC(0x04, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	Eq_45802 wLoc06_440;
	wLoc06_440.u0 = 0x00;
	Eq_45802 v13_48;
	do
	{
		Mem41[Mem32[ds_20:0x54FC:selector]:wLoc06_440 + 12872:byte] = Mem32[ds_20:0x54FA:selector]:50980[wLoc06_440 * 0x7D];
		Mem41[ds_20:0x54FA:selector]:50980[wLoc06_440 * 0x7D] = ~0x00;
		v13_48 = (word16) wLoc06_440 + 1;
		wLoc06_440 = v13_48;
	} while (v13_48 < 0x04);
	int16 wLoc06_443 = 0x00;
	int16 v16_63;
	do
	{
		Mem56[ds_20:0x54FA:selector]:0xC620[wLoc06_443 * 0x11] = 0x00;
		v16_63 = wLoc06_443 + 0x01;
		wLoc06_443 = v16_63;
	} while (v16_63 < 0x08);
	Mem64[ds_20:0x54FE:selector]->tA44B.u0 = 0x0C06;
	Mem68[ds_20:0x5500:selector]->tA44D.u0 = 0xC07E;
	selector ss;
	(ss->*((word32) sp_18 - 2)).u0 = 12264;
	(ss->*((word32) sp_18 - 4)).u0 = 0x01B0;
	fn207F_00D1(ss->*((word32) sp_18 - 4), ss->*((word32) sp_18 - 2));
	(ss->*((word32) sp_18 - 2)).u0 = 0x02;
	Eq_5 si_105 = fn0800_28CC(si_22, di_19, ds_20, ss->*((word32) sp_18 - 2), out di_101, out ds_102);
	Eq_45899 wLoc06_446;
	wLoc06_446.u0 = 0x0564;
	Eq_45899 v18_121;
	do
	{
		Mem116[ds_102:0x5502:selector]->*wLoc06_446 = 0xD0;
		v18_121 = (word16) wLoc06_446 + 1;
		wLoc06_446 = v18_121;
	} while (v18_121 < ~0x0323);
	(ss->*((word32) sp_18 - 2)).u0 = 0x0E;
	(ss->*((word32) sp_18 - 4)).u0 = 0x04;
	Eq_36 bp_136 = fn0800_2DA8(si_105, di_101, ds_102, ss->*((word32) sp_18 - 2), out si_143, out di_139, out ds_140);
	ss->*((word16) bp_136 - 4) = 0x00;
	Eq_5 sp_144;
	sp_144.u0 = <invalid>;
	do
	{
		Mem156[ds_140:0x5504:selector]->*((word16) (ss->*((word16) bp_136 - 4)) + 0x09F3) = ~0x00;
		ss->*((word16) bp_136 - 4) = (word16) (ss->*((word16) bp_136 - 4)) + 1;
	} while (ss->*((word16) bp_136 - 4) < 0x03);
	Mem162[ds_140:0x5506:selector]->w4FBC = 0x01;
	(ss->*sp_144.u7).w0002 = 0x246C;
	(ss->*sp_144.u7).t0000.u1 = 0x244B;
	ss->*((word32) sp_144 - 2) = ds_140;
	(ss->*((word32) sp_144 - 4)).u0 = 0x2068;
	Eq_36 bp_183 = fn1F3D_063B(si_143, di_139, ds_140, out si_190, out di_186, out ds_187);
	Eq_5 sp_191;
	sp_191.u0 = <invalid>;
	(ss->*sp_191.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x3092;
	(ss->*((word32) sp_191 + 4)).u0 = 0x4614;
	(ss->*sp_191.u7).w0002 = 0x246C;
	(ss->*sp_191.u7).t0000.u1 = 0x244B;
	Eq_5 si_218 = fn1F3D_049D(si_190, di_186, ds_187, ss->*sp_191, ss->*((word32) sp_191 + 4), (ss->*sp_191.u7).ptr0006, out di_214, out ds_215);
	if (Mem210[ds_215:0x5508:selector]->w4FBA == 0x02)
	{
		(ss->*sp_191.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0xA400;
		(ss->*((word32) sp_191 + 4)).u0 = 0x3092;
		(ss->*sp_191.u7).w0002 = 0x4614;
		fn207F_0260((ss->*sp_191.u7).w0002, ss->*((word32) sp_191 + 4), (ss->*sp_191.u7).ptr0006);
	}
	Mem248[ds_215:0x550A:selector]->w3988 = 0x02;
	fn207F_1DA8();
	(ss->*sp_191.u7).ptr0006 = (struct Eq_104903 Eq_5::*) Mem250[ds_215:0x5500:selector]->tA44D;
	ss->*((word32) sp_191 + 4) = Mem264[ds_215:0x54FE:selector]->tA44B;
	fn207F_1314(ss->*((word32) sp_191 + 4), (ss->*sp_191.u7).ptr0006);
	fn207F_18EF();
	Eq_5 si_301 = fn1F3D_06C3(bp_183, si_218, di_214, ds_215, out di_297, out ds_298);
	(ss->*sp_191.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x3C;
	Eq_5 si_317 = fn1F3D_0006(si_301, di_297, ds_298, (ss->*sp_191.u7).ptr0006, out di_313, out ds_314);
	(ss->*sp_191.u7).ptr0006 = (struct Eq_104903 Eq_5::*) ~0x00;
	(ss->*((word32) sp_191 + 4)).u0 = 2429;
	(ss->*sp_191.u7).w0002 = 0x0C03;
	Eq_5 si_341 = fn135D_0AB6(si_317, di_313, ds_314, (ss->*sp_191.u7).w0002, ss->*((word32) sp_191 + 4), (ss->*sp_191.u7).ptr0006, out di_337, out ds_338);
	ss->*((word16) bp_183 - 4) = 0x00;
	do
	{
		Mem353[ds_338:0x54FA:selector]:0xC620[Mem353[ss:bp_183 + -4:word16] * 0x11] = 0x08;
		ss->*((word16) bp_183 - 4) = (word16) (ss->*((word16) bp_183 - 4)) + 1;
	} while (ss->*((word16) bp_183 - 4) < 0x08);
	(ss->*sp_191.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x17;
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	Eq_5 stackArg4;
	stackArg4.u0 = <invalid>;
	fn0FDC_0008(si_341, di_337, ds_338, stackArg4);
	ss->*((word16) bp_183 - 2) = 0x00;
	do
	{
		Eq_5 bx_390;
		bx_390.u5 = ss->*((word16) bp_183 - 2);
		if (Mem389[ds_338:0x54FA:selector]->*((word32) bx_390 + 54095) != 0x00)
		{
			(ss->*sp_191.u7).ptr0006 = (struct Eq_104903 Eq_5::*) bx_390;
			(ss->*((word32) sp_191 + 4)).u0 = 0x00;
			(ss->*sp_191.u7).w0002 = 0x00;
			si_341 = fn135D_0AB6(si_341, di_337, ds_338, (ss->*sp_191.u7).w0002, ss->*((word32) sp_191 + 4), (ss->*sp_191.u7).ptr0006, out di_337, out ds_338);
		}
		ss->*((word16) bp_183 - 2) = (word16) (ss->*((word16) bp_183 - 2)) + 1;
	} while (ss->*((word16) bp_183 - 2) < 11);
	Eq_28 bp_430 = ss->*bp_183;
	siOut = si_341;
	diOut = di_337;
	dsOut = ds_338;
	return bp_430;
}

// 135D:01E9: Register Eq_5 fn135D_01E9(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Register out ui16 diOut, Register out (ptr16 Eq_7119) dsOut)
// Called from:
//      fn0800_1C12
Eq_5 fn135D_01E9(Eq_5 si, Eq_5 di, Eq_5 ds, ui16 & diOut, struct Eq_7119 & dsOut)
{
	Eq_5 ds_124;
	Eq_5 di_123;
	Eq_5 ds_111;
	Eq_5 di_110;
	Eq_5 ds_98;
	Eq_5 di_97;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	Eq_5 di_19;
	Eq_5 ds_20;
	fn207F_2FDC(0x06, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	selector ss;
	ss->*((word32) sp_18 - 2) = si_22;
	int16 wLoc04_178 = 0x0A10;
	int16 wLoc06_179 = 0x00;
	Eq_5 ax_40;
	int16 v18_55;
	do
	{
		Eq_46307 wLoc08_180;
		wLoc08_180.u0 = 0x00;
		Eq_46307 v14_49;
		do
		{
			ax_40 = wLoc06_179 *s 0x03;
			Mem38[ds_20:0x550C:selector]->*((word16) ((word16) wLoc08_180 + wLoc04_178) + 0x0000101D) = (word16) ((word16) wLoc08_180 + 8380)[wLoc06_179].b0000;
			v14_49 = (word16) wLoc08_180 + 1;
			wLoc08_180 = v14_49;
		} while (v14_49 < 0x03);
		v18_55 = wLoc06_179 + 0x01;
		wLoc04_178 += 0x08;
		wLoc06_179 = v18_55;
	} while (v18_55 < 0x06);
	ss->*((word32) sp_18 - 4) = Mem56[ds_20:0x5500:selector]->tA44D;
	ss->*((word32) sp_18 - 6) = Mem64[ds_20:0x54FE:selector]->tA44B;
	fn207F_1314(ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4));
	fn207F_18EF();
	Eq_5 si_127 = fn1CD3_17C6(fp - 2, fn1F3D_06C3(fp - 2, fn0800_051B(ax_40, di_19, ds_20, out di_97, out ds_98), di_97, ds_98, out di_110, out ds_111), di_110, ds_111, out di_123, out ds_124);
	Eq_5 sp_128;
	sp_128.u0 = <invalid>;
	ss->*((word32) sp_128 - 2) = ds_124;
	(ss->*((word32) sp_128 - 4)).u0 = 0x2075;
	Eq_5 di_143;
	Eq_5 ds_144;
	word16 si_195;
	ui16 di_158;
	struct Eq_7119 * ds_159;
	fn1F3D_0259(fn1CD3_17EA(si_127, di_123, ds_124, ss->*((word32) sp_128 - 4), ss->*((word32) sp_128 - 2), out di_143, out ds_144), di_143, ds_144, out si_195, out di_158, out ds_159);
	Mem139[ds_159:0x550E:selector]->wD55C = 0x01;
	Eq_5 si_170;
	si_170.u5 = (ss->*sp_128.u7).t0000.u1;
	diOut = di_158;
	dsOut = ds_159;
	return si_170;
}

// 135D:0288: void fn135D_0288(Register Eq_36 bp, Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds)
// Called from:
//      fn0800_1C12
void fn135D_0288(Eq_36 bp, Eq_5 si, Eq_5 di, Eq_5 ds)
{
	word16 wLoc04;
	cup16 wLoc02;
	Eq_5 si_23;
	Eq_5 di_20;
	Eq_5 ds_21;
	fn207F_2FDC(0x00, bp, si, di, ds, wLoc04, wLoc02, out si_23, out di_20, out ds_21);
	if (Mem0[ds_21:0x54FA:selector]->bD34B == 0x00)
		fn0FDC_0008(si_23, di_20, ds_21, 22);
}

// 135D:02A8: Register Eq_5 fn135D_02A8(Register Eq_36 bp, Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Register out ui16 diOut, Register out (ptr16 Eq_7415) dsOut)
// Called from:
//      fn0800_1C12
Eq_5 fn135D_02A8(Eq_36 bp, Eq_5 si, Eq_5 di, Eq_5 ds, ui16 & diOut, struct Eq_7415 & dsOut)
{
	Eq_5 ds_33;
	Eq_5 di_32;
	word16 wLoc04;
	cup16 wLoc02;
	Eq_5 si_23;
	Eq_5 di_20;
	Eq_5 ds_21;
	fn207F_2FDC(0x00, bp, si, di, ds, wLoc04, wLoc02, out si_23, out di_20, out ds_21);
	Eq_5 si_36 = fn1CD3_17C6(bp, si_23, di_20, ds_21, out di_32, out ds_33);
	Eq_5 sp_37;
	sp_37.u0 = <invalid>;
	selector ss;
	ss->*((word32) sp_37 - 2) = ds_33;
	(ss->*((word32) sp_37 - 4)).u0 = 8398;
	Eq_5 di_52;
	Eq_5 ds_53;
	Eq_5 si_71;
	ui16 di_67;
	struct Eq_7415 * ds_68;
	fn1F3D_0259(fn1CD3_17EA(si_36, di_32, ds_33, ss->*((word32) sp_37 - 4), ss->*((word32) sp_37 - 2), out di_52, out ds_53), di_52, ds_53, out si_71, out di_67, out ds_68);
	Mem48[ds_68:0x550E:selector]->wD55C = 0x01;
	diOut = di_67;
	dsOut = ds_68;
	return si_71;
}

// 135D:02D2: Register Eq_5 fn135D_02D2(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Stack Eq_5 wArg06, Register out Eq_5 diOut, Register out Eq_5 dsOut)
// Called from:
//      fn0800_1C12
Eq_5 fn135D_02D2(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, Eq_5 wArg06, union Eq_5 & diOut, union Eq_5 & dsOut)
{
	Eq_5 ds_48;
	Eq_5 di_47;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_132;
	Eq_5 di_119;
	Eq_5 ds_120;
	fn207F_2FDC(0x00, fp - 2, si, di, ds, wLoc06, wLoc04, out si_132, out di_119, out ds_120);
	if (((word32) wArg04 + 1 & 0x7E) == 0x4E && ((wArg06 & 0x7E) >= 0x0C && (wArg06 & 0x7E) <= 0x11))
	{
		Eq_5 si_51 = fn1CD3_17C6(fp - 2, si_132, di_119, ds_120, out di_47, out ds_48);
		Eq_5 sp_52;
		sp_52.u0 = <invalid>;
		selector ss;
		ss->*((word32) sp_52 - 2) = ds_48;
		(ss->*((word32) sp_52 - 4)).u0 = 0x2113;
		Eq_5 di_67;
		Eq_5 ds_68;
		fn1F3D_0259(fn1CD3_17EA(si_51, di_47, ds_48, ss->*((word32) sp_52 - 4), ss->*((word32) sp_52 - 2), out di_67, out ds_68), di_67, ds_68, out si_132, out di_119, out ds_120);
		Mem63[ds_120:0x54FA:selector]->bD34C = 0x01;
		Mem94[ds_120:0x550E:selector]->wD55C = 1;
	}
	diOut = di_119;
	dsOut = ds_120;
	return si_132;
}

// 135D:0327: Register Eq_5 fn135D_0327(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Register out word16 diOut, Register out (ptr16 Eq_15333) dsOut)
// Called from:
//      fn0800_3D40
Eq_5 fn135D_0327(Eq_5 si, Eq_5 di, Eq_5 ds, word16 & diOut, struct Eq_15333 & dsOut)
{
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	word16 di_19;
	struct Eq_15333 * ds_20;
	fn207F_2FDC(0x04, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	Eq_46604 wLoc06_73;
	wLoc06_73.u0 = 0x00;
	while (wLoc06_73 < 0xFA)
	{
		byte al_40 = (byte) (Mem31[ds_20:0x5510:selector]->*((word16) wLoc06_73 + 8541));
		if (Mem42[ds_20:0x54FA:selector]->bD34E != 0x00)
		{
			Mem42[ds_20:0x5510:selector]->*((word16) wLoc06_73 + 8541) = Mem42[ds_20:0x5512:selector]->*((word16) wLoc06_73 + 9041);
			Mem58[ds_20:0x5512:selector]->*((word16) wLoc06_73 + 9041) = al_40;
		}
		else
		{
			Mem42[ds_20:0x5510:selector]->*((word16) wLoc06_73 + 8541) = Mem42[ds_20:0x5514:selector]->*((word16) wLoc06_73 + 0x00002257);
			Mem50[ds_20:0x5514:selector]->*((word16) wLoc06_73 + 0x00002257) = al_40;
		}
		wLoc06_73 = (word16) wLoc06_73 + 1;
	}
	diOut = di_19;
	dsOut = ds_20;
	return si_22;
}

// 135D:03AA: Register Eq_5 fn135D_03AA(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Stack Eq_5 wArg06, Register out Eq_5 diOut, Register out Eq_5 dsOut)
// Called from:
//      fn0800_1C12
Eq_5 fn135D_03AA(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, Eq_5 wArg06, union Eq_5 & diOut, union Eq_5 & dsOut)
{
	Eq_5 ds_194;
	Eq_5 di_193;
	Eq_5 ds_70;
	Eq_5 di_69;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	Eq_5 di_108;
	Eq_5 ds_109;
	fn207F_2FDC(0x02, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_108, out ds_109);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	selector ss;
	ss->*((word32) sp_18 - 2) = si_22;
	Eq_5 sp_271 = sp_18 - 2;
	Eq_5 ax_32 = (word32) wArg04 + 1 & 0x7F;
	Eq_46696 wLoc04_285;
	wLoc04_285.u0 = 0x00;
	while (true)
	{
		byte bLoc04_290 = (byte) wLoc04_285;
		if (wLoc04_285 >= 33)
			break;
		if ((int16) (ds_109->*((word16) wLoc04_285 + 8688)) == (wArg06 & 0x7F))
		{
			Eq_5 ax_57;
			ax_57.u2 = (int16) (ds_109->*((word16) wLoc04_285 + 8654));
			if (ax_32 >= ax_57 && ax_32 < (word16) ax_57.u2 + 3)
			{
				Eq_5 si_73 = fn1CD3_17C6(fp - 2, ax_57, di_108, ds_109, out di_69, out ds_70);
				Eq_5 sp_74;
				sp_74.u0 = <invalid>;
				if (Mem42[ds_70:0x5516:selector]->*((word16) wLoc04_285 + 17886) == 0x00)
				{
					ss->*((word32) sp_74 - 2) = ds_70;
					(ss->*((word32) sp_74 - 4)).u0 = 8583;
					Eq_5 si_130;
					Eq_5 di_126;
					Eq_5 ds_127;
					fn1E56_03F5(si_73, di_69, ds_70, ss->*((word32) sp_74 - 4), out si_130, out di_126, out ds_127);
					int16 ax_139 = (int16) (ds_127->*((word16) wLoc04_285 + 0x00002212));
					(ss->*((word32) sp_74 - 2)).u0 = (*((word32) ds_127 + 8758))[ax_139].u0;
					(ss->*((word32) sp_74 - 4)).u0 = (*((word32) ds_127 + 0x00002234))[ax_139].u0;
					Eq_5 si_157;
					Eq_5 di_153;
					Eq_5 ds_154;
					fn1E56_03F5(si_130, di_126, ds_127, ss->*((word32) sp_74 - 4), out si_157, out di_153, out ds_154);
					ss->*((word32) sp_74 - 2) = ds_154;
					(ss->*((word32) sp_74 - 4)).u0 = 0x21B2;
					Eq_5 si_177;
					Eq_5 di_173;
					Eq_5 ds_174;
					fn1E56_03F5(si_157, di_153, ds_154, ss->*((word32) sp_74 - 4), out si_177, out di_173, out ds_174);
					(ss->*((word32) sp_74 - 2)).u5 = (word16) wLoc04_285 + 1;
					Eq_5 si_197 = fn1F3D_0053(si_177, di_173, ds_174, ss->*((word32) sp_74 - 2), out di_193, out ds_194);
					ss->*((word32) sp_74 - 2) = ds_194;
					(ss->*((word32) sp_74 - 4)).u0 = 8633;
					Eq_5 si_218;
					Eq_5 di_214;
					Eq_5 ds_215;
					fn1E56_03F5(si_197, di_193, ds_194, ss->*((word32) sp_74 - 4), out si_218, out di_214, out ds_215);
					(ss->*((word32) sp_74 - 2)).u0 = 0x01;
					word16 si_333;
					if (fn0800_1A13(si_218, di_214, ds_215, ss->*((word32) sp_74 - 2), out si_333, out di_108, out ds_109) != 0x00)
						(&Mem228[ds_109:0x54FA:selector]->bD347)[(int16) (ds_109->*((word16) wLoc04_285 + 0x00002212))] = bLoc04_290;
				}
				else
				{
					ss->*((word32) sp_74 - 2) = ds_70;
					(ss->*((word32) sp_74 - 4)).u0 = 0x215D;
					Eq_5 di_93;
					Eq_5 ds_94;
					word16 si_332;
					fn1F3D_0259(fn1CD3_17EA(si_73, di_69, ds_70, ss->*((word32) sp_74 - 4), ss->*((word32) sp_74 - 2), out di_93, out ds_94), di_93, ds_94, out si_332, out di_108, out ds_109);
				}
				Mem260[ds_109:0x550E:selector]->wD55C = 0x01;
				sp_271 = sp_74;
			}
		}
		wLoc04_285 = (word16) wLoc04_285 + 1;
	}
	Eq_5 si_46;
	si_46.u5 = (ss->*sp_271.u7).t0000.u1;
	diOut = di_108;
	dsOut = ds_109;
	return si_46;
}

// 135D:04AB: void fn135D_04AB(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Stack Eq_5 wArg06)
// Called from:
//      fn0800_1C12
void fn135D_04AB(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, Eq_5 wArg06)
{
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_25;
	Eq_5 di_22;
	Eq_5 ds_23;
	fn207F_2FDC(0x00, fp - 2, si, di, ds, wLoc06, wLoc04, out si_25, out di_22, out ds_23);
	Eq_5 sp_21;
	sp_21.u0 = <invalid>;
	cui16 ax_33 = (word32) wArg04 + 1 & 0x7E;
	if (((wArg06 & 0x7E) != 0x04 || ax_33 != 0x04) && (ax_33 != 0x02 || (wArg06 & 0x7E) != 0x0E))
		return;
	Eq_5 si_113;
	Eq_5 di_109;
	Eq_5 ds_110;
	Eq_5 sp_114;
	Eq_5 ax_121;
	selector ss;
	if (Mem36[ds_23:0x54FA:selector]->bD34C == 0x00)
	{
		si_113 = fn1CD3_17C6(fp - 2, si_25, di_22, ds_23, out di_109, out ds_110);
		sp_114.u0 = <invalid>;
		ax_121.u0 = 0x2240;
	}
	else if (Mem36[ds_23:0x54FA:selector]->bD34A != 0x01)
	{
		si_113 = fn1CD3_17C6(fp - 2, si_25, di_22, ds_23, out di_109, out ds_110);
		sp_114.u0 = <invalid>;
		ax_121.u0 = 0x2275;
	}
	else
	{
		if (Mem36[ds_23:0x54FA:selector]->bD34D != 0x00)
		{
			(ss->*((word32) sp_21 - 2)).u5 = 0x19;
			// Failed to bind call argument.
			// Please report this issue at https://github.com/uxmal/reko
			Eq_5 stackArg4;
			stackArg4.u0 = <invalid>;
			fn0FDC_0008(si_25, di_22, ds_23, stackArg4);
			Mem89[ds_23:0x550E:selector]->wD55C = 0x01;
			Mem103[ds_23:0x5518:selector]->w01A8 = 0x01;
			return;
		}
		si_113 = fn1CD3_17C6(fp - 2, si_25, di_22, ds_23, out di_109, out ds_110);
		sp_114.u0 = <invalid>;
		ax_121.u0 = 0x228B;
	}
	struct Eq_46985 Eq_46987::* sp_139 = sp_114 - 2;
	(ss->*sp_139).t0000.u0 = (wchar_t) ds_110;
	(ss->*sp_139).tFFFFFFFE.u0 = (wchar_t) ax_121;
	Eq_5 di_152;
	Eq_5 ds_153;
	word16 si_236;
	word16 di_237;
	struct Eq_47015 * ds_168;
	fn1F3D_0259(fn1CD3_17EA(si_113, di_109, ds_110, (ss->*sp_139).tFFFFFFFE.u0, (ss->*sp_139).t0000.u0, out di_152, out ds_153), di_152, ds_153, out si_236, out di_237, out ds_168);
	Mem145[ds_168:0x550E:selector]->wD55C = 0x01;
}

// 135D:055A: void fn135D_055A(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Stack Eq_5 wArg06)
// Called from:
//      fn0800_1C12
void fn135D_055A(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, Eq_5 wArg06)
{
	Eq_5 ds_347;
	Eq_5 di_346;
	Eq_5 si_350;
	Eq_5 ds_270;
	Eq_5 di_269;
	Eq_5 ds_242;
	Eq_5 di_241;
	Eq_5 si_245;
	Eq_5 ds_197;
	Eq_5 di_196;
	Eq_5 ds_125;
	Eq_5 di_124;
	Eq_5 ds_72;
	Eq_5 di_71;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	Eq_5 di_19;
	Eq_5 ds_20;
	fn207F_2FDC(0x08, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	cui16 ax_30 = (word32) wArg04 + 1 & 0x7E;
	selector ss;
	if (ax_30 == 0x7C && (wArg06 & 0x7E) == 0x04)
	{
		(ss->*((word32) sp_18 - 2)).u0 = 0x18;
		// Failed to bind call argument.
		// Please report this issue at https://github.com/uxmal/reko
		Eq_5 stackArg4;
		stackArg4.u0 = <invalid>;
		fn0FDC_0008(si_22, di_19, ds_20, stackArg4);
		Mem41[ds_20:0x54FA:selector]->bD34D = 0x01;
		Mem53[ds_20:0x550E:selector]->wD55C = 1;
	}
	if (ax_30 == 0x48 && (wArg06 & 0x7E) == 0x38)
	{
		Eq_5 si_75 = fn1CD3_17C6(fp - 2, si_22, di_19, ds_20, out di_71, out ds_72);
		Mem59[ds_72:0x550E:selector]->wD55C = 0x01;
		Eq_5 sp_76;
		sp_76.u0 = <invalid>;
		if (Mem84[ds_72:0x54FA:selector]->bD34A == 0x01)
		{
			ss->*((word32) sp_76 - 2) = ds_72;
			(ss->*((word32) sp_76 - 4)).u0 = 0x22C7;
			Eq_5 di_474;
			Eq_5 ds_475;
			word16 si_565;
			word16 di_566;
			selector ds_567;
			fn1F3D_0259(fn1CD3_17EA(si_75, di_71, ds_72, ss->*((word32) sp_76 - 4), ss->*((word32) sp_76 - 2), out di_474, out ds_475), di_474, ds_475, out si_565, out di_566, out ds_567);
		}
		else
		{
			ss->*((word32) sp_76 - 2) = ds_72;
			(ss->*((word32) sp_76 - 4)).u0 = 0x22E8;
			Eq_5 di_96;
			Eq_5 ds_97;
			Eq_5 si_115;
			Eq_5 di_111;
			Eq_5 ds_112;
			fn1F3D_0259(fn1CD3_17EA(si_75, di_71, ds_72, ss->*((word32) sp_76 - 4), ss->*((word32) sp_76 - 2), out di_96, out ds_97), di_96, ds_97, out si_115, out di_111, out ds_112);
			Eq_5 si_128 = fn1E56_0388(fp - 2, si_115, di_111, ds_112, out di_124, out ds_125);
			Eq_5 sp_129;
			sp_129.u0 = <invalid>;
			ss->*((word32) sp_129 - 2) = ds_125;
			(ss->*((word32) sp_129 - 4)).u0 = 9000;
			Eq_5 di_143;
			Eq_5 ds_144;
			Eq_5 si_162;
			Eq_5 di_158;
			Eq_5 ds_159;
			fn1F3D_0259(fn1CD3_17EA(si_128, di_124, ds_125, ss->*((word32) sp_129 - 4), ss->*((word32) sp_129 - 2), out di_143, out ds_144), di_143, ds_144, out si_162, out di_158, out ds_159);
			Mem139[ds_159:0x551A:selector]->w015A = 0x01;
			Mem169[ds_159:0x54FE:selector]->tA44B.u0 = 0x0C04;
			Mem171[ds_159:0x5500:selector]->tA44D.u0 = 0xC022;
			(ss->*((word32) sp_129 - 2)).u0 = 12264;
			(ss->*((word32) sp_129 - 4)).u0 = 464;
			fn207F_00D1(ss->*((word32) sp_129 - 4), ss->*((word32) sp_129 - 2));
			(ss->*((word32) sp_129 - 2)).u0 = 0x02;
			Eq_5 si_200 = fn0800_28CC(si_162, di_158, ds_159, ss->*((word32) sp_129 - 2), out di_196, out ds_197);
			Eq_47272 wLoc0A_520;
			wLoc0A_520.u0 = 0x0564;
			Eq_47272 v19_216;
			do
			{
				Mem211[ds_197:0x5502:selector]->*wLoc0A_520 = 0xD1;
				v19_216 = (word16) wLoc0A_520 + 1;
				wLoc0A_520 = v19_216;
			} while (v19_216 < ~0x0323);
			Mem217[ds_197:0x5506:selector]->w4FBC = 0x01;
			(ss->*((word32) sp_129 - 2)).u0 = 0x246C;
			(ss->*((word32) sp_129 - 4)).u0 = 0x244B;
			ss->*((word32) sp_129 - 6) = ds_197;
			(ss->*((word32) sp_129 - 8)).u5 = 0x2355;
			Eq_36 bp_238 = fn1F3D_063B(si_200, di_196, ds_197, out si_245, out di_241, out ds_242);
			Eq_5 sp_246;
			sp_246.u0 = <invalid>;
			(ss->*sp_246.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x3092;
			(ss->*((word32) sp_246 + 4)).u0 = 0x4614;
			(ss->*sp_246.u7).w0002 = 0x246C;
			(ss->*sp_246.u7).t0000.u1 = 0x244B;
			Eq_5 si_273 = fn1F3D_049D(si_245, di_241, ds_242, ss->*sp_246, ss->*((word32) sp_246 + 4), (ss->*sp_246.u7).ptr0006, out di_269, out ds_270);
			if (Mem265[ds_270:0x5508:selector]->w4FBA == 0x02)
			{
				(ss->*sp_246.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0xA400;
				(ss->*((word32) sp_246 + 4)).u0 = 0x3092;
				(ss->*sp_246.u7).w0002 = 0x4614;
				fn207F_0260((ss->*sp_246.u7).w0002, ss->*((word32) sp_246 + 4), (ss->*sp_246.u7).ptr0006);
			}
			ss->*((word16) bp_238 - 8) = 0x00;
			do
			{
				Eq_5 bx_308;
				bx_308.u5 = ss->*((word16) bp_238 - 8);
				Mem307[ds_270:0x551C:selector]->*((word32) bx_308 + 0x00004614) = Mem307[ds_270:0x550C:selector]->*((word32) bx_308 + 0x0000101D);
				ss->*((word16) bp_238 - 8) = (word16) (ss->*((word16) bp_238 - 8)) + 1;
			} while (ss->*((word16) bp_238 - 8) < 0x0300);
			Mem315[ds_270:0x550A:selector]->w3988 = 0x03;
			(ss->*sp_246.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x0300;
			(ss->*((word32) sp_246 + 4)).u0 = 0x246C;
			(ss->*sp_246.u7).w0002 = 0x101D;
			(ss->*sp_246.u7).t0000.u1 = (word16) ds_270;
			(ss->*((word32) sp_246 - 2)).u0 = 0x235D;
			Eq_36 bp_343 = fn1F3D_0814(si_273, di_269, ds_270, out si_350, out di_346, out ds_347);
			Mem335[ds_347:0x54FA:selector]->bD34E = 0x01;
			ss->*((word16) bp_343 - 2) = 0x90;
			ss->*((word16) bp_343 - 6) = 0x00;
			Eq_5 sp_351;
			sp_351.u0 = <invalid>;
			while (ss->*((word16) bp_343 - 6) < 0x03)
			{
				ss->*((word16) bp_343 - 4) = 0x00;
				while (ss->*((word16) bp_343 - 4) < 0x04)
				{
					byte al_461 = (byte) (ss->*((word16) bp_343 + 2));
					ss->*((word16) bp_343 - 2) = (word16) (ss->*((word16) bp_343 - 2)) + 1;
					Mem453[ds_347:0x551E:selector]->*((word16) ((ss->*((word16) bp_343 - 6) << 0x03) + ss->*((word16) bp_343 - 4)) + 0x0664) = (word16) al_461;
					ss->*((word16) bp_343 - 4) = (word16) (ss->*((word16) bp_343 - 4)) + 1;
				}
				ss->*((word16) bp_343 - 6) = (word16) (ss->*((word16) bp_343 - 6)) + 1;
			}
			fn207F_1DA8();
			(ss->*sp_351.u7).t0008.u0 = (wchar_t) Mem365[ds_347:0x5500:selector]->tA44D;
			(ss->*sp_351.u7).ptr0006 = (struct Eq_104903 Eq_5::*) Mem381[ds_347:0x54FE:selector]->tA44B;
			fn207F_1314((ss->*sp_351.u7).ptr0006, (ss->*sp_351.u7).t0008.u0);
			fn207F_18EF();
			if (Mem385[ds_347:0x5508:selector]->w4FBA == 0x00)
			{
				(ss->*sp_351.u7).t0008.u0 = 0x01;
				fn207F_0BA7((ss->*sp_351.u7).t0008.u1);
			}
			word16 di_568;
			struct Eq_47583 * ds_430;
			fn1F3D_06C3(bp_343, si_350, di_346, ds_347, out di_568, out ds_430);
			Mem439[ds_430:0x5520:selector]->w0150 = 0x8B;
		}
	}
}

// 135D:079C: Register Eq_28 fn135D_079C(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Register out Eq_5 siOut, Register out word16 diOut, Register out (ptr16 Eq_6821) dsOut)
// Called from:
//      fn0800_1C12
Eq_28 fn135D_079C(Eq_5 si, Eq_5 di, Eq_5 ds, union Eq_5 & siOut, word16 & diOut, struct Eq_6821 & dsOut)
{
	struct Eq_6821 * ds_315;
	word16 di_314;
	Eq_5 ds_197;
	Eq_5 di_196;
	Eq_5 ds_169;
	Eq_5 di_168;
	Eq_5 si_172;
	Eq_5 ds_103;
	Eq_5 di_102;
	Eq_5 ds_32;
	Eq_5 di_31;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	Eq_5 di_19;
	Eq_5 ds_20;
	fn207F_2FDC(0x02, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	Eq_5 si_35 = fn1CD3_17C6(fp - 2, si_22, di_19, ds_20, out di_31, out ds_32);
	Eq_5 sp_36;
	sp_36.u0 = <invalid>;
	selector ss;
	ss->*((word32) sp_36 - 2) = ds_32;
	(ss->*((word32) sp_36 - 4)).u0 = 0x2367;
	Eq_5 di_51;
	Eq_5 ds_52;
	Eq_5 si_70;
	Eq_5 di_66;
	Eq_5 ds_67;
	fn1F3D_0259(fn1CD3_17EA(si_35, di_31, ds_32, ss->*((word32) sp_36 - 4), ss->*((word32) sp_36 - 2), out di_51, out ds_52), di_51, ds_52, out si_70, out di_66, out ds_67);
	Mem47[ds_67:0x54FE:selector]->tA44B.u0 = 3141;
	Mem77[ds_67:0x5500:selector]->tA44D.u0 = 0xC039;
	(ss->*((word32) sp_36 - 2)).u0 = 12264;
	(ss->*((word32) sp_36 - 4)).u0 = 0x01B0;
	fn207F_00D1(ss->*((word32) sp_36 - 4), ss->*((word32) sp_36 - 2));
	(ss->*((word32) sp_36 - 2)).u0 = 0x02;
	Eq_5 si_106 = fn0800_28CC(si_70, di_66, ds_67, ss->*((word32) sp_36 - 2), out di_102, out ds_103);
	Eq_47762 wLoc04_335;
	wLoc04_335.u0 = 0x0564;
	Eq_47762 v12_122;
	do
	{
		Mem117[ds_103:0x5502:selector]->*wLoc04_335 = 0xD0;
		v12_122 = (word16) wLoc04_335 + 1;
		wLoc04_335 = v12_122;
	} while (v12_122 < ~0x0323);
	Eq_47777 wLoc04_338;
	wLoc04_338.u0 = 0x00;
	Eq_47777 v16_136;
	do
	{
		Mem129[ds_103:0x550C:selector]->*((word16) wLoc04_338 + 0x0000101D) = Mem129[ds_103:0x551C:selector]->*((word16) wLoc04_338 + 0x00004614);
		v16_136 = (word16) wLoc04_338 + 1;
		wLoc04_338 = v16_136;
	} while (v16_136 < 0x0300);
	Mem137[ds_103:0x5506:selector]->w4FBC = 0x01;
	Mem142[ds_103:0x550E:selector]->wD55C = 0x01;
	(ss->*((word32) sp_36 - 2)).u0 = 0x246C;
	(ss->*((word32) sp_36 - 4)).u0 = 0x244B;
	ss->*((word32) sp_36 - 6) = ds_103;
	(ss->*((word32) sp_36 - 8)).u5 = 0x23A5;
	Eq_36 bp_165 = fn1F3D_063B(si_106, di_102, ds_103, out si_172, out di_168, out ds_169);
	Eq_5 sp_173;
	sp_173.u0 = <invalid>;
	(ss->*sp_173.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x3092;
	(ss->*((word32) sp_173 + 4)).u0 = 0x4614;
	(ss->*sp_173.u7).w0002 = 0x246C;
	(ss->*sp_173.u7).t0000.u1 = 0x244B;
	Eq_5 si_200 = fn1F3D_049D(si_172, di_168, ds_169, ss->*sp_173, ss->*((word32) sp_173 + 4), (ss->*sp_173.u7).ptr0006, out di_196, out ds_197);
	if (Mem192[ds_197:0x5508:selector]->w4FBA == 0x02)
	{
		(ss->*sp_173.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0xA400;
		(ss->*((word32) sp_173 + 4)).u0 = 0x3092;
		(ss->*sp_173.u7).w0002 = 0x4614;
		fn207F_0260((ss->*sp_173.u7).w0002, ss->*((word32) sp_173 + 4), (ss->*sp_173.u7).ptr0006);
	}
	Mem230[ds_197:0x550A:selector]->w3988 = 0x02;
	ss->*((word16) bp_165 - 2) = 0x00;
	do
	{
		Mem238[ds_197:0x551E:selector]->*((word16) (ss->*((word16) bp_165 - 2)) + 0x0664) = ss->*((word16) bp_165 - 2) - 0x70;
		ss->*((word16) bp_165 - 2) = (word16) (ss->*((word16) bp_165 - 2)) + 1;
	} while (ss->*((word16) bp_165 - 2) < 0x40);
	fn207F_1DA8();
	(ss->*sp_173.u7).ptr0006 = (struct Eq_104903 Eq_5::*) Mem246[ds_197:0x5500:selector]->tA44D;
	ss->*((word32) sp_173 + 4) = Mem262[ds_197:0x54FE:selector]->tA44B;
	fn207F_1314(ss->*((word32) sp_173 + 4), (ss->*sp_173.u7).ptr0006);
	fn207F_18EF();
	if (Mem266[ds_197:0x5508:selector]->w4FBA == 0x00)
	{
		(ss->*sp_173.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x00;
		fn207F_0BA7(ss->*((word32) sp_173 + 6));
	}
	Eq_5 si_318 = fn1F3D_06C3(bp_165, si_200, di_196, ds_197, out di_314, out ds_315);
	Mem324[ds_315:0x54FA:selector]->bD34E = 0x00;
	Mem326[ds_315:0x5520:selector]->w0150 = 33;
	Eq_28 bp_330 = ss->*bp_165;
	siOut = si_318;
	diOut = di_314;
	dsOut = ds_315;
	return bp_330;
}

// 135D:0913: Register Eq_5 fn135D_0913(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Stack Eq_5 wArg06, Register out ui16 diOut, Register out (ptr16 Eq_6970) dsOut)
// Called from:
//      fn0800_1C12
Eq_5 fn135D_0913(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, Eq_5 wArg06, ui16 & diOut, struct Eq_6970 & dsOut)
{
	struct Eq_6970 * ds_69;
	ui16 di_68;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	Eq_5 di_19;
	Eq_5 ds_20;
	fn207F_2FDC(0x02, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	ci16 ax_30 = (word32) wArg04 + 1 & 0x7F;
	Eq_48071 v15_51 = ((wArg06 & 0x70) << 0x04) + ((wArg06 & 0x0E) << 0x02) + (((ax_30 & 0x70) << 0x02) + (ax_30 >> 0x01 & 0x07));
	selector es_54 = Mem52[ds_20:0x550C:selector];
	es_54->*((word16) v15_51 + 0x0000101D) = ((word16) (es_54->*((word16) v15_51 + 0x0000101D)) + 1 ^ 0x01) - 0x01;
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	selector ss;
	(ss->*((word32) sp_18 - 2)).u0 = 0x0F;
	Eq_5 si_72 = fn0800_19BF(si_22, di_19, ds_20, ss->*((word32) sp_18 - 2), out di_68, out ds_69);
	diOut = di_68;
	dsOut = ds_69;
	return si_72;
}

// 135D:0980: Register Eq_5 fn135D_0980(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Register out (ptr16 Eq_7079) dsOut)
// Called from:
//      fn0800_1C12
Eq_5 fn135D_0980(Eq_5 si, Eq_5 di, Eq_5 ds, struct Eq_7079 & dsOut)
{
	Eq_5 ds_153;
	Eq_5 di_152;
	Eq_5 ds_220;
	Eq_5 di_219;
	Eq_5 ds_132;
	Eq_5 di_131;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	Eq_5 di_19;
	Eq_5 ds_20;
	fn207F_2FDC(0x0A, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	word16 wLoc04_288 = 0x01;
	int16 wLoc08_289 = 0x00;
	int16 v15_46;
	do
	{
		if (((Mem32[ds_20:0x550C:selector]->*(*((word32) ds_20 + 9246))[wLoc08_289]).b101D & 0x01) != 0x00)
			wLoc04_288 = 0x00;
		v15_46 = wLoc08_289 + 0x01;
		wLoc08_289 = v15_46;
	} while (v15_46 < 0x07);
	if (wLoc04_288 != 0x00)
	{
		Eq_48162 wLoc08_296;
		wLoc08_296.u0 = 0x00;
		Eq_48162 v23_97;
		do
		{
			uint8 al_59 = (uint8) (Mem55[ds_20:0x550C:selector]->*((word16) wLoc08_296 + 0x0000101D));
			Eq_48169 ax_61;
			ax_61.u1 = (uint16) al_59;
			if (ax_61 >= 151 && (ax_61 <= 0xF0 && (al_59 & 0x01) == 0x00))
			{
				word16 wLoc0A_300 = 0x00;
				int16 wLoc0C_301 = 0x00;
				int16 v20_87;
				do
				{
					if ((*((word32) ds_20 + 9246))[wLoc0C_301].u0 == wLoc08_296)
					{
						wLoc0A_300 = 0x01;
						wLoc0C_301 = 0x08;
					}
					v20_87 = wLoc0C_301 + 0x01;
					wLoc0C_301 = v20_87;
				} while (v20_87 < 0x07);
				if (wLoc0A_300 == 0x00)
					wLoc04_288 = 0x00;
			}
			v23_97 = (word16) wLoc08_296 + 1;
			wLoc08_296 = v23_97;
		} while (v23_97 < 0x0300);
	}
	Eq_5 si_135 = fn1CD3_17C6(fp - 2, si_22, di_19, ds_20, out di_131, out ds_132);
	Eq_5 sp_136;
	sp_136.u0 = <invalid>;
	selector ss;
	Eq_5 si_176;
	Eq_5 di_172;
	Eq_5 ds_173;
	if (wLoc04_288 != 0x00)
	{
		(ss->*((word32) sp_136 - 2)).u0 = 0x10;
		Eq_5 si_223 = fn0800_19BF(si_135, di_131, ds_132, ss->*((word32) sp_136 - 2), out di_219, out ds_220);
		ss->*((word32) sp_136 - 2) = ds_220;
		(ss->*((word32) sp_136 - 4)).u0 = 0x23B2;
		si_176 = fn1CD3_17EA(si_223, di_219, ds_220, ss->*((word32) sp_136 - 4), ss->*((word32) sp_136 - 2), out di_172, out ds_173);
		Mem235[ds_173:0x54FA:selector]->bD34A = 0x01;
	}
	else
	{
		(ss->*((word32) sp_136 - 2)).u0 = 0x11;
		Eq_5 si_156 = fn0800_19BF(si_135, di_131, ds_132, ss->*((word32) sp_136 - 2), out di_152, out ds_153);
		ss->*((word32) sp_136 - 2) = ds_153;
		(ss->*((word32) sp_136 - 4)).u0 = 9225;
		si_176 = fn1CD3_17EA(si_156, di_152, ds_153, ss->*((word32) sp_136 - 4), ss->*((word32) sp_136 - 2), out di_172, out ds_173);
		Eq_48229 wLoc08_319;
		wLoc08_319.u0 = 0x00;
		Eq_48229 v22_209;
		do
		{
			selector es_190 = Mem187[ds_173:0x550C:selector];
			uint8 al_191 = (uint8) (es_190->*((word16) wLoc08_319 + 0x0000101D));
			Eq_48304 ax_193;
			ax_193.u1 = (uint16) al_191;
			if (ax_193 >= 151 && (ax_193 <= 0xF0 && (al_191 & 0x01) == 0x00))
				--es_190->*((word16) wLoc08_319 + 0x0000101D);
			v22_209 = (word16) wLoc08_319 + 1;
			wLoc08_319 = v22_209;
		} while (v22_209 < 0x0300);
	}
	word16 si_349;
	Eq_5 di_268;
	struct Eq_7079 * ds_269;
	fn1F3D_0259(si_176, di_172, ds_173, out si_349, out di_268, out ds_269);
	Mem278[ds_269:0x550E:selector]->wD55C = 0x01;
	dsOut = ds_269;
	return di_268;
}

// 135D:0AB6: Register Eq_5 fn135D_0AB6(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Stack Eq_5 wArg06, Stack Eq_5 wArg08, Register out Eq_5 diOut, Register out Eq_5 dsOut)
// Called from:
//      fn0800_1C12
//      fn135D_0004
Eq_5 fn135D_0AB6(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, Eq_5 wArg06, Eq_5 wArg08, union Eq_5 & diOut, union Eq_5 & dsOut)
{
	Eq_5 ds_449;
	Eq_5 di_448;
	Eq_5 ds_100;
	Eq_5 di_125;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	Eq_5 di_19;
	Eq_5 ds_20;
	fn207F_2FDC(22, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	selector ss;
	ss->*((word32) sp_18 - 2) = si_22;
	int16 ax_32 = (word32) wArg04 + 1 & 0x7F;
	Eq_5 sp_218 = sp_18 - 2;
	byte bArg04_665 = (byte) ax_32;
	int16 wArg06_526 = wArg06 & 0x7E;
	word16 wLoc08_528;
	Eq_5 wLoc10;
	int16 wArg04_554;
	Eq_48421 wLoc14;
	Eq_48429 wLoc0E;
	Eq_48437 wLoc16;
	if (wArg08 >= 0x00)
	{
		wLoc08_528 = 0x01;
		wLoc10 = wArg08;
		wArg04_554 = (int16) (ds_20->*((word32) wArg08 + 9338));
		wArg06_526 = (int16) (ds_20->*((word32) wArg08 + 9350));
	}
	else
	{
		wLoc08_528 = 0x00;
		Eq_5 wLoc0A_529;
		wLoc0A_529.u0 = 0x00;
		while (true)
		{
			wArg04_554 = ax_32;
			if (wLoc0A_529 >= 0x0C)
				break;
			if ((int16) (ds_20->*((word32) wLoc0A_529 + 9350)) == (wArg06 & 0x7E) && ds_20->*((word32) wLoc0A_529 + 9338) == (bArg04_665 & 0x7E))
			{
				int16 ax_57 = (int16) (ds_20->*((word32) wLoc0A_529 + 0x00002492));
				int16 ax_61 = (int16) (ds_20->*((word32) wLoc0A_529 + 9374));
				int16 ax_65 = (int16) (ds_20->*((word32) wLoc0A_529 + 0x000024AA));
				wLoc14 = ax_57 - 0x01;
				wLoc0E = ax_61 - 0x01;
				wLoc16 = ax_65 - 0x01;
				wLoc08_528 = 0x01;
				wLoc10 = wLoc0A_529;
				wLoc0A_529.u0 = 0x0C;
				if (wLoc0A_529 != 11)
				{
					selector es_74 = Mem71[ds_20:0x54FA:selector];
					if ((int16) es_74->bD347 != ax_57 - 0x01 || ((int16) es_74->bD348 != ax_61 - 0x01 || (int16) es_74->bD349 != ax_65 - 0x01))
					{
						Eq_5 si_103 = fn1CD3_17C6(fp - 2, si_22, di_19, ds_20, out di_125, out ds_100);
						Eq_5 sp_104;
						sp_104.u0 = <invalid>;
						if ((int16) Mem71[ds_100:0x54FA:selector]->bD347 != ax_57 - 0x01)
						{
							ss->*((word32) sp_104 - 2) = ds_100;
							(ss->*((word32) sp_104 - 4)).u0 = 0x242C;
							fn1E56_03F5(si_103, di_125, ds_100, ss->*((word32) sp_104 - 4), out si_103, out di_125, out ds_100);
						}
						if ((int16) Mem138[ds_100:0x54FA:selector]->bD348 != ax_61 - 0x01)
						{
							ss->*((word32) sp_104 - 2) = ds_100;
							(ss->*((word32) sp_104 - 4)).u0 = 0x2441;
							fn1E56_03F5(si_103, di_125, ds_100, ss->*((word32) sp_104 - 4), out si_103, out di_125, out ds_100);
						}
						if ((int16) Mem171[ds_100:0x54FA:selector]->bD349 != ax_65 - 0x01)
						{
							ss->*((word32) sp_104 - 2) = ds_100;
							(ss->*((word32) sp_104 - 4)).u0 = 9303;
							fn1E56_03F5(si_103, di_125, ds_100, ss->*((word32) sp_104 - 4), out si_103, out di_125, out ds_100);
						}
						Eq_5 di_213;
						Eq_5 ds_214;
						fn1F3D_0259(fn1F3D_086A(fp - 2, si_103, di_125, ds_100, out di_213, out ds_214), di_213, ds_214, out si_22, out di_19, out ds_20);
						Mem205[ds_20:0x550E:selector]->wD55C = 0x01;
						wLoc08_528 = 0x00;
						sp_218.u0 = <invalid>;
					}
				}
			}
			wLoc0A_529.u5 = (word32) wLoc0A_529 + 1;
		}
	}
	if (wLoc08_528 != 0x00)
	{
		if (wArg08 >= 0x00)
		{
			wLoc14 = (int16) (ds_20->*((word32) wLoc10 + 0x00002492)) - 0x01;
			wLoc0E = (int16) (ds_20->*((word32) wLoc10 + 9374)) - 0x01;
			wLoc16 = (int16) (ds_20->*((word32) wLoc10 + 0x000024AA)) - 0x01;
		}
		if (wLoc10 != 11)
		{
			selector es_288 = Mem279[ds_20:0x5516:selector];
			es_288->*((word16) wLoc14 + 17886) = 0x01;
			es_288->*((word16) wLoc0E + 17886) = 0x01;
			es_288->*((word16) wLoc16 + 17886) = 0x01;
		}
		else
		{
			selector es_283 = Mem279[ds_20:0x54FA:selector];
			es_283->bD347 = ~0x00;
			es_283->bD348 = ~0x00;
			es_283->bD349 = ~0x00;
		}
		(Mem296[ds_20:0x54FA:selector]->*((word32) wLoc10 + 54095)).u5 = 0x01;
		if (wArg08 == ~0x00)
		{
			struct Eq_48639 Eq_48358::* sp_309 = sp_218 - 2;
			(ss->*sp_309).t0000.u0 = 0x0A;
			fn0800_19BF(si_22, di_19, ds_20, (ss->*sp_309).t0000.u0, out di_19, out ds_20);
		}
		cui16 ax_350 = wArg04_554 >> 0x01 & 0x07;
		Eq_48634 v23_357 = ((wArg06_526 & 0x70) << 0x05) + ((wArg06_526 & 0x0E) << 0x02) + (((wArg04_554 & 0x70) << 0x02) + ax_350);
		int16 wLoc06_621 = 0x00;
		int16 v31_494;
		do
		{
			cui16 wArg04_623 = ax_350;
			Eq_48700 wLoc0C_624;
			wLoc0C_624.u0 = 0x00;
			if (wArg08 != ~0x00)
				wLoc06_621 = 0x02;
			Eq_107481 wLoc12_627[];
			wLoc12_627.u0 = 0x246E;
			Eq_48692 v28_398;
			do
			{
				Mem375[ds_20:0x550C:selector]->*((word16) (v23_357 + wLoc0C_624) + 0x0000101D) = (word16) wLoc12_627[wLoc06_621].b0000;
				cui16 v24_386 = wArg04_623 + 0x01;
				Eq_48700 v25_388 = (word16) wLoc0C_624 + 1;
				wArg04_623 = v24_386;
				wLoc0C_624 = v25_388;
				if (v24_386 == 0x08)
					wLoc0C_624 = (word16) v25_388 + 56;
				v28_398 = (word16) wLoc12_627 + 1;
				wLoc12_627 = v28_398;
			} while (v28_398 < ~0x2469);
			struct Eq_48727 Eq_48358::* sp_409 = sp_218 - 2;
			(ss->*sp_409).t0000.u0 = (wchar_t) Mem399[ds_20:0x5500:selector]->tA44D;
			(ss->*sp_409).tFFFFFFFE.u0 = (wchar_t) Mem410[ds_20:0x54FE:selector]->tA44B;
			fn207F_1314((ss->*sp_409).tFFFFFFFE.u0, (ss->*sp_409).t0000.u0);
			fn207F_18EF();
			Eq_5 si_465 = fn1F3D_06C3(fp - 2, fn0800_051B(wLoc06_621 << 0x02, di_19, ds_20, out di_448, out ds_449), di_448, ds_449, out di_19, out ds_20);
			if (wArg08 == ~0x00)
			{
				(ss->*sp_409).t0000.u0 = 0x14;
				fn1F3D_0006(si_465, di_19, ds_20, (ss->*sp_409).t0000.u0, out di_19, out ds_20);
			}
			v31_494 = wLoc06_621 + 0x01;
			wLoc06_621 = v31_494;
		} while (v31_494 < 0x03);
	}
	Eq_5 si_502;
	si_502.u5 = (ss->*sp_218.u7).t0000.u1;
	diOut = di_19;
	dsOut = ds_20;
	return si_502;
}

