// UNBTECH.globals.c
// Generated by decompiling UNBTECH.exe
// using Reko decompiler version 0.12.2.0.

#include "UNBTECH.h"

Eq_26706 g_t046C;
int16 g_w046E; // 0000046E
struct Eq_95471 * g_ptrFFFA0000; // FFFA0000
struct Eq_96161 * g_ptrFFFA4000; // FFFA4000
struct Eq_94775 * g_ptrFFFA8000; // FFFA8000
struct Eq_95582 * g_ptrFFFB8000; // FFFB8000
