// UNBTECH_0D27.c
// Generated by decompiling UNBTECH.exe
// using Reko decompiler version 0.12.2.0.

#include "UNBTECH.h"

// 0D27:000A: Register Eq_5 fn0D27_000A(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 ptrArg04, Register out word16 diOut, Register out (ptr16 Eq_21242) dsOut)
// Called from:
//      main
Eq_5 fn0D27_000A(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 ptrArg04, word16 & diOut, struct Eq_21242 & dsOut)
{
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	word16 di_19;
	struct Eq_21242 * ds_20;
	fn207F_2FDC(0x02, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	selector ss;
	ss->*((word32) sp_18 - 2) = si_22;
	word16 wLoc04_63 = 0x00;
	while (ptrArg04.u5[(uipr32) wLoc04_63] != 0x00)
	{
		(ss->*((word32) sp_18 - 4)).u2 = (int16) ptrArg04.u5[(uipr32) wLoc04_63];
		fn207F_0213(ss->*((word32) sp_18 - 4));
		++wLoc04_63;
	}
	Eq_5 si_56 = ss->*((word32) sp_18 - 2);
	diOut = di_19;
	dsOut = ds_20;
	return si_56;
}

// 0D27:0044: void main(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds)
void main(Eq_5 si, Eq_5 di, Eq_5 ds)
{
	Eq_5 ds_1816;
	Eq_5 di_1815;
	Eq_5 ds_1681;
	Eq_5 di_1680;
	Eq_5 ds_1651;
	Eq_5 di_1650;
	Eq_5 ds_1621;
	Eq_5 di_1620;
	Eq_5 ds_1591;
	Eq_5 di_1590;
	Eq_5 ds_1465;
	Eq_5 di_1464;
	Eq_5 ds_1435;
	Eq_5 di_1434;
	Eq_5 ds_1405;
	Eq_5 di_1404;
	Eq_5 ds_1375;
	Eq_5 di_1374;
	Eq_5 ds_1345;
	Eq_5 di_1344;
	Eq_5 ds_1315;
	Eq_5 di_1314;
	Eq_5 ds_1285;
	Eq_5 di_1284;
	Eq_5 ds_1255;
	Eq_5 di_1254;
	Eq_5 ds_1225;
	Eq_5 di_1224;
	Eq_5 ds_1195;
	Eq_5 di_1194;
	Eq_5 ds_1054;
	Eq_5 di_1056;
	Eq_5 ds_863;
	Eq_5 di_862;
	Eq_5 si_866;
	Eq_5 ds_817;
	Eq_5 di_816;
	Eq_5 si_820;
	word16 dx_818;
	Eq_5 ds_760;
	Eq_5 di_759;
	Eq_5 ds_686;
	Eq_5 di_685;
	Eq_5 si_689;
	word16 dx_687;
	Eq_5 ds_629;
	Eq_5 di_628;
	Eq_5 ds_560;
	Eq_5 di_559;
	Eq_5 ds_546;
	Eq_5 di_545;
	Eq_5 ds_479;
	Eq_5 di_478;
	Eq_5 ds_462;
	Eq_5 di_461;
	Eq_5 ds_430;
	Eq_5 di_429;
	Eq_5 ds_368;
	Eq_5 di_367;
	Eq_5 ds_340;
	Eq_5 di_339;
	Eq_5 si_343;
	Eq_5 ds_281;
	Eq_5 di_280;
	Eq_5 ds_263;
	Eq_5 di_262;
	Eq_5 ds_164;
	Eq_5 di_163;
	Eq_5 ds_103;
	Eq_5 di_102;
	Eq_5 ds_57;
	Eq_5 di_56;
	Eq_5 ds_37;
	Eq_5 di_36;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	Eq_5 di_19;
	Eq_5 ds_20;
	fn207F_2FDC(0x1A, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	selector ss;
	ss->*((word32) sp_18 - 2) = ds_20;
	(ss->*((word32) sp_18 - 4)).u0 = 0x0CD6;
	Eq_5 si_40 = fn0D27_000A(si_22, di_19, ds_20, ss->*((word32) sp_18 - 4), out di_36, out ds_37);
	ss->*((word32) sp_18 - 2) = ds_37;
	(ss->*((word32) sp_18 - 4)).u0 = 3370;
	Eq_5 si_60 = fn0D27_000A(si_40, di_36, ds_37, ss->*((word32) sp_18 - 4), out di_56, out ds_57);
	Eq_5 ax_73;
	do
	{
		ax_73 = fn1F3D_0259(si_60, di_56, ds_57, out si_60, out di_56, out ds_57);
		Mem86[ds_57:21512:selector]->t4FBA = ax_73;
	} while (ax_73 < 0x31 || ax_73 > 0x34);
	ss->*((word32) sp_18 - 2) = ds_57;
	(ss->*((word32) sp_18 - 4)).u0 = 3474;
	Eq_5 si_106 = fn0D27_000A(si_60, di_56, ds_57, ss->*((word32) sp_18 - 4), out di_102, out ds_103);
	Mem98[ds_103:0x540A:selector]->wD580 = 0x00;
	word16 wLoc14_2131 = 0x00;
	while (wLoc14_2131 == 0x00)
	{
		Eq_5 ax_128 = fn1F3D_0259(si_106, di_102, ds_103, out si_106, out di_102, out ds_103);
		if (ax_128 >= 0x31 && ax_128 <= 0x33)
		{
			selector es_146 = Mem141[ds_103:0x540C:selector];
			es_146->w3FFE = ax_128 - 0x31;
			if (ax_128 == 0x33)
			{
				es_146->w3FFE = 0x00;
				Mem151[ds_103:0x540A:selector]->wD580 = 0x01;
				ss->*((word32) sp_18 - 2) = ds_103;
				(ss->*((word32) sp_18 - 4)).u0 = 0x0E2C;
				Eq_5 si_167 = fn0D27_000A(si_106, di_102, ds_103, ss->*((word32) sp_18 - 4), out di_163, out ds_164);
				ss->*((word32) sp_18 - 2) = ds_164;
				(ss->*((word32) sp_18 - 4)).u0 = 0x0E78;
				Eq_5 di_183;
				Eq_5 ds_184;
				fn1F3D_0259(fn0D27_000A(si_167, di_163, ds_164, ss->*((word32) sp_18 - 4), out di_183, out ds_184), di_183, ds_184, out si_106, out di_102, out ds_103);
			}
			if (Mem209[ds_103:0x540C:selector]->w3FFE != 0x00)
			{
				ss->*((word32) sp_18 - 2) = ds_103;
				(ss->*((word32) sp_18 - 4)).u0 = 0x0DD0;
				Eq_5 di_226;
				Eq_5 ds_227;
				fn1F3D_0259(fn0D27_000A(si_106, di_102, ds_103, ss->*((word32) sp_18 - 4), out di_226, out ds_227), di_226, ds_227, out si_106, out di_102, out ds_103);
			}
			wLoc14_2131 = 0x01;
		}
	}
	selector es_255 = Mem121[ds_103:21512:selector];
	es_255->t4FBA -= 0x31;
	Eq_5 si_266 = fn0DAB_0C8F(fp - 2, si_106, di_102, ds_103, out di_262, out ds_263);
	Eq_5 sp_267;
	sp_267.u0 = <invalid>;
	(ss->*((word32) sp_267 - 2)).u0 = 0x02;
	Eq_5 si_284 = fn0800_28CC(si_266, di_262, ds_263, ss->*((word32) sp_267 - 2), out di_280, out ds_281);
	if (Mem276[ds_281:21512:selector]->t4FBA == 0x00)
	{
		(ss->*((word32) sp_267 - 2)).u0 = 0x00;
		fn207F_0BA7(ss->*((word32) sp_267 + 2));
	}
	(ss->*((word32) sp_267 - 2)).u0 = 12264;
	(ss->*((word32) sp_267 - 4)).u0 = 0x0230;
	fn207F_00D1(ss->*((word32) sp_267 - 4), ss->*((word32) sp_267 - 2));
	(ss->*((word32) sp_267 - 2)).u0 = 0x3092;
	(ss->*((word32) sp_267 - 4)).u0 = 0x4614;
	ss->*((word32) sp_267 - 6) = ds_281;
	(ss->*((word32) sp_267 - 8)).u5 = 3234;
	Eq_36 bp_336 = fn1F3D_063B(si_284, di_280, ds_281, out si_343, out di_339, out ds_340);
	Eq_5 sp_344;
	sp_344.u0 = <invalid>;
	(ss->*sp_344.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x246C;
	(ss->*((word32) sp_344 + 4)).u0 = 0x244B;
	(ss->*sp_344.u7).w0002 = 0x3092;
	(ss->*sp_344.u7).t0000.u1 = 0x4614;
	Eq_5 si_371 = fn1F3D_049D(si_343, di_339, ds_340, ss->*sp_344, ss->*((word32) sp_344 + 4), (ss->*sp_344.u7).ptr0006, out di_367, out ds_368);
	if (Mem363[ds_368:21512:selector]->t4FBA == 0x02)
	{
		(ss->*sp_344.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0xA800;
		(ss->*((word32) sp_344 + 4)).u0 = 0x246C;
		(ss->*sp_344.u7).w0002 = 0x244B;
		fn207F_0260((ss->*sp_344.u7).w0002, ss->*((word32) sp_344 + 4), (ss->*sp_344.u7).ptr0006);
	}
	Eq_5 ax_405;
	if (Mem401[ds_368:21512:selector]->t4FBA != 0x03)
		ax_405.u0 = 0x00;
	else
		ax_405.u0 = 0x10;
	(ss->*sp_344.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 12264;
	ss->*((word32) sp_344 + 4) = ax_405;
	Eq_5 si_433 = fn1F3D_0525(si_371, di_367, ds_368, ss->*((word32) sp_344 + 4), out di_429, out ds_430);
	(ss->*sp_344.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 200;
	(ss->*((word32) sp_344 + 4)).u0 = 0x28;
	(ss->*sp_344.u7).w0002 = 0x00;
	(ss->*sp_344.u7).t0000.u1 = 0x00;
	(ss->*((word32) sp_344 - 2)).u0 = 0x246C;
	(ss->*((word32) sp_344 - 4)).u0 = 0x244B;
	Eq_5 si_482 = fn0800_2A2B(bp_336, fn1F3D_0086(si_433, di_429, ds_430, ss->*((word32) sp_344 - 4), ss->*((word32) sp_344 - 2), (ss->*sp_344.u7).t0000.u1, (ss->*sp_344.u7).w0002, ss->*((word32) sp_344 + 4), (ss->*sp_344.u7).ptr0006, out di_461, out ds_462), di_461, ds_462, out di_478, out ds_479);
	ss->*((word16) bp_336 - 2) = 700;
	Eq_5 ds_2187;
	Eq_5 si_2188;
	Eq_5 di_2189;
	while (true)
	{
		Eq_5 ax_492;
		ax_492.u5 = ss->*((word16) bp_336 - 2);
		--ss->*((word16) bp_336 - 2);
		if (ax_492 == 0x00)
			break;
		(ss->*sp_344.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x01;
		ds_2187 = ds_479;
		si_2188 = si_482;
		di_2189 = di_478;
		Eq_5 di_511;
		Eq_5 ds_512;
		if (fn1F3D_002F(bp_336, fn1F3D_0006(si_2188, di_2189, ds_2187, (ss->*sp_344.u7).ptr0006, out di_511, out ds_512), di_511, ds_512, out si_482, out di_478, out ds_479) != 0x00)
			ss->*((word16) bp_336 - 2) = 0x00;
	}
	Eq_5 si_563 = fn0800_46A7(bp_336, fn0800_2A2B(bp_336, si_2188, di_2189, ds_2187, out di_545, out ds_546), di_545, ds_546, out di_559, out ds_560);
	(ss->*sp_344.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 12264;
	(ss->*((word32) sp_344 + 4)).u0 = 0x0130;
	fn207F_00D1(ss->*((word32) sp_344 + 4), (ss->*sp_344.u7).ptr0006);
	(ss->*sp_344.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x3092;
	(ss->*((word32) sp_344 + 4)).u0 = 0x4614;
	(ss->*sp_344.u7).w0002 = (word16) ds_560;
	(ss->*sp_344.u7).t0000.u1 = 0x0CAE;
	Eq_5 si_604;
	Eq_5 di_600;
	Eq_5 ds_601;
	fn1F3D_063B(si_563, di_559, ds_560, out si_604, out di_600, out ds_601);
	Eq_5 sp_605;
	sp_605.u0 = <invalid>;
	(ss->*sp_605.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x246C;
	(ss->*((word32) sp_605 + 4)).u0 = 0x244B;
	(ss->*sp_605.u7).w0002 = 0x3092;
	(ss->*sp_605.u7).t0000.u1 = 0x4614;
	Eq_5 si_632 = fn1F3D_049D(si_604, di_600, ds_601, ss->*sp_605, ss->*((word32) sp_605 + 4), (ss->*sp_605.u7).ptr0006, out di_628, out ds_629);
	if (Mem624[ds_629:21512:selector]->t4FBA == 0x02)
	{
		(ss->*sp_605.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0xA800;
		(ss->*((word32) sp_605 + 4)).u0 = 0x246C;
		(ss->*sp_605.u7).w0002 = 0x244B;
		fn207F_0260((ss->*sp_605.u7).w0002, ss->*((word32) sp_605 + 4), (ss->*sp_605.u7).ptr0006);
	}
	(ss->*sp_605.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x08;
	(ss->*((word32) sp_605 + 4)).u0 = 0x00;
	(ss->*sp_605.u7).w0002 = 0x00;
	(ss->*sp_605.u7).t0000.u1 = 0x246C;
	(ss->*((word32) sp_605 - 2)).u0 = 0x244B;
	word16 ax_682 = fn1E56_0AE5(si_632, di_628, ds_629, ss->*((word32) sp_605 - 2), (ss->*sp_605.u7).t0000.u1, (ss->*sp_605.u7).w0002, ss->*((word32) sp_605 + 4), (ss->*sp_605.u7).ptr0006, out dx_687, out si_689, out di_685, out ds_686);
	selector es_697 = Mem677[ds_686:0x540E:selector];
	es_697->w4066 = ax_682;
	es_697->w4068 = dx_687;
	(ss->*sp_605.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 12264;
	(ss->*((word32) sp_605 + 4)).u0 = 400;
	fn207F_00D1(ss->*((word32) sp_605 + 4), (ss->*sp_605.u7).ptr0006);
	(ss->*sp_605.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x3092;
	(ss->*((word32) sp_605 + 4)).u0 = 0x4614;
	(ss->*sp_605.u7).w0002 = (word16) ds_686;
	(ss->*sp_605.u7).t0000.u1 = 0x0CBB;
	Eq_5 si_735;
	Eq_5 di_731;
	Eq_5 ds_732;
	fn1F3D_063B(si_689, di_685, ds_686, out si_735, out di_731, out ds_732);
	Eq_5 sp_736;
	sp_736.u0 = <invalid>;
	(ss->*sp_736.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x246C;
	(ss->*((word32) sp_736 + 4)).u0 = 0x244B;
	(ss->*sp_736.u7).w0002 = 0x3092;
	(ss->*sp_736.u7).t0000.u1 = 0x4614;
	Eq_5 si_763 = fn1F3D_049D(si_735, di_731, ds_732, ss->*sp_736, ss->*((word32) sp_736 + 4), (ss->*sp_736.u7).ptr0006, out di_759, out ds_760);
	if (Mem755[ds_760:21512:selector]->t4FBA == 0x02)
	{
		(ss->*sp_736.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0xA800;
		(ss->*((word32) sp_736 + 4)).u0 = 0x246C;
		(ss->*sp_736.u7).w0002 = 0x244B;
		fn207F_0260((ss->*sp_736.u7).w0002, ss->*((word32) sp_736 + 4), (ss->*sp_736.u7).ptr0006);
	}
	(ss->*sp_736.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 66;
	(ss->*((word32) sp_736 + 4)).u0 = 0x00;
	(ss->*sp_736.u7).w0002 = 0x00;
	(ss->*sp_736.u7).t0000.u1 = 0x246C;
	(ss->*((word32) sp_736 - 2)).u0 = 0x244B;
	word16 ax_813 = fn1E56_0AE5(si_763, di_759, ds_760, ss->*((word32) sp_736 - 2), (ss->*sp_736.u7).t0000.u1, (ss->*sp_736.u7).w0002, ss->*((word32) sp_736 + 4), (ss->*sp_736.u7).ptr0006, out dx_818, out si_820, out di_816, out ds_817);
	selector es_828 = Mem808[ds_817:0x5410:selector];
	es_828->w4588 = ax_813;
	es_828->w458A = dx_818;
	(ss->*sp_736.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 12264;
	(ss->*((word32) sp_736 + 4)).u0 = 0x0170;
	fn207F_00D1(ss->*((word32) sp_736 + 4), (ss->*sp_736.u7).ptr0006);
	(ss->*sp_736.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x3092;
	(ss->*((word32) sp_736 + 4)).u0 = 0x4614;
	(ss->*sp_736.u7).w0002 = (word16) ds_817;
	(ss->*sp_736.u7).t0000.u1 = 0x0CC8;
	Eq_36 bp_859 = fn1F3D_063B(si_820, di_816, ds_817, out si_866, out di_862, out ds_863);
	ss->*((word16) bp_859 - 0x0A) = 0x00;
	Eq_5 sp_867;
	sp_867.u0 = <invalid>;
	selector es_875 = Mem874[ds_863:21512:selector];
	if (es_875->t4FBA == 0x00)
	{
		ss->*((word16) bp_859 - 0x0A) = 0x01;
		es_875->t4FBA.u0 = 0x01;
		(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x01;
		fn207F_2CE1((ss->*sp_867.u7).ptr0006);
	}
	(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x246C;
	(ss->*((word32) sp_867 + 4)).u0 = 0x244B;
	(ss->*sp_867.u7).w0002 = 0x3092;
	(ss->*sp_867.u7).t0000.u1 = 0x4614;
	Eq_5 si_1055 = fn1F3D_049D(si_866, di_862, ds_863, ss->*sp_867, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006, out di_1056, out ds_1054);
	if (ss->*((word16) bp_859 - 0x0A) != 0x00)
	{
		(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 16000;
		(ss->*((word32) sp_867 + 4)).u0 = 0x3092;
		(ss->*sp_867.u7).w0002 = 0x4614;
		(ss->*sp_867.u7).t0000.u1 = 0x246C;
		(ss->*((word32) sp_867 - 2)).u0 = 0x244B;
		fn207F_0A76(ss->*((word32) sp_867 - 2), ss->*((word32) sp_867 + 2), (ss->*sp_867.u7).ptr0006);
		Mem935[ds_1054:21512:selector]->t4FBA.u0 = 0x00;
		(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x00;
		fn207F_2CE1((ss->*sp_867.u7).ptr0006);
		(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 16000;
		(ss->*((word32) sp_867 + 4)).u0 = 0x50;
		(ss->*sp_867.u7).w0002 = 0x246C;
		(ss->*sp_867.u7).t0000.u1 = 0x244B;
		(ss->*((word32) sp_867 - 2)).u0 = 0x246C;
		(ss->*((word32) sp_867 - 4)).u0 = 0x244B;
		fn207F_0163(ss->*((word32) sp_867 - 4), ss->*((word32) sp_867 - 2), (ss->*sp_867.u7).t0000.u1, (ss->*sp_867.u7).w0002, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006);
		(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x3092;
		(ss->*((word32) sp_867 + 4)).u0 = 0x4614;
		(ss->*sp_867.u7).w0002 = 0x3092;
		(ss->*sp_867.u7).t0000.u1 = 0x4614;
		fn207F_0A26((ss->*sp_867.u7).t0000.u1, (ss->*sp_867.u7).w0002, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006);
	}
	if (Mem997[ds_1054:21512:selector]->t4FBA == 0x02)
	{
		(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 16000;
		(ss->*((word32) sp_867 + 4)).u0 = 0x246C;
		(ss->*sp_867.u7).w0002 = 0x244B;
		(ss->*sp_867.u7).t0000.u1 = 0x246C;
		(ss->*((word32) sp_867 - 2)).u0 = 0x244B;
		fn207F_0572(0x24, 0x6C, ss->*((word32) sp_867 - 2), (ss->*sp_867.u7).t0000.u1, (ss->*sp_867.u7).w0002, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006);
	}
	ss->*((word16) bp_859 - 0x0E) = 0x00;
	do
	{
		(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x18;
		(ss->*((word32) sp_867 + 4)).u0 = 0x03;
		(ss->*sp_867.u7).w0002 = 0x00;
		(ss->*sp_867.u7).t0000.u1 = (word16) (ss->*((word16) bp_859 - 0x0E) *s 0x03);
		(ss->*((word32) sp_867 - 2)).u5 = ss->*((word16) bp_859 - 0x0E);
		si_1055 = fn1F3D_070A(si_1055, di_1056, ds_1054, ss->*((word32) sp_867 - 2), (ss->*sp_867.u7).t0000.u1, (ss->*sp_867.u7).w0002, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006, out di_1056, out ds_1054);
		ss->*((word16) bp_859 - 0x0E) = (word16) (ss->*((word16) bp_859 - 0x0E)) + 1;
	} while (ss->*((word16) bp_859 - 0x0E) < 0x0C);
	ss->*((word16) bp_859 - 0x0E) = 0x0C;
	do
	{
		(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x18;
		(ss->*((word32) sp_867 + 4)).u0 = 0x03;
		(ss->*sp_867.u7).w0002 = 0x18;
		(ss->*sp_867.u7).t0000.u1 = (word16) (ss->*((word16) bp_859 - 0x0E) *s 0x03 - 0x24);
		(ss->*((word32) sp_867 - 2)).u5 = ss->*((word16) bp_859 - 0x0E);
		si_1055 = fn1F3D_070A(si_1055, di_1056, ds_1054, ss->*((word32) sp_867 - 2), (ss->*sp_867.u7).t0000.u1, (ss->*sp_867.u7).w0002, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006, out di_1056, out ds_1054);
		ss->*((word16) bp_859 - 0x0E) = (word16) (ss->*((word16) bp_859 - 0x0E)) + 1;
	} while (ss->*((word16) bp_859 - 0x0E) < 0x10);
	ss->*((word16) bp_859 - 0x0E) = 0x10;
	do
	{
		(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x08;
		(ss->*((word32) sp_867 + 4)).u0 = 0x01;
		(ss->*sp_867.u7).w0002 = 0x18;
		(ss->*sp_867.u7).t0000.u1 = (word16) (ss->*((word16) bp_859 - 0x0E) - 0x04);
		(ss->*((word32) sp_867 - 2)).u5 = ss->*((word16) bp_859 - 0x0E);
		si_1055 = fn1F3D_070A(si_1055, di_1056, ds_1054, ss->*((word32) sp_867 - 2), (ss->*sp_867.u7).t0000.u1, (ss->*sp_867.u7).w0002, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006, out di_1056, out ds_1054);
		ss->*((word16) bp_859 - 0x0E) = (word16) (ss->*((word16) bp_859 - 0x0E)) + 1;
	} while (ss->*((word16) bp_859 - 0x0E) < 0x24);
	ss->*((word16) bp_859 - 22) = 0x09;
	while (ss->*((word16) bp_859 - 22) < 0x10)
	{
		ss->*((word16) bp_859 - 0x0E) = 0x0C;
		while (ss->*((word16) bp_859 - 0x0E) < 0x18)
		{
			(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x08;
			(ss->*((word32) sp_867 + 4)).u0 = 0x01;
			(ss->*sp_867.u7).w0002 = (word16) (ss->*((word16) bp_859 - 22) << 0x03);
			(ss->*sp_867.u7).t0000.u1 = (word16) (ss->*((word16) bp_859 - 0x0E));
			ss->*((word32) sp_867 - 2) = (word16) (ss->*((word16) bp_859 - 0x0E)) + ss->*((word16) bp_859 - 22) *s 0x0C - 0x54;
			si_1055 = fn1F3D_070A(si_1055, di_1056, ds_1054, ss->*((word32) sp_867 - 2), (ss->*sp_867.u7).t0000.u1, (ss->*sp_867.u7).w0002, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006, out di_1056, out ds_1054);
			ss->*((word16) bp_859 - 0x0E) = (word16) (ss->*((word16) bp_859 - 0x0E)) + 1;
		}
		ss->*((word16) bp_859 - 22) = (word16) (ss->*((word16) bp_859 - 22)) + 1;
	}
	(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x18;
	(ss->*((word32) sp_867 + 4)).u0 = 0x03;
	(ss->*sp_867.u7).w0002 = 0x60;
	(ss->*sp_867.u7).t0000.u1 = 0x00;
	(ss->*((word32) sp_867 - 2)).u0 = 0x78;
	Eq_5 si_1198 = fn1F3D_070A(si_1055, di_1056, ds_1054, ss->*((word32) sp_867 - 2), (ss->*sp_867.u7).t0000.u1, (ss->*sp_867.u7).w0002, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006, out di_1194, out ds_1195);
	(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x18;
	(ss->*((word32) sp_867 + 4)).u0 = 0x03;
	(ss->*sp_867.u7).w0002 = 0x60;
	(ss->*sp_867.u7).t0000.u1 = 0x03;
	(ss->*((word32) sp_867 - 2)).u0 = 121;
	Eq_5 si_1228 = fn1F3D_070A(si_1198, di_1194, ds_1195, ss->*((word32) sp_867 - 2), (ss->*sp_867.u7).t0000.u1, (ss->*sp_867.u7).w0002, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006, out di_1224, out ds_1225);
	(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x18;
	(ss->*((word32) sp_867 + 4)).u0 = 0x03;
	(ss->*sp_867.u7).w0002 = 0x78;
	(ss->*sp_867.u7).t0000.u1 = 0x09;
	(ss->*((word32) sp_867 - 2)).u0 = 122;
	Eq_5 si_1258 = fn1F3D_070A(si_1228, di_1224, ds_1225, ss->*((word32) sp_867 - 2), (ss->*sp_867.u7).t0000.u1, (ss->*sp_867.u7).w0002, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006, out di_1254, out ds_1255);
	(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x18;
	(ss->*((word32) sp_867 + 4)).u0 = 0x03;
	(ss->*sp_867.u7).w0002 = 0x78;
	(ss->*sp_867.u7).t0000.u1 = 0x06;
	(ss->*((word32) sp_867 - 2)).u0 = 0x7B;
	Eq_5 si_1288 = fn1F3D_070A(si_1258, di_1254, ds_1255, ss->*((word32) sp_867 - 2), (ss->*sp_867.u7).t0000.u1, (ss->*sp_867.u7).w0002, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006, out di_1284, out ds_1285);
	(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x0E;
	(ss->*((word32) sp_867 + 4)).u0 = 0x02;
	(ss->*sp_867.u7).w0002 = 0xA0;
	(ss->*sp_867.u7).t0000.u1 = 0x08;
	(ss->*((word32) sp_867 - 2)).u0 = 0x7C;
	Eq_5 si_1318 = fn1F3D_070A(si_1288, di_1284, ds_1285, ss->*((word32) sp_867 - 2), (ss->*sp_867.u7).t0000.u1, (ss->*sp_867.u7).w0002, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006, out di_1314, out ds_1315);
	(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x0E;
	(ss->*((word32) sp_867 + 4)).u0 = 0x02;
	(ss->*sp_867.u7).w0002 = 0xA0;
	(ss->*sp_867.u7).t0000.u1 = 0x0A;
	(ss->*((word32) sp_867 - 2)).u0 = 0x7D;
	Eq_5 si_1348 = fn1F3D_070A(si_1318, di_1314, ds_1315, ss->*((word32) sp_867 - 2), (ss->*sp_867.u7).t0000.u1, (ss->*sp_867.u7).w0002, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006, out di_1344, out ds_1345);
	(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x08;
	(ss->*((word32) sp_867 + 4)).u0 = 0x01;
	(ss->*sp_867.u7).w0002 = 0xA0;
	(ss->*sp_867.u7).t0000.u1 = 0x00;
	(ss->*((word32) sp_867 - 2)).u0 = 0x7E;
	Eq_5 si_1378 = fn1F3D_070A(si_1348, di_1344, ds_1345, ss->*((word32) sp_867 - 2), (ss->*sp_867.u7).t0000.u1, (ss->*sp_867.u7).w0002, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006, out di_1374, out ds_1375);
	(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x08;
	(ss->*((word32) sp_867 + 4)).u0 = 0x01;
	(ss->*sp_867.u7).w0002 = 0xA0;
	(ss->*sp_867.u7).t0000.u1 = 0x01;
	(ss->*((word32) sp_867 - 2)).u0 = 0x7F;
	Eq_5 si_1408 = fn1F3D_070A(si_1378, di_1374, ds_1375, ss->*((word32) sp_867 - 2), (ss->*sp_867.u7).t0000.u1, (ss->*sp_867.u7).w0002, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006, out di_1404, out ds_1405);
	(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x10;
	(ss->*((word32) sp_867 + 4)).u0 = 0x02;
	(ss->*sp_867.u7).w0002 = 0x90;
	(ss->*sp_867.u7).t0000.u1 = 0x08;
	(ss->*((word32) sp_867 - 2)).u0 = 0x80;
	Eq_5 si_1438 = fn1F3D_070A(si_1408, di_1404, ds_1405, ss->*((word32) sp_867 - 2), (ss->*sp_867.u7).t0000.u1, (ss->*sp_867.u7).w0002, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006, out di_1434, out ds_1435);
	(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x10;
	(ss->*((word32) sp_867 + 4)).u0 = 0x02;
	(ss->*sp_867.u7).w0002 = 0x90;
	(ss->*sp_867.u7).t0000.u1 = 0x0A;
	(ss->*((word32) sp_867 - 2)).u0 = 0x81;
	Eq_5 si_1468 = fn1F3D_070A(si_1438, di_1434, ds_1435, ss->*((word32) sp_867 - 2), (ss->*sp_867.u7).t0000.u1, (ss->*sp_867.u7).w0002, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006, out di_1464, out ds_1465);
	ss->*((word16) bp_859 - 22) = 0x12;
	while (ss->*((word16) bp_859 - 22) < 22)
	{
		ss->*((word16) bp_859 - 0x0E) = 0x04;
		while (ss->*((word16) bp_859 - 0x0E) < 0x08)
		{
			(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x08;
			(ss->*((word32) sp_867 + 4)).u0 = 0x01;
			(ss->*sp_867.u7).w0002 = (word16) (ss->*((word16) bp_859 - 22) << 0x03);
			(ss->*sp_867.u7).t0000.u1 = (word16) (ss->*((word16) bp_859 - 0x0E));
			ss->*((word32) sp_867 - 2) = (word16) (ss->*((word16) bp_859 - 0x0E)) + (ss->*((word16) bp_859 - 22) << 0x02) + 0x36;
			si_1468 = fn1F3D_070A(si_1468, di_1464, ds_1465, ss->*((word32) sp_867 - 2), (ss->*sp_867.u7).t0000.u1, (ss->*sp_867.u7).w0002, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006, out di_1464, out ds_1465);
			ss->*((word16) bp_859 - 0x0E) = (word16) (ss->*((word16) bp_859 - 0x0E)) + 1;
		}
		ss->*((word16) bp_859 - 22) = (word16) (ss->*((word16) bp_859 - 22)) + 1;
	}
	ss->*((word16) bp_859 - 0x0E) = 0x00;
	do
	{
		(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x18;
		(ss->*((word32) sp_867 + 4)).u0 = 0x03;
		(ss->*sp_867.u7).w0002 = 0x30;
		(ss->*sp_867.u7).t0000.u1 = (word16) (ss->*((word16) bp_859 - 0x0E) *s 0x03);
		(ss->*((word32) sp_867 - 2)).u5 = (word16) (ss->*((word16) bp_859 - 0x0E)) + 0x0092;
		si_1468 = fn1F3D_070A(si_1468, di_1464, ds_1465, ss->*((word32) sp_867 - 2), (ss->*sp_867.u7).t0000.u1, (ss->*sp_867.u7).w0002, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006, out di_1464, out ds_1465);
		ss->*((word16) bp_859 - 0x0E) = (word16) (ss->*((word16) bp_859 - 0x0E)) + 1;
	} while (ss->*((word16) bp_859 - 0x0E) < 0x0C);
	ss->*((word16) bp_859 - 0x0E) = 0x00;
	do
	{
		(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x18;
		(ss->*((word32) sp_867 + 4)).u0 = 0x03;
		(ss->*sp_867.u7).w0002 = 0x48;
		(ss->*sp_867.u7).t0000.u1 = (word16) (ss->*((word16) bp_859 - 0x0E) *s 0x03);
		(ss->*((word32) sp_867 - 2)).u5 = (word16) (ss->*((word16) bp_859 - 0x0E)) + 0x009E;
		si_1468 = fn1F3D_070A(si_1468, di_1464, ds_1465, ss->*((word32) sp_867 - 2), (ss->*sp_867.u7).t0000.u1, (ss->*sp_867.u7).w0002, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006, out di_1464, out ds_1465);
		ss->*((word16) bp_859 - 0x0E) = (word16) (ss->*((word16) bp_859 - 0x0E)) + 1;
	} while (ss->*((word16) bp_859 - 0x0E) < 0x04);
	(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x18;
	(ss->*((word32) sp_867 + 4)).u0 = 0x03;
	(ss->*sp_867.u7).w0002 = 0x60;
	(ss->*sp_867.u7).t0000.u1 = 0x06;
	(ss->*((word32) sp_867 - 2)).u0 = 0xA2;
	Eq_5 si_1594 = fn1F3D_070A(si_1468, di_1464, ds_1465, ss->*((word32) sp_867 - 2), (ss->*sp_867.u7).t0000.u1, (ss->*sp_867.u7).w0002, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006, out di_1590, out ds_1591);
	(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x18;
	(ss->*((word32) sp_867 + 4)).u0 = 0x03;
	(ss->*sp_867.u7).w0002 = 0x60;
	(ss->*sp_867.u7).t0000.u1 = 0x09;
	(ss->*((word32) sp_867 - 2)).u0 = 0xA3;
	Eq_5 si_1624 = fn1F3D_070A(si_1594, di_1590, ds_1591, ss->*((word32) sp_867 - 2), (ss->*sp_867.u7).t0000.u1, (ss->*sp_867.u7).w0002, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006, out di_1620, out ds_1621);
	(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x18;
	(ss->*((word32) sp_867 + 4)).u0 = 0x03;
	(ss->*sp_867.u7).w0002 = 0x78;
	(ss->*sp_867.u7).t0000.u1 = 0x00;
	(ss->*((word32) sp_867 - 2)).u0 = 0xA4;
	Eq_5 si_1654 = fn1F3D_070A(si_1624, di_1620, ds_1621, ss->*((word32) sp_867 - 2), (ss->*sp_867.u7).t0000.u1, (ss->*sp_867.u7).w0002, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006, out di_1650, out ds_1651);
	(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x18;
	(ss->*((word32) sp_867 + 4)).u0 = 0x03;
	(ss->*sp_867.u7).w0002 = 0x78;
	(ss->*sp_867.u7).t0000.u1 = 0x03;
	(ss->*((word32) sp_867 - 2)).u0 = 0xA5;
	Eq_5 si_1684 = fn1F3D_070A(si_1654, di_1650, ds_1651, ss->*((word32) sp_867 - 2), (ss->*sp_867.u7).t0000.u1, (ss->*sp_867.u7).w0002, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006, out di_1680, out ds_1681);
	ss->*((word16) bp_859 - 0x0E) = 166;
	do
	{
		(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x08;
		(ss->*((word32) sp_867 + 4)).u0 = 0x01;
		(ss->*sp_867.u7).w0002 = 0x20;
		(ss->*sp_867.u7).t0000.u1 = (word16) (ss->*((word16) bp_859 - 0x0E) - 0x9A);
		(ss->*((word32) sp_867 - 2)).u5 = ss->*((word16) bp_859 - 0x0E);
		si_1684 = fn1F3D_070A(si_1684, di_1680, ds_1681, ss->*((word32) sp_867 - 2), (ss->*sp_867.u7).t0000.u1, (ss->*sp_867.u7).w0002, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006, out di_1680, out ds_1681);
		ss->*((word16) bp_859 - 0x0E) = (word16) (ss->*((word16) bp_859 - 0x0E)) + 1;
	} while (ss->*((word16) bp_859 - 0x0E) < 0xBA);
	ss->*((word16) bp_859 - 22) = 0x09;
	while (ss->*((word16) bp_859 - 22) < 0x10)
	{
		ss->*((word16) bp_859 - 0x0E) = 0x18;
		while (ss->*((word16) bp_859 - 0x0E) < 0x24)
		{
			(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x08;
			(ss->*((word32) sp_867 + 4)).u0 = 0x01;
			(ss->*sp_867.u7).w0002 = (word16) (ss->*((word16) bp_859 - 22) << 0x03);
			(ss->*sp_867.u7).t0000.u1 = (word16) (ss->*((word16) bp_859 - 0x0E));
			ss->*((word32) sp_867 - 2) = (word16) (ss->*((word16) bp_859 - 0x0E)) + ss->*((word16) bp_859 - 22) *s 0x0C + 0x36;
			si_1684 = fn1F3D_070A(si_1684, di_1680, ds_1681, ss->*((word32) sp_867 - 2), (ss->*sp_867.u7).t0000.u1, (ss->*sp_867.u7).w0002, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006, out di_1680, out ds_1681);
			ss->*((word16) bp_859 - 0x0E) = (word16) (ss->*((word16) bp_859 - 0x0E)) + 1;
		}
		ss->*((word16) bp_859 - 22) = (word16) (ss->*((word16) bp_859 - 22)) + 1;
	}
	ss->*((word16) bp_859 - 0x0E) = 266;
	do
	{
		(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x08;
		(ss->*((word32) sp_867 + 4)).u0 = 0x01;
		(ss->*sp_867.u7).w0002 = 0x28;
		(ss->*sp_867.u7).t0000.u1 = (word16) (ss->*((word16) bp_859 - 0x0E) - 0xFE);
		(ss->*((word32) sp_867 - 2)).u5 = (word16) (ss->*((word16) bp_859 - 0x0E)) + 4;
		si_1684 = fn1F3D_070A(si_1684, di_1680, ds_1681, ss->*((word32) sp_867 - 2), (ss->*sp_867.u7).t0000.u1, (ss->*sp_867.u7).w0002, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006, out di_1680, out ds_1681);
		ss->*((word16) bp_859 - 0x0E) = (word16) (ss->*((word16) bp_859 - 0x0E)) + 1;
	} while (ss->*((word16) bp_859 - 0x0E) < 0x011E);
	ss->*((word16) bp_859 - 22) = 0x10;
	while (ss->*((word16) bp_859 - 22) < 0x17)
	{
		ss->*((word16) bp_859 - 0x0E) = 0x0C;
		while (ss->*((word16) bp_859 - 0x0E) < 0x18)
		{
			(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x08;
			(ss->*((word32) sp_867 + 4)).u0 = 0x01;
			(ss->*sp_867.u7).w0002 = (word16) (ss->*((word16) bp_859 - 22) << 0x03);
			(ss->*sp_867.u7).t0000.u1 = (word16) (ss->*((word16) bp_859 - 0x0E));
			ss->*((word32) sp_867 - 2) = (word16) (ss->*((word16) bp_859 - 0x0E)) + ss->*((word16) bp_859 - 22) *s 0x0C + 0x56;
			si_1684 = fn1F3D_070A(si_1684, di_1680, ds_1681, ss->*((word32) sp_867 - 2), (ss->*sp_867.u7).t0000.u1, (ss->*sp_867.u7).w0002, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006, out di_1680, out ds_1681);
			ss->*((word16) bp_859 - 0x0E) = (word16) (ss->*((word16) bp_859 - 0x0E)) + 1;
		}
		ss->*((word16) bp_859 - 22) = (word16) (ss->*((word16) bp_859 - 22)) + 1;
	}
	(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 11;
	(ss->*((word32) sp_867 + 4)).u0 = 0x02;
	(ss->*sp_867.u7).w0002 = 0x90;
	(ss->*sp_867.u7).t0000.u1 = 0x00;
	(ss->*((word32) sp_867 - 2)).u0 = 0x0176;
	Eq_5 si_1819 = fn1F3D_070A(si_1684, di_1680, ds_1681, ss->*((word32) sp_867 - 2), (ss->*sp_867.u7).t0000.u1, (ss->*sp_867.u7).w0002, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006, out di_1815, out ds_1816);
	(ss->*sp_867.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 11;
	(ss->*((word32) sp_867 + 4)).u0 = 0x02;
	(ss->*sp_867.u7).w0002 = 0x90;
	(ss->*sp_867.u7).t0000.u1 = 0x02;
	(ss->*((word32) sp_867 - 2)).u0 = 0x0177;
	Eq_5 di_1845;
	Eq_5 ds_1846;
	Eq_5 si_1865;
	Eq_5 di_1861;
	Eq_5 ds_1862;
	fn0DAB_0D12(fn0800_50C8(fn1F3D_070A(si_1819, di_1815, ds_1816, ss->*((word32) sp_867 - 2), (ss->*sp_867.u7).t0000.u1, (ss->*sp_867.u7).w0002, ss->*((word32) sp_867 + 4), (ss->*sp_867.u7).ptr0006, out di_1845, out ds_1846), di_1845, ds_1846, out si_1865, out di_1861, out ds_1862), si_1865, di_1861, ds_1862);
}

