// UNBTECH_1631.c
// Generated by decompiling UNBTECH.exe
// using Reko decompiler version 0.12.2.0.

#include "UNBTECH.h"

// 1631:0006: Register Eq_5 fn1631_0006(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Stack Eq_5 wArg06, Stack Eq_5 wArg08, Stack Eq_5 wArg0A, Stack Eq_5 wArg0C, Stack Eq_5 wArg0E, Register out word16 diOut, Register out Eq_5 dsOut)
// Called from:
//      fn0800_24C2
//      fn183B_193B
//      fn183B_28DB
Eq_5 fn1631_0006(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, Eq_5 wArg06, Eq_5 wArg08, Eq_5 wArg0A, Eq_5 wArg0C, Eq_5 wArg0E, word16 & diOut, union Eq_5 & dsOut)
{
	byte bArg04_437 = (byte) wArg04;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	word16 di_19;
	Eq_5 ds_144;
	fn207F_2FDC(0x1C, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_144);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	selector ss;
	(ss->*((word32) sp_18 - 2)).u5 = di_19;
	ss->*((word32) sp_18 - 4) = si_22;
	if (wArg0E != 0x00)
	{
		word16 v12_35 = Mem31[ds_144:0x315A:word16] - 0x01;
		Mem36[ds_144:0x315A:word16] = v12_35;
		if (v12_35 == 0x00)
		{
			Mem39[ds_144:0x315A:word16] = 0x1E;
			Mem41[ds_144:12636:byte] = Mem39[ds_144:12636:byte] ^ 0x08;
		}
	}
	else
		Mem34[ds_144:12636:word16] = 0x00;
	int16 ax_53 = (int16) (Mem47[ds_144:0x5578:selector]->*((word16) (wArg04 & 0x7F) + 14624));
	Mem54[ds_144:21882:selector]->w4590 = 0x00;
	Mem58[ds_144:0x557C:selector]->w458E = 0x00;
	int16 wLoc12_435 = ax_53;
	word16 wLoc1A_436 = 0x00;
	if ((bArg04_437 & 0x7F) < 0x04 || wArg04 >= 0x0C && wArg04 < 0x10)
		wLoc1A_436 = 0x01;
	ss->*((word32) sp_18 - 6) = wArg08;
	ss->*((word32) sp_18 - 8) = wArg06;
	ss->*((word32) sp_18 - 0x0A) = Mem83[ds_144:0x557E:selector]->tE488;
	ss->*((word32) sp_18 - 0x0C) = Mem89[ds_144:21888:selector]->tE486;
	Eq_5 ax_94 = fn207F_0971(ss->*((word32) sp_18 - 0x0C), ss->*((word32) sp_18 - 0x0A), ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6));
	if (ax_94 != ~0x00)
	{
		cui16 ax_109 = ax_94 - ax_53;
		if (ax_109 != 0x00)
		{
			int16 wLoc12_452;
			if ((ax_109 & 0x07) < 0x05)
				wLoc12_452 = ax_53 + 0x01;
			else
				wLoc12_452 = ax_53 - 0x01;
			wLoc12_435 = wLoc12_452 & 0x07;
		}
		Eq_5 wLoc16_456;
		wLoc16_456.u0 = 0x07;
		for (; wLoc16_456 > ~0x00; --wLoc16_456)
		{
			int16 ax_147 = CONVERT(Mem140[ds_144:Mem140[ds_144:12636:word16] + 0x310A + wLoc16_456:byte], int8, int16);
			int16 ax_148 = ax_147 + wLoc12_435;
			Eq_5 ax_155;
			ax_155.u5 = Mem150[ds_144:21888:selector]->tE486.u5 + (*((word32) ds_144 + 0x0000311A))[ax_148 & 0x07];
			byte bLoc12_547 = (byte) ax_148 & 0x07;
			Eq_5 wLoc04_460 = ax_155;
			if (((byte) ax_155 & 0x80) != 0x00)
				wLoc04_460.u5 = ax_155.u5 + (*((word32) ds_144 + 0x0000313A))[ax_148 & 0x07];
			Eq_5 ax_173;
			ax_173.u5 = Mem167[ds_144:0x557E:selector]->tE488.u5 + (*((word32) ds_144 + 0x0000312A))[ax_148 & 0x07];
			Eq_5 wLoc08_464 = ax_173;
			if (((byte) ax_173 & 0x80) != 0x00)
				wLoc08_464.u5 = ax_173.u5 + (*((word32) ds_144 + 12618))[ax_148 & 0x07];
			ci16 ax_190 = (ci16) (wArg0A.u5 + (*((word32) ds_144 + 0x0000311A))[ax_148 & 0x07]);
			ci16 ax_193 = (ci16) (wArg0C.u5 + (*((word32) ds_144 + 0x0000312A))[ax_148 & 0x07]);
			int16 ax_202 = (ax_193 >> 0x01) *s 0x18 + (ax_190 - 0x0D >> 0x01);
			byte bLoc0A_477 = (byte) ax_190;
			byte bLoc0C_480 = (byte) ax_193;
			int16 wLoc10_476 = ax_202;
			if ((bLoc0A_477 & 0x01) == 0x00 && (Mem203[ds_144:0x5582:selector]->tA44B & 0x01) != 0x00)
				wLoc10_476 = ax_202 + 0x01;
			if ((bLoc0C_480 & 0x01) != 0x00 && (Mem218[ds_144:0x5584:selector]->tA44D & 0x01) != 0x00)
				wLoc10_476 += 0x18;
			if (Mem243[ds_144:0x558A:selector]->t0150 > (uint16) ((char *) Mem233[ds_144:0x5586:selector]->ptr09ED + wLoc10_476)[0x07AD])
			{
				word16 wLoc0E_485 = 0x01;
				if (wLoc1A_436 != 0x00)
				{
					int16 wLoc10_493;
					if (((bLoc0A_477 ^ Mem247[ds_144:0x5582:selector]->tA44B) & 0x01) == 0x00)
						wLoc10_493 = wLoc10_476 + 0x01;
					else
						wLoc10_493 = wLoc10_476 - 0x01;
					if ((uint16) ((char *) Mem264[ds_144:0x5586:selector]->ptr09ED + wLoc10_493)[0x07AD] >= Mem264[ds_144:0x558A:selector]->t0150)
						wLoc0E_485 = 0x00;
				}
				if (wLoc0E_485 != 0x00 && wArg04 < 0x80)
				{
					Eq_5 ax_287 = Mem280[ds_144:0x5582:selector]->tA44B;
					Eq_5 ax_290 = Mem288[ds_144:0x5584:selector]->tA44D;
					Mem291[ds_144:0x5582:selector]->tA44B = wLoc04_460;
					Mem294[ds_144:0x5584:selector]->tA44D = wLoc08_464;
					(ss->*((word32) sp_18 - 6)).u0 = 0x00;
					(ss->*((word32) sp_18 - 8)).u0 = (*((word32) ds_144 + 0x0000312A))[ax_148 & 0x07].t0000.u0;
					(ss->*((word32) sp_18 - 0x0A)).u0 = (*((word32) ds_144 + 0x0000311A))[ax_148 & 0x07].t0000.u0;
					ss->*((word32) sp_18 - 0x0C) = wArg04;
					word16 di_727;
					if (fn1631_16AB((ax_148 & 0x07) << 0x01, wLoc16_456, ds_144, ss->*((word32) sp_18 - 0x0C), ss->*((word32) sp_18 - 6), out di_727, out ds_144) != 0x00)
					{
						wLoc0E_485 = 0x00;
						if (wLoc04_460 == wArg06 && wLoc08_464 == wArg08)
							Mem352[ds_144:0x558C:selector]->wD57E = 0x01;
					}
					Mem362[ds_144:0x5582:selector]->tA44B = ax_287;
					Mem367[ds_144:0x5584:selector]->tA44D = ax_290;
				}
				if (wLoc0E_485 != 0x00)
				{
					Mem373[ds_144:21888:selector]->tE486 = wLoc04_460;
					Mem379[ds_144:0x557E:selector]->tE488 = wLoc08_464;
					Mem382[ds_144:0x5578:selector]->*((word16) (wArg04 & 0x7F) + 14624) = bLoc12_547;
					Mem387[ds_144:0x557C:selector]->w458E = (*((word32) ds_144 + 0x0000311A))[ax_148 & 0x07];
					Mem393[ds_144:21882:selector]->w4590 = (*((word32) ds_144 + 0x0000312A))[ax_148 & 0x07];
					break;
				}
			}
			wLoc12_435 = ax_147 + wLoc12_435 & 0x07;
		}
	}
	Eq_5 si_408 = ss->*((word32) sp_18 - 4);
	diOut = (word16) (ss->*((word32) sp_18 - 2));
	dsOut = ds_144;
	return si_408;
}

// 1631:02E4: Register Eq_5 fn1631_02E4(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Register out word16 diOut, Register out (ptr16 Eq_14154) dsOut)
// Called from:
//      fn0800_378D
//      fn0DAB_1467
//      fn0DAB_18E8
Eq_5 fn1631_02E4(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, word16 & diOut, struct Eq_14154 & dsOut)
{
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	Eq_5 di_19;
	Eq_5 ds_20;
	fn207F_2FDC(0x04, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	selector ss;
	ss->*((word32) sp_18 - 2) = si_22;
	struct Eq_57354 * es_34 = Mem29[ds_20:0x558E:selector];
	int16 ax_47 = (word32) (&es_34->bC620)[3][wArg04] /16 (int16) (((es_34->aC614))[0].b0001)[wArg04];
	(ss->*((word32) sp_18 - 4)).u5 = (*((word32) ds_20 + 0x00002E0E))[ax_47].w0000;
	(ss->*((word32) sp_18 - 6)).u0 = (*((word32) ds_20 + 11788))[ax_47].u0;
	word16 si_89;
	word16 di_61;
	struct Eq_14154 * ds_62;
	fn1E56_03F5(wArg04 *s16 0x11, di_19, ds_20, ss->*((word32) sp_18 - 6), out si_89, out di_61, out ds_62);
	Eq_5 si_73 = ss->*((word32) sp_18 - 2);
	diOut = di_61;
	dsOut = ds_62;
	return si_73;
}

// 1631:032F: Register Eq_5 fn1631_032F(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Register out word16 diOut, Register out (ptr16 Eq_12066) dsOut)
// Called from:
//      fn0800_32B3
//      fn0800_35D3
//      fn0DAB_1467
Eq_5 fn1631_032F(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, word16 & diOut, struct Eq_12066 & dsOut)
{
	struct Eq_12066 * ds_198;
	word16 di_197;
	Eq_5 ds_181;
	Eq_5 di_180;
	Eq_5 ds_166;
	Eq_5 di_165;
	Eq_5 ds_147;
	Eq_5 di_146;
	Eq_5 ds_130;
	Eq_5 di_129;
	Eq_5 ds_115;
	Eq_5 di_114;
	Eq_5 ds_98;
	Eq_5 di_97;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_25;
	Eq_5 di_22;
	Eq_5 ds_23;
	fn207F_2FDC(0x00, fp - 2, si, di, ds, wLoc06, wLoc04, out si_25, out di_22, out ds_23);
	Eq_5 sp_21;
	sp_21.u0 = <invalid>;
	selector ss;
	ss->*((word32) sp_21 - 2) = Mem7[ds_23:0x5584:selector]->tA44D;
	ss->*((word32) sp_21 - 4) = Mem34[ds_23:0x5582:selector]->tA44B;
	fn207F_1314(ss->*((word32) sp_21 - 4), ss->*((word32) sp_21 - 2));
	fn207F_18EF();
	Eq_5 si_69;
	Eq_5 di_65;
	Eq_5 ds_66;
	if (wArg04 != 0x00)
		si_69 = fn0800_0E4B(si_25, di_22, ds_23, out di_65, out ds_66);
	else
		si_69 = fn0800_051B(si_25, di_22, ds_23, out di_65, out ds_66);
	Eq_5 si_101 = fn1F3D_06C3(fp - 2, si_69, di_65, ds_66, out di_97, out ds_98);
	(ss->*((word32) sp_21 - 2)).u0 = 0x04;
	Eq_5 si_133 = fn1E56_0388(fp - 2, fn1E56_0281(si_101, di_97, ds_98, ss->*((word32) sp_21 - 2), out di_114, out ds_115), di_114, ds_115, out di_129, out ds_130);
	Eq_5 sp_134;
	sp_134.u0 = <invalid>;
	(ss->*((word32) sp_134 - 2)).u0 = 0x04;
	Eq_5 si_150 = fn1E56_0004(si_133, di_129, ds_130, ss->*((word32) sp_134 - 2), out di_146, out ds_147);
	(ss->*((word32) sp_134 - 2)).u0 = 0x03;
	Eq_5 si_201 = fn1E56_0004(fn1E56_0388(fp - 2, fn1E56_0281(si_150, di_146, ds_147, ss->*((word32) sp_134 - 2), out di_165, out ds_166), di_165, ds_166, out di_180, out ds_181), di_180, ds_181, 0x03, out di_197, out ds_198);
	diOut = di_197;
	dsOut = ds_198;
	return si_201;
}

// 1631:03AB: Register Eq_5 fn1631_03AB(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Stack Eq_5 wArg06, Register out Eq_5 diOut, Register out (ptr16 Eq_58158) dsOut)
// Called from:
//      fn183B_000A
//      fn183B_1482
//      fn183B_14C3
Eq_5 fn1631_03AB(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, Eq_5 wArg06, union Eq_5 & diOut, struct Eq_58158 & dsOut)
{
	Eq_5 ds_1089;
	Eq_5 di_1088;
	Eq_5 ds_1021;
	Eq_5 di_1039;
	Eq_5 si_1022;
	Eq_5 ds_53;
	Eq_5 di_52;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	Eq_5 di_19;
	Eq_5 ds_20;
	fn207F_2FDC(0x3A, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	selector ss;
	ss->*((word32) sp_18 - 2) = di_19;
	ss->*((word32) sp_18 - 4) = si_22;
	Eq_5 ax_33 = Mem31[ds_20:0x5582:selector]->tA44B;
	Eq_5 ax_36 = Mem34[ds_20:0x5584:selector]->tA44D;
	Mem44[ss:sp_18 + -6:word16] = Mem37[ds_20:0x5590:selector]:0x4036[wArg04 *16 0x02];
	Mem48[ss:sp_18 + -8:word16] = Mem44[ds_20:0x5592:selector]:0x4004[wArg04 *16 0x02];
	Eq_5 si_56 = fn0800_17BB(wArg04 << 0x01, di_19, ds_20, ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), out di_52, out ds_53);
	Eq_57629 wLoc10_1312;
	wLoc10_1312.u0 = 0x00;
	Eq_57629 v16_76;
	do
	{
		Mem68[ds_53:0x5594:selector]->*((word16) (wArg04 *s16 0x30 + wLoc10_1312) + 12998) = (word16) ~0x00;
		v16_76 = (word16) wLoc10_1312 + 1;
		wLoc10_1312 = v16_76;
	} while (v16_76 < 0x30);
	Eq_57647 wLoc38_1316;
	wLoc38_1316.u0 = 0x00;
	if (wArg04 >= 0x0C)
	{
		wArg04 -= 0x0C;
		wLoc38_1316.u0 = 0x04;
	}
	else
		(Mem80[ds_53:0x5596:selector]->*((word32) wArg04 + 0x00003994)).u5 = 0x01;
	Eq_5 wLoc1C_1319;
	wLoc1C_1319.u0 = 0x01;
	if (wArg04 >= 0x04 || Mem92[ds_53:21912:selector]->*((word16) (wArg04 + wLoc38_1316) + 110) != 0x00)
		wLoc1C_1319.u0 = 0x00;
	byte bLoc1C_1843 = (byte) wLoc1C_1319;
	Eq_5 di_1215;
	Eq_5 ds_1216;
	if (wArg04 < 0x04)
	{
		ss->*((word32) sp_18 - 6) = wLoc1C_1319;
		(ss->*((word32) sp_18 - 8)).u5 = wArg04 + wLoc38_1316;
		fn183B_22BC(si_56, di_52, ds_53, ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), out di_1215, out ds_1216);
	}
	else
	{
		(ss->*((word32) sp_18 - 6)).u5 = wArg04 + wLoc38_1316;
		fn183B_2474(si_56, di_52, ds_53, ss->*((word32) sp_18 - 6), out di_1215, out ds_1216);
	}
	word16 wLoc24_1328 = 0x04;
	Eq_5 wLoc36_1329;
	wLoc36_1329.u0 = 0x0C;
	Eq_5 wLoc06_1330;
	wLoc06_1330.u0 = ~0x00;
	Eq_5 wLoc04_1331;
	wLoc04_1331.u0 = ~0x00;
	Eq_57740 wLoc0C_1332;
	wLoc0C_1332.u0 = 0x7FFF;
	if (wLoc38_1316 != 0x00)
		wLoc36_1329.u0 = 0x00;
	Eq_5 wLoc14_1335;
	wLoc14_1335.u0 = 0x17;
	if (wArg04 >= 0x04)
	{
		wLoc24_1328 = 0x08;
		wLoc36_1329.u0 = 0x10;
		if (wLoc38_1316 != 0x00)
			wLoc36_1329.u0 = 0x04;
	}
	byte bLoc14_1595;
	while (true)
	{
		word16 v22_195 = wLoc24_1328 - 0x01;
		bLoc14_1595 = (byte) wLoc14_1335;
		wLoc24_1328 = v22_195;
		if (wLoc24_1328 == 0x00)
			break;
		if (Mem196[ds_1216:0x559A:selector]:0x406A[wLoc36_1329 *16 0x02] != 0x00)
		{
			Eq_5 ax_1165 = Mem196[ds_1216:0x5592:selector]:0x4004[wLoc36_1329 *16 0x02];
			Eq_5 ax_1168 = Mem1166[ds_1216:0x5590:selector]:0x4036[wLoc36_1329 *16 0x02];
			word16 wLoc3A_1771 = 0x01;
			if (Mem1170[ds_1216:0x559C:selector]->wE48E != 0x00 && wLoc36_1329 == 0x0D)
				wLoc3A_1771 = 0x00;
			if (wLoc38_1316 != 0x00)
			{
				selector es_1183 = Mem1179[ds_1216:0x558E:selector];
				if (es_1183->bD333 != 0x00 && (int16) es_1183->bD331 + 0x04 == wLoc36_1329)
					wLoc3A_1771 = 0x00;
			}
			if (wLoc3A_1771 != 0x00)
			{
				ss->*((word32) sp_18 - 6) = ax_1168;
				ss->*((word32) sp_18 - 8) = ax_1165;
				Eq_5 si_1219;
				if (fn1631_0BB5(wLoc36_1329 << 0x01, di_1215, ds_1216, ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), out si_1219, out di_1215, out ds_1216) < wLoc0C_1332)
				{
					ss->*((word32) sp_18 - 6) = ax_1168;
					ss->*((word32) sp_18 - 8) = ax_1165;
					word16 si_1986;
					wLoc0C_1332 = fn1631_0BB5(si_1219, di_1215, ds_1216, ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), out si_1986, out di_1215, out ds_1216);
					wLoc04_1331 = ax_1165;
					wLoc06_1330 = ax_1168;
					wLoc14_1335 = wLoc36_1329;
				}
			}
		}
		Eq_5 v28_1259;
		v28_1259.u5 = (word32) wLoc36_1329 + 1;
		wLoc36_1329 = v28_1259;
		if (v22_195 == 0x00 && wLoc04_1331 == ~0x00)
		{
			if (v28_1259 == 0x0C || v28_1259 == 0x18)
				wLoc36_1329 = v28_1259 - 0x0C;
			wLoc24_1328 = 0x08;
		}
	}
	if (wLoc38_1316 != 0x00)
		wArg04.u5 = (word32) wArg04 + 0x0C;
	Eq_57740 wLoc2E_1368;
	if (wArg04 < 0x10 && (wArg04 < 0x04 || wArg04 >= 0x0C))
	{
		ci16 wLoc2E_1349 = 0xFF;
		Eq_5 wLoc30_1351 = wArg04;
		if (wLoc38_1316 != 0x00)
			wLoc30_1351 = wArg04 - 0x08;
		Eq_57857 wLoc10_1355;
		wLoc10_1355.u0 = 0x33;
		Eq_57857 v71_274;
		do
		{
			uint8 al_240 = (uint8) (Mem233[ds_1216:0x558E:selector]->*((word16) (wLoc30_1351 *s16 0x7D + wLoc10_1355) + 50980));
			Eq_57938 ax_242;
			ax_242.u1 = (uint16) al_240;
			if (ax_242 != 0x00 && ((al_240 & 0x80) == 0x00 && (ax_242 >= 0x10 && ax_242 <= 0x20)))
			{
				uint16 ax_263 = (uint16) (*((word32) ds_1216 + 0x00002EE6))[ax_242].b0000;
				if ((ax_263 & 0xE0) < wLoc2E_1349)
					wLoc2E_1349 = ax_263 & 0xE0;
			}
			v71_274 = (word16) wLoc10_1355 + 1;
			wLoc10_1355 = v71_274;
		} while (v71_274 <= 0x55);
		if (wLoc2E_1349 == 0xFF)
			wLoc2E_1368.u0 = 0x00;
		else
			wLoc2E_1368 = wLoc2E_1349 >> 0x03;
	}
	else
	{
		struct Eq_57354 * es_295 = Mem209[ds_1216:0x558E:selector];
		int16 wLoc1E_1371 = (int16) es_295->aC5DB[0].b0000[wArg04].b0000;
		if (wArg04 >= 0x10)
			wLoc1E_1371 = (int16) es_295->aC597[0].b0000[wArg04].b0000;
		wLoc2E_1368 = (uint16) (*((word32) ds_1216 + 0x00002EE6))[wLoc1E_1371].b0000 >> 0x05 & 0x07;
	}
	Mem342[ss:sp_18 + -6:word16] = Mem324[ds_1216:0x5590:selector]:0x4036[wLoc14_1335 *16 0x02];
	Mem346[ss:sp_18 + -8:word16] = Mem342[ds_1216:0x5592:selector]:0x4004[wLoc14_1335 *16 0x02];
	ss->*((word32) sp_18 - 0x0A) = wLoc14_1335;
	ss->*((word32) sp_18 - 0x0C) = wArg04;
	word16 wLoc34_1389 = fn1631_1BFE(wLoc14_1335 << 0x01, di_1215, ds_1216, ss->*((word32) sp_18 - 0x0A), ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), out si_1022, out di_1039, out ds_1021);
	if ((wArg04 >= 0x10 || wArg04 >= 0x04 && wArg04 < 0x0C) && (wLoc14_1335 < 0x04 || wLoc14_1335 >= 0x0C && wLoc14_1335 < 0x10))
	{
		word16 ax_407;
		if (wArg04 < 0x0C)
			ax_407 = 0x01;
		else
			ax_407 = 0x00;
		Mem386[ds_1021:0x559E:selector]->w3992 = ax_407;
		if (wArg04 >= 0x10)
			Mem416[ds_1021:0x55A0:selector]->w374C = 0x01;
		Eq_5 ax_426 = Mem424[ds_1021:0x5582:selector]->tA44B;
		Eq_5 ax_431 = Mem429[ds_1021:0x5584:selector]->tA44D;
		if (ax_426 > wLoc04_1331)
		{
			wLoc04_1331.u5 = &ax_426.u7->ptr0006;
			if (((byte) ax_426 + 0x06 & 0x80) != 0x00)
				wLoc04_1331.u5 = (word32) ax_426 + 0x0086;
		}
		else if (ax_426 < wLoc04_1331)
		{
			wLoc04_1331 = ax_426 - 0x06;
			if (((byte) ax_426 - 0x06 & 0x80) != 0x00)
				wLoc04_1331 = ax_426 - 0x06 & 0x0F7F;
		}
		if (ax_431 > wLoc06_1330)
		{
			wLoc06_1330.u5 = &ax_431.u7->ptr0006;
			if (((byte) ax_431 + 0x06 & 0x80) != 0x00)
				wLoc06_1330.u5 = (word32) ax_431 + 0x0F86;
		}
		else if (ax_431 < wLoc06_1330)
		{
			wLoc06_1330 = ax_431 - 0x06;
			if (((byte) ax_431 - 0x06 & 0x80) != 0x00)
				wLoc06_1330 = ax_431 - 0x06 & ~0x0F80;
		}
		wLoc34_1389 = 0x00;
		wLoc2E_1368.u0 = 0x00;
	}
	byte al_620;
	struct Eq_57996 * es_si_1980;
	if (wLoc2E_1368 != 0x00 && wLoc34_1389 != 0x00)
	{
		if (wLoc0C_1332 <= wLoc2E_1368)
			goto l1631_08F9;
		Eq_5 wLoc20_1459 = Mem500[ds_1021:0x5582:selector]->tA44B;
		Eq_5 wLoc28_1460 = Mem513[ds_1021:0x5584:selector]->tA44D;
		cui16 wLoc18_1461 = 0x00;
		word16 wLoc12_1462 = 0x00;
		selector es_520 = Mem519[ds_1021:0x5582:selector];
		if (es_520->tA44B > wLoc04_1331)
			wLoc12_1462 = ~0x00;
		else if (es_520->tA44B < wLoc04_1331)
			wLoc12_1462 = 0x01;
		selector es_531 = Mem530[ds_1021:0x5584:selector];
		if (es_531->tA44D > wLoc06_1330)
			wLoc18_1461 = ~0x00;
		else if (es_531->tA44D < wLoc06_1330)
			wLoc18_1461 = 0x01;
		while (true)
		{
			--wLoc0C_1332;
			if (wLoc0C_1332 <= wLoc2E_1368)
				break;
			Eq_5 v49_551;
			v49_551.u5 = wLoc20_1459.u5 + wLoc12_1462;
			wLoc20_1459 = v49_551;
			if (((byte) v49_551 & 0x80) != 0x00)
			{
				if (wLoc12_1462 == ~0x00)
					wLoc20_1459 = v49_551 & 0x0F7F;
				else if (wLoc12_1462 == 0x01)
					wLoc20_1459.u5 = (word32) v49_551 + 0x0080;
			}
			Eq_5 v52_573;
			v52_573.u5 = wLoc28_1460.u5 + wLoc18_1461;
			wLoc28_1460 = v52_573;
			if (((byte) v52_573 & 0x80) != 0x00)
			{
				if (wLoc18_1461 == ~0x00)
					wLoc28_1460 = v52_573 & ~0x0F80;
				else if (wLoc18_1461 == 0x01)
					wLoc28_1460.u5 = (word32) v52_573 + 0x0F80;
			}
		}
		int16 ax_593 = wArg04 *s16 0x30;
		struct Eq_57634 * es_598 = Mem547[ds_1021:0x5594:selector];
		es_598->a32C6[0].b0000[wArg04].b0000 = bLoc1C_1843;
		es_598->a32C6[0].b0001[wArg04].b0000 = (byte) ((wLoc20_1459 & 0x0F00 | wLoc28_1460 & 0xF000) >> 0x08);
		es_598->a32C6[0].b0002[wArg04].b0000 = (byte) wLoc20_1459 & 0x7F;
		al_620 = (byte) wLoc28_1460 & 0x7F;
		es_si_1980 = (struct Eq_57996 *) ax_593;
	}
	else
	{
		int16 ax_626 = wArg04 *s16 0x30;
		struct Eq_57634 * es_630 = Mem500[ds_1021:0x5594:selector];
		es_630->a32C6[0].b0000[wArg04].b0000 = bLoc1C_1843;
		es_630->a32C6[0].b0001[wArg04] = (Eq_107843) (byte) ((wLoc04_1331 & 0x0F00 | wLoc06_1330 & 0xF000) >> 0x08);
		es_630->a32C6[0].b0002[wArg04] = (Eq_107845) ((byte) wLoc04_1331 & 0x7F);
		al_620 = (byte) wLoc06_1330 & 0x7F;
		es_si_1980 = (struct Eq_57996 *) ax_626;
	}
	es_si_1980->b32C9 = al_620;
	si_1022 = (word16) es_si_1980;
l1631_08F9:
	if (wArg04 >= 0x04 && wArg04 < 0x0C || wArg04 >= 0x10)
	{
		Mem661[ds_1021:21922:selector]:0x3800[wArg04 *16 0x0C] = bLoc14_1595;
		selector es_992 = Mem991[ds_1021:0x558E:selector];
		if (es_992->bD333 != 0x00 && (int16) es_992->bD331 + 0x04 == wArg04)
			Mem991[ds_1021:21922:selector]:0x3800[wArg04 *16 0x0C] = ~0x00;
	}
	else
	{
		if (wArg04 < 0x04 && wLoc14_1335 < 0x10 || wArg04 >= 0x0C && (wArg04 < 0x10 && wLoc14_1335 < 0x04))
		{
			cui16 ax_695 = Mem661[ds_1021:0x5592:selector]:0x4004[wArg04 *16 0x02];
			cui16 ax_698 = Mem696[ds_1021:0x5590:selector]:0x4036[wArg04 *16 0x02];
			cui16 ax_720 = Mem716[ds_1021:0x5592:selector]:0x4004[wLoc14_1335 *16 0x02];
			cui16 ax_723 = Mem721[ds_1021:0x5590:selector]:0x4036[wLoc14_1335 *16 0x02];
			cui16 ax_705 = (ax_695 & 0x0F00) >> 0x01 | ax_695 & 0x7F;
			cui16 ax_713 = (ax_698 & 0xF000) >> 0x05 | ax_698 & 0x7F;
			si_1022 = wLoc14_1335 << 0x01;
			cui16 ax_730 = (ax_720 & 0x0F00) >> 0x01 | ax_720 & 0x7F;
			cui16 ax_738 = (ax_723 & 0xF000) >> 0x05 | ax_723 & 0x7F;
			if (wLoc34_1389 != 0x00)
			{
				ss->*((word32) sp_18 - 6) = ax_730 + 0x01 - (ax_705 + 0x01);
				if (fn207F_3C6C(ss->*((word32) sp_18 - 6)) <= 0x03)
				{
					ss->*((word32) sp_18 - 6) = ax_738 - ax_713;
					if (fn207F_3C6C(ss->*((word32) sp_18 - 6)) < 0x02)
					{
						(Mem777[ds_1021:0x55A4:selector]->*((word32) wArg04 + 14700)).u5 = ~0x00;
						Mem789[ds_1021:0x5594:selector]:12998[wArg04 *16 0x30] = ~0x00;
						Mem808[ss:sp_18 + -6:word16] = Mem799[ds_1021:0x5590:selector]:0x4036[wLoc14_1335 *16 0x02];
						Mem812[ss:sp_18 + -8:word16] = Mem808[ds_1021:0x5592:selector]:0x4004[wLoc14_1335 *16 0x02];
						Mem816[ss:sp_18 + -0x0A:word16] = Mem812[ds_1021:0x5590:selector]:0x4036[wArg04 *16 0x02];
						Mem820[ss:sp_18 + -0x0C:word16] = Mem816[ds_1021:0x5592:selector]:0x4004[wArg04 *16 0x02];
						(Mem820[ds_1021:0x5578:selector]->*((word32) wArg04 + 14624)).u5 = (byte) fn207F_0971(ss->*((word32) sp_18 - 0x0C), ss->*((word32) sp_18 - 0x0A), ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6));
						si_1022 = wArg04 << 0x01;
						di_1039 = wLoc14_1335 << 0x01;
					}
				}
			}
		}
		Eq_58407 wLoc10_1571;
		wLoc10_1571.u0 = 0x00;
		Eq_58407 v58_849;
		do
		{
			Mem841[ds_1021:21922:selector]->*((word16) (wArg04 *s16 0x0C + wLoc10_1571) + 0x00003800) = (word16) ~0x00;
			v58_849 = (word16) wLoc10_1571 + 1;
			wLoc10_1571 = v58_849;
		} while (v58_849 < 0x0C);
		selector es_854 = Mem850[ds_1021:21912:selector];
		int16 wLoc36_1575 = (int16) (es_854->*((word32) wArg04 + 110));
		if (wArg04 >= 0x0C)
			wLoc36_1575 = (int16) (es_854->*((word32) wArg04 + 0x0066));
		if (wLoc36_1575 < 0x1E)
		{
			Eq_5 wLoc30_1583 = wArg04;
			if (wArg04 >= 0x0C)
				wLoc30_1583 = wArg04 - 0x08;
			Eq_5 wLoc10_1585;
			wLoc10_1585.u0 = 0x00;
			Eq_5 v70_952;
			do
			{
				ss->*((word32) sp_18 - 6) = wLoc10_1585;
				ss->*((word32) sp_18 - 8) = wLoc30_1583;
				if (fn1631_10A2(si_1022, di_1039, ds_1021, ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), out si_1022, out di_1039, out ds_1021) != 0xFF)
					Mem915[ds_1021:21922:selector]->*((word16) (wArg04 *s16 0x0C + wLoc10_1585) + 0x00003800) = (word16) bLoc14_1595;
				v70_952.u5 = (word32) wLoc10_1585 + 1;
				wLoc10_1585 = v70_952;
			} while (v70_952 < 0x0A);
			Mem953[ds_1021:21922:selector]:0x380B[wArg04 *16 0x0C] = bLoc14_1595;
		}
		else
		{
			Mem865[ds_1021:0x5594:selector]:12998[wArg04 *16 0x30] = ~0x00;
			ci16 wLoc10_1579 = 0x00;
			ci16 v69_891;
			do
			{
				Eq_58608 bx_885 = wArg04 *s16 0x0C + wLoc10_1579;
				selector es_887 = Mem881[ds_1021:21922:selector];
				es_887->*((word16) bx_885 + 0x00003800) |= 0x80;
				v69_891 = wLoc10_1579 + 0x01;
				wLoc10_1579 = v69_891;
			} while (v69_891 < 0x0C);
		}
	}
	ss->*((word32) sp_18 - 6) = wArg04;
	Eq_5 si_1092 = fn183B_193B(si_1022, di_1039, ds_1021, ss->*((word32) sp_18 - 6), out di_1088, out ds_1089);
	if (wLoc38_1316 == 0x00 && wArg06 != 0x00)
	{
		(ss->*((word32) sp_18 - 6)).u0 = 0x01;
		ss->*((word32) sp_18 - 8) = wArg04;
		si_1092 = fn183B_1774(si_1092, di_1088, ds_1089, ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), out di_1088, out ds_1089);
	}
	ss->*((word32) sp_18 - 6) = ax_36;
	ss->*((word32) sp_18 - 8) = ax_33;
	word16 di_1985;
	struct Eq_58158 * ds_1142;
	fn0800_17BB(si_1092, di_1088, ds_1089, ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), out di_1985, out ds_1142);
	Eq_5 si_1153 = ss->*((word32) sp_18 - 4);
	diOut = ss->*((word32) sp_18 - 2);
	dsOut = ds_1142;
	return si_1153;
}

// 1631:0BB5: Register int16 fn1631_0BB5(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Stack Eq_5 wArg06, Register out int16 siOut, Register out int16 diOut, Register out (ptr16 Eq_58741) dsOut)
// Called from:
//      fn1631_03AB
//      fn1631_0F24
//      fn183B_000A
int16 fn1631_0BB5(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, Eq_5 wArg06, int16 & siOut, int16 & diOut, struct Eq_58741 & dsOut)
{
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	int16 si_22;
	int16 di_19;
	struct Eq_58741 * ds_20;
	fn207F_2FDC(0x0A, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	struct Eq_58784 * es_43 = ds_20->ptr5582;
	struct Eq_58788 * es_51 = ds_20->ptr5584;
	ci16 ax_61 = ((es_43->wA44B & 0x0F00) >> 0x01 | es_43->wA44B & 0x7F) - ((wArg04 & 0x0F00) >> 0x01 | wArg04 & 0x7F);
	cui16 ax_41 = (wArg06 & 0xF000) >> 0x05 | wArg06 & 0x7F;
	cui16 ax_58 = (es_51->wA44D & 0xF000) >> 0x05 | es_51->wA44D & 0x7F;
	ci16 wLoc0A_119 = ax_61;
	if (ax_61 < 0x00)
		wLoc0A_119 = -ax_61;
	ci16 ax_77 = ax_58 - ax_41;
	ci16 wLoc0C_123 = ax_77;
	if (ax_77 < 0x00)
		wLoc0C_123 = -ax_77;
	int16 ax_101;
	if (wLoc0A_119 > wLoc0C_123)
		ax_101 = (wLoc0A_119 >> 0x01) + wLoc0C_123;
	else
		ax_101 = (wLoc0C_123 >> 0x01) + wLoc0A_119;
	siOut = si_22;
	diOut = di_19;
	dsOut = ds_20;
	return ax_101;
}

// 1631:0C63: Register Eq_5 fn1631_0C63(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 ptrArg04)
// Called from:
//      fn1AE8_000C
Eq_5 fn1631_0C63(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 ptrArg04)
{
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	word16 si_22;
	word16 di_593;
	Eq_5 ds_20;
	fn207F_2FDC(0x10, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_593, out ds_20);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	selector ss;
	(ss->*((word32) sp_18 - 2)).u5 = si_22;
	int16 wLoc0A_388;
	for (wLoc0A_388 = 0x00; wLoc0A_388 < 0x18; ++wLoc0A_388)
	{
		ci16 wLoc0C_463;
		for (wLoc0C_463 = 0x00; wLoc0C_463 < 0x0C; ++wLoc0C_463)
		{
			int8 * ptrLoc12_469 = SEQ(0x3092, wLoc0A_388 *s 0x0C + wLoc0C_463 + 0x3800);
			if (*ptrLoc12_469 != ~0x00)
			{
				*ptrLoc12_469 &= 0x7F;
				if (Mem345[ds_20:0x559A:selector]:0x406A[CONVERT(Mem345[ptrLoc12_469 + 0x00:byte], int8, int16) * 2] == 0x00)
					*ptrLoc12_469 = ~0x00;
			}
		}
	}
	Eq_58880 wLoc0A_390;
	wLoc0A_390.u0 = 0x00;
	while (wLoc0A_390 < 0x04)
	{
		Eq_58932 wLoc0C_410;
		wLoc0C_410.u0 = 0x00;
		while (wLoc0C_410 < 0x05)
		{
			if (Mem114[ds_20:0x558E:selector]:50980[(wLoc0A_390 + wLoc0C_410) * 0x7D] != ~0x00)
			{
				int16 ax_133 = CONVERT(Mem114[ds_20:0x5594:selector]:12998[wLoc0A_390 * 0x30], int8, int16);
				int16 wLoc06_413 = ax_133 + 0x01;
				if (ax_133 == 0x02)
				{
					int8 al_142 = (int8) ptrArg04.u5[(uipr32) wLoc0A_390];
					if (al_142 > 0x03)
						wLoc06_413 = (int16) al_142;
				}
				if (wLoc0C_410 != 0x00)
				{
					int16 ax_160 = CONVERT(Mem150[ds_20:0x5594:selector]:0x3506[wLoc0A_390 * 0x30], int8, int16);
					wLoc06_413 = ax_160 + 0x01;
					if (ax_160 == 0x02)
					{
						int8 al_169 = (int8) (SLICE(ptrArg04, selector, 16)->*(((char *) ((word16) ptrArg04) + 0x0C) + wLoc0A_390));
						if (al_169 > 0x03)
							wLoc06_413 = (int16) al_169;
					}
				}
				Eq_59046 ax_179 = wLoc0A_390 + wLoc0C_410;
				struct Eq_57354 * es_185 = Mem177[ds_20:0x558E:selector];
				uint16 wLoc06_428 = wLoc06_413 + (((es_185->aC744))[0].b0055)[ax_179] *16 0x05 - (uint16) (((es_185->aC744))[0].b0006)[ax_179];
				Eq_59067 wLoc0E_429;
				wLoc0E_429.u0 = 0x33;
				Eq_59067 v34_217;
				do
				{
					if (Mem199[ds_20:0x558E:selector]->*((word16) ((wLoc0A_390 + wLoc0C_410) *s 0x7D + wLoc0E_429) + 50980) == 0x22)
						--wLoc06_428;
					v34_217 = (word16) wLoc0E_429 + 1;
					wLoc0E_429 = v34_217;
				} while (v34_217 <= 0x55);
				Eq_59114 si_222 = wLoc0A_390 + wLoc0C_410;
				selector es_230 = Mem228[ds_20:21912:selector];
				es_230->*((word16) si_222 + 110) = (word16) (es_230->*((word16) si_222 + 110)) + ((word16) (Mem218[ds_20:0x55A6:selector]->*((word16) si_222 + 0x0092)) + (byte) wLoc06_428);
				if (Mem232[ds_20:0x55A8:selector]->*((word16) si_222 + 54646) != 0x00)
				{
					selector es_236 = Mem232[ds_20:21912:selector];
					es_236->*((word16) si_222 + 110) = (word16) (es_236->*((word16) si_222 + 110)) + 6;
					selector es_240 = Mem238[ds_20:0x55A8:selector];
					--es_240->*((word16) si_222 + 54646);
				}
				int16 wLoc08_443 = (int16) (Mem246[ds_20:0x55AA:selector]->*((word16) wLoc0A_390 + 0x000032AE));
				Eq_59163 wLoc04_444;
				wLoc04_444.u1 = (uint16) (Mem252[ds_20:0x55AC:selector]->*((word16) wLoc0A_390 + 14160));
				if (wLoc0C_410 != 0x00)
				{
					wLoc08_443 = (int16) (Mem257[ds_20:0x55AA:selector]->*((word16) wLoc0A_390 + 0x000032BA));
					wLoc04_444.u1 = (uint16) (Mem263[ds_20:0x55AC:selector]->*((word16) wLoc0A_390 + 14172));
				}
				if (wLoc08_443 != 0x00 && wLoc04_444 < 0x10)
				{
					Eq_59225 bx_278 = wLoc0A_390 + wLoc0C_410;
					selector es_280 = Mem272[ds_20:21912:selector];
					es_280->*((word16) bx_278 + 110) -= 0x04;
				}
				ci8 * ptrLoc12_456 = SEQ(0x3092, wLoc0A_390 + wLoc0C_410 + 110);
				if (*ptrLoc12_456 < 0x00)
					*ptrLoc12_456 = 0x00;
				selector es_304 = Mem300[ds_20:21912:selector];
				if (es_304->*((word16) wLoc0A_390 + 110) > 0x1E)
					es_304->*((word16) wLoc0A_390 + 110) = 0x1E;
			}
			Mem310[ds_20:0x55A6:selector]->*((word16) (wLoc0A_390 + wLoc0C_410) + 0x0092) = (word16) 0x00;
			wLoc0C_410 = (word16) wLoc0C_410 + 4;
		}
		wLoc0A_390 = (word16) wLoc0A_390 + 1;
	}
	int16 wLoc0A_392 = 0x00;
	int16 v26_97;
	do
	{
		if (Mem46[ds_20:0x558E:selector]:50708[wLoc0A_392 * 0x11] == ~0x00)
		{
			Eq_58955 wLoc0C_394 = wLoc0A_392 + 0x04;
			if (wLoc0A_392 >= 0x08)
				wLoc0C_394 = (word16) wLoc0C_394 + 4;
			if (wLoc0A_392 != 0x00)
			{
				Mem64[ds_20:0x5590:selector]:0x4036[wLoc0C_394 * 0x02] = ~0x00;
				Mem73[ds_20:0x5592:selector]:0x4004[wLoc0C_394 * 0x02] = ~0x00;
			}
			if (wLoc0C_394 >= 0x10)
				Mem78[ds_20:0x55AE:selector]->*((word16) wLoc0C_394 + 0x0000D55E) = ~0x01;
			if (wLoc0A_392 == 0x00)
				Mem87[ds_20:0x55AE:selector]->*((word16) wLoc0C_394 + 0x0000D55E) = 0x96;
		}
		v26_97 = wLoc0A_392 + 0x01;
		wLoc0A_392 = v26_97;
	} while (v26_97 < 0x10);
	return ds_20;
}

// 1631:0F24: Register word16 fn1631_0F24(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Stack Eq_5 wArg06, Register out word16 siOut, Register out Eq_53466 diOut, Register out (ptr16 Eq_53469) dsOut)
// Called from:
//      fn1543_0004
//      fn1543_07CB
//      fn1AE8_000C
word16 fn1631_0F24(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, Eq_5 wArg06, word16 & siOut, union Eq_53466 & diOut, struct Eq_53469 & dsOut)
{
	struct Eq_53469 * ds_153;
	Eq_53466 di_152;
	word16 si_337;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	word16 si_22;
	Eq_5 di_143;
	Eq_5 ds_139;
	fn207F_2FDC(0x0E, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_143, out ds_139);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	selector ss;
	(ss->*((word32) sp_18 - 2)).u5 = si_22;
	Eq_5 ax_33 = Mem29[ds_139:0x5592:selector]:0x4004[wArg04 *16 0x02];
	Eq_5 ax_36 = Mem34[ds_139:0x5590:selector]:0x4036[wArg04 *16 0x02];
	Eq_5 si_140 = wArg04 << 0x01;
	Eq_5 wLoc0C_237 = ax_33;
	Eq_5 wLoc0E_238 = ax_36;
	if (wArg04 < 0x04 || wArg04 >= 0x0C && wArg04 <= 0x0F)
	{
		ss->*((word32) sp_18 - 4) = ax_36;
		ss->*((word32) sp_18 - 6) = ax_33;
		if (fn1631_0BB5(wArg04 << 0x01, di_143, ds_139, ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4), out si_140, out di_143, out ds_139) > 0x03)
		{
			if (Mem53[ds_139:0x5582:selector]->tA44B < ax_33)
			{
				wLoc0C_237 = ax_33 - 0x01;
				if (((byte) ax_33 - 0x01 & 0x80) != 0x00)
					wLoc0C_237 = ax_33 - 0x01 & 0x0F7F;
			}
			if (Mem91[ds_139:0x5582:selector]->tA44B > wLoc0C_237)
			{
				Eq_5 v24_98;
				v24_98.u5 = (word32) wLoc0C_237 + 1;
				wLoc0C_237 = v24_98;
				if (((byte) v24_98 & 0x80) != 0x00)
					wLoc0C_237.u5 = (word32) v24_98 + 0x0080;
			}
			if (Mem109[ds_139:0x5584:selector]->tA44D < ax_36)
			{
				wLoc0E_238 = ax_36 - 0x02;
				if (((byte) ax_36 - 0x02 & 0x80) != 0x00)
					wLoc0E_238 = ax_36 - 0x02 & ~0x0F80;
			}
		}
	}
	ss->*((word32) sp_18 - 4) = wLoc0E_238;
	ss->*((word32) sp_18 - 6) = wLoc0C_237;
	Eq_57740 ax_149 = fn1631_0BB5(si_140, di_143, ds_139, ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4), out si_337, out di_152, out ds_153);
	word16 wLoc10_257 = 0x03;
	if ((uint16) ds_153->a2EE4[0].b0003[wArg06] > ax_149)
		wLoc10_257 = 0x02;
	uint16 ax_185 = (uint16) ds_153->a2EE4[0].b0002[wArg06];
	Eq_57740 wLoc04_266 = ax_185 & 0x1F;
	Eq_57740 wLoc08_267 = ax_185 >> 0x05;
	if (ds_153->a2EE4[0].b0000[wArg06].b0000 < 0x80 && wArg06 != 0x20)
	{
		wLoc04_266 = (ax_185 & 0x1F) * 0x03;
		wLoc08_267 = (ax_185 >> 0x05) * 0x03;
	}
	if (ax_149 < wLoc04_266)
		wLoc10_257 = 0x01;
	if (ax_149 < wLoc08_267)
		wLoc10_257 = 0x00;
	siOut = (word16) (ss->*((word32) sp_18 - 2));
	diOut = di_152;
	dsOut = ds_153;
	return wLoc10_257;
}

// 1631:1057: Register Eq_5 fn1631_1057(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Stack Eq_5 wArg06, Register out word16 diOut, Register out (ptr16 Eq_54294) dsOut)
// Called from:
//      fn1543_0004
Eq_5 fn1631_1057(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, Eq_5 wArg06, word16 & diOut, struct Eq_54294 & dsOut)
{
	struct Eq_54294 * ds_118;
	word16 di_117;
	Eq_5 ds_101;
	Eq_5 di_100;
	Eq_5 ds_53;
	Eq_5 di_52;
	Eq_5 ds_38;
	Eq_5 di_37;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	Eq_5 di_19;
	Eq_5 ds_20;
	fn207F_2FDC(0x02, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	Eq_5 ax_29 = Mem7[ds_20:0x55B0:selector]->t4600;
	selector ss;
	(ss->*((word32) sp_18 - 2)).u0 = 0x04;
	Eq_5 si_56 = fn1E56_0388(fp - 2, fn1E56_0281(si_22, di_19, ds_20, ss->*((word32) sp_18 - 2), out di_37, out ds_38), di_37, ds_38, out di_52, out ds_53);
	Eq_5 sp_57;
	sp_57.u0 = <invalid>;
	ss->*((word32) sp_57 - 2) = wArg06;
	ss->*((word32) sp_57 - 4) = wArg04;
	Eq_5 si_76;
	Eq_5 di_72;
	Eq_5 ds_73;
	fn1E56_03F5(si_56, di_52, ds_53, ss->*((word32) sp_57 - 4), out si_76, out di_72, out ds_73);
	Eq_5 si_91;
	Eq_5 di_87;
	Eq_5 ds_88;
	fn1F3D_0259(si_76, di_72, ds_73, out si_91, out di_87, out ds_88);
	Eq_5 si_104 = fn1E56_0388(fp - 2, si_91, di_87, ds_88, out di_100, out ds_101);
	Eq_5 sp_105;
	sp_105.u0 = <invalid>;
	ss->*((word32) sp_105 - 2) = ax_29;
	Eq_5 si_121 = fn1E56_0281(si_104, di_100, ds_101, ss->*((word32) sp_105 - 2), out di_117, out ds_118);
	diOut = di_117;
	dsOut = ds_118;
	return si_121;
}

// 1631:10A2: Register cui16 fn1631_10A2(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Stack Eq_5 wArg06, Register out int16 siOut, Register out Eq_58654 diOut, Register out (ptr16 Eq_58656) dsOut)
// Called from:
//      fn1631_03AB
//      fn1AE8_000C
cui16 fn1631_10A2(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, Eq_5 wArg06, int16 & siOut, union Eq_58654 & diOut, struct Eq_58656 & dsOut)
{
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	int16 si_22;
	Eq_58654 di_19;
	struct Eq_58656 * ds_20;
	fn207F_2FDC(0x08, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	selector ss;
	(ss->*((word32) sp_18 - 2)).u5 = di_19;
	(ss->*((word32) sp_18 - 4)).u2 = si_22;
	Eq_5 wLoc04_100;
	wLoc04_100.u0 = 0x00;
	cui16 wLoc0A_102 = 0xFF;
	Eq_59587 wLoc06_104;
	wLoc06_104.u0 = 0x33;
	Eq_59587 v23_74;
	do
	{
		struct Eq_57354 * es_45 = ds_20->ptr558E;
		uint16 ax_48 = (uint16) (es_45->*((word16) ((word16) wLoc06_104 + wArg04 *s16 0x7D) + 50980));
		if ((ax_48 & 0x7F) >= 0x10 && (ax_48 & 0x7F) <= 0x20)
		{
			wLoc04_100.u5 = (word32) wLoc04_100 + 1;
			if (wLoc04_100 == wArg06)
			{
				wLoc0A_102 = ax_48 - 1;
				if ((wArg06.u5 + wArg04 *s16 0x7D)[51019] == 0x00)
					wLoc0A_102 = 0xFF;
				wLoc06_104.u0 = 0x57;
			}
		}
		v23_74 = (word16) wLoc06_104 + 1;
		wLoc06_104 = v23_74;
	} while (v23_74 < 0x56);
	Eq_58654 di_84 = ss->*((word32) sp_18 - 2);
	siOut = (int16) (ss->*((word32) sp_18 - 4));
	diOut = di_84;
	dsOut = ds_20;
	return wLoc0A_102;
}

// 1631:1122: Register cup16 fn1631_1122(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Register out Eq_59650 siOut, Register out word16 diOut, Register out (ptr16 Eq_59654) dsOut)
// Called from:
//      fn1AE8_000C
cup16 fn1631_1122(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, union Eq_59650 & siOut, word16 & diOut, struct Eq_59654 & dsOut)
{
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_59650 si_22;
	word16 di_19;
	struct Eq_59654 * ds_20;
	fn207F_2FDC(0x02, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	if (wArg04 >= 0x11 && wArg04 <= 0x18)
		wLoc04 = (cup16) ((word32) wArg04 + 11);
	else if (wArg04 <= 0x23 && wArg04 >= 0x19)
	{
		switch (wArg04)
		{
		case 0x19:
			wLoc04 = 0x1D;
			break;
		case 0x1A:
			wLoc04 = 0x20;
			break;
		case 0x1B:
			wLoc04 = 0x22;
			break;
		case 0x1C:
		case 0x1E:
			wLoc04 = 0x12;
			break;
		case 0x1D:
		case 0x22:
			wLoc04 = 0x15;
			break;
		case 0x1F:
		case 0x20:
			Mem7[ds_20:0x55B2:selector]->wE484 = 0x01;
			break;
		case 33:
		case 0x23:
			wLoc04 = 0x17;
			break;
		}
	}
	siOut = si_22;
	diOut = di_19;
	dsOut = ds_20;
	return wLoc04;
}

// 1631:11AB: Register Eq_5 fn1631_11AB(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Stack Eq_5 wArg06, Register out Eq_5 diOut, Register out Eq_5 dsOut)
// Called from:
//      fn1AE8_000C
Eq_5 fn1631_11AB(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, Eq_5 wArg06, union Eq_5 & diOut, union Eq_5 & dsOut)
{
	word16 si_1106;
	Eq_5 ds_89;
	Eq_5 di_88;
	Eq_5 ds_109;
	Eq_5 di_108;
	Eq_5 si_112;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	Eq_5 di_19;
	Eq_5 ds_20;
	fn207F_2FDC(0x12, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	selector ss;
	ss->*((word32) sp_18 - 2) = si_22;
	word16 wLoc06_835 = 0x00;
	int16 wLoc0C_836 = 0x01;
	if (Mem31[ds_20:0x558E:selector]->*((word16) (wArg04 *s16 0x7D + wArg06) + 50980) == 0x00)
		wLoc06_835 = 0x01;
	Eq_27220 ax_47 = fn0800_19DD(fp - 2, si_22, di_19, ds_20, out si_112, out di_108, out ds_109);
	Eq_5 sp_55;
	sp_55.u0 = <invalid>;
	if (ax_47 >= 0x08)
		wLoc0C_836 = (ax_47 - 0x08 >> 0x01) + 0x01;
	if (Mem71[ds_109:11832:word16] != 0x00 && wLoc0C_836 != 0x00)
	{
		(ss->*((word32) sp_55 - 2)).u0 = 0x04;
		Eq_5 si_92 = fn1E56_0281(si_112, di_108, ds_109, ss->*((word32) sp_55 - 2), out di_88, out ds_89);
		ss->*((word32) sp_55 - 2) = ds_89;
		(ss->*((word32) sp_55 - 4)).u0 = 0x315E;
		si_112 = fn1631_1DAB(si_92, di_88, ds_89, ss->*((word32) sp_55 - 4), out di_108, out ds_109);
		Mem104[ds_109:0x55B4:selector]->w4586 = 0x01;
	}
	Eq_5 sp_252 = sp_55;
	if (wLoc06_835 != 0x00)
	{
		wLoc0C_836 = 0x00;
		int16 ax_131 = (int16) (ds_109->*((word32) wArg06 + 0x0000316E));
		int16 wLoc0A_852;
		for (wLoc0A_852 = 0x00; (int16) (ds_109->*((word32) wArg06 + 12662)) > wLoc0A_852; ++wLoc0A_852)
		{
			byte * ptrLoc12_859 = SEQ(0x3092, wArg04 *s16 0x7D + ax_131 + wLoc0A_852 + 50980);
			if (*ptrLoc12_859 != 0x00)
				*ptrLoc12_859 |= 0x80;
		}
		if (wArg06 != 0x1C)
		{
			if (wArg06 != 0x1E)
			{
				if (wArg06 != 33)
				{
					if (wArg06 == 0x23)
					{
						struct Eq_57354 * es_210 = Mem136[ds_109:0x558E:selector];
						es_210->aC744[0].b0005[wArg04].b0000 = es_210->aC744[0].b0005[wArg04].b0000 & 0xF0;
					}
				}
				else
				{
					struct Eq_57354 * es_198 = Mem136[ds_109:0x558E:selector];
					es_198->aC744[0].b0005[wArg04].b0000 = es_198->aC744[0].b0005[wArg04] & 0x0F;
				}
			}
			else
			{
				struct Eq_57354 * es_186 = Mem136[ds_109:0x558E:selector];
				es_186->aC744[0].b0004[wArg04].b0000 = es_186->aC744[0].b0004[wArg04].b0000 & 0xF0;
			}
		}
		else
		{
			struct Eq_57354 * es_174 = Mem136[ds_109:0x558E:selector];
			es_174->aC744[0].b0004[wArg04].b0000 = es_174->aC744[0].b0004[wArg04] & 0x0F;
		}
	}
	while (true)
	{
l1631_129E:
		if (wLoc0C_836 == 0x00)
			break;
		if (wArg06 <= 0x23 && wArg06 >= 0x1C)
		{
			switch (wArg06)
			{
			case 0x1C:
			case 33:
				<unknown> Eq_57354::* wLoc04_898 = &Eq_57354::t0024;
				word16 wLoc08_899 = 0x33;
				if (wArg06 == 33)
				{
					wLoc04_898 = &Eq_57354::t0025;
					wLoc08_899 = 0x41;
				}
				si_112 = wArg04 *s16 0x7D;
				if ((((char *) wLoc04_898 + wArg04 *s16 0x7D)[50980] & 0xF0) != 0x00)
					goto l1631_157B;
				struct Eq_60329 Eq_59705::* sp_594 = sp_252 - 2;
				(ss->*sp_594).w0000 = 0x07;
				(ss->*sp_594).tFFFFFFFE.u0 = 0x3092;
				(ss->*sp_594).tFFFFFFFC.u0 = (word16) (wLoc08_899 + 50980 + wArg04 *s16 0x7D);
				Eq_60288 bx_513;
				byte al_515;
				word16 wLoc04_887;
				if (fn1631_15FA(wArg04 *s16 0x7D, di_108, ds_109, (ss->*sp_594).tFFFFFFFC.u1, (ss->*sp_594).w0000, out si_112, out di_108, out ds_109) != 0x00)
				{
l1631_157B:
					struct Eq_5398 * ds_ax_1100 = fn0800_19F3(si_112, di_108, ds_109, out si_112, out di_108);
					ds_109.u5 = SLICE(ds_ax_1100, selector, 16);
					Eq_5 ax_631 = (word16) ds_ax_1100;
					if (ax_631 >= 0x03)
					{
						Eq_60369 ax_651 = (char *) wLoc04_898 + wArg04 *s16 0x7D;
						uint8 al_658 = *SEQ(0x3092, (word16) ax_651 + 50980);
						if ((al_658 & 0xF0) != 0x00)
						{
							if (((uint16) al_658 & (int16) ds_ax_1100->b317A) == 0x00)
								goto l1631_129E;
							bx_513 = (word16) ax_651 + 50980;
							si_112 = ax_631;
							al_515 = ds_ax_1100->b3182;
							goto l1631_14C1;
						}
					}
					wLoc04_887 = 0x33;
					if (wArg06 == 33)
						wLoc04_887 = 0x41;
					goto l1631_1520;
				}
				break;
			case 0x1D:
			case 0x22:
				wLoc04_887 = 0x3A;
				if (wArg06 == 0x22)
					wLoc04_887 = 0x48;
				struct Eq_60111 Eq_59705::* sp_525 = sp_252 - 2;
				(ss->*sp_525).w0000 = 0x07;
				(ss->*sp_525).tFFFFFFFE.u0 = 0x3092;
				(ss->*sp_525).tFFFFFFFC.u0 = (word16) (wLoc04_887 + 50980 + wArg04 *s16 0x7D);
				word16 ax_502;
				if (fn1631_15FA(wArg04 *s16 0x7D, di_108, ds_109, (ss->*sp_525).tFFFFFFFC.u1, (ss->*sp_525).w0000, out si_112, out di_108, out ds_109) != 0x00)
				{
l1631_1520:
					ax_502 = 0x07;
					goto l1631_14DA;
				}
				break;
			case 0x1E:
			case 0x23:
				<unknown> Eq_57354::* wLoc04_871 = &Eq_57354::t0024;
				word16 wLoc08_872 = 0x4F;
				if (wArg06 == 0x23)
				{
					wLoc04_871 = &Eq_57354::t0025;
					wLoc08_872 = 0x51;
				}
				si_112 = wArg04 *s16 0x7D;
				word16 Eq_59705::* sp_253;
				Eq_5 ax_261;
				if ((((char *) wLoc04_871 + wArg04 *s16 0x7D)[50980] & 0x0F) != 0x00)
				{
l1631_1473:
					struct Eq_5398 * ds_ax_1099 = fn0800_19F3(si_112, di_108, ds_109, out si_112, out di_108);
					ds_109.u5 = SLICE(ds_ax_1099, selector, 16);
					Eq_5 ax_463 = (word16) ds_ax_1099;
					if (ax_463 >= 0x03)
					{
						Eq_60267 ax_483 = (char *) wLoc04_871 + wArg04 *s16 0x7D;
						uint8 al_490 = *SEQ(0x3092, (word16) ax_483 + 50980);
						if ((al_490 & 0x0F) != 0x00)
						{
							if (((uint16) al_490 & (int16) ds_ax_1099->b316A) == 0x00)
								goto l1631_129E;
							bx_513 = (word16) ax_483 + 50980;
							si_112 = ax_463;
							al_515 = ds_ax_1099->b3172;
l1631_14C1:
							0x3092->*bx_513 &= al_515;
							goto l1631_1341;
						}
					}
					wLoc04_887 = 0x4F;
					if (wArg06 == 0x23)
						wLoc04_887 = 0x51;
					ax_502 = 0x02;
l1631_14DA:
					sp_253 = sp_252 - 2;
					ss->*sp_253 = ax_502;
					si_112 = wArg04 *s16 0x7D;
					ax_261 = wLoc04_887 + 50980 + wArg04 *s16 0x7D;
					goto l1631_13A3;
				}
				struct Eq_60183 Eq_59705::* sp_426 = sp_252 - 2;
				(ss->*sp_426).w0000 = 0x02;
				(ss->*sp_426).tFFFFFFFE.u0 = 0x3092;
				(ss->*sp_426).tFFFFFFFC.u0 = (word16) (wLoc08_872 + 50980 + wArg04 *s16 0x7D);
				if (fn1631_15FA(wArg04 *s16 0x7D, di_108, ds_109, (ss->*sp_426).tFFFFFFFC.u1, (ss->*sp_426).w0000, out si_112, out di_108, out ds_109) != 0x00)
					goto l1631_1473;
				break;
			case 0x1F:
				struct Eq_5398 * ds_ax_1103 = fn0800_19F3(si_112, di_108, ds_109, out si_112, out di_108);
				word16 ax_309 = (word16) ds_ax_1103;
				ds_109.u5 = SLICE(ds_ax_1103, selector, 16);
				if (ax_309 != 0x01)
				{
					if (ax_309 == 0x02)
					{
l1631_1347:
						struct Eq_57354 * es_357 = Mem218[ds_109:0x558E:selector];
						if (es_357->aC744[0].b0057[wArg04] >= 0x02)
							goto l1631_129E;
						es_357->aC744[0].b0057[wArg04].b0000 = es_357->aC744[0].b0057[wArg04].b0000 + 0x01;
l1631_1341:
						--wLoc0C_836;
						goto l1631_129E;
					}
					if (ax_309 == 0x03)
					{
						Mem329[ds_109:0x558E:selector]:51011[wArg04 *16 0x7D] = 0x00;
						goto l1631_1385;
					}
					if (ax_309 == 0x04)
					{
						sp_253 = sp_252 - 2;
						ss->*sp_253 = 0x01;
						ax_261 = wArg04 *s16 0x7D + ~0x3886;
						goto l1631_13A3;
					}
					if (ax_309 == 0x05)
						goto l1631_1347;
					if (ax_309 != 0x06)
						goto l1631_129E;
				}
				struct Eq_57354 * es_379 = Mem218[ds_109:0x558E:selector];
				if (es_379->aC744[0].b0058[wArg04] == 0x00)
					goto l1631_129E;
				es_379->aC744[0].b0058[wArg04].b0000 = ~0x00;
				goto l1631_1341;
			case 0x20:
				struct Eq_5398 * ds_ax_1104 = fn0800_19F3(si_112, di_108, ds_109, out si_112, out di_108);
				ds_109.u5 = SLICE(ds_ax_1104, selector, 16);
				if ((word16) ds_ax_1104 <= 0x03)
				{
					struct Eq_5398 * ds_ax_1105 = fn0800_19F3(si_112, di_108, ds_109, out si_1106, out di_108);
					ds_109.u5 = SLICE(ds_ax_1105, selector, 16);
					struct Eq_57354 * es_283;
					bool v49_829;
					if ((word16) ds_ax_1105 <= 0x03)
					{
						es_283 = Mem288[ds_109:0x558E:selector];
						es_283->aC744[0].b0056[wArg04].b0000 = (byte) ((word1000) es_283->aC744[0].b0056[wArg04] + 1);
						--wLoc0C_836;
						v49_829 = es_283->aC744[0].b0056[wArg04].b0000 >= 0x02;
					}
					else
					{
						es_283 = Mem278[ds_109:0x558E:selector];
						es_283->aC744[0].b0055[wArg04].b0000 = es_283->aC744[0].b0055[wArg04].b0000 + 0x01;
						--wLoc0C_836;
						v49_829 = es_283->aC744[0].b0055[wArg04].b0000 >= 0x03;
					}
					si_112 = wArg04 *s16 0x7D;
					if (v49_829)
					{
						es_283->aC744[0].b0000[wArg04].b0000 = 0x00;
l1631_1385:
						Mem342[ds_109:0x55B2:selector]->wE484 = 0x01;
						wLoc0C_836 = 0x00;
					}
				}
				else
				{
					sp_253 = sp_252 - 2;
					ss->*sp_253 = 0x02;
					ax_261 = wArg04 *s16 0x7D + ~0x3888;
l1631_13A3:
					struct Eq_60227 Eq_59705::* sp_697 = sp_253 - 2;
					(ss->*sp_697).w0000 = 0x3092;
					(ss->*sp_697).tFFFFFFFE.u0 = (wchar_t) ax_261;
					sp_252.u5 = sp_697 + 2;
					wLoc0C_836 -= fn1631_163E(si_112, di_108, ds_109, (ss->*sp_697).tFFFFFFFE.u5, sp_697[1], out si_112, out di_108, out ds_109);
				}
				goto l1631_129E;
			}
			wLoc0C_836 = 0x00;
		}
	}
	Eq_5 si_773;
	si_773.u5 = (ss->*sp_252.u7).t0000.u1;
	diOut = di_108;
	dsOut = ds_109;
	return si_773;
}

// 1631:15FA: Register word16 fn1631_15FA(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_60126 ptrArg04, Stack ci16 wArg08, Register out int16 siOut, Register out word16 diOut, Register out (ptr16 Eq_60151) dsOut)
// Called from:
//      fn1631_11AB
//      fn1631_163E
word16 fn1631_15FA(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_60126 ptrArg04, ci16 wArg08, int16 & siOut, word16 & diOut, struct Eq_60151 & dsOut)
{
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	int16 si_22;
	word16 di_19;
	struct Eq_60151 * ds_20;
	fn207F_2FDC(0x06, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	selector ss;
	(ss->*((word32) sp_18 - 2)).u2 = si_22;
	word16 wLoc06_72 = 0x00;
	ci16 wLoc04_73;
	for (wLoc04_73 = 0x00; wLoc04_73 < wArg08; ++wLoc04_73)
	{
		byte al_42 = (byte) *((word32) ptrArg04.u1 + (uipr32) wLoc04_73);
		if (al_42 != 0x00 && (al_42 & 0x80) == 0x00)
			++wLoc06_72;
	}
	siOut = (int16) (ss->*((word32) sp_18 - 2));
	diOut = di_19;
	dsOut = ds_20;
	return wLoc06_72;
}

// 1631:163E: Register word16 fn1631_163E(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 ptrArg04, Stack ci16 wArg08, Register out Eq_5 siOut, Register out word16 diOut, Register out (ptr16 Eq_60258) dsOut)
// Called from:
//      fn1631_11AB
word16 fn1631_163E(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 ptrArg04, ci16 wArg08, union Eq_5 & siOut, word16 & diOut, struct Eq_60258 & dsOut)
{
	word16 wArg06 = SLICE(ptrArg04, word16, 16);
	Eq_60126 wArg04 = (word16) ptrArg04;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	Eq_5 di_19;
	Eq_5 ds_20;
	fn207F_2FDC(0x06, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	selector ss;
	ss->*((word32) sp_18 - 2) = si_22;
	(ss->*((word32) sp_18 - 4)).u5 = wArg08;
	(ss->*((word32) sp_18 - 6)).u5 = wArg06;
	(ss->*((word32) sp_18 - 8)).u5 = wArg04;
	word16 wLoc06_124 = 0x00;
	word16 si_196;
	word16 di_43;
	struct Eq_60258 * ds_44;
	if (fn1631_15FA(si_22, di_19, ds_20, ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 4), out si_196, out di_43, out ds_44) != 0x00)
	{
		ci16 wLoc04_128 = fn207F_0BC0() & 0x03;
		while (true)
		{
			if (wLoc04_128 >= wArg08)
				wLoc04_128 = 0x00;
			if (wLoc06_124 != 0x00)
				break;
			byte al_85 = ptrArg04.u5[(uipr32) wLoc04_128];
			if (al_85 != 0x00 && (al_85 & 0x80) == 0x00)
			{
				ptrArg04.u5[(uipr32) wLoc04_128] |= 0x80;
				++wLoc06_124;
			}
			++wLoc04_128;
		}
	}
	siOut = ss->*((word32) sp_18 - 2);
	diOut = di_43;
	dsOut = ds_44;
	return wLoc06_124;
}

// 1631:16AB: Register word16 fn1631_16AB(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Stack Eq_5 wArg0A, Register out Eq_57235 diOut, Register out Eq_5 dsOut)
// Called from:
//      fn1631_0006
//      fn1AE8_000C
word16 fn1631_16AB(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, Eq_5 wArg0A, union Eq_57235 & diOut, union Eq_5 & dsOut)
{
	Eq_5 ds_491;
	Eq_5 di_490;
	Eq_5 ds_473;
	Eq_5 di_472;
	Eq_5 ds_453;
	Eq_5 di_452;
	Eq_5 ds_404;
	Eq_5 di_403;
	Eq_5 ds_389;
	Eq_5 di_388;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	Eq_5 di_167;
	Eq_5 ds_125;
	fn207F_2FDC(0x22, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_167, out ds_125);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	selector ss;
	ss->*((word32) sp_18 - 2) = di_167;
	ss->*((word32) sp_18 - 4) = si_22;
	Eq_5 sp_30 = sp_18 - 4;
	word16 wLoc08_746 = 0x00;
	if (wArg04 >= 0x04 && wArg04 < 0x0C || wArg04 >= 0x10)
	{
		Eq_5 wLoc1A_751;
		wLoc1A_751.u0 = 0x04;
		Eq_5 v32_106;
		do
		{
			if (wLoc1A_751 != wArg04 && (Mem60[ds_125:0x5592:selector]:0x4004[wLoc1A_751 *16 0x02] == Mem60[Mem60[ds_125:0x5582:selector]:0xA44B:word16] && Mem60[ds_125:0x5590:selector]:0x4036[wLoc1A_751 *16 0x02] == Mem60[Mem60[ds_125:0x5584:selector]:0xA44D:word16]))
			{
				wLoc08_746 = 0x01;
				wLoc1A_751.u0 = 0x0C;
			}
			if (wLoc08_746 == 0x00 && ((word32) wLoc1A_751 + 0x0C != wArg04 && (Mem81[ds_125:0x5592:selector]:0x401C[wLoc1A_751 *16 0x02] == Mem81[Mem81[ds_125:0x5582:selector]:0xA44B:word16] && Mem81[ds_125:0x5590:selector]:0x404E[wLoc1A_751 *16 0x02] == Mem81[Mem81[ds_125:0x5584:selector]:0xA44D:word16])))
			{
				wLoc08_746 = 0x01;
				wLoc1A_751.u0 = 0x0C;
			}
			v32_106.u5 = (word32) wLoc1A_751 + 1;
			wLoc1A_751 = v32_106;
		} while (v32_106 < 0x0C);
		if (wLoc08_746 == 0x00)
		{
			Eq_5 ax_114 = Mem107[ds_125:0x5582:selector]->tA44B;
			Eq_5 ax_117 = Mem115[ds_125:0x5584:selector]->tA44D;
			ci16 wLoc1A_767 = 0x00;
			while (true)
			{
				sp_30 = sp_18 - 4;
				if (wLoc1A_767 >= 0x04)
					break;
				ci16 wLoc20_771;
				for (wLoc20_771 = 0x00; wLoc20_771 < 0x0D; wLoc20_771 += 0x0C)
				{
					int16 si_142 = wLoc1A_767 + wLoc20_771;
					Mem148[Mem135[ds_125:0x5582:selector]:0xA44B:word16] = Mem135[ds_125:0x5592:selector]:0x4004[si_142 * 0x02];
					Eq_5 ax_150 = Mem148[ds_125:0x5590:selector]:0x4036[si_142 * 0x02];
					Mem148[ds_125:0x5584:selector]->tA44D = ax_150;
					if (ax_117 == ax_150)
					{
						if (ax_114 != Mem152[ds_125:0x5582:selector]->tA44B)
						{
							(ss->*((word32) sp_18 - 6)).u0 = 0x00;
							(ss->*((word32) sp_18 - 8)).u0 = ~0x00;
							Eq_5 si_176 = fn0800_191B(si_142 << 0x01, di_167, ds_125, ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), out di_167, out ds_125);
							if (ax_114 == Mem166[ds_125:0x5582:selector]->tA44B)
								goto l1631_17DC;
							(ss->*((word32) sp_18 - 6)).u0 = 0x00;
							(ss->*((word32) sp_18 - 8)).u0 = 0x02;
							fn0800_191B(si_176, di_167, ds_125, ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), out di_167, out ds_125);
							if (ax_114 == Mem193[ds_125:0x5582:selector]->tA44B)
								goto l1631_17DC;
						}
						else
						{
l1631_17DC:
							wLoc08_746 = 0x01;
						}
					}
					if (wLoc08_746 != 0x00)
					{
						wLoc1A_767 = 0x0E;
						wLoc20_771 = 0x0E;
					}
				}
				++wLoc1A_767;
			}
			Mem122[ds_125:0x5582:selector]->tA44B = ax_114;
			Mem128[ds_125:0x5584:selector]->tA44D = ax_117;
		}
	}
	else
	{
		Eq_5 ax_231 = Mem32[ds_125:0x5582:selector]->tA44B;
		cui16 wLoc1E_786 = (cui16) ((word32) ax_231 + 1);
		if (((byte) ax_231 + 0x01 & 0x80) != 0x00)
			wLoc1E_786 = (cui16) ((word32) ax_231 + 0x0081);
		cui16 ax_249 = (wLoc1E_786 & 0x0F00) >> 0x01 | wLoc1E_786 & 0x7F;
		ci16 wLoc1A_791;
		for (wLoc1A_791 = 0x00; wLoc1A_791 < 0x04; ++wLoc1A_791)
		{
			ci16 wLoc20_862;
			for (wLoc20_862 = 0x00; wLoc20_862 < 0x0D; wLoc20_862 += 0x0C)
			{
				Eq_5 si_625 = wLoc1A_791 + wLoc20_862;
				di_167 = si_625 << 0x01;
				if (Mem618[ds_125:0x559A:selector]:0x406A[si_625 *16 0x02] != 0x00 && (wArg04 != si_625 && Mem618[ds_125:0x5590:selector]:0x4036[si_625 *16 0x02] == Mem618[Mem618[ds_125:0x5584:selector]:0xA44D:word16]))
				{
					word16 ax_640 = Mem618[ds_125:0x5592:selector]:0x4004[si_625 *16 0x02];
					cui16 wLoc0A_867 = ax_640 + 0x01;
					if (((byte) ax_640 + 0x01 & 0x80) != 0x00)
						wLoc0A_867 = ax_640 + 0x81;
					ss->*((word32) sp_18 - 6) = ((wLoc0A_867 & 0x0F00) >> 0x01 | wLoc0A_867 & 0x7F) - ax_249;
					if (fn207F_3C6C(ss->*((word32) sp_18 - 6)) < 0x03)
					{
						wLoc08_746 = 0x01;
						wLoc20_862 = 0x0D;
						wLoc1A_791 = 0x0D;
					}
				}
			}
		}
		int16 wLoc12_793 = 0x04;
		if (wArg04 >= 0x0C)
			wLoc12_793 = 0x10;
		int16 wLoc1A_800 = wLoc12_793;
		byte bLoc12_818;
		byte bLoc11_820;
		while (true)
		{
			bLoc12_818 = (byte) wLoc12_793;
			bLoc11_820 = SLICE(wLoc12_793, byte, 8);
			sp_30 = sp_18 - 4;
			if (wLoc12_793 + 0x08 <= wLoc1A_800)
				break;
			if (Mem274[ds_125:0x559A:selector]:0x406A[wLoc1A_800 * 0x02] != 0x00 && Mem274[ds_125:0x5590:selector]:0x4036[wLoc1A_800 * 0x02] == Mem274[Mem274[ds_125:0x5584:selector]:0xA44D:word16])
			{
				cui16 ax_291 = Mem274[ds_125:0x5592:selector]:0x4004[wLoc1A_800 * 0x02];
				ss->*((word32) sp_18 - 6) = ax_249 - 0x01 - ((ax_291 & 0x0F00) >> 0x01 | ax_291 & 0x7F);
				if (fn207F_3C6C(ss->*((word32) sp_18 - 6)) < 0x02)
				{
					wLoc08_746 = 0x01;
					wLoc1A_800 = wLoc12_793 + 0x09;
				}
			}
			++wLoc1A_800;
		}
		if (wLoc08_746 == 0x00 && wArg0A != 0x00)
		{
			Eq_60761 wLoc12_821 = SEQ(bLoc11_820, bLoc12_818 ^ 0x14);
			Eq_60761 wLoc1A_822 = wLoc12_821;
			while ((word16) wLoc12_821 + 8 > wLoc1A_822)
			{
				if (Mem337[ds_125:0x559A:selector]:0x406A[wLoc1A_822 * 0x02] != 0x00 && Mem337[ds_125:0x5590:selector]:0x4036[wLoc1A_822 * 0x02] == Mem337[Mem337[ds_125:0x5584:selector]:0xA44D:word16])
				{
					cui16 ax_354 = Mem337[ds_125:0x5592:selector]:0x4004[wLoc1A_822 * 0x02];
					struct Eq_60855 Eq_60556::* sp_366 = sp_30 - 2;
					(ss->*sp_366).t0000.u0 = (wchar_t) (ax_249 - 0x01 - ((ax_354 & 0x0F00) >> 0x01 | ax_354 & 0x7F));
					sp_30.u5 = sp_366 + 1;
					if (fn207F_3C6C((ss->*sp_366).t0000.u0) < 0x02)
					{
						(ss->*sp_366).t0000.u0 = 0x04;
						Eq_60886 wLoc22_828 = wLoc1A_822 - 0x04;
						Eq_5 si_407 = fn1E56_0388(fp - 2, fn1E56_0281(wLoc1A_822 << 0x01, di_167, ds_125, (ss->*sp_366).t0000.u0, out di_388, out ds_389), di_388, ds_389, out di_403, out ds_404);
						Eq_5 sp_408;
						sp_408.u0 = <invalid>;
						if (wLoc22_828 < 0x0C)
						{
							int16 ax_430 = CONVERT(Mem382[ds_404:0x558E:selector]:50708[wLoc22_828 * 0x11], int8, int16);
							struct Eq_60934 * es_435 = Mem382[ds_404:0x55B6:selector];
							(ss->*((word32) sp_408 - 2)).u0 = es_435->a01CC[0].u5[ax_430].u0;
							(ss->*((word32) sp_408 - 4)).u0 = es_435->a01CA[0].u5[ax_430].u0;
						}
						else
						{
							ss->*((word32) sp_408 - 2) = ds_404;
							(ss->*((word32) sp_408 - 4)).u0 = 0x319A;
							wLoc22_828 -= 0x04;
						}
						Eq_5 si_456 = fn1631_1DAB(si_407, di_403, ds_404, ss->*((word32) sp_408 - 4), out di_452, out ds_453);
						ss->*((word32) sp_408 - 2) = ds_453;
						(ss->*((word32) sp_408 - 4)).u0 = 12710;
						Eq_5 si_476 = fn1631_1DAB(si_456, di_452, ds_453, ss->*((word32) sp_408 - 4), out di_472, out ds_473);
						(ss->*((word32) sp_408 - 2)).u0 = 0x12;
						Eq_5 si_494 = fn0800_19BF(si_476, di_472, ds_473, ss->*((word32) sp_408 - 2), out di_490, out ds_491);
						if (Mem486[ds_491:0x55B8:selector]->w015E < 0x05)
						{
							Eq_5 si_512 = fn1631_1DCC(fp - 2, si_494, di_490, ds_491, out di_490, out ds_491);
							if (wLoc22_828 < 0x08)
								fn1631_1DCC(fp - 2, si_512, di_490, ds_491, out di_490, out ds_491);
						}
						Mem544[ss:sp_408 + -2:word16] = Mem486[ds_491:0x5590:selector]:0x4036[wLoc1A_822 * 0x02];
						Mem548[ss:sp_408 + -4:word16] = Mem544[ds_491:0x5592:selector]:0x4004[wLoc1A_822 * 0x02];
						(ss->*((word32) sp_408 - 6)).u0 = 0x7E;
						fn183B_27C9(wLoc1A_822 << 0x01, di_490, ds_491, ss->*((word32) sp_408 - 6), ss->*((word32) sp_408 - 4), ss->*((word32) sp_408 - 2), out di_167, out ds_125);
						Mem551[ds_125:0x55BA:selector]->*((word16) wLoc1A_822 + 0x0000409A) = 0x7E;
						Mem570[ds_125:0x55AE:selector]->*((word16) wLoc1A_822 + 0x0000D55E) = 0x00;
						Mem573[ds_125:0x559A:selector]:0x406A[wLoc1A_822 * 0x02] = 0x00;
						struct Eq_57354 * es_583 = Mem582[ds_125:0x558E:selector];
						(&es_583->bC620)[3][wLoc22_828].b0000 = 0x00;
						es_583->aC614[0].b0000[wLoc22_828].b0000 = ~0x00;
						sp_30 = sp_408;
						if (wLoc22_828 < 0x02)
							Mem586[ds_125:0x55BC:selector]->w014A = 0x00;
					}
				}
				wLoc1A_822 = (word16) wLoc1A_822 + 1;
			}
		}
	}
	diOut = (ss->*sp_30.u7).w0002;
	dsOut = ds_125;
	return wLoc08_746;
}

// 1631:1B44: Register word16 fn1631_1B44(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack int16 wArg04, Stack Eq_61319 wArg06, Register out word16 siOut, Register out word16 diOut, Register out (ptr16 Eq_61331) dsOut)
// Called from:
//      fn1AE8_000C
word16 fn1631_1B44(Eq_5 si, Eq_5 di, Eq_5 ds, int16 wArg04, Eq_61319 wArg06, word16 & siOut, word16 & diOut, struct Eq_61331 & dsOut)
{
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	word16 si_22;
	word16 di_19;
	struct Eq_61331 * ds_20;
	fn207F_2FDC(0x04, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	byte al_34 = (byte) (Mem7[ds_20:0x558E:selector]->*((word16) (wArg04 *s 0x7D + wArg06) + 50980));
	word16 wLoc06_79 = 0x00;
	if ((al_34 & 0x04) == 0x00)
		wLoc06_79 = 0x01;
	if ((al_34 & 0x02) == 0x00)
		++wLoc06_79;
	if ((al_34 & 0x01) == 0x00)
		++wLoc06_79;
	siOut = si_22;
	diOut = di_19;
	dsOut = ds_20;
	return wLoc06_79;
}

// 1631:1B8F: Register Eq_5 fn1631_1B8F(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Register out Eq_5 diOut, Register out Eq_5 dsOut)
// Called from:
//      fn1AE8_000C
Eq_5 fn1631_1B8F(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, union Eq_5 & diOut, union Eq_5 & dsOut)
{
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_105;
	Eq_5 di_101;
	Eq_5 ds_102;
	fn207F_2FDC(0x02, fp - 2, si, di, ds, wLoc06, wLoc04, out si_105, out di_101, out ds_102);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	Eq_61386 wLoc04_132;
	wLoc04_132.u0 = 0x00;
	Eq_61386 v15_117;
	do
	{
		if ((int16) (ds_102->*((word16) wLoc04_132 + 0x00003242)) == wArg04)
		{
			selector ss;
			(ss->*((word32) sp_18 - 2)).u0 = (*((word32) ds_102 + 12880))[wLoc04_132].u0;
			(ss->*((word32) sp_18 - 4)).u0 = (*((word32) ds_102 + 12878))[wLoc04_132].u0;
			(ss->*((word32) sp_18 - 6)).u0 = 0x3092;
			(ss->*((word32) sp_18 - 8)).u0 = 0x12;
			fn207F_3B68(ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 4));
			ss->*((word32) sp_18 - 2) = ds_102;
			(ss->*((word32) sp_18 - 4)).u0 = 0x3240;
			(ss->*((word32) sp_18 - 6)).u0 = 0x3092;
			(ss->*((word32) sp_18 - 8)).u0 = 0x12;
			fn207F_3B22(ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 4));
			(ss->*((word32) sp_18 - 2)).u0 = 0x3092;
			(ss->*((word32) sp_18 - 4)).u0 = 0x12;
			si_105 = fn1631_1DAB(si_105, di_101, ds_102, ss->*((word32) sp_18 - 4), out di_101, out ds_102);
			wLoc04_132.u0 = 11;
		}
		v15_117 = (word16) wLoc04_132 + 1;
		wLoc04_132 = v15_117;
	} while (v15_117 < 11);
	diOut = di_101;
	dsOut = ds_102;
	return si_105;
}

// 1631:1BFE: Register word16 fn1631_1BFE(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg06, Stack Eq_5 wArg08, Stack Eq_5 wArg0A, Register out word16 siOut, Register out word16 diOut, Register out (ptr16 Eq_57922) dsOut)
// Called from:
//      fn1631_03AB
//      fn1AE8_000C
word16 fn1631_1BFE(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg06, Eq_5 wArg08, Eq_5 wArg0A, word16 & siOut, word16 & diOut, struct Eq_57922 & dsOut)
{
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	word16 si_22;
	word16 di_19;
	struct Eq_57922 * ds_20;
	fn207F_2FDC(0x1C, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	selector ss;
	(ss->*((word32) sp_18 - 2)).u5 = si_22;
	Eq_5 ax_31 = Mem29[ds_20:0x5582:selector]->tA44B;
	Eq_5 ax_34 = Mem32[ds_20:0x5584:selector]->tA44D;
	ss->*((word32) sp_18 - 4) = ax_34;
	ss->*((word32) sp_18 - 6) = ax_31;
	fn207F_1314(ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4));
	fn207F_1DF8();
	byte bLoc06_312 = (byte) ax_31;
	Eq_5 wLoc0A_305 = ax_34;
	word16 ax_121;
	if (Mem40[ds_20:0x559C:selector]->wE48E != 0x00 && wArg06 == 0x0D)
		ax_121 = 0x01;
	else
	{
		word16 ax_66 = Mem40[ds_20:0x5586:selector]->w09ED;
		struct Eq_61559 Eq_61624::* wLoc12_307 = ax_66 + 0x96;
		cui16 wLoc1E_308 = 0x01;
		cui16 wLoc04_310 = ax_34 & 0x01;
		Eq_5 wLoc06_325 = ax_31;
		if ((bLoc06_312 & 0x01) != 0x00)
		{
			wLoc12_307 = ax_66 + 151;
			wLoc1E_308 = 0x00;
		}
		ss->*((word32) sp_18 - 4) = wArg0A;
		ss->*((word32) sp_18 - 6) = wArg08;
		ss->*((word32) sp_18 - 8) = ax_34;
		ss->*((word32) sp_18 - 0x0A) = ax_31;
		Eq_5 wLoc14_326 = fn207F_0971(ss->*((word32) sp_18 - 0x0A), ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4));
		word16 wLoc10_327 = 0x01;
		if (Mem117[ds_20:0x558A:selector]->t0150 > (uint16) (Mem110[ds_20:0x5588:selector]->*wLoc12_307).b07AD)
		{
			while (wLoc06_325 != wArg08 || wLoc0A_305 != wArg0A)
			{
				ss->*((word32) sp_18 - 4) = wArg0A;
				ss->*((word32) sp_18 - 6) = wArg08;
				ss->*((word32) sp_18 - 8) = wLoc0A_305;
				ss->*((word32) sp_18 - 0x0A) = wLoc06_325;
				cui16 ax_160 = fn207F_0971(ss->*((word32) sp_18 - 0x0A), ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4)) - wLoc14_326;
				if (ax_160 != 0x00)
				{
					ui16 wLoc14_344;
					if ((ax_160 & 0x07) >= 0x05)
						wLoc14_344 = wLoc14_326 - 0x01;
					else
						wLoc14_344 = (ui16) ((word32) wLoc14_326 + 1);
					wLoc14_326 = wLoc14_344 & 0x07;
				}
				Eq_5 v30_196;
				v30_196.u5 = wLoc06_325.u5 + ((ds_20->a328A))[0][wLoc14_326];
				wLoc06_325 = v30_196;
				if (((byte) v30_196 & 0x80) != 0x00)
					wLoc06_325.u5 = v30_196.u5 + ((ds_20->a32AA))[0][wLoc14_326];
				Eq_5 v34_213;
				v34_213.u5 = wLoc0A_305.u5 + ((ds_20->a329A))[0][wLoc14_326];
				wLoc0A_305 = v34_213;
				if (((byte) v34_213 & 0x80) != 0x00)
					wLoc0A_305.u5 = v34_213.u5 + ((ds_20->a32BA))[0][wLoc14_326];
				int16 si_229 = ds_20->a328A[0][wLoc14_326];
				if (si_229 != 0x00)
				{
					cui16 ax_236 = wLoc1E_308 + si_229;
					wLoc1E_308 = ax_236 & 0x01;
					if ((ax_236 & 0x01) == 0x00)
						wLoc12_307 = (struct Eq_61559 Eq_61624::*) ((char *) wLoc12_307 + si_229);
				}
				if (ds_20->a329A[0][wLoc14_326] != 0x00)
				{
					cui16 ax_256 = ds_20->a329A[0][wLoc14_326] + wLoc04_310;
					wLoc04_310 = ax_256 & 0x01;
					if ((ax_256 & 0x01) == 0x00)
						wLoc12_307 = (struct Eq_61559 Eq_61624::*) ((char *) wLoc12_307 + ((ds_20->a32CA))[0][wLoc14_326]);
				}
				if (Mem277[ds_20:0x558A:selector]->t0150 <= (uint16) (Mem270[ds_20:0x5588:selector]->*wLoc12_307).b07AD)
				{
					wLoc06_325 = wArg08;
					wLoc0A_305 = wArg0A;
					wLoc10_327 = 0x00;
				}
			}
			ax_121 = wLoc10_327;
		}
		else
			ax_121 = 0x00;
	}
	siOut = (word16) (ss->*((word32) sp_18 - 2));
	diOut = di_19;
	dsOut = ds_20;
	return ax_121;
}

// 1631:1DAB: Register Eq_5 fn1631_1DAB(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 dwArg04, Register out Eq_5 diOut, Register out Eq_5 dsOut)
// Called from:
//      fn1543_0A35
//      fn1631_11AB
//      fn1631_16AB
//      fn1631_1B8F
//      fn1AE8_000C
//      fn1AE8_12C7
Eq_5 fn1631_1DAB(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 dwArg04, union Eq_5 & diOut, union Eq_5 & dsOut)
{
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_25;
	Eq_5 di_22;
	Eq_5 ds_23;
	fn207F_2FDC(0x00, fp - 2, si, di, ds, wLoc06, wLoc04, out si_25, out di_22, out ds_23);
	if (Mem7[ds_23:11832:word16] != 0x00)
		fn1E56_03F5(si_25, di_22, ds_23, dwArg04, out si_25, out di_22, out ds_23);
	diOut = di_22;
	dsOut = ds_23;
	return si_25;
}

// 1631:1DCC: Register Eq_5 fn1631_1DCC(Register Eq_36 bp, Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Register out word16 diOut, Register out (ptr16 Eq_56314) dsOut)
// Called from:
//      fn1543_0A35
//      fn1631_16AB
//      fn1AE8_000C
Eq_5 fn1631_1DCC(Eq_36 bp, Eq_5 si, Eq_5 di, Eq_5 ds, word16 & diOut, struct Eq_56314 & dsOut)
{
	word16 wLoc04;
	cup16 wLoc02;
	Eq_5 si_23;
	Eq_5 di_20;
	Eq_5 ds_21;
	fn207F_2FDC(0x00, bp, si, di, ds, wLoc04, wLoc02, out si_23, out di_20, out ds_21);
	selector es_29 = Mem0[ds_21:0x55B8:selector];
	Eq_5 si_39;
	word16 di_35;
	struct Eq_56314 * ds_36;
	if (es_29->w015E < 0x05)
		si_39 = fn1F3D_0006(si_23, di_20, ds_21, es_29->w015E *s 0x0C, out di_35, out ds_36);
	else
		fn1F3D_0259(si_23, di_20, ds_21, out si_39, out di_35, out ds_36);
	diOut = di_35;
	dsOut = ds_36;
	return si_39;
}

// 1631:1DF8: Register Eq_5 fn1631_1DF8(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Stack Eq_5 wArg06, Stack Eq_5 wArg08, Stack Eq_5 wArg0A, Register out word16 diOut, Register out (ptr16 Eq_61858) dsOut)
// Called from:
//      fn1AE8_12C7
Eq_5 fn1631_1DF8(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, Eq_5 wArg06, Eq_5 wArg08, Eq_5 wArg0A, word16 & diOut, struct Eq_61858 & dsOut)
{
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_25;
	word16 di_22;
	struct Eq_61858 * ds_23;
	fn207F_2FDC(0x00, fp - 2, si, di, ds, wLoc06, wLoc04, out si_25, out di_22, out ds_23);
	Mem7[ds_23:21888:selector]->wE486 = 0x1A;
	Mem32[ds_23:0x557E:selector]->wE488 = 0x0C;
	while (wArg06 > wArg0A)
	{
		Eq_5 v14_41 = wArg06 - 0x01;
		wArg06 = v14_41;
		if (((byte) v14_41 & 0x80) != 0x00)
			wArg06 = v14_41 & ~0x0F80;
		struct Eq_61871 * es_56 = ds_23->ptr557E;
		--es_56->wE488;
	}
	while (wArg06 < wArg0A)
	{
		Eq_5 v21_66;
		v21_66.u5 = (word32) wArg06 + 1;
		wArg06 = v21_66;
		if (((byte) v21_66 & 0x80) != 0x00)
			wArg06.u5 = (word32) v21_66 + 0x0F80;
		struct Eq_61871 * es_79 = ds_23->ptr557E;
		++es_79->wE488;
	}
	while (wArg04 > wArg08)
	{
		Eq_5 v23_89 = wArg04 - 0x01;
		wArg04 = v23_89;
		if (((byte) v23_89 & 0x80) != 0x00)
			wArg04 = v23_89 & 0x0F7F;
		struct Eq_61864 * es_104 = ds_23->ptr5580;
		--es_104->wE486;
	}
	while (wArg04 < wArg08)
	{
		Eq_5 v26_114;
		v26_114.u5 = (word32) wArg04 + 1;
		wArg04 = v26_114;
		if (((byte) v26_114 & 0x80) != 0x00)
			wArg04.u5 = (word32) v26_114 + 0x0080;
		struct Eq_61864 * es_127 = ds_23->ptr5580;
		++es_127->wE486;
	}
	diOut = di_22;
	dsOut = ds_23;
	return si_25;
}

// 1631:1EA2: Sequence segptr32 fn1631_1EA2(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Stack Eq_5 wArg06, Register out ui16 siOut, Register out word16 diOut)
// Called from:
//      fn1AE8_12C7
segptr32 fn1631_1EA2(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, Eq_5 wArg06, ui16 & siOut, word16 & diOut)
{
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	ui16 si_22;
	word16 di_19;
	struct Eq_61982 * ds_20;
	fn207F_2FDC(0x02, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	<unknown> Eq_61982::* wLoc04_81;
	bool v25_72;
	if (wArg04 < 0x00)
	{
		if (wArg06 > 0x00)
		{
			wLoc04_81 = &Eq_61982::t0002;
			v25_72 = -wArg04 <= wArg06;
		}
		else
		{
			wLoc04_81 = &Eq_61982::t0004;
			v25_72 = -wArg06 <= -wArg04;
		}
	}
	else
	{
		if (wArg06 <= 0x00)
		{
			wLoc04_81 = &Eq_61982::t0006;
			if (-wArg06 < wArg04)
				goto l1631_1EFF;
			goto l1631_1F02;
		}
		wLoc04_81 = &Eq_61982::t0000;
		v25_72 = wArg06 <= wArg04;
	}
	if (!v25_72)
	{
l1631_1EFF:
		wLoc04_81 = (<unknown> Eq_61982::*) ((char *) wLoc04_81 + 1);
		goto l1631_1F02;
	}
l1631_1F02:
	siOut = si_22;
	diOut = di_19;
	return wLoc04_81;
}

// 1631:1F09: Register Eq_5 fn1631_1F09(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Stack Eq_5 wArg06, Register out word16 diOut, Register out (ptr16 Eq_62129) dsOut)
// Called from:
//      fn1AE8_12C7
Eq_5 fn1631_1F09(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, Eq_5 wArg06, word16 & diOut, struct Eq_62129 & dsOut)
{
	Eq_5 ds_92;
	Eq_5 di_91;
	Eq_5 ds_77;
	Eq_5 di_76;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	Eq_5 di_19;
	Eq_5 ds_20;
	fn207F_2FDC(0x02, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	selector ss;
	ss->*((word32) sp_18 - 2) = si_22;
	(ss->*((word32) sp_18 - 4)).u0 = 0x01;
	ss->*((word32) sp_18 - 6) = wArg06;
	ss->*((word32) sp_18 - 8) = wArg04;
	fn207F_1ECE(ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4));
	int16 wLoc04_133 = 0x04;
	selector es_49 = Mem48[ds_20:0x558E:selector];
	if (es_49->bC620 < 0x08)
		wLoc04_133 = (int16) es_49->bC620;
	Mem66[ss:sp_18 + -4:word16] = Mem57[ds_20:0x5590:selector]:0x4036[wLoc04_133 * 0x02];
	Mem70[ss:sp_18 + -6:word16] = Mem66[ds_20:0x5592:selector]:0x4004[wLoc04_133 * 0x02];
	Eq_5 si_95 = fn0800_240B(fn0800_17BB(wLoc04_133 << 0x01, di_19, ds_20, ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4), out di_76, out ds_77), di_76, ds_77, out di_91, out ds_92);
	fn207F_18EF();
	word16 di_114;
	struct Eq_62129 * ds_115;
	fn0800_0E4B(si_95, di_91, ds_92, out di_114, out ds_115);
	Eq_5 si_124 = ss->*((word32) sp_18 - 2);
	diOut = di_114;
	dsOut = ds_115;
	return si_124;
}

// 1631:1F73: Register Eq_5 fn1631_1F73(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Stack Eq_5 wArg06, Stack Eq_5 wArg08, Register out word16 diOut, Register out (ptr16 Eq_62160) dsOut)
// Called from:
//      fn1AE8_12C7
Eq_5 fn1631_1F73(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, Eq_5 wArg06, Eq_5 wArg08, word16 & diOut, struct Eq_62160 & dsOut)
{
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_25;
	word16 di_22;
	struct Eq_62160 * ds_23;
	fn207F_2FDC(0x00, fp - 2, si, di, ds, wLoc06, wLoc04, out si_25, out di_22, out ds_23);
	if (Mem7[ds_23:0x55BE:selector]->w4FBA != 0x02)
	{
		struct Eq_62173 * es_75 = ds_23->ptr55C0;
		fn207F_28EB(0x244B, 0x246C, es_75->a39FA[0].u5[wArg04].u0, es_75->a39FC[0].u5[wArg04].u0, wArg06, wArg08);
	}
	else
	{
		struct Eq_62173 * es_43 = ds_23->ptr55C0;
		fn207F_0377(0xAC00, 0x00, 0xAC00, es_43->a39FA[0].u5[wArg04].u0, es_43->a39FC[0].u5[wArg04].u0, wArg06, wArg08);
	}
	diOut = di_22;
	dsOut = ds_23;
	return si_25;
}

// 1631:1FDF: Register word16 fn1631_1FDF(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Register out Eq_5 siOut, Register out word16 diOut, Register out (ptr16 Eq_1067) dsOut)
// Called from:
//      fn0800_0000
//      fn0800_4CAC
//      fn0FDC_01C0
//      fn11B8_0002
//      fn11B8_0925
//      fn11B8_1762
//      fn1CD3_0004
word16 fn1631_1FDF(Eq_5 si, Eq_5 di, Eq_5 ds, union Eq_5 & siOut, word16 & diOut, struct Eq_1067 & dsOut)
{
	struct Eq_1067 * ds_185;
	word16 di_184;
	Eq_5 ds_108;
	Eq_5 di_107;
	Eq_5 si_111;
	Eq_5 ds_38;
	Eq_5 di_37;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	Eq_5 di_19;
	Eq_5 ds_20;
	fn207F_2FDC(0x04, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	selector ss;
	(ss->*((word32) sp_18 - 2)).u0 = 0x03;
	Eq_5 si_41 = fn1E56_0281(si_22, di_19, ds_20, ss->*((word32) sp_18 - 2), out di_37, out ds_38);
	Mem33[ds_38:0x55C2:selector]->w3748 = 0x00;
	Mem50[ds_38:0x55C4:selector]->w374E = 0x09;
	ss->*((word32) sp_18 - 2) = ds_38;
	(ss->*((word32) sp_18 - 4)).u0 = 13018;
	Eq_5 si_65;
	Eq_5 di_61;
	Eq_5 ds_62;
	fn1E56_03F5(si_41, di_37, ds_38, ss->*((word32) sp_18 - 4), out si_65, out di_61, out ds_62);
	word16 si_206;
	word16 di_207;
	struct Eq_62283 * ds_77;
	fn0800_28A2(fp - 2, si_65, di_61, ds_62, out si_206, out di_207, out ds_77);
	(ss->*((word32) sp_18 - 2)).u0 = 0x0A;
	(ss->*((word32) sp_18 - 4)).u0 = 0x3092;
	(ss->*((word32) sp_18 - 6)).u0 = 0x12;
	struct Eq_62302 * es_95 = ds_77->ptr558E;
	ss->*((word32) sp_18 - 8) = es_95->tD372;
	ss->*((word32) sp_18 - 0x0A) = es_95->tD370;
	struct Eq_62351 Eq_62226::* bp_104 = fn207F_3BD2(0x00, ss->*((word32) sp_18 - 0x0A), ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 2), out si_111, out di_107, out ds_108);
	(ss->*((word32) sp_18 - 2)).u0 = 0x3092;
	(ss->*((word32) sp_18 - 4)).u0 = 0x12;
	(ss->*bp_104).tFFFFFFFE.u0 = (wchar_t) fn207F_3B9E(ss->*((word32) sp_18 - 4));
	while ((ss->*bp_104).tFFFFFFFE.u0 < 0x0A)
	{
		Eq_5 bx_141;
		bx_141.u0 = (ss->*bp_104).tFFFFFFFE.u0;
		(ss->*bp_104).tFFFFFFFE.u0 = (wchar_t) ((ss->*bp_104).tFFFFFFFE.u0 + 0x01);
		(Mem143[ds_108:0x55C6:selector]->*((word32) bx_141 + 18)).u5 = 0x20;
	}
	Mem138[ds_108:0x55C6:selector]->*((word16) ((ss->*bp_104).tFFFFFFFE).u0 + 18) = (wchar_t) 0x00;
	(ss->*((word32) sp_18 - 2)).u0 = 0x3092;
	(ss->*((word32) sp_18 - 4)).u0 = 0x12;
	Eq_5 si_168;
	Eq_5 di_164;
	Eq_5 ds_165;
	fn1E56_03F5(si_111, di_107, ds_108, ss->*((word32) sp_18 - 4), out si_168, out di_164, out ds_165);
	Mem157[ds_165:0x55C8:selector]->w37FE = 0x0F;
	(ss->*((word32) sp_18 - 2)).u0 = (ss->*bp_104).tFFFFFFFC.u0;
	Eq_5 si_188 = fn1E56_0281(si_168, di_164, ds_165, ss->*((word32) sp_18 - 2), out di_184, out ds_185);
	word16 bp_195 = (ss->*bp_104).w0000;
	siOut = si_188;
	diOut = di_184;
	dsOut = ds_185;
	return bp_195;
}

