// UNBTECH_1CD3.c
// Generated by decompiling UNBTECH.exe
// using Reko decompiler version 0.12.2.0.

#include "UNBTECH.h"

// 1CD3:0004: Register word16 fn1CD3_0004(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Register out word16 siOut, Register out word16 diOut, Register out (ptr16 Eq_13594) dsOut)
// Called from:
//      fn0800_378D
//      fn0FDC_0008
//      fn0FDC_01C0
//      fn11B8_0002
//      fn11B8_080A
//      fn1431_000A
//      fn1CD3_0004
word16 fn1CD3_0004(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, word16 & siOut, word16 & diOut, struct Eq_13594 & dsOut)
{
	word16 Eq_62226::* bp_4687;
	struct Eq_80526 Eq_62226::* sp_4652;
	word16 sp_4510;
	Eq_5 ds_436;
	Eq_5 di_435;
	Eq_5 si_439;
	Eq_5 ds_417;
	Eq_5 di_416;
	Eq_5 ds_304;
	Eq_5 di_303;
	Eq_5 si_307;
	Eq_5 ds_259;
	Eq_5 di_258;
	Eq_5 ds_227;
	Eq_5 di_226;
	Eq_5 ds_165;
	Eq_5 di_164;
	Eq_5 ds_110;
	Eq_5 di_109;
	selector ds_468;
	Eq_5 ds_541;
	Eq_5 di_540;
	selector ds_737;
	word16 di_736;
	Eq_5 di_730;
	Eq_5 si_728;
	word16 sp_4378;
	int8 al_776;
	word16 sp_1190;
	selector ds_1154;
	word16 di_1153;
	word16 si_1157;
	Eq_5 ds_1126;
	Eq_5 di_1147;
	Eq_5 si_1146;
	word16 sp_1136;
	struct Eq_83766 Eq_62226::* bp_1122;
	Eq_5 ds_1258;
	Eq_5 di_1257;
	Eq_5 ds_866;
	Eq_5 di_865;
	Eq_5 ds_821;
	Eq_5 di_820;
	Eq_5 si_824;
	word16 sp_1633;
	word16 sp_1605;
	selector ds_1586;
	word16 di_1585;
	word16 si_1589;
	Eq_5 ds_1441;
	Eq_5 di_1440;
	selector ds_1368;
	word16 di_1367;
	selector ds_4135;
	word16 di_7903;
	word16 si_7902;
	Eq_5 ds_4110;
	Eq_5 di_4120;
	Eq_5 si_4115;
	selector ds_2014;
	word16 sp_2239;
	word16 sp_2187;
	Eq_5 ds_2174;
	ui16 wArg04_4878;
	Eq_5 ds_2351;
	Eq_5 di_2350;
	Eq_5 si_2354;
	word16 wArg04_4891;
	word16 sp_4340;
	Eq_5 ds_2402;
	Eq_5 di_2401;
	Eq_5 si_2405;
	Eq_5 ds_2502;
	Eq_5 di_2501;
	Eq_5 si_2505;
	Eq_36 bp_3692;
	word16 sp_3666;
	word16 sp_3639;
	Eq_5 ds_2902;
	Eq_5 di_2901;
	Eq_5 si_2905;
	Eq_5 ds_2724;
	Eq_5 di_2723;
	Eq_5 si_2727;
	Eq_5 ds_2614;
	Eq_5 di_2613;
	Eq_5 si_2617;
	Eq_5 ds_2540;
	Eq_5 di_2539;
	Eq_5 ds_3450;
	Eq_5 di_3449;
	Eq_5 si_3453;
	Eq_5 ds_3276;
	Eq_5 di_3275;
	Eq_5 si_3279;
	Eq_5 ds_3105;
	Eq_5 di_3104;
	Eq_5 ds_3871;
	Eq_5 di_3870;
	Eq_5 si_3874;
	Eq_5 ds_3812;
	struct Eq_81634 Eq_62226::* bp_3807;
	Eq_5 ds_3740;
	Eq_5 di_3739;
	Eq_5 si_3743;
	Eq_5 ds_4203;
	Eq_5 di_4202;
	Eq_5 si_4206;
	selector ds_4628;
	word16 di_4627;
	Eq_5 ds_4609;
	Eq_5 di_4608;
	Eq_5 ds_4596;
	Eq_5 di_4595;
	Eq_5 ds_4553;
	Eq_5 di_4552;
	Eq_5 di_4547;
	Eq_5 si_4546;
	selector ds_4442;
	word16 di_4441;
	word16 si_4445;
	word16 wLoc14_4936;
	word16 wLoc12_4945;
	selector seg2FE8;
	<unknown> Eq_62226::* fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	Eq_5 di_19;
	Eq_5 ds_20;
	fn207F_2FDC(0x34, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	selector ss;
	ss->*((word32) sp_18 - 2) = di_19;
	ss->*((word32) sp_18 - 4) = si_22;
	mp16 bp_8 = fp - 2;
	struct Eq_80515 Eq_62226::* sp_30 = sp_18 - 4;
	if (wArg04 <= 0x2F)
	{
		byte bh_2396 = SLICE((wArg04 - 0x01) * 0x02, byte, 8);
		switch (wArg04)
		{
		case 0x01:
			Mem4382[ds_20:22172:selector]->bD55E = 0x00;
			selector es_4385 = Mem4384[ds_20:22174:selector];
			segptr32 ptrLoc14_4942 = &seg2FE8->t02F0;
			if (es_4385->bD30E != 0x00)
			{
				Mem4384[ds_20:22172:selector]->bD55E = 0x92;
				selector es_4392 = Mem4391[ds_20:22174:selector];
				segptr32 ptrLoc14_4943 = &seg2FE8->t036D;
				if (es_4392->bD30E == 0x02)
				{
					segptr32 ptrLoc14_4944 = &seg2FE8->t04E4;
				}
			}
			selector es_4397;
			es_4397->bC620 = 0x00;
			word16 wLoc18_4934 = 50980;
			selector es_4413;
			Eq_86139 v138_4415;
			do
			{
				byte * ptrLoc14_4946 = SEQ(wLoc12_4945, wLoc14_4936 + 0x01);
				es_4413 = Mem4407[ds_20:22174:selector];
				byte Eq_80552::* wLoc18_4938;
				byte * ptrLoc14_4935;
				es_4413->*wLoc18_4938 = *ptrLoc14_4935;
				v138_4415 = wLoc18_4938 + 1;
				wLoc14_4936 = (word16) ptrLoc14_4935;
				wLoc12_4945 = SLICE(ptrLoc14_4935, word16, 16);
				Eq_86139 wLoc18_4939 = v138_4415;
				ptrLoc14_4935 = ptrLoc14_4946;
			} while (v138_4415 < 0x3959);
			es_4413->bC79D = 0x00;
			if (Mem4419[ds_20:0x56A0:selector]->w3938 == 0x00)
			{
				(ss->*((word32) sp_18 - 6)).u0 = 0x00;
				(ss->*((word32) sp_18 - 8)).u0 = 0x00;
				Eq_5 sp_4446;
				sp_4446.u0 = <invalid>;
				Eq_36 bp_4438 = fn0800_48B7(si_22, di_19, ds_20, ss->*((word32) sp_18 - 8), out si_4445, out di_4441, out ds_4442);
				word16 sp_4453 = (word16) ((word32) sp_4446 + 4);
			}
			selector ds_4455;
			Mem4456[ds_4455:22178:selector]->wA44D = 0xC04F;
			struct Eq_86168 * es_4459 = ds_4455->ptr56A4;
			es_4459->w01F6 = 0x0280;
			es_4459->t01F8.u0 = 12264;
			struct Eq_86179 * es_4462 = ds_4455->ptr56A6;
			es_4462->wA44B = 0x0C3C;
			selector es_4464;
			word16 sp_4778;
			Eq_5 si_4475;
			Eq_5 di_4476;
			Eq_5 ds_4474;
			while (es_4464->wA44B < 0x0C40)
			{
				union Eq_5 Eq_62226::* sp_4515 = sp_4778 - 2;
				(ss->*sp_4515).u0 = 0x00;
				struct Eq_86582 * ds_4521;
				word16 si_4524;
				word16 di_4520;
				Mem4516[ds_4521:22184:selector]->b409A = (byte) fn0800_1732(si_4475, di_4476, ds_4474, (ss->*sp_4515).u0, out si_4524, out di_4520, out ds_4521);
				Eq_36 bp_4783;
				ss->*((word16) bp_4783 - 28) = 0x00;
				Eq_5 ds_4541;
				while (ss->*((word16) bp_4783 - 28) < 0x06)
				{
					Eq_5 si_4556 = fn0800_240B(si_4546, di_4547, ds_4541, out di_4552, out ds_4553);
					struct Eq_86626 Eq_62226::* sp_4565 = sp_4778 - 2;
					(ss->*sp_4565).t0000.u0 = (wchar_t) Mem4538[ds_4553:22178:selector]->tA44D;
					(ss->*sp_4565).tFFFFFFFE.u0 = (wchar_t) Mem4566[ds_4553:22182:selector]->tA44B;
					fn207F_1314((ss->*sp_4565).tFFFFFFFE.u0, (ss->*sp_4565).t0000.u0);
					fn207F_18EF();
					Eq_5 si_4612 = fn1F3D_06C3(bp_4783, fn0800_051B(si_4556, di_4552, ds_4553, out di_4595, out ds_4596), di_4595, ds_4596, out di_4608, out ds_4609);
					if (Mem4570[ds_4609:0x56AA:selector]->w3FF4 > 0x08)
					{
						(ss->*sp_4565).t0000.u0 = 0x03;
						Eq_5 si_4631 = fn1F3D_0006(si_4612, di_4608, ds_4609, (ss->*sp_4565).t0000.u0, out di_4627, out ds_4628);
					}
					ss->*((word16) bp_4783 - 28) = (word16) (ss->*((word16) bp_4783 - 28)) + 1;
				}
				selector es_4542 = Mem4538[ds_4541:22182:selector];
				es_4542->tA44B.u5 = (word32) es_4542->tA44B + 1;
			}
			union Eq_5 Eq_62226::* sp_4471 = sp_4778 - 2;
			(ss->*sp_4471).u0 = 0x00;
			Eq_5 ds_4482;
			Eq_5 si_4485;
			Eq_5 di_4481;
			Mem4473[ds_4482:22184:selector]->b409A = (byte) fn0800_1732(si_4475, di_4476, ds_4474, (ss->*sp_4471).u0, out si_4485, out di_4481, out ds_4482);
			(ss->*sp_4471).u0 = (wchar_t) (int16) Mem4495[ds_4482:22174:selector]->bD30C;
			// Failed to bind call argument.
			// Please report this issue at https://github.com/uxmal/reko
			Eq_5 stackArg4;
			stackArg4.u0 = <invalid>;
			fn0FDC_0629(si_4485, di_4481, ds_4482, stackArg4);
			Eq_5 sp_4503;
			sp_4503.u0 = <invalid>;
			goto l1CD3_0181;
		case 0x02:
			selector es_4305 = Mem31[ds_20:22174:selector];
			if (es_4305->bC724 == 0x4C)
			{
				word16 ax_4339 = 18611;
			}
			else
			{
				if (es_4305->bC724 == 0x57)
				{
					word16 ax_4311 = 18655;
				}
				else
				{
					word16 ax_4310 = 0x48E4;
				}
				ss->*((word32) sp_18 - 6) = ds_20;
				Eq_5 ax_4318;
				ss->*((word32) sp_18 - 8) = ax_4318;
				word16 si_4330;
				word16 di_4326;
				selector ds_4327;
				fn1E56_03F5(si_22, di_19, ds_20, ss->*((word32) sp_18 - 8), out si_4330, out di_4326, out ds_4327);
				struct Eq_82125 Eq_62226::* sp_4336 = sp_18 - 0x04;
				word16 ax_4338 = 0x48EE;
			}
			goto l1CD3_01B5;
		case 0x03:
			selector es_4270 = Mem31[ds_20:22174:selector];
			es_4270->bC724 = ~0x00;
			es_4270->bC620 = 0x08;
			Mem4272[ds_20:22182:selector]->tA44B.u0 = 3118;
			Mem4274[ds_20:22178:selector]->tA44D.u0 = 0xC076;
			if (Mem4276[ds_20:22174:selector]->bD310 == 0x00)
			{
				word16 wLoc1A_4924 = 0x00;
				ci16 v149_4301;
				do
				{
					selector es_4286 = Mem4283[ds_20:22174:selector];
					struct Eq_86212 Eq_80552::* wLoc1A_4925;
					if (((es_4286->*wLoc1A_4925).bD457 & 0x7E) == 0x7C)
					{
						(es_4286->*wLoc1A_4925).bD4D7 = 0x00;
						(es_4286->*wLoc1A_4925).bD497 = 0x00;
						(es_4286->*wLoc1A_4925).bD457 = 0x00;
					}
					v149_4301 = (char *) wLoc1A_4925 + 1;
					ci16 wLoc1A_4927 = v149_4301;
				} while (v149_4301 < 0x40);
			}
			break;
		case 0x04:
			while (true)
			{
				struct Eq_85096 Eq_62226::* sp_4185 = sp_18 - 4;
				struct Eq_85098 Eq_62226::* bp_4172;
				if ((ss->*bp_4172).tFFFFFFE2.u0 >= 0x03)
					break;
				Eq_85102 bx_4176;
				bx_4176.u0 = (ss->*bp_4172).tFFFFFFE2.u0;
				selector ds_4177;
				(ss->*bp_4172).tFFFFFFD2.u0 = (wchar_t) (Mem4173[ds_4177:22174:selector]->*((word16) bx_4176 + 0x0000C618) *s16 0x7D + 0x4B);
				(ss->*((word32) sp_18 - 6)).u0 = 0x0A;
				(ss->*((word32) sp_18 - 8)).u0 = 0x3092;
				(ss->*((word32) sp_18 - 0x0A)).u0 = 0x12;
				(ss->*((word32) sp_18 - 0x0C)).u0 = (ss->*bp_4172).tFFFFFFD2.u0;
				Eq_36 bp_4199 = fn207F_3BB6(SLICE(bx_4176, byte, 8), ss->*((word32) sp_18 - 0x0C), ss->*((word32) sp_18 - 0x0A), ss->*((word32) sp_18 - 6), out si_4206, out di_4202, out ds_4203);
				(ss->*((word32) sp_18 - 6)).u0 = 0x00;
				(ss->*((word32) sp_18 - 8)).u0 = 0x0A;
				(ss->*((word32) sp_18 - 0x0A)).u5 = (word16) (ss->*((word16) bp_4199 - 30)) + 5;
				(ss->*((word32) sp_18 - 0x0C)).u0 = 0x3092;
				(ss->*((word32) sp_18 - 0x0E)).u0 = 0x12;
				ss->*((word32) sp_18 - 0x0C) = 0x27 - fn207F_3B9E(ss->*((word32) sp_18 - 0x0E));
				(ss->*((word32) sp_18 - 0x0E)).u0 = 0x3092;
				(ss->*((word32) sp_18 - 16)).u0 = 0x12;
				word16 si_7914;
				word16 di_7915;
				selector ds_4256;
				fn1F3D_00D5(si_4206, di_4202, ds_4203, ss->*((word32) sp_18 - 16), ss->*((word32) sp_18 - 0x0C), ss->*((word32) sp_18 - 0x0A), ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), out si_7914, out di_7915, out ds_4256);
				ss->*((word16) bp_4199 - 30) = (word16) (ss->*((word16) bp_4199 - 30)) + 1;
			}
			break;
		case 0x05:
			ss->*((word32) sp_18 - 6) = ds_20;
			(ss->*((word32) sp_18 - 8)).u0 = 18714;
			Eq_5 si_3962;
			Eq_5 di_3958;
			Eq_5 ds_3959;
			fn1E56_03F5(si_22, di_19, ds_20, ss->*((word32) sp_18 - 8), out si_3962, out di_3958, out ds_3959);
			selector es_3969 = Mem3954[ds_3959:22174:selector];
			int16 ax_3974 = (int16) es_3969->aC618[(int16) es_3969->bD314];
			(ss->*((word32) sp_18 - 6)).u0 = (*((word32) ds_3959 + 0x00004EA4))[ax_3974].u0;
			(ss->*((word32) sp_18 - 8)).u0 = (*((word32) ds_3959 + 20130))[ax_3974].u0;
			Eq_5 si_3993;
			Eq_5 di_3989;
			Eq_5 ds_3990;
			fn1E56_03F5(si_3962, di_3958, ds_3959, ss->*((word32) sp_18 - 8), out si_3993, out di_3989, out ds_3990);
			int16 ax_4002 = (int16) Mem3985[ds_3990:22174:selector]->bD314;
			(ss->*((word32) sp_18 - 6)).u0 = (*((word32) ds_3990 + 20152))[ax_4002].u0;
			(ss->*((word32) sp_18 - 8)).u0 = (*((word32) ds_3990 + 20150))[ax_4002].u0;
			Eq_5 si_4020;
			Eq_5 di_4016;
			Eq_5 ds_4017;
			fn1E56_03F5(si_3993, di_3989, ds_3990, ss->*((word32) sp_18 - 8), out si_4020, out di_4016, out ds_4017);
			if (ax_3974 == 0x04)
			{
				ss->*((word32) sp_18 - 6) = ds_4017;
				(ss->*((word32) sp_18 - 8)).u0 = 0x4948;
				word16 si_7912;
				word16 di_7913;
				selector ds_4155;
				fn1E56_03F5(si_4020, di_4016, ds_4017, ss->*((word32) sp_18 - 8), out si_7912, out di_7913, out ds_4155);
				struct Eq_85094 Eq_62226::* sp_4164 = sp_18 - 0x04;
			}
			else
			{
				selector es_4029 = Mem4012[ds_4017:22174:selector];
				Eq_85065 ax_4034 = es_4029->aC618[(int16) es_4029->bD314] *s16 0x7D;
				if (es_4029->tD372 >= 0x00 && (es_4029->tD372 > 0x00 || (word16) ax_4034 + 75 <= es_4029->tD370))
				{
					es_4029->bD315 = 0x01;
					Eq_85442 ax_4089;
					ax_4089.u0 = (int16) es_4029->bD314;
					es_4029->*((word16) ax_4089 + 0x0000C618) = (word16) (es_4029->*((word16) ax_4089 + 0x0000C618)) + 1;
					es_4029->tD370 -= (uint32) ((word16) ax_4034 + 75);
					goto l1CD3_0961;
				}
				ss->*((word32) sp_18 - 6) = ds_4017;
				(ss->*((word32) sp_18 - 8)).u0 = 0x4999;
				Eq_5 si_4063;
				Eq_5 di_4059;
				Eq_5 ds_4060;
				fn1E56_03F5(si_4020, di_4016, ds_4017, ss->*((word32) sp_18 - 8), out si_4063, out di_4059, out ds_4060);
				word16 di_7919;
				selector ds_4076;
				fn1CD3_1809(fp - 2, si_4063, di_4059, ds_4060, out di_7919, out ds_4076);
				Eq_5 sp_4080;
				sp_4080.u0 = <invalid>;
			}
			selector ds_4166;
			Mem4167[ds_4166:22174:selector]->bD315 = 0x00;
			break;
		case 0x06:
			Mem3708[ds_20:22188:selector]->w4FBA != 0x00;
			(ss->*((word32) sp_18 - 6)).u0 = 0x0A;
			(ss->*((word32) sp_18 - 8)).u0 = 0x3092;
			(ss->*((word32) sp_18 - 0x0A)).u0 = 0x12;
			selector es_3727 = Mem3725[ds_20:22174:selector];
			ss->*((word32) sp_18 - 0x0C) = es_3727->tD372;
			ss->*((word32) sp_18 - 0x0E) = es_3727->tD370;
			struct Eq_62351 Eq_62226::* bp_3736 = fn207F_3BD2(bh_2396, ss->*((word32) sp_18 - 0x0E), ss->*((word32) sp_18 - 0x0C), ss->*((word32) sp_18 - 0x0A), ss->*((word32) sp_18 - 6), out si_3743, out di_3739, out ds_3740);
			(ss->*((word32) sp_18 - 6)).u0 = 0x00;
			(ss->*((word32) sp_18 - 8)).u0 = (ss->*bp_3736).tFFFFFFD0.u0;
			(ss->*((word32) sp_18 - 0x0A)).u0 = 0x01;
			(ss->*((word32) sp_18 - 0x0C)).u0 = 0x3092;
			(ss->*((word32) sp_18 - 0x0E)).u0 = 0x12;
			ss->*((word32) sp_18 - 0x0C) = 0x27 - fn207F_3B9E(ss->*((word32) sp_18 - 0x0E));
			(ss->*((word32) sp_18 - 0x0E)).u0 = 0x3092;
			(ss->*((word32) sp_18 - 16)).u0 = 0x12;
			word16 si_7878;
			word16 di_3791;
			struct Eq_81405 * ds_3792;
			fn1F3D_00D5(si_3743, di_3739, ds_3740, ss->*((word32) sp_18 - 16), ss->*((word32) sp_18 - 0x0C), ss->*((word32) sp_18 - 0x0A), ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), out si_7878, out di_3791, out ds_3792);
			Mem3786[ds_3792:22190:selector]->wE482 = 0x00;
			(ss->*bp_3736).wFFFFFFE2 = 0x00;
			struct Eq_81782 Eq_62226::* bp_3939;
			do
			{
				ui16 si_3809 = (ss->*bp_3807).wFFFFFFE2;
				struct Eq_80552 * es_3813 = Mem3808[ds_3812:22174:selector];
				ui16 si_3811 = si_3809 << 0x02;
				if ((es_3813->aD374[0].w0000[si_3809].w0000 | (((es_3813->aD374))[0].w0002)[si_3809]) != 0x00)
				{
					Mem3808[ds_3812:22192:selector]->t37FE.u0 = 0x0F;
					(ss->*((word32) sp_18 - 6)).u0 = (*((word32) ds_3812 + 20096))[si_3809].u0;
					(ss->*((word32) sp_18 - 8)).u0 = (*((word32) ds_3812 + 0x00004E7E))[si_3809].u0;
					Eq_5 di_3829;
					word16 si_7879;
					word16 di_7880;
					struct Eq_81617 * ds_3835;
					fn1E56_03F5(si_3809 << 0x02, di_3829, ds_3812, ss->*((word32) sp_18 - 8), out si_7879, out di_7880, out ds_3835);
					(ss->*((word32) sp_18 - 6)).u0 = 0x0A;
					(ss->*((word32) sp_18 - 8)).u0 = 0x3092;
					(ss->*((word32) sp_18 - 0x0A)).u0 = 0x12;
					ui16 bx_3854 = (ss->*bp_3807).wFFFFFFE2;
					struct Eq_81642 * es_3858 = ds_3835->ptr569E;
					(ss->*((word32) sp_18 - 0x0C)).u0 = es_3858->aD376[0].u5[bx_3854].u0;
					(ss->*((word32) sp_18 - 0x0E)).u0 = es_3858->aD374[0].u5[bx_3854].u0;
					struct Eq_62351 Eq_62226::* bp_3867 = fn207F_3BD2(SLICE(bx_3854 << 0x02, byte, 8), ss->*((word32) sp_18 - 0x0E), ss->*((word32) sp_18 - 0x0C), ss->*((word32) sp_18 - 0x0A), ss->*((word32) sp_18 - 6), out si_3874, out di_3870, out ds_3871);
					(ss->*((word32) sp_18 - 6)).u0 = 0x00;
					(ss->*((word32) sp_18 - 8)).u0 = (ss->*bp_3867).tFFFFFFD0.u0;
					ss->*((word32) sp_18 - 0x0A) = Mem3887[ds_3871:22194:selector]->t374E;
					(ss->*((word32) sp_18 - 0x0C)).u0 = 0x3092;
					(ss->*((word32) sp_18 - 0x0E)).u0 = 0x12;
					ss->*((word32) sp_18 - 0x0C) = 0x27 - fn207F_3B9E(ss->*((word32) sp_18 - 0x0E));
					(ss->*((word32) sp_18 - 0x0E)).u0 = 0x3092;
					(ss->*((word32) sp_18 - 16)).u0 = 0x12;
					word16 si_3926;
					word16 di_3922;
					struct Eq_81768 * ds_3923;
					fn1F3D_00D5(si_3874, di_3870, ds_3871, ss->*((word32) sp_18 - 16), ss->*((word32) sp_18 - 0x0C), ss->*((word32) sp_18 - 0x0A), ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), out si_3926, out di_3922, out ds_3923);
					struct Eq_81773 * es_3934 = ds_3923->ptr56AE;
					++es_3934->wE482;
				}
				++(ss->*bp_3939).wFFFFFFE2;
				struct Eq_81794 Eq_62226::* sp_4341 = sp_18 - 0x04;
			} while ((ss->*bp_3939).wFFFFFFE2 < 0x03);
			selector ds_3945;
			if (Mem3942[ds_3945:22190:selector]->wE482 == 0x00)
			{
				word16 ax_3949 = 18899;
				goto l1CD3_01B5;
			}
			break;
		case 0x07:
			selector es_3094 = Mem31[ds_20:22174:selector];
			if ((es_3094->tD370 | es_3094->tD372) == 0x00)
			{
				word16 ax_3707 = 19189;
				goto l1CD3_01B5;
			}
			Eq_5 si_3108 = fn1E56_0388(fp - 2, si_22, di_19, ds_20, out di_3104, out ds_3105);
			Eq_5 sp_3109;
			sp_3109.u0 = <invalid>;
			ss->*((word32) sp_3109 - 2) = ds_3105;
			(ss->*((word32) sp_3109 - 4)).u0 = 0x4B3B;
			word16 si_3127;
			word16 di_3123;
			selector ds_3124;
			fn1E56_03F5(si_3108, di_3104, ds_3105, ss->*((word32) sp_3109 - 4), out si_3127, out di_3123, out ds_3124);
			word16 wLoc20_4912 = 0x00;
			Eq_5 si_3161;
			Eq_5 di_3157;
			Eq_5 ds_3158;
			int16 v103_3168;
			do
			{
				Eq_5 ds_3143;
				ui16 wLoc20_4913;
				(ss->*((word32) sp_3109 - 2)).u0 = (*((word32) ds_3143 + 20096))[wLoc20_4913].u0;
				(ss->*((word32) sp_3109 - 4)).u0 = (*((word32) ds_3143 + 0x00004E7E))[wLoc20_4913].u0;
				Eq_5 si_3151;
				Eq_5 di_3152;
				fn1E56_03F5(si_3151, di_3152, ds_3143, ss->*((word32) sp_3109 - 4), out si_3161, out di_3157, out ds_3158);
				v103_3168 = wLoc20_4913 + 0x01;
				int16 wLoc20_4914 = v103_3168;
			} while (v103_3168 < 0x03);
			(ss->*((word32) sp_3109 - 2)).u0 = 0x07;
			Eq_5 si_3182;
			Eq_5 di_3178;
			Eq_5 ds_3179;
			fn1E56_0B5E(si_3161, di_3157, ds_3158, ss->*((word32) sp_3109 - 2), out si_3182, out di_3178, out ds_3179);
			ss->*((word32) sp_3109 - 2) = ds_3179;
			(ss->*((word32) sp_3109 - 4)).u0 = 19282;
			Eq_5 si_3203;
			Eq_5 di_3199;
			Eq_5 ds_3200;
			fn1E56_03F5(si_3182, di_3178, ds_3179, ss->*((word32) sp_3109 - 4), out si_3203, out di_3199, out ds_3200);
			(ss->*((word32) sp_3109 - 2)).u0 = 0x00;
			(ss->*((word32) sp_3109 - 4)).u0 = 0x0F;
			(ss->*((word32) sp_3109 - 6)).u0 = 0x17;
			ss->*((word32) sp_3109 - 8) = Mem3219[ds_3200:22196:selector]->t39A0;
			ss->*((word32) sp_3109 - 0x0A) = ds_3200;
			(ss->*((word32) sp_3109 - 0x0C)).u0 = 19303;
			word16 si_7908;
			word16 di_7909;
			struct Eq_84708 * ds_3233;
			fn1F3D_00D5(si_3203, di_3199, ds_3200, ss->*((word32) sp_3109 - 0x0C), ss->*((word32) sp_3109 - 8), ss->*((word32) sp_3109 - 6), ss->*((word32) sp_3109 - 4), ss->*((word32) sp_3109 - 2), out si_7908, out di_7909, out ds_3233);
			Mem3243[ds_3233:22188:selector]->w4FBA != 0x00;
			(ss->*((word32) sp_3109 - 2)).u0 = 0x0A;
			(ss->*((word32) sp_3109 - 4)).u0 = 0x3092;
			(ss->*((word32) sp_3109 - 6)).u0 = 0x12;
			struct Eq_84735 * es_3262 = ds_3233->ptr569E;
			ss->*((word32) sp_3109 - 8) = es_3262->tD372;
			ss->*((word32) sp_3109 - 0x0A) = es_3262->tD370;
			struct Eq_62351 Eq_62226::* bp_3272 = fn207F_3BD2(0x00, ss->*((word32) sp_3109 - 0x0A), ss->*((word32) sp_3109 - 8), ss->*((word32) sp_3109 - 6), ss->*((word32) sp_3109 - 2), out si_3279, out di_3275, out ds_3276);
			(ss->*((word32) sp_3109 - 2)).u0 = 0x00;
			(ss->*((word32) sp_3109 - 4)).u0 = (ss->*bp_3272).tFFFFFFD0.u0;
			(ss->*((word32) sp_3109 - 6)).u0 = 0x17;
			(ss->*((word32) sp_3109 - 8)).u0 = 0x3092;
			(ss->*((word32) sp_3109 - 0x0A)).u0 = 0x12;
			ss->*((word32) sp_3109 - 8) = 0x27 - fn207F_3B9E(ss->*((word32) sp_3109 - 0x0A));
			(ss->*((word32) sp_3109 - 0x0A)).u0 = 0x3092;
			(ss->*((word32) sp_3109 - 0x0C)).u0 = 0x12;
			Eq_5 si_3331;
			Eq_5 di_3327;
			Eq_5 ds_3328;
			fn1F3D_00D5(si_3279, di_3275, ds_3276, ss->*((word32) sp_3109 - 0x0C), ss->*((word32) sp_3109 - 8), ss->*((word32) sp_3109 - 6), ss->*((word32) sp_3109 - 4), ss->*((word32) sp_3109 - 2), out si_3331, out di_3327, out ds_3328);
			Eq_5 dx_3344;
			Eq_5 si_3346;
			Eq_5 di_3342;
			Eq_5 ds_3343;
			(ss->*bp_3272).tFFFFFFDE.u0 = (wchar_t) fn1543_0CDE(si_3331, di_3327, ds_3328, out dx_3344, out si_3346, out di_3342, out ds_3343);
			(ss->*bp_3272).tFFFFFFE0.u0 = (wchar_t) dx_3344;
			selector es_3354 = Mem3353[ds_3343:22174:selector];
			if ((ss->*bp_3272).tFFFFFFDE.u5 > es_3354->tD370)
			{
				Eq_5 dx_3365 = es_3354->tD372;
				(ss->*bp_3272).tFFFFFFDE.u0 = (wchar_t) es_3354->tD370;
				(ss->*bp_3272).tFFFFFFE0.u0 = (wchar_t) dx_3365;
				ss->*((word32) sp_3109 - 2) = ds_3343;
				(ss->*((word32) sp_3109 - 4)).u0 = 19319;
				word16 si_3387;
				word16 di_3383;
				selector ds_3384;
				fn1E56_03F5(si_3346, di_3342, ds_3343, ss->*((word32) sp_3109 - 4), out si_3387, out di_3383, out ds_3384);
			}
			Eq_5 sp_3405 = sp_3109;
			if (((ss->*bp_3272).tFFFFFFDE.u0 | ((ss->*bp_3272).tFFFFFFE0).u0) != 0x00)
			{
				Eq_5 ds_3407;
				ss->*((word32) sp_3109 - 2) = ds_3407;
				(ss->*((word32) sp_3109 - 4)).u0 = 0x4BB8;
				Eq_5 si_3411;
				Eq_5 di_3412;
				word16 si_7916;
				word16 di_7917;
				selector ds_7918;
				fn1E56_03F5(si_3411, di_3412, ds_3407, ss->*((word32) sp_3109 - 4), out si_7916, out di_7917, out ds_7918);
				(ss->*((word32) sp_3109 - 2)).u0 = 0x0A;
				(ss->*((word32) sp_3109 - 4)).u0 = 0x3092;
				(ss->*((word32) sp_3109 - 6)).u0 = 0x12;
				(ss->*((word32) sp_3109 - 8)).u0 = (ss->*bp_3272).tFFFFFFE0.u0;
				(ss->*((word32) sp_3109 - 0x0A)).u0 = (ss->*bp_3272).tFFFFFFDE.u0;
				struct Eq_62351 Eq_62226::* bp_3446 = fn207F_3BD2(0x00, ss->*((word32) sp_3109 - 0x0A), ss->*((word32) sp_3109 - 8), ss->*((word32) sp_3109 - 6), ss->*((word32) sp_3109 - 2), out si_3453, out di_3449, out ds_3450);
				Mem3443[ds_3450:22192:selector]->t37FE.u0 = 0x02;
				if (Mem3461[ds_3450:22188:selector]->w4FBA == 0x00)
					Mem3461[ds_3450:22192:selector]->t37FE.u0 = 0x01;
				(ss->*((word32) sp_3109 - 2)).u0 = 0x3092;
				(ss->*((word32) sp_3109 - 4)).u0 = 0x12;
				Eq_5 si_3486;
				Eq_5 di_3482;
				Eq_5 ds_3483;
				fn1E56_03F5(si_3453, di_3449, ds_3450, ss->*((word32) sp_3109 - 4), out si_3486, out di_3482, out ds_3483);
				ss->*((word32) sp_3109 - 2) = ds_3483;
				(ss->*((word32) sp_3109 - 4)).u0 = 19416;
				Eq_5 si_3506;
				Eq_5 di_3502;
				Eq_5 ds_3503;
				fn1E56_03F5(si_3486, di_3482, ds_3483, ss->*((word32) sp_3109 - 4), out si_3506, out di_3502, out ds_3503);
				ui16 bx_3514 = (ss->*bp_3446).wFFFFFFE2;
				(ss->*((word32) sp_3109 - 2)).u0 = (*((word32) ds_3503 + 20096))[bx_3514].u0;
				(ss->*((word32) sp_3109 - 4)).u0 = (*((word32) ds_3503 + 0x00004E7E))[bx_3514].u0;
				Eq_5 si_3531;
				Eq_5 di_3527;
				Eq_5 ds_3528;
				fn1E56_03F5(si_3506, di_3502, ds_3503, ss->*((word32) sp_3109 - 4), out si_3531, out di_3527, out ds_3528);
				ss->*((word32) sp_3109 - 2) = ds_3528;
				(ss->*((word32) sp_3109 - 4)).u0 = 0x4BDF;
				word16 si_7920;
				word16 di_7921;
				struct Eq_85606 * ds_3548;
				fn1E56_03F5(si_3531, di_3527, ds_3528, ss->*((word32) sp_3109 - 4), out si_7920, out di_7921, out ds_3548);
				ui16 bx_3560 = (ss->*bp_3446).wFFFFFFE2;
				struct Eq_85616 * es_3563 = ds_3548->ptr569E;
				es_3563->*((word16) (bx_3560 << 0x02) - 0x00002C8C) = (ss->*bp_3446).tFFFFFFDE.u5 + ((es_3563->aD374))[0][bx_3560];
				es_3563->dwD370 -= (ss->*bp_3446).tFFFFFFDE.u5;
				(ss->*((word32) sp_3109 - 2)).u0 = 0x0A;
				(ss->*((word32) sp_3109 - 4)).u0 = 0x3092;
				(ss->*((word32) sp_3109 - 6)).u0 = 0x12;
				ui16 bx_3587 = (ss->*bp_3446).wFFFFFFE2;
				(ss->*((word32) sp_3109 - 8)).u0 = es_3563->aD376[0].u5[bx_3587].u0;
				(ss->*((word32) sp_3109 - 0x0A)).u0 = es_3563->aD374[0][bx_3587].u0;
				Eq_5 ds_3603;
				Eq_5 si_3606;
				Eq_5 di_3602;
				Mem3596[ds_3603:22192:selector]->t37FE.u0 = (ss->*fn207F_3BD2(SLICE(bx_3587 << 0x02, byte, 8), ss->*((word32) sp_3109 - 0x0A), ss->*((word32) sp_3109 - 8), ss->*((word32) sp_3109 - 6), ss->*((word32) sp_3109 - 2), out si_3606, out di_3602, out ds_3603)).tFFFFFFD0.u0;
				(ss->*((word32) sp_3109 - 2)).u0 = 0x3092;
				(ss->*((word32) sp_3109 - 4)).u0 = 0x12;
				word16 si_3630;
				word16 di_3626;
				selector ds_3627;
				fn1E56_03F5(si_3606, di_3602, ds_3603, ss->*((word32) sp_3109 - 4), out si_3630, out di_3626, out ds_3627);
				Eq_5 sp_3636 = sp_3109;
				word16 ax_3638 = 0x4C07;
				goto l1CD3_0957;
			}
			else
			{
				word16 ax_3665 = 0x4C0B;
				goto l1CD3_070D;
			}
		case 0x08:
			if (Mem31[ds_20:22190:selector]->wE482 == 0x00)
			{
				word16 ax_3093 = 0x49D9;
				goto l1CD3_01B5;
			}
			Eq_5 si_2543 = fn1E56_0388(fp - 2, si_22, di_19, ds_20, out di_2539, out ds_2540);
			Eq_5 sp_2544;
			sp_2544.u0 = <invalid>;
			ss->*((word32) sp_2544 - 2) = ds_2540;
			(ss->*((word32) sp_2544 - 4)).u0 = 0x49F6;
			word16 si_2562;
			word16 di_2558;
			selector ds_2559;
			fn1E56_03F5(si_2543, di_2539, ds_2540, ss->*((word32) sp_2544 - 4), out si_2562, out di_2558, out ds_2559);
			word16 wLoc20_4905 = 0x00;
			Eq_5 si_2596;
			Eq_5 di_2592;
			Eq_5 ds_2593;
			int16 v108_2603;
			do
			{
				Eq_5 ds_2578;
				ui16 wLoc20_4906;
				(ss->*((word32) sp_2544 - 2)).u0 = (*((word32) ds_2578 + 20096))[wLoc20_4906].u0;
				(ss->*((word32) sp_2544 - 4)).u0 = (*((word32) ds_2578 + 0x00004E7E))[wLoc20_4906].u0;
				Eq_5 si_2586;
				Eq_5 di_2587;
				fn1E56_03F5(si_2586, di_2587, ds_2578, ss->*((word32) sp_2544 - 4), out si_2596, out di_2592, out ds_2593);
				v108_2603 = wLoc20_4906 + 0x01;
				int16 wLoc20_4907 = v108_2603;
			} while (v108_2603 < 0x03);
			(ss->*((word32) sp_2544 - 2)).u0 = 0x07;
			Eq_5 ax_2610 = fn1E56_0B5E(si_2596, di_2592, ds_2593, ss->*((word32) sp_2544 - 2), out si_2617, out di_2613, out ds_2614);
			struct Eq_80552 * es_2628 = Mem2624[ds_2614:22174:selector];
			Eq_5 sp_2623 = sp_2544;
			if ((es_2628->aD374[0].w0000[ax_2610].w0000 | ((((es_2628->aD374))[0].w0002))[ax_2610].w0000) == 0x00)
			{
				word16 ax_3092 = 19147;
				goto l1CD3_01B5;
			}
			ss->*((word32) sp_2544 - 2) = ds_2614;
			(ss->*((word32) sp_2544 - 4)).u0 = 0x4A09;
			Eq_5 si_2647;
			Eq_5 di_2643;
			Eq_5 ds_2644;
			fn1E56_03F5(si_2617, di_2613, ds_2614, ss->*((word32) sp_2544 - 4), out si_2647, out di_2643, out ds_2644);
			(ss->*((word32) sp_2544 - 2)).u0 = 0x00;
			(ss->*((word32) sp_2544 - 4)).u0 = 0x0F;
			(ss->*((word32) sp_2544 - 6)).u0 = 0x17;
			ss->*((word32) sp_2544 - 8) = Mem2663[ds_2644:22196:selector]->t39A0;
			ss->*((word32) sp_2544 - 0x0A) = ds_2644;
			(ss->*((word32) sp_2544 - 0x0C)).u0 = 0x4A1C;
			word16 si_7910;
			word16 di_7911;
			struct Eq_85039 * ds_2677;
			fn1F3D_00D5(si_2647, di_2643, ds_2644, ss->*((word32) sp_2544 - 0x0C), ss->*((word32) sp_2544 - 8), ss->*((word32) sp_2544 - 6), ss->*((word32) sp_2544 - 4), ss->*((word32) sp_2544 - 2), out si_7910, out di_7911, out ds_2677);
			Mem2687[ds_2677:22188:selector]->w4FBA != 0x00;
			(ss->*((word32) sp_2544 - 2)).u0 = 0x0A;
			(ss->*((word32) sp_2544 - 4)).u0 = 0x3092;
			(ss->*((word32) sp_2544 - 6)).u0 = 0x12;
			struct Eq_85766 * es_2711 = ds_2677->ptr569E;
			(ss->*((word32) sp_2544 - 8)).u0 = es_2711->aD376[0].u5[ax_2610].u0;
			(ss->*((word32) sp_2544 - 0x0A)).u0 = es_2711->aD374[0].u5[ax_2610].u0;
			struct Eq_62351 Eq_62226::* bp_2720 = fn207F_3BD2(SLICE(ax_2610 << 0x02, byte, 8), ss->*((word32) sp_2544 - 0x0A), ss->*((word32) sp_2544 - 8), ss->*((word32) sp_2544 - 6), ss->*((word32) sp_2544 - 2), out si_2727, out di_2723, out ds_2724);
			(ss->*((word32) sp_2544 - 2)).u0 = 0x00;
			(ss->*((word32) sp_2544 - 4)).u0 = (ss->*bp_2720).tFFFFFFD0.u0;
			(ss->*((word32) sp_2544 - 6)).u0 = 0x17;
			(ss->*((word32) sp_2544 - 8)).u0 = 0x3092;
			(ss->*((word32) sp_2544 - 0x0A)).u0 = 0x12;
			ss->*((word32) sp_2544 - 8) = 0x27 - fn207F_3B9E(ss->*((word32) sp_2544 - 0x0A));
			(ss->*((word32) sp_2544 - 0x0A)).u0 = 0x3092;
			(ss->*((word32) sp_2544 - 0x0C)).u0 = 0x12;
			Eq_5 si_2779;
			Eq_5 di_2775;
			Eq_5 ds_2776;
			fn1F3D_00D5(si_2727, di_2723, ds_2724, ss->*((word32) sp_2544 - 0x0C), ss->*((word32) sp_2544 - 8), ss->*((word32) sp_2544 - 6), ss->*((word32) sp_2544 - 4), ss->*((word32) sp_2544 - 2), out si_2779, out di_2775, out ds_2776);
			Eq_5 dx_2792;
			Eq_5 si_2794;
			Eq_5 di_2790;
			Eq_5 ds_2791;
			(ss->*bp_2720).tFFFFFFDE.u0 = (wchar_t) fn1543_0CDE(si_2779, di_2775, ds_2776, out dx_2792, out si_2794, out di_2790, out ds_2791);
			(ss->*bp_2720).tFFFFFFE0.u0 = (wchar_t) dx_2792;
			ui16 bx_2802 = (ss->*bp_2720).wFFFFFFE2;
			struct Eq_80552 * es_2805 = Mem2801[ds_2791:22174:selector];
			Eq_5 ax_2806;
			ax_2806.u0 = es_2805->aD374[0].w0000[bx_2802].u0;
			Eq_5 dx_2807;
			dx_2807.u0 = es_2805->aD374[0].w0002[bx_2802].u0;
			(ss->*bp_2720).tFFFFFFCC.u0 = (wchar_t) ax_2806;
			(ss->*bp_2720).tFFFFFFCE.u0 = (wchar_t) dx_2807;
			if ((ss->*bp_2720).tFFFFFFDE.u5 > SEQ(dx_2807, ax_2806))
			{
				Eq_5 dx_2819;
				dx_2819.u0 = (ss->*bp_2720).tFFFFFFCE.u0;
				(ss->*bp_2720).tFFFFFFDE.u0 = (ss->*bp_2720).tFFFFFFCC.u0;
				(ss->*bp_2720).tFFFFFFE0.u0 = (wchar_t) dx_2819;
				ss->*((word32) sp_2544 - 2) = ds_2791;
				(ss->*((word32) sp_2544 - 4)).u0 = 18987;
				word16 si_2839;
				word16 di_2835;
				selector ds_2836;
				fn1E56_03F5(si_2794, di_2790, ds_2791, ss->*((word32) sp_2544 - 4), out si_2839, out di_2835, out ds_2836);
			}
			Eq_5 sp_2857 = sp_2544;
			if (((ss->*bp_2720).tFFFFFFDE.u0 | ((ss->*bp_2720).tFFFFFFE0).u0) != 0x00)
			{
				Eq_5 ds_2859;
				ss->*((word32) sp_2544 - 2) = ds_2859;
				(ss->*((word32) sp_2544 - 4)).u0 = 0x4A6A;
				Eq_5 si_2863;
				Eq_5 di_2864;
				word16 si_7922;
				word16 di_7923;
				selector ds_7924;
				fn1E56_03F5(si_2863, di_2864, ds_2859, ss->*((word32) sp_2544 - 4), out si_7922, out di_7923, out ds_7924);
				(ss->*((word32) sp_2544 - 2)).u0 = 0x0A;
				(ss->*((word32) sp_2544 - 4)).u0 = 0x3092;
				(ss->*((word32) sp_2544 - 6)).u0 = 0x12;
				(ss->*((word32) sp_2544 - 8)).u0 = (ss->*bp_2720).tFFFFFFE0.u0;
				(ss->*((word32) sp_2544 - 0x0A)).u0 = (ss->*bp_2720).tFFFFFFDE.u0;
				struct Eq_62351 Eq_62226::* bp_2898 = fn207F_3BD2(0x00, ss->*((word32) sp_2544 - 0x0A), ss->*((word32) sp_2544 - 8), ss->*((word32) sp_2544 - 6), ss->*((word32) sp_2544 - 2), out si_2905, out di_2901, out ds_2902);
				Mem2895[ds_2902:22192:selector]->t37FE.u0 = 0x02;
				if (Mem2913[ds_2902:22188:selector]->w4FBA == 0x00)
					Mem2913[ds_2902:22192:selector]->t37FE.u0 = 0x01;
				(ss->*((word32) sp_2544 - 2)).u0 = 0x3092;
				(ss->*((word32) sp_2544 - 4)).u0 = 0x12;
				Eq_5 si_2938;
				Eq_5 di_2934;
				Eq_5 ds_2935;
				fn1E56_03F5(si_2905, di_2901, ds_2902, ss->*((word32) sp_2544 - 4), out si_2938, out di_2934, out ds_2935);
				ss->*((word32) sp_2544 - 2) = ds_2935;
				(ss->*((word32) sp_2544 - 4)).u0 = 0x4A86;
				Eq_5 si_2958;
				Eq_5 di_2954;
				Eq_5 ds_2955;
				fn1E56_03F5(si_2938, di_2934, ds_2935, ss->*((word32) sp_2544 - 4), out si_2958, out di_2954, out ds_2955);
				ui16 bx_2966 = (ss->*bp_2898).wFFFFFFE2;
				(ss->*((word32) sp_2544 - 2)).u0 = (*((word32) ds_2955 + 20096))[bx_2966].u0;
				(ss->*((word32) sp_2544 - 4)).u0 = (*((word32) ds_2955 + 0x00004E7E))[bx_2966].u0;
				Eq_5 si_2983;
				Eq_5 di_2979;
				Eq_5 ds_2980;
				fn1E56_03F5(si_2958, di_2954, ds_2955, ss->*((word32) sp_2544 - 4), out si_2983, out di_2979, out ds_2980);
				ss->*((word32) sp_2544 - 2) = ds_2980;
				(ss->*((word32) sp_2544 - 4)).u0 = 0x4A8D;
				word16 si_7925;
				word16 di_7926;
				struct Eq_86330 * ds_3000;
				fn1E56_03F5(si_2983, di_2979, ds_2980, ss->*((word32) sp_2544 - 4), out si_7925, out di_7926, out ds_3000);
				ui16 bx_3012 = (ss->*bp_2898).wFFFFFFE2;
				struct Eq_86340 * es_3015 = ds_3000->ptr569E;
				es_3015->*((word16) (bx_3012 << 0x02) - 0x00002C8C) = es_3015->aD374[0][bx_3012] - ((ss->*bp_2898).tFFFFFFDE).u5;
				es_3015->dwD370 = (ss->*bp_2898).tFFFFFFDE.u5 + es_3015->dwD370;
				(ss->*((word32) sp_2544 - 2)).u0 = 0x0A;
				(ss->*((word32) sp_2544 - 4)).u0 = 0x3092;
				(ss->*((word32) sp_2544 - 6)).u0 = 0x12;
				ui16 bx_3039 = (ss->*bp_2898).wFFFFFFE2;
				(ss->*((word32) sp_2544 - 8)).u0 = es_3015->aD376[0].u5[bx_3039].u0;
				(ss->*((word32) sp_2544 - 0x0A)).u0 = es_3015->aD374[0][bx_3039].u0;
				Eq_5 ds_3055;
				Eq_5 si_3058;
				Eq_5 di_3054;
				Mem3048[ds_3055:22192:selector]->t37FE.u0 = (ss->*fn207F_3BD2(SLICE(bx_3039 << 0x02, byte, 8), ss->*((word32) sp_2544 - 0x0A), ss->*((word32) sp_2544 - 8), ss->*((word32) sp_2544 - 6), ss->*((word32) sp_2544 - 2), out si_3058, out di_3054, out ds_3055)).tFFFFFFD0.u0;
				(ss->*((word32) sp_2544 - 2)).u0 = 0x3092;
				(ss->*((word32) sp_2544 - 4)).u0 = 0x12;
				word16 si_3082;
				word16 di_3078;
				selector ds_3079;
				fn1E56_03F5(si_3058, di_3054, ds_3055, ss->*((word32) sp_2544 - 4), out si_3082, out di_3078, out ds_3079);
				Eq_5 sp_3088 = sp_2544;
				word16 ax_3090 = 19132;
l1CD3_0957:
				struct Eq_86476 Eq_62226::* sp_3640 = sp_3639 - 2;
				Eq_5 ds_3641;
				(ss->*sp_3640).t0000.u0 = (wchar_t) ds_3641;
				Eq_5 ax_3645;
				(ss->*sp_3640).tFFFFFFFE.u0 = (wchar_t) ax_3645;
				Eq_5 si_3647;
				Eq_5 di_3648;
				word16 si_3657;
				word16 di_3653;
				selector ds_3654;
				fn1E56_03F5(si_3647, di_3648, ds_3641, (ss->*sp_3640).tFFFFFFFE.u5, out si_3657, out di_3653, out ds_3654);
				goto l1CD3_0961;
			}
			word16 ax_3091 = 0x4AC0;
l1CD3_070D:
			struct Eq_85471 Eq_62226::* sp_3667 = sp_3666 - 2;
			Eq_5 ds_3668;
			(ss->*sp_3667).t0000.u0 = (wchar_t) ds_3668;
			Eq_5 ax_3672;
			(ss->*sp_3667).tFFFFFFFE.u0 = (wchar_t) ax_3672;
			Eq_5 si_3674;
			Eq_5 di_3675;
			Eq_5 si_3684;
			Eq_5 di_3680;
			Eq_5 ds_3681;
			fn1E56_03F5(si_3674, di_3675, ds_3668, (ss->*sp_3667).tFFFFFFFE.u5, out si_3684, out di_3680, out ds_3681);
			struct Eq_85500 * ds_3697 = fn0FDC_19E1(bp_3692, si_3684, di_3680, ds_3681);
			Eq_5 sp_3701;
			sp_3701.u0 = <invalid>;
			break;
		case 0x09:
			word16 wArg04_4898 = Mem31[ds_20:0x56B6:selector]->w0178;
			if (Mem2451[ds_20:22174:selector]->bD316 != 0x00)
			{
				word16 wArg04_4899 = Mem2451[ds_20:0x56B6:selector]->w0168;
			}
			selector es_2460 = Mem2459[ds_20:22174:selector];
			es_2460->bD317 = 0x00;
			Eq_5 ax_2467;
			ui16 wArg04_4900;
			ax_2467.u0 = (*((word32) ds_20 + 20262))[wArg04_4900].u0;
			Eq_5 dx_2468;
			dx_2468.u0 = (*((word32) ds_20 + 20264))[wArg04_4900].u0;
			if (es_2460->tD372 >= dx_2468 && (es_2460->tD372 > dx_2468 || es_2460->tD370 >= ax_2467))
			{
				es_2460->tD370 -= SEQ(dx_2468, ax_2467);
				es_2460->bD317 = 0x01;
				Eq_36 bp_2498 = fn1631_1FDF(si_22, di_19, ds_20, out si_2505, out di_2501, out ds_2502);
				Eq_5 bx_2513;
				bx_2513.u5 = ss->*((word16) bp_2498 + 6);
				Eq_5 sp_2506;
				sp_2506.u0 = <invalid>;
				(ss->*((word32) sp_2506 - 2)).u2 = (int16) (ds_2502->*((word32) bx_2513 + 0x00004DDB));
				ss->*((word32) sp_2506 - 4) = bx_2513;
				struct Eq_84481 Eq_62226::* sp_2518 = sp_2506 - 4;
				struct Eq_84493 * ds_2524 = fn0FDC_13DE(si_2505, di_2501, ds_2502, ss->*((word32) sp_2506 - 4), ss->*((word32) sp_2506 - 2));
				goto l1CD3_01BC;
			}
			break;
		case 0x0A:
			(ss->*((word32) sp_18 - 6)).u0 = 0x0A;
			(ss->*((word32) sp_18 - 8)).u0 = 0x3092;
			(ss->*((word32) sp_18 - 0x0A)).u0 = 0x12;
			selector es_2389 = Mem2388[ds_20:22174:selector];
			ss->*((word32) sp_18 - 0x0C) = es_2389->tD372;
			ss->*((word32) sp_18 - 0x0E) = es_2389->tD370;
			struct Eq_62351 Eq_62226::* bp_2398 = fn207F_3BD2(bh_2396, ss->*((word32) sp_18 - 0x0E), ss->*((word32) sp_18 - 0x0C), ss->*((word32) sp_18 - 0x0A), ss->*((word32) sp_18 - 6), out si_2405, out di_2401, out ds_2402);
			Mem2395[ds_2402:22192:selector]->t37FE.u0 = 0x02;
			if (Mem2413[ds_2402:22188:selector]->w4FBA == 0x00)
			{
				selector es_2417 = Mem2413[ds_2402:22192:selector];
				--es_2417->t37FE;
			}
			(ss->*((word32) sp_18 - 6)).u0 = 0x3092;
			(ss->*((word32) sp_18 - 8)).u0 = 0x12;
			word16 si_2440;
			word16 di_2436;
			selector ds_2437;
			fn1E56_03F5(si_2405, di_2401, ds_2402, ss->*((word32) sp_18 - 8), out si_2440, out di_2436, out ds_2437);
			struct Eq_84341 Eq_62226::* sp_2446 = sp_18 - 0x04;
			word16 ax_2448 = 0x4C18;
l1CD3_01B5:
			struct Eq_81260 Eq_62226::* sp_4342 = sp_4340 - 2;
			struct Eq_81262 * ds_4343;
			(ss->*sp_4342).ptr0000 = ds_4343;
			word16 ax_4347;
			(ss->*sp_4342).wFFFFFFFE = ax_4347;
			struct Eq_81273 Eq_62226::* sp_4346 = sp_4342 - 2;
			goto l1CD3_01B7;
		case 11:
			word16 wArg04_4888 = Mem31[ds_20:0x56B6:selector]->w0198;
			if (Mem2281[ds_20:22174:selector]->bD318 == 0x06)
			{
				word16 wArg04_4889 = Mem2281[ds_20:0x56B6:selector]->w01A8 + 0x06;
			}
			if (Mem2291[ds_20:22174:selector]->bD318 == 0x09)
			{
				word16 wArg04_4890 = Mem2291[ds_20:0x56B6:selector]->w01B8 + 0x09;
			}
			selector es_2308 = Mem2306[ds_20:22174:selector];
			es_2308->bD317 = 0x00;
			ui16 v91_2305 = wArg04_4891 - 0x01;
			Eq_5 ax_2313;
			ax_2313.u0 = (*((word32) ds_20 + 0x00004F44))[v91_2305].u0;
			Eq_5 dx_2314;
			dx_2314.u0 = (*((word32) ds_20 + 0x00004F46))[v91_2305].u0;
			if (es_2308->tD372 >= dx_2314 && (es_2308->tD372 > dx_2314 || es_2308->tD370 >= ax_2313))
			{
				es_2308->tD370 -= SEQ(dx_2314, ax_2313);
				es_2308->bD317 = 0x01;
				Eq_36 bp_2347 = fn1631_1FDF(si_22, di_19, ds_20, out si_2354, out di_2350, out ds_2351);
				Eq_5 sp_2355;
				sp_2355.u0 = <invalid>;
				(ss->*((word32) sp_2355 - 2)).u5 = (word16) (ss->*((word16) bp_2347 + 6)) + 1;
				word16 di_7907;
				selector ds_2371;
				fn0FDC_15E6(si_2354, di_2350, ds_2351, ss->*((word32) sp_2355 - 2), out di_7907, out ds_2371);
				struct Eq_84431 Eq_62226::* sp_2365 = sp_2355 - 2;
				goto l1CD3_0181;
			}
			break;
		case 0x0C:
			struct Eq_80841 * ds_2270 = fn0FDC_17B9(si_22, di_19, ds_20);
			break;
		case 0x0D:
			(ss->*((word32) sp_18 - 6)).u0 = 0x0E;
			// Failed to bind call argument.
			// Please report this issue at https://github.com/uxmal/reko
			Eq_5 stackArg4;
			stackArg4.u0 = <invalid>;
			word16 si_7875;
			word16 di_7876;
			selector ds_7877;
			fn1CD3_0004(si_22, di_19, ds_20, stackArg4, out si_7875, out di_7876, out ds_7877);
			Eq_5 sp_2132;
			sp_2132.u0 = <invalid>;
			word16 sp_2139 = (word16) &sp_2132.u7->w0002;
			word16 wLoc20_4873 = 0x00;
			int16 v86_2147;
			do
			{
				int16 wLoc20_4874;
				ss->*((char *) (fp - 0x0A) + wLoc20_4874) = (<unknown> Eq_62226::*) 0x00;
				v86_2147 = wLoc20_4874 + 0x01;
				int16 si_2145 = wLoc20_4874;
				int16 wLoc20_4875 = v86_2147;
			} while (v86_2147 < 0x08);
			Mem2148[ds_20:0x56B6:selector]->t0202 = Mem2148[ds_20:22194:selector]->t374E;
			selector es_2160 = Mem2155[ds_20:0x56B6:selector];
			es_2160->w0206 = (int16) Mem2155[ds_20:22174:selector]->bD31A + 0x01;
			es_2160->w0208 = 0x00;
			word16 wLoc20_4876 = 0x00;
			word16 wArg04_4877 = 0x00;
			ci16 v90_2234;
			do
			{
				byte bArg04_4882 = (byte) wArg04_4878;
				int8 al_2176 = Mem2170[ds_2174:22174:selector]:50708[wArg04_4878 * 0x11];
				if (al_2176 != ~0x00)
				{
					int16 ax_2180 = (int16) al_2176;
					struct Eq_82477 * es_2185 = Mem2177[ds_2174:22200:selector];
					struct Eq_84150 Eq_62226::* sp_2188 = sp_2187 - 2;
					(ss->*sp_2188).w0000 = es_2185->a01CC[0].u5[ax_2180].w0000;
					(ss->*sp_2188).tFFFFFFFE.u0 = es_2185->a01CA[0].u5[ax_2180].u0;
					Eq_5 si_2193;
					Eq_5 di_2194;
					Eq_5 si_2203;
					Eq_5 di_2199;
					Eq_5 ds_2200;
					fn1E56_03F5(si_2193, di_2194, ds_2174, (ss->*sp_2188).tFFFFFFFE.u5, out si_2203, out di_2199, out ds_2200);
					word16 di_2214;
					selector ds_2215;
					fn1CD3_181E(fp - 2, si_2203, di_2199, ds_2200, out di_2214, out ds_2215);
					int16 wLoc20_4880;
					ss->*((char *) (fp - 0x0A) + wLoc20_4880) = (<unknown> Eq_62226::*) bArg04_4882;
					Eq_5 sp_2219;
					sp_2219.u0 = <invalid>;
					int16 si_2225 = wLoc20_4880;
					int16 wLoc20_4881 = wLoc20_4880 + 0x01;
				}
				v90_2234 = wArg04_4878 + 0x01;
				ci16 wArg04_4886 = v90_2234;
			} while (v90_2234 < 0x08);
			union Eq_5 Eq_62226::* sp_2240 = sp_2239 - 2;
			(ss->*sp_2240).u0 = 0x17;
			struct Eq_84254 * ds_2250;
			Eq_5 si_2243;
			Eq_5 di_2244;
			Eq_5 ds_2242;
			word16 si_7905;
			word16 di_7906;
			Mem2261[ds_2250:22174:selector]->bD31A = (byte) (ss->*((fp - 0x0A) + fn1E56_0B5E(si_2243, di_2244, ds_2242, (ss->*sp_2240).u0, out si_7905, out di_7906, out ds_2250)));
			union Eq_5 Eq_62226::* sp_2259 = (union Eq_5 Eq_62226::*) ((char *) sp_2240 + 2);
			break;
		case 0x0E:
			struct Eq_80552 * es_2105 = Mem31[ds_20:22174:selector];
			es_2105->bD31A = 0x00;
			word16 wArg04_4869 = 0x01;
			int16 wArg04_4870;
			while (wArg04_4870 < 0x08)
			{
				if (es_2105->bC614[wArg04_4870].b0000 != ~0x00)
					++es_2105->bD31A;
				int16 wArg04_4872 = wArg04_4870 + 0x01;
			}
			break;
		case 0x0F:
			struct Eq_80552 * es_2075 = Mem31[ds_20:22174:selector];
			if (es_2075->tD372 == 0x00 && es_2075->tD370 < 500)
				goto l1CD3_0C3D;
			es_2075->tD370 -= 500;
			es_2075->aC618[5][es_2075->bD31A].b0000 = (byte) ((word136) es_2075->aC618[5][es_2075->bD31A] + 1);
			(&es_2075->bC623)[1][es_2075->bD31A].b0000 = (&es_2075->bC623)[1][es_2075->bD31A].b0000 | 0x01;
			goto l1CD3_0C9B;
		case 0x10:
			struct Eq_80552 * es_2063 = Mem31[ds_20:22174:selector];
			word16 ax_7869 = SEQ(SLICE(es_2063->bD31A *s16 0x11, byte, 8), (&es_2063->bC623)[1][es_2063->bD31A] & 0x01);
			goto l1CD3_0BF5;
		case 0x11:
			struct Eq_80552 * es_2039 = Mem31[ds_20:22174:selector];
			es_2039->bD31C = 0x00;
			word16 wLoc20_4865 = 0x00;
			int16 wLoc20_4866;
			while (wLoc20_4866 < 0x04)
			{
				if (es_2039->bC724[wLoc20_4866].b0000 != ~0x00)
					++es_2039->bD31C;
				int16 wLoc20_4868 = wLoc20_4866 + 0x01;
			}
			break;
		case 0x12:
			fn11B8_0002(si_22, di_19, ds_20);
			Eq_5 sp_2032;
			sp_2032.u0 = <invalid>;
			break;
		case 0x13:
			fn11B8_080A(si_22, di_19, ds_20);
			struct Eq_80919 Eq_62226::* sp_2025 = sp_18 - 4;
			break;
		case 0x14:
			word16 bp_2010 = fn11B8_0925(si_22, di_19, ds_20, out ds_2014);
			Eq_5 sp_2018;
			sp_2018.u0 = <invalid>;
			break;
		case 0x15:
			struct Eq_80552 * es_1983 = Mem31[ds_20:22174:selector];
			if (es_1983->tD372 != 0x00 || es_1983->tD370 >= 500)
			{
				es_1983->tD370 -= 500;
				es_1983->aC618[6][es_1983->bD31A].b0000 = (byte) ((word136) es_1983->aC618[6][es_1983->bD31A] + 1);
				(&es_1983->bC623)[1][es_1983->bD31A].b0000 = (&es_1983->bC623)[1][es_1983->bD31A].b0000 | 0x02;
l1CD3_0C9B:
				selector es_2103;
				es_2103->bD31A = 0x01;
				goto l1CD3_0961;
			}
l1CD3_0C3D:
			selector es_2080;
			es_2080->bD31A = 0x00;
			break;
		case 22:
			struct Eq_80552 * es_1974 = Mem31[ds_20:22174:selector];
			word16 ax_7868 = SEQ(SLICE(es_1974->bD31A *s16 0x11, byte, 8), (&es_1974->bC623)[1][es_1974->bD31A].b0000 & 0x02);
l1CD3_0BF5:
			selector es_2073;
			word16 ax_7870;
			es_2073->bD31B = (byte) ax_7870;
			break;
		case 0x17:
			Mem31[ds_20:22174:selector]->bD325 = 0x00;
			word16 wLoc20_4861 = 0x00;
			int16 wLoc20_4862;
			while (wLoc20_4862 < 0x08)
			{
				struct Eq_80552 * es_1957 = Mem1949[ds_20:22174:selector];
				if (es_1957->bC614[wLoc20_4862].b0000 != ~0x00 && ((((es_1957->aC615))[0].b0000))[wLoc20_4862].b0000 *s16 0x0A != (int16) ((es_1957->bC623))[wLoc20_4862].b0000)
					es_1957->bD325 = 0x01;
				int16 wLoc20_4864 = wLoc20_4862 + 0x01;
			}
			break;
		case 0x18:
			selector es_1814 = Mem31[ds_20:22174:selector];
			if (es_1814->bD326 == 0x00)
			{
				(ss->*((word32) sp_18 - 6)).u0 = 0x00;
				// Failed to bind call argument.
				// Please report this issue at https://github.com/uxmal/reko
				Eq_5 stackArg4;
				stackArg4.u0 = <invalid>;
				word16 si_7895;
				word16 di_7896;
				selector ds_7897;
				fn1431_000A(si_22, di_19, ds_20, stackArg4, out si_7895, out di_7896, out ds_7897);
				struct Eq_83342 Eq_62226::* sp_1821 = sp_18 - 6;
				goto l1CD3_0181;
			}
			Eq_5 ax_1829;
			ax_1829.u2 = (int16) es_1814->bD326;
			Eq_5 si_1830 = ax_1829;
			Eq_5 ax_1833;
			ax_1833.u0 = (*((word32) ds_20 + 20334))[ax_1829].t0000.u0;
			if (es_1814->tD372 >= 0x00 && (es_1814->tD372 > 0x00 || es_1814->tD370 >= ax_1833))
			{
				es_1814->tD370 -= (uint32) ax_1833;
				ss->*((word32) sp_18 - 6) = ax_1829;
				// Failed to bind call argument.
				// Please report this issue at https://github.com/uxmal/reko
				Eq_5 stackArg4;
				stackArg4.u0 = <invalid>;
				word16 si_7899;
				word16 di_7900;
				selector ds_7901;
				fn1431_000A(ax_1829, di_19, ds_20, stackArg4, out si_7899, out di_7900, out ds_7901);
			}
			else
			{
				Eq_5 di_1853;
				Eq_5 ds_1854;
				Eq_5 di_1867;
				Eq_5 ds_1868;
				Eq_5 di_1881;
				Eq_5 ds_1882;
				word16 si_1899;
				word16 di_1895;
				struct Eq_83387 * ds_1896;
				fn1F3D_0259(fn1F3D_086A(fp - 2, fn1CD3_1809(fp - 2, fn1CD3_181E(fp - 2, ax_1829, di_19, ds_20, out di_1853, out ds_1854), di_1853, ds_1854, out di_1867, out ds_1868), di_1867, ds_1868, out di_1881, out ds_1882), di_1881, ds_1882, out si_1899, out di_1895, out ds_1896);
				struct Eq_83392 * es_1906 = ds_1896->ptr569E;
				es_1906->dwD370 += 0x19;
			}
l1CD3_0961:
			Eq_36 bp_4131 = fn1631_1FDF(si_4115, di_4120, ds_4110, out si_7902, out di_7903, out ds_4135);
			Eq_5 sp_4139;
			sp_4139.u0 = <invalid>;
			break;
		case 0x19:
			Mem31[ds_20:22174:selector]->bD450 = 0x01;
			break;
		case 0x1A:
			Mem31[ds_20:22174:selector]->bD451 = 0x01;
			break;
		case 0x1B:
			goto l1CD3_0E54;
		case 0x1C:
			word16 wLoc1A_4850 = 0x00;
			Eq_83139 wLoc1A_4851;
			while (wLoc1A_4851 < 0x04)
			{
				struct Eq_80552 * es_1720 = Mem1712[ds_20:22174:selector];
				es_1720->*((word16) wLoc1A_4851 + 54354) = es_1720->bC724[wLoc1A_4851].b0000;
				es_1720->bC724[wLoc1A_4851].b0000 = ~0x00;
				es_1720->aC664[0].b0000[wLoc1A_4851].b0000 = 0x08;
				es_1720->bC620[wLoc1A_4851].b0000 = 0x08;
				Eq_83195 wLoc1A_4852 = (word16) wLoc1A_4851 + 1;
			}
			break;
		case 0x1D:
			selector es_1686 = Mem31[ds_20:22174:selector];
			es_1686->bD31C = 0x00;
			word16 wLoc20_4846 = 0x00;
			Eq_83028 wLoc20_4847;
			while (wLoc20_4847 < 0x04)
			{
				if (es_1686->*((word16) wLoc20_4847 + 54354) >= 0x41 && es_1686->*((word16) wLoc20_4847 + 54354) <= 0x5A)
					++es_1686->bD31C;
				Eq_83179 wLoc20_4849 = (word16) wLoc20_4847 + 1;
			}
			break;
		case 0x1E:
			fn11B8_104E(si_22, di_19, ds_20);
			struct Eq_81006 Eq_62226::* sp_1679 = sp_18 - 4;
			break;
		case 0x1F:
			struct Eq_80552 * es_1672 = Mem31[ds_20:22174:selector];
			es_1672->bD32B = (byte) (&es_1672->bC620)[1][es_1672->bD31A];
			break;
		case 0x20:
			struct Eq_80552 * es_1315 = Mem31[ds_20:22174:selector];
			int16 ax_1317 = (int16) es_1315->bD31A;
			Eq_81037 ax_1324;
			ax_1324.u0 = (int16) (&es_1315->bC620)[1][ax_1317].b0000;
			int16 si_1322 = ax_1317 *s 0x11;
			int16 ax_1328 = (int16) (&es_1315->bC620)[2][ax_1317];
			if ((int16) (ds_20->*((word16) ax_1324 + 0x00004DDB)) == ax_1328)
			{
				word16 ax_1632 = 0x4C1C;
				goto l1CD3_0F2A;
			}
			ss->*((word32) sp_18 - 6) = ds_20;
			(ss->*((word32) sp_18 - 8)).u0 = 0x4C60;
			Eq_5 si_1347;
			Eq_5 di_1343;
			Eq_5 ds_1344;
			fn1E56_03F5(ax_1317 *s 0x11, di_19, ds_20, ss->*((word32) sp_18 - 8), out si_1347, out di_1343, out ds_1344);
			Eq_5 ax_1357 = (int16) (ds_1344->*((word16) ax_1324 + 0x00004DDB)) - ax_1328;
			if (ax_1328 == 0x00)
			{
				word16 ax_1381 = 0x4C75;
			}
			else
			{
				ss->*((word32) sp_18 - 6) = ax_1357;
				Eq_5 si_1371 = fn1F3D_0053(si_1347, di_1343, ds_1344, ss->*((word32) sp_18 - 6), out di_1367, out ds_1368);
				word16 ax_1380 = 19577;
			}
			Eq_5 ds_1384;
			ss->*((word32) sp_18 - 6) = ds_1384;
			Eq_5 ax_1388;
			ss->*((word32) sp_18 - 8) = ax_1388;
			Eq_5 si_1390;
			Eq_5 di_1391;
			Eq_5 si_1400;
			Eq_5 di_1396;
			Eq_5 ds_1397;
			fn1E56_03F5(si_1390, di_1391, ds_1384, ss->*((word32) sp_18 - 8), out si_1400, out di_1396, out ds_1397);
			ss->*((word32) sp_18 - 6) = ds_1397;
			(ss->*((word32) sp_18 - 8)).u0 = 19585;
			Eq_5 si_1420;
			Eq_5 di_1416;
			Eq_5 ds_1417;
			fn1E56_03F5(si_1400, di_1396, ds_1397, ss->*((word32) sp_18 - 8), out si_1420, out di_1416, out ds_1417);
			ss->*((word32) sp_18 - 6) = ax_1357 *s16 (int16) (ds_1417->*((word16) ax_1324 + 20285));
			Eq_5 si_1444 = fn1F3D_0053(si_1420, di_1416, ds_1417, ss->*((word32) sp_18 - 6), out di_1440, out ds_1441);
			ss->*((word32) sp_18 - 6) = ds_1441;
			(ss->*((word32) sp_18 - 8)).u0 = 0x4CAE;
			Eq_5 si_1465;
			Eq_5 di_1461;
			Eq_5 ds_1462;
			fn1E56_03F5(si_1444, di_1440, ds_1441, ss->*((word32) sp_18 - 8), out si_1465, out di_1461, out ds_1462);
			(ss->*((word32) sp_18 - 6)).u0 = 0x0A;
			// Failed to bind call argument.
			// Please report this issue at https://github.com/uxmal/reko
			Eq_5 stackArg4;
			stackArg4.u0 = <invalid>;
			word16 si_7889;
			word16 di_7890;
			selector ds_7891;
			fn1CD3_0004(si_1465, di_1461, ds_1462, stackArg4, out si_7889, out di_7890, out ds_7891);
			Eq_5 sp_1477;
			sp_1477.u0 = <invalid>;
			(ss->*sp_1477.u7).t0000.u1 = (word16) ds_1462;
			(ss->*((word32) sp_1477 - 2)).u0 = 19667;
			Eq_5 si_1498;
			Eq_5 di_1494;
			Eq_5 ds_1495;
			fn1E56_03F5(si_1465, di_1461, ds_1462, ss->*((word32) sp_1477 - 2), out si_1498, out di_1494, out ds_1495);
			(ss->*sp_1477.u7).t0000.u1 = 0x01;
			struct Eq_82890 Eq_62226::* sp_1522 = (struct Eq_82890 Eq_62226::*) &sp_1477.u7->w0002;
			word16 si_1516;
			word16 di_1512;
			selector ds_1513;
			if (fn0800_1A13(si_1498, di_1494, ds_1495, (ss->*sp_1477.u7).t0000.u1, out si_1516, out di_1512, out ds_1513) != 0x00)
			{
				struct Eq_83004 Eq_62226::* bp_1530;
				Eq_5 ds_1535;
				Eq_5 si_1576;
				Eq_5 di_1578;
				while ((ss->*bp_1530).wFFFFFFF4 != 0x00)
				{
					struct Eq_83034 Eq_5::* bx_1534 = (ss->*bp_1530).ptrFFFFFFF6;
					Eq_5 ax_1537;
					ax_1537.u2 = (int16) (ds_1535->*bx_1534).b4F3E;
					struct Eq_80552 * es_1539 = Mem1531[ds_1535:22174:selector];
					if (es_1539->tD372 < 0x00 || es_1539->tD372 <= 0x00 && ax_1537 > es_1539->tD370)
						break;
					(ss->*bp_1530).wFFFFFFD4 = 0x01;
					--(ss->*bp_1530).wFFFFFFF4;
					es_1539->tD370 -= (uint32) (ds_1535->*bx_1534).b4F3E;
					(&es_1539->bC620)[2][(ss->*bp_1530).wFFFFFFD6].b0000 = (&es_1539->bC620)[2][(ss->*bp_1530).wFFFFFFD6].b0000 + 0x01;
					Eq_36 bp_1582 = fn1631_1FDF(si_1576, di_1578, ds_1535, out si_1589, out di_1585, out ds_1586);
					Eq_5 sp_1590;
					sp_1590.u0 = <invalid>;
				}
				if ((ss->*bp_1530).wFFFFFFF4 != 0x00)
				{
					struct Eq_83062 Eq_62226::* sp_1606 = sp_1605 - 2;
					(ss->*sp_1606).t0000.u0 = (wchar_t) ds_1535;
					(ss->*sp_1606).tFFFFFFFE.u0 = 0x4CEE;
					word16 si_1621;
					word16 di_1617;
					selector ds_1618;
					fn1E56_03F5(si_1576, di_1578, ds_1535, (ss->*sp_1606).tFFFFFFFE.u5, out si_1621, out di_1617, out ds_1618);
					struct Eq_83088 Eq_62226::* sp_1627 = (struct Eq_83088 Eq_62226::*) ((char *) &sp_1606->t0000 + 2);
					if ((ss->*bp_1530).wFFFFFFD4 != 0x00)
					{
						word16 ax_1631 = 0x4D14;
					}
					else
					{
						word16 ax_1630 = 19791;
					}
				}
				else
				{
					word16 ax_1602 = 19815;
				}
l1CD3_0F2A:
				struct Eq_83102 Eq_62226::* sp_1634 = sp_1633 - 2;
				Eq_5 ds_1635;
				(ss->*sp_1634).t0000.u0 = (wchar_t) ds_1635;
				Eq_5 ax_1639;
				(ss->*sp_1634).tFFFFFFFE.u0 = (wchar_t) ax_1639;
				Eq_5 si_1641;
				Eq_5 di_1642;
				Eq_5 si_1651;
				Eq_5 di_1647;
				Eq_5 ds_1648;
				fn1E56_03F5(si_1641, di_1642, ds_1635, (ss->*sp_1634).tFFFFFFFE.u5, out si_1651, out di_1647, out ds_1648);
				word16 si_7892;
				word16 di_7893;
				selector ds_1663;
				fn1F3D_0259(si_1651, di_1647, ds_1648, out si_7892, out di_7893, out ds_1663);
				struct Eq_83137 Eq_62226::* sp_1657 = (struct Eq_83137 Eq_62226::*) ((char *) &sp_1634->t0000 + 2);
			}
			break;
		case 33:
			struct Eq_81055 * ds_1306 = fn0FDC_1C9B(si_22, di_19, ds_20);
			break;
		case 0x22:
			struct Eq_81059 * ds_1293 = fn0FDC_1A26(si_22, di_19, ds_20);
			break;
		case 0x23:
			Mem31[ds_20:22172:selector]->bD55E = 0x00;
			if (Mem794[ds_20:22174:selector]->bC79F != 0x00)
				Mem794[ds_20:22172:selector]->bD55E = 0x92;
			selector es_802 = Mem801[ds_20:22174:selector];
			es_802->bC620 = 0x00;
			es_802->bC79D = 0x00;
			(ss->*((word32) sp_18 - 6)).u0 = 0x00;
			(ss->*((word32) sp_18 - 8)).u0 = 0x00;
			Eq_36 bp_817 = fn0800_48B7(si_22, di_19, ds_20, ss->*((word32) sp_18 - 8), out si_824, out di_820, out ds_821);
			Mem812[ds_821:22182:selector]->tA44B.u0 = 0x0A2B;
			Mem834[ds_821:22178:selector]->tA44D.u0 = 0x8057;
			selector es_837 = Mem836[ds_821:22180:selector];
			es_837->w01F6 = 0x02A0;
			es_837->t01F8.u0 = 12264;
			Eq_5 sp_825;
			sp_825.u0 = <invalid>;
			(ss->*sp_825.u7).w0002 = 0x00;
			Eq_5 ds_848;
			Eq_5 si_851;
			Eq_5 di_847;
			Mem843[ds_848:22184:selector]->b409A = (byte) fn0800_1732(si_824, di_820, ds_821, (ss->*sp_825.u7).w0002, out si_851, out di_847, out ds_848);
			Eq_5 si_869 = fn11B8_137F(si_851, di_847, ds_848, out di_865, out ds_866);
			(ss->*sp_825.u7).w0002 = 0x08;
			// Failed to bind call argument.
			// Please report this issue at https://github.com/uxmal/reko
			Eq_5 stackArg4;
			stackArg4.u0 = <invalid>;
			fn0FDC_0629(si_869, di_865, ds_866, stackArg4);
			ss->*((word16) bp_817 - 24) = 0x00;
			Eq_5 sp_879;
			sp_879.u0 = <invalid>;
			word16 sp_886 = (word16) &sp_879.u7->w0002;
			do
			{
				Eq_82600 bx_892 = ss->*((word16) bp_817 - 24);
				selector es_894 = Mem891[ds_866:22174:selector];
				if ((es_894->*((word16) bx_892 + 54359) & 0x7E) == 0x7C && es_894->*((word16) bx_892 + 54423) == 0x8A)
				{
					es_894->*((word16) bx_892 + 0x0000D4D7) = 0x00;
					es_894->*((word16) (ss->*((word16) bp_817 - 24)) + 54423) = 0x00;
					es_894->*((word16) (ss->*((word16) bp_817 - 24)) + 54359) = 0x00;
				}
				ss->*((word16) bp_817 - 24) = (word16) (ss->*((word16) bp_817 - 24)) + 1;
			} while (ss->*((word16) bp_817 - 24) < 0x40);
			if (Mem912[ds_866:22202:selector]->w014A == 0x00)
				Mem912[ds_866:22174:selector]->bD334 = 0x01;
			if (Mem922[ds_866:22174:selector]->bD32F == 0x00)
			{
				struct Eq_82980 * ds_1271 = fn0FDC_1B41(fn11B8_1441(si_869, di_865, ds_866, out di_1257, out ds_1258), di_1257, ds_1258);
				Mem922[ds_1271:22182:selector]->wA44B = 0x0A39;
				Mem1281[ds_1271:22178:selector]->wA44D = 0x805D;
			}
			else
			{
				Mem922[ds_866:22182:selector]->tA44B.u0 = 0x0970;
				Mem927[ds_866:22178:selector]->tA44D = Mem927[ds_866:22204:selector]->t4036;
				if (Mem931[ds_866:22206:selector]->w406A == 0x00)
					Mem931[ds_866:22178:selector]->tA44D = Mem931[ds_866:22204:selector]->t403E;
				ss->*((word16) bp_817 - 30) = 0x01;
				do
				{
					Eq_83011 bx_947 = ss->*((word16) bp_817 - 30);
					Mem946[ds_866:22174:selector]:50708[bx_947 * 0x11] = Mem946[Mem946[ds_866:22208:selector]:bx_947 + 16361:byte];
					ss->*((word16) bp_817 - 30) = (word16) (ss->*((word16) bp_817 - 30)) + 1;
				} while (ss->*((word16) bp_817 - 30) < 0x08);
				ss->*((word16) bp_817 - 40) = 0x01;
				ss->*((word16) bp_817 - 30) = 0x00;
				do
				{
					if (Mem969[ds_866:22174:selector]->*((word16) (ss->*((word16) bp_817 - 30)) + 54354) != ~0x00)
						ss->*((word16) bp_817 - 40) = 0x00;
					ss->*((word16) bp_817 - 30) = (word16) (ss->*((word16) bp_817 - 30)) + 1;
				} while (ss->*((word16) bp_817 - 30) < 0x04);
				ss->*((word16) bp_817 - 30) = 0x01;
				do
				{
					if (ss->*((word16) bp_817 - 40) == 0x00)
					{
						struct Eq_80552 * es_991 = Mem986[ds_866:22174:selector];
						if (es_991->*((word16) (ss->*((word16) bp_817 - 30)) + 54354) == ~0x00)
						{
							ss->*((word16) bp_817 - 40) = 0x01;
							ss->*((word16) bp_817 - 24) = 0x01;
							do
							{
								Eq_82600 bx_999 = ss->*((word16) bp_817 - 24);
								es_991->bC724[bx_999].b0000 = (byte) (es_991->*((word16) bx_999 + 54354));
								ss->*((word16) bp_817 - 24) = (word16) (ss->*((word16) bp_817 - 24)) + 1;
							} while (ss->*((word16) bp_817 - 24) < 0x04);
							ss->*((word16) bp_817 - 36) = 0x00;
							struct Eq_80552 * es_1031;
							do
							{
								es_1031 = Mem1018[ds_866:22174:selector];
								es_1031->*((word16) (ss->*((word16) bp_817 - 30) *s 0x7D + ss->*((word16) bp_817 - 36)) + 50980) = (word16) (Mem1018[ds_866:22210:selector]->*((word16) (ss->*((word16) bp_817 - 36)) + 0x00003780));
								ss->*((word16) bp_817 - 36) = (word16) (ss->*((word16) bp_817 - 36)) + 1;
							} while (ss->*((word16) bp_817 - 36) < 0x7D);
							es_1031->bC724[ss->*((word16) bp_817 - 30)].b0000 = es_1031->bD452;
						}
					}
					ss->*((word16) bp_817 - 30) = (word16) (ss->*((word16) bp_817 - 30)) + 1;
				} while (ss->*((word16) bp_817 - 30) < 0x04);
				if (ss->*((word16) bp_817 - 40) == 0x00)
				{
					ss->*((word16) bp_817 - 30) = 0x00;
					struct Eq_80552 * es_1067;
					do
					{
						Eq_83011 bx_1063 = ss->*((word16) bp_817 - 30);
						es_1067 = Mem1062[ds_866:22174:selector];
						es_1067->*((word16) bx_1063 + 50980) = Mem1062[ds_866:22210:selector]->*((word16) bx_1063 + 0x00003780);
						ss->*((word16) bp_817 - 30) = (word16) (ss->*((word16) bp_817 - 30)) + 1;
					} while (ss->*((word16) bp_817 - 30) < 0x7D);
					ss->*((word16) bp_817 - 30) = 0x00;
					do
					{
						Eq_83011 bx_1077 = ss->*((word16) bp_817 - 30);
						es_1067->bC724[bx_1077].b0000 = (byte) (es_1067->*((word16) bx_1077 + 54354));
						ss->*((word16) bp_817 - 30) = (word16) (ss->*((word16) bp_817 - 30)) + 1;
					} while (ss->*((word16) bp_817 - 30) < 0x04);
				}
				(ss->*sp_879.u7).t0000.u1 = 0x89;
				fn207F_104E((ss->*sp_879.u7).t0000.u1);
				ss->*((word16) bp_817 - 0x0E) = 0x78;
				ss->*((word16) bp_817 - 26) = 0x00;
				union Eq_5 Eq_62226::* sp_1113 = (union Eq_5 Eq_62226::*) &sp_879.u7->w0002;
				struct Eq_83739 Eq_62226::* bp_1168;
				do
				{
					struct Eq_83851 Eq_62226::* bp_1119;
					(ss->*bp_1119).wFFFFFFEA = 0x00;
					do
					{
						int8 al_1128 = (int8) ((char *) (ss->*bp_1122).ptrFFFFFFF2 + (ss->*bp_1122).wFFFFFFEA)[48];
						(ss->*bp_1122).bFFFFFFCC = al_1128;
						if (al_1128 != 0x00)
						{
							struct Eq_83758 Eq_62226::* sp_1137 = sp_1136 - 2;
							(ss->*sp_1137).t0000.u0 = (wchar_t) (int16) al_1128;
							(ss->*sp_1137).wFFFFFFFE = (ss->*bp_1122).wFFFFFFE6 *s 0x03 + (ss->*bp_1122).wFFFFFFEA;
							Eq_5 sp_1158;
							sp_1158.u0 = <invalid>;
							Eq_36 bp_1150 = fn0800_2DA8(si_1146, di_1147, ds_1126, (ss->*sp_1137).t0000.u0, out si_1157, out di_1153, out ds_1154);
							word16 sp_1165 = (word16) ((word32) sp_1158 + 4);
						}
						++(ss->*bp_1168).wFFFFFFEA;
					} while ((ss->*bp_1168).wFFFFFFEA < 0x03);
					(ss->*bp_1168).wFFFFFFF2 += 0x10;
					++(ss->*bp_1168).wFFFFFFE6;
				} while ((ss->*bp_1168).wFFFFFFE6 < 0x03);
				fn207F_1DA8();
				union Eq_5 Eq_62226::* sp_1191 = sp_1190 - 2;
				(ss->*sp_1191).u0 = 0x00;
				Eq_5 si_1194;
				Eq_5 di_1195;
				Eq_5 ds_1193;
				word16 di_7904;
				struct Eq_83877 * ds_1201;
				fn1543_0C72(si_1194, di_1195, ds_1193, (ss->*sp_1191).u0, out di_7904, out ds_1201);
				(ss->*bp_1168).tFFFFFFE2.u0 = 0x00;
				union Eq_5 Eq_62226::* sp_1210 = (union Eq_5 Eq_62226::*) ((char *) sp_1191 + 2);
				struct Eq_83890 * es_1223;
				do
				{
					es_1223 = ds_1201->ptr569E;
					es_1223->*((word16) ((ss->*bp_1168).tFFFFFFE2).u0 + 54354) = (int16) ~0x00;
					es_1223->aC79D[0].b0001[(ss->*bp_1168).tFFFFFFE2.u0] = (Eq_108719) ~0x00;
					es_1223->aC79D[0].b0000[(ss->*bp_1168).tFFFFFFE2.u0].b0000 = ~0x00;
					(ss->*bp_1168).tFFFFFFE2.u0 = (int16) ((ss->*bp_1168).tFFFFFFE2.u0 + 0x01);
				} while ((ss->*bp_1168).tFFFFFFE2.u0 < 0x04);
				(ss->*bp_1168).tFFFFFFE2.u0 = 0x00;
				do
				{
					es_1223->aC620[0].b0000[(ss->*bp_1168).tFFFFFFE2.u0].b0000 = 0x08;
					(ss->*bp_1168).tFFFFFFE2.u0 = (int16) ((ss->*bp_1168).tFFFFFFE2.u0 + 0x01);
				} while ((ss->*bp_1168).tFFFFFFE2.u0 < 0x08);
			}
			selector ds_1284;
			Mem1286[ds_1284:22214:selector]->wE48E = 0x00;
			break;
		case 0x24:
			struct Eq_80552 * es_770 = Mem31[ds_20:22174:selector];
			byte al_775 = es_770->bC614[es_770->bD331].b0000;
			goto l1CD3_13CE;
		case 0x25:
			Mem31[ds_20:22202:selector]->w014A = 0x00;
			Mem767[ds_20:22174:selector]->bC614 = ~0x00;
			break;
		case 0x26:
			byte al_765 = Mem31[ds_20:22174:selector]->bD456;
l1CD3_13CE:
			int16 ax_777 = (int16) al_776;
			struct Eq_82477 * es_784 = Mem31[ds_20:22200:selector];
			(ss->*((word32) sp_18 - 6)).u0 = es_784->a01CC[0].u5[ax_777].u0;
			(ss->*((word32) sp_18 - 8)).u0 = es_784->a01CA[0].u5[ax_777].u0;
			struct Eq_82498 Eq_62226::* sp_791 = sp_18 - 8;
l1CD3_01B7:
			Eq_5 si_4351;
			Eq_5 di_4355;
			Eq_5 ds_4350;
			union Eq_5 Eq_62226::* sp_4363;
			word16 si_7885;
			word16 di_7886;
			selector ds_4369;
			fn1E56_03F5(si_4351, di_4355, ds_4350, (ss->*sp_4363).u5, out si_7885, out di_7886, out ds_4369);
l1CD3_01BC:
			word16 sp_4379 = sp_4378 + 0x04;
			break;
		case 0x27:
			word16 ax_763 = 0x01;
			goto l1CD3_0E92;
		case 0x28:
			fn11B8_152F(si_22, di_19, ds_20);
			struct Eq_81115 Eq_62226::* sp_751 = sp_18 - 4;
			if (Mem31[ds_20:22202:selector]->w014A == 0x00)
				Mem31[ds_20:22174:selector]->bD334 = 0x01;
			break;
		case 0x29:
			if (Mem31[ds_20:22174:selector]->bD31A != 0x00)
			{
				word16 wLoc1A_4826 = 0x00;
				while (true)
				{
					struct Eq_82375 Eq_62226::* sp_723 = sp_18 - 4;
					Eq_5 ds_641;
					int16 wLoc1A_4827;
					if ((int16) Mem642[ds_641:22174:selector]->bD31A < wLoc1A_4827)
						break;
					word16 wLoc20_4834 = 0x0D;
					if (wLoc1A_4827 != 0x00)
					{
						word16 wLoc20_4835 = 0x0D - (fn207F_0BC0() & 0x01);
					}
					Eq_5 wLoc20_4836;
					ss->*((word32) sp_18 - 6) = wLoc20_4836;
					Eq_5 si_740 = fn0FDC_15E6(si_728, di_730, ds_641, ss->*((word32) sp_18 - 6), out di_736, out ds_737);
					ci16 wLoc1A_4838 = wLoc1A_4827 + 0x01;
				}
			}
			else
			{
				Eq_5 si_544 = fn1E56_0388(fp - 2, si_22, di_19, ds_20, out di_540, out ds_541);
				Eq_5 sp_545;
				sp_545.u0 = <invalid>;
				ss->*((word32) sp_545 - 2) = ds_541;
				(ss->*((word32) sp_545 - 4)).u0 = 0x4D8A;
				Eq_5 si_563;
				Eq_5 di_559;
				Eq_5 ds_560;
				fn1E56_03F5(si_544, di_540, ds_541, ss->*((word32) sp_545 - 4), out si_563, out di_559, out ds_560);
				int16 ax_572 = Mem555[ds_560:22174:selector]->bC61F *s16 0x11;
				(ss->*((word32) sp_545 - 2)).u0 = 16091;
				ss->*((word32) sp_545 - 4) = ax_572 + 11992;
				Eq_5 si_588;
				Eq_5 di_584;
				Eq_5 ds_585;
				fn1E56_03F5(si_563, di_559, ds_560, ss->*((word32) sp_545 - 4), out si_588, out di_584, out ds_585);
				ss->*((word32) sp_545 - 2) = ds_585;
				(ss->*((word32) sp_545 - 4)).u0 = 0x4DA4;
				Eq_5 si_608;
				Eq_5 di_604;
				Eq_5 ds_605;
				fn1E56_03F5(si_588, di_584, ds_585, ss->*((word32) sp_545 - 4), out si_608, out di_604, out ds_605);
				(ss->*((word32) sp_545 - 2)).u0 = 0x01;
				Eq_5 sp_632 = sp_545;
				word16 si_7882;
				word16 di_7883;
				struct Eq_82368 * ds_623;
				if (fn0800_1A13(si_608, di_604, ds_605, ss->*((word32) sp_545 - 2), out si_7882, out di_7883, out ds_623) != 0x00)
					Mem618[ds_623:22174:selector]->bC61F = 0x0D;
			}
			word16 wLoc1A_4828 = 0x00;
			int16 wLoc1A_4829;
			while (wLoc1A_4829 < 0x08)
			{
				selector ds_4706;
				if (ds_4706->ptr569E->aC614[0].b0000[wLoc1A_4829].b0000 != ~0x00)
				{
					int16 cx_673 = (fn207F_0BC0() & 0x01) + 0x06;
					struct Eq_82619 * es_674 = ds_4706->ptr569E;
					int16 ax_678 = cx_673 *s (int16) (((es_674->aC614))[0].b0001)[wLoc1A_4829];
					byte bLoc20_4831 = (byte) ax_678;
					if ((int16) es_674->aC614[0].b000F[wLoc1A_4829] > ax_678)
						es_674->aC614[0].b000F[wLoc1A_4829].b0000 = bLoc20_4831;
				}
				int16 wLoc1A_4833 = wLoc1A_4829 + 0x01;
			}
			break;
		case 0x2A:
			word16 wLoc1A_4822 = 0x00;
			int16 v44_526;
			do
			{
				Eq_5 ax_512 = Mem504[ds_20:22182:selector]->tA44B;
				ui16 wLoc1A_4823;
				Mem504[ds_20:22216:selector]:0x4024[wLoc1A_4823 * 0x02] = ax_512;
				Mem514[ds_20:22174:selector]:0xD390[wLoc1A_4823 * 0x1A] = ax_512;
				Eq_5 ax_518 = Mem516[ds_20:22178:selector]->tA44D;
				Mem516[ds_20:22204:selector]:0x4056[wLoc1A_4823 * 0x02] = ax_518;
				struct Eq_80552 * es_521 = Mem520[ds_20:22174:selector];
				es_521->wD392[wLoc1A_4823].t0000.u0 = (wchar_t) ax_518;
				es_521->bD399[wLoc1A_4823].b0000 = (byte) wLoc1A_4823;
				es_521->bD398[wLoc1A_4823].b0000 = 0x77;
				v44_526 = wLoc1A_4823 + 0x01;
				int16 wLoc1A_4825 = v44_526;
			} while (v44_526 < 0x08);
			selector es_530 = Mem527[ds_20:22178:selector];
			es_530->tA44D.u5 = (word32) es_530->tA44D + 1;
			break;
		case 0x2B:
			word16 ax_479 = Mem31[ds_20:22218:selector]->w4572;
			Mem31[ds_20:22216:selector]->w4024 = ax_479;
			Mem481[ds_20:22174:selector]->wD390 = ax_479;
			word16 ax_485 = Mem483[ds_20:22220:selector]->w45A4;
			Mem483[ds_20:22204:selector]->w4056 = ax_485;
			selector es_488 = Mem487[ds_20:22174:selector];
			es_488->wD392 = ax_485;
			es_488->bD399 = ~0x00;
			es_488->bD398 = 0x70;
			Mem491[ds_20:22174:selector]->wD394 = Mem491[ds_20:22218:selector]->w4564;
			Mem495[ds_20:22174:selector]->wD396 = Mem495[ds_20:22220:selector]->w4596;
			break;
		case 44:
			word16 bp_464 = fn11B8_1762(si_22, di_19, ds_20, out ds_468);
			Eq_5 sp_472;
			sp_472.u0 = <invalid>;
			break;
		case 0x2D:
			(ss->*((word32) sp_18 - 6)).u0 = 12264;
			(ss->*((word32) sp_18 - 8)).u0 = 0x01F0;
			fn207F_00D1(ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6));
			if (Mem74[ds_20:22188:selector]->w4FBA == 0x00)
			{
				(ss->*((word32) sp_18 - 6)).u0 = 0x01;
				fn207F_0BA7(ss->*((word32) sp_18 + 6));
			}
			Mem95[ds_20:22222:selector]->w4FBC = 0x00;
			(ss->*((word32) sp_18 - 6)).u0 = 0x02;
			Eq_5 si_113 = fn0800_28CC(si_22, di_19, ds_20, ss->*((word32) sp_18 - 6), out di_109, out ds_110);
			(ss->*((word32) sp_18 - 6)).u0 = 0x3092;
			(ss->*((word32) sp_18 - 8)).u0 = 0x4614;
			ss->*((word32) sp_18 - 0x0A) = ds_110;
			(ss->*((word32) sp_18 - 0x0C)).u0 = 19903;
			Eq_5 si_140;
			Eq_5 di_136;
			Eq_5 ds_137;
			fn1F3D_063B(si_113, di_109, ds_110, out si_140, out di_136, out ds_137);
			Eq_5 sp_141;
			sp_141.u0 = <invalid>;
			(ss->*sp_141.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x246C;
			(ss->*((word32) sp_141 + 4)).u0 = 0x244B;
			(ss->*sp_141.u7).w0002 = 0x3092;
			(ss->*sp_141.u7).t0000.u1 = 0x4614;
			Eq_5 si_168 = fn1F3D_049D(si_140, di_136, ds_137, ss->*sp_141, ss->*((word32) sp_141 + 4), (ss->*sp_141.u7).ptr0006, out di_164, out ds_165);
			if (Mem160[ds_165:22188:selector]->w4FBA == 0x02)
			{
				(ss->*sp_141.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0xA800;
				(ss->*((word32) sp_141 + 4)).u0 = 0x246C;
				(ss->*sp_141.u7).w0002 = 0x244B;
				fn207F_0260((ss->*sp_141.u7).w0002, ss->*((word32) sp_141 + 4), (ss->*sp_141.u7).ptr0006);
			}
			if (Mem198[ds_165:22188:selector]->w4FBA != 0x03)
			{
				word16 ax_204 = 0x00;
			}
			else
			{
				word16 ax_202 = 0x10;
			}
			(ss->*sp_141.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x3058;
			Eq_5 ax_214;
			ss->*((word32) sp_141 + 4) = ax_214;
			Eq_5 si_230 = fn1F3D_0525(si_168, di_164, ds_165, ss->*((word32) sp_141 + 4), out di_226, out ds_227);
			(ss->*sp_141.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 200;
			(ss->*((word32) sp_141 + 4)).u0 = 0x28;
			(ss->*sp_141.u7).w0002 = 0x00;
			(ss->*sp_141.u7).t0000.u1 = 0x00;
			(ss->*((word32) sp_141 - 2)).u0 = 0x246C;
			(ss->*((word32) sp_141 - 4)).u0 = 0x244B;
			Eq_5 si_262 = fn1F3D_0086(si_230, di_226, ds_227, ss->*((word32) sp_141 - 4), ss->*((word32) sp_141 - 2), (ss->*sp_141.u7).t0000.u1, (ss->*sp_141.u7).w0002, ss->*((word32) sp_141 + 4), (ss->*sp_141.u7).ptr0006, out di_258, out ds_259);
			Mem254[ds_259:22222:selector]->w4FBC = 0x01;
			(ss->*sp_141.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 12264;
			(ss->*((word32) sp_141 + 4)).u0 = 0x01B0;
			fn207F_00D1(ss->*((word32) sp_141 + 4), (ss->*sp_141.u7).ptr0006);
			(ss->*sp_141.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x246C;
			(ss->*((word32) sp_141 + 4)).u0 = 0x244B;
			(ss->*sp_141.u7).w0002 = (word16) ds_259;
			(ss->*sp_141.u7).t0000.u1 = 19915;
			Eq_36 bp_300 = fn1F3D_063B(si_262, di_258, ds_259, out si_307, out di_303, out ds_304);
			Eq_5 sp_308;
			sp_308.u0 = <invalid>;
			(ss->*sp_308.u7).ptr0006 = (struct Eq_104903 Eq_5::*) 0x3092;
			(ss->*((word32) sp_308 + 4)).u0 = 0x4614;
			(ss->*sp_308.u7).w0002 = 0x246C;
			(ss->*sp_308.u7).t0000.u1 = 0x244B;
			Eq_5 di_331;
			Eq_5 ds_332;
			Eq_5 di_346;
			Eq_5 ds_347;
			Eq_5 si_364;
			Eq_5 di_360;
			Eq_5 ds_361;
			fn1F3D_0259(fn1F3D_086A(bp_300, fn1F3D_049D(si_307, di_303, ds_304, ss->*sp_308, ss->*((word32) sp_308 + 4), (ss->*sp_308.u7).ptr0006, out di_331, out ds_332), di_331, ds_332, out di_346, out ds_347), di_346, ds_347, out si_364, out di_360, out ds_361);
			fn207F_1FBE();
			Eq_5 sp_351;
			sp_351.u0 = <invalid>;
			if (Mem327[ds_361:22188:selector]->w4FBA == 0x00)
			{
				(ss->*((word32) sp_351 - 2)).u0 = 0x00;
				fn207F_0BA7(ss->*((word32) sp_351 + 2));
			}
			if (Mem388[ds_361:22188:selector]->w4FBA != 0x03)
			{
				word16 ax_394 = 0x00;
			}
			else
			{
				word16 ax_392 = 0x10;
			}
			(ss->*((word32) sp_351 - 2)).u0 = 12264;
			Eq_5 ax_404;
			ss->*((word32) sp_351 - 4) = ax_404;
			Eq_5 si_420 = fn1F3D_0525(si_364, di_360, ds_361, ss->*((word32) sp_351 - 4), out di_416, out ds_417);
			(ss->*((word32) sp_351 - 2)).u0 = 0x01;
			Eq_36 bp_432 = fn0800_4CAC(si_420, di_416, ds_417, ss->*((word32) sp_351 - 2), out si_439, out di_435, out ds_436);
			word16 di_7881;
			selector ds_453;
			fn1E56_0388(bp_432, si_439, di_435, ds_436, out di_7881, out ds_453);
			Eq_5 sp_457;
			sp_457.u0 = <invalid>;
			break;
		case 0x2E:
			word16 wLoc1A_4819 = 0x00;
			Eq_81445 v24_65;
			do
			{
				struct Eq_80552 * es_54 = Mem51[ds_20:22174:selector];
				Eq_81434 wLoc1A_4820;
				es_54->bC724[wLoc1A_4820].b0000 = (byte) (es_54->*((word16) wLoc1A_4820 + 54354));
				v24_65 = (word16) wLoc1A_4820 + 1;
				Eq_81445 wLoc1A_4821 = v24_65;
			} while (v24_65 < 0x04);
l1CD3_0E54:
			word16 wLoc1A_4853 = 0x00;
			ci16 v33_1764;
			do
			{
				Eq_81450 wLoc1A_4854;
				Mem1746[ds_20:22172:selector]->*((word16) wLoc1A_4854 + 0x0000D55E) = 0x00;
				if (Mem1750[ds_20:22174:selector]:50980[wLoc1A_4854 * 0x7D] != 0x4C)
					Mem1750[ds_20:22172:selector]->*((word16) wLoc1A_4854 + 0x0000D55E) = 0x92;
				v33_1764 = (word16) wLoc1A_4854 + 1;
				ci16 wLoc1A_4856 = v33_1764;
			} while (v33_1764 < 0x04);
			word16 ax_1768 = 0x00;
l1CD3_0E92:
			Eq_5 ax_1776;
			ss->*((word32) sp_18 - 6) = ax_1776;
			word16 di_7884;
			selector ds_1800;
			fn1467_0002(si_22, di_19, ds_20, ss->*((word32) sp_18 - 6), out di_7884, out ds_1800);
			struct Eq_82410 Eq_62226::* sp_1775 = sp_18 - 6;
l1CD3_0181:
			word16 sp_4511 = sp_4510 + 0x02;
			break;
		case 0x2F:
			selector es_42 = Mem31[ds_20:22174:selector];
			if (es_42->bC623 > 0x05)
				es_42->bC623 -= 0x04;
			break;
		}
	}
	word16 di_4686 = (ss->*sp_4652).w0002;
	word16 bp_4702 = ss->*bp_4687;
	siOut = (ss->*sp_4652).w0000;
	diOut = di_4686;
	struct Eq_13594 * ds_5137;
	dsOut = ds_5137;
	return bp_4702;
}

// 1CD3:17C6: Register Eq_5 fn1CD3_17C6(Register Eq_36 bp, Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Register out word16 diOut, Register out (ptr16 Eq_1182) dsOut)
// Called from:
//      fn0800_0000
//      fn0800_1C12
//      fn0800_35D3
//      fn0800_4D57
//      fn0FDC_0629
//      fn135D_01E9
//      fn135D_02A8
//      fn135D_02D2
//      fn135D_03AA
//      fn135D_04AB
//      fn135D_055A
//      fn135D_079C
//      fn135D_0980
//      fn135D_0AB6
//      fn1431_000A
//      fn1467_0002
//      fn183B_000A
//      fn1AE8_12C7
Eq_5 fn1CD3_17C6(Eq_36 bp, Eq_5 si, Eq_5 di, Eq_5 ds, word16 & diOut, struct Eq_1182 & dsOut)
{
	struct Eq_1182 * ds_69;
	word16 di_68;
	Eq_5 ds_51;
	Eq_5 di_50;
	Eq_5 ds_36;
	Eq_5 di_35;
	word16 wLoc04;
	cup16 wLoc02;
	Eq_5 si_23;
	Eq_5 di_20;
	Eq_5 ds_21;
	fn207F_2FDC(0x00, bp, si, di, ds, wLoc04, wLoc02, out si_23, out di_20, out ds_21);
	Eq_5 sp_19;
	sp_19.u0 = <invalid>;
	selector ss;
	(ss->*((word32) sp_19 - 2)).u0 = 0x07;
	Eq_5 si_54 = fn1E56_0388(bp, fn1E56_0281(si_23, di_20, ds_21, ss->*((word32) sp_19 - 2), out di_35, out ds_36), di_35, ds_36, out di_50, out ds_51);
	Eq_5 sp_55;
	sp_55.u0 = <invalid>;
	(ss->*((word32) sp_55 - 2)).u0 = 0x00;
	Eq_5 si_72 = fn1E56_0004(si_54, di_50, ds_51, ss->*((word32) sp_55 - 2), out di_68, out ds_69);
	diOut = di_68;
	dsOut = ds_69;
	return si_72;
}

// 1CD3:17EA: Register Eq_5 fn1CD3_17EA(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Stack Eq_5 wArg06, Register out word16 diOut, Register out (ptr16 Eq_1307) dsOut)
// Called from:
//      fn0800_0000
//      fn0800_1C12
//      fn0800_35D3
//      fn0800_4D57
//      fn0FDC_0008
//      fn0FDC_0629
//      fn11B8_1762
//      fn135D_01E9
//      fn135D_02A8
//      fn135D_02D2
//      fn135D_03AA
//      fn135D_04AB
//      fn135D_055A
//      fn135D_079C
//      fn135D_0980
//      fn1431_000A
//      fn1467_0002
//      fn1467_08A8
//      fn183B_000A
//      fn1AE8_12C7
Eq_5 fn1CD3_17EA(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, Eq_5 wArg06, word16 & diOut, struct Eq_1307 & dsOut)
{
	struct Eq_1307 * ds_56;
	word16 di_55;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_25;
	Eq_5 di_22;
	Eq_5 ds_23;
	fn207F_2FDC(0x00, fp - 2, si, di, ds, wLoc06, wLoc04, out si_25, out di_22, out ds_23);
	Eq_5 sp_21;
	sp_21.u0 = <invalid>;
	selector ss;
	ss->*((word32) sp_21 - 2) = wArg06;
	ss->*((word32) sp_21 - 4) = wArg04;
	Eq_5 si_44;
	Eq_5 di_40;
	Eq_5 ds_41;
	fn1E56_03F5(si_25, di_22, ds_23, ss->*((word32) sp_21 - 4), out si_44, out di_40, out ds_41);
	Eq_5 si_59 = fn1F3D_086A(fp - 2, si_44, di_40, ds_41, out di_55, out ds_56);
	diOut = di_55;
	dsOut = ds_56;
	return si_59;
}

// 1CD3:1809: Register Eq_5 fn1CD3_1809(Register Eq_36 bp, Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Register out word16 diOut, Register out (ptr16 Eq_39848) dsOut)
// Called from:
//      fn11B8_0002
//      fn11B8_0925
//      fn1CD3_0004
Eq_5 fn1CD3_1809(Eq_36 bp, Eq_5 si, Eq_5 di, Eq_5 ds, word16 & diOut, struct Eq_39848 & dsOut)
{
	word16 wLoc04;
	cup16 wLoc02;
	Eq_5 si_23;
	Eq_5 di_20;
	Eq_5 ds_21;
	fn207F_2FDC(0x00, bp, si, di, ds, wLoc04, wLoc02, out si_23, out di_20, out ds_21);
	Eq_5 sp_19;
	sp_19.u0 = <invalid>;
	selector ss;
	ss->*((word32) sp_19 - 2) = ds_21;
	(ss->*((word32) sp_19 - 4)).u0 = 20350;
	Eq_5 si_41;
	word16 di_37;
	struct Eq_39848 * ds_38;
	fn1E56_03F5(si_23, di_20, ds_21, ss->*((word32) sp_19 - 4), out si_41, out di_37, out ds_38);
	diOut = di_37;
	dsOut = ds_38;
	return si_41;
}

// 1CD3:181E: Register Eq_5 fn1CD3_181E(Register Eq_36 bp, Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Register out word16 diOut, Register out (ptr16 Eq_37769) dsOut)
// Called from:
//      fn0FDC_13DE
//      fn0FDC_15E6
//      fn0FDC_17B9
//      fn11B8_0002
//      fn11B8_0925
//      fn1431_000A
//      fn1467_0002
//      fn1467_0B98
//      fn1CD3_0004
Eq_5 fn1CD3_181E(Eq_36 bp, Eq_5 si, Eq_5 di, Eq_5 ds, word16 & diOut, struct Eq_37769 & dsOut)
{
	word16 wLoc04;
	cup16 wLoc02;
	Eq_5 si_23;
	Eq_5 di_20;
	Eq_5 ds_21;
	fn207F_2FDC(0x00, bp, si, di, ds, wLoc04, wLoc02, out si_23, out di_20, out ds_21);
	Eq_5 sp_19;
	sp_19.u0 = <invalid>;
	selector ss;
	ss->*((word32) sp_19 - 2) = ds_21;
	(ss->*((word32) sp_19 - 4)).u0 = 0x4FA0;
	Eq_5 si_41;
	word16 di_37;
	struct Eq_37769 * ds_38;
	fn1E56_03F5(si_23, di_20, ds_21, ss->*((word32) sp_19 - 4), out si_41, out di_37, out ds_38);
	diOut = di_37;
	dsOut = ds_38;
	return si_41;
}

