// UNBTECH_1AE8.c
// Generated by decompiling UNBTECH.exe
// using Reko decompiler version 0.12.2.0.

#include "UNBTECH.h"

// 1AE8:000C: Register Eq_5 fn1AE8_000C(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Register out int16 diOut, Register out Eq_5 dsOut)
// Called from:
//      fn183B_000A
Eq_5 fn1AE8_000C(Eq_5 si, Eq_5 di, Eq_5 ds, int16 & diOut, union Eq_5 & dsOut)
{
	Eq_5 ds_3116;
	Eq_5 di_3115;
	Eq_5 ds_2750;
	Eq_5 di_2749;
	Eq_5 ds_1929;
	Eq_5 di_1928;
	word16 si_3727;
	Eq_5 ds_433;
	Eq_5 di_432;
	Eq_5 ds_374;
	Eq_5 di_373;
	Eq_5 ds_148;
	Eq_5 di_147;
	Eq_5 ds_127;
	Eq_5 di_126;
	<unknown> Eq_72746::* fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	Eq_5 di_174;
	Eq_5 ds_175;
	fn207F_2FDC(0x80, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_174, out ds_175);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	struct Eq_72746 * ss;
	ss->*((word32) sp_18 - 2) = di_174;
	ss->*((word32) sp_18 - 4) = si_22;
	Eq_36 bp_3153 = fp - 2;
	Eq_5 sp_30 = sp_18 - 4;
	Eq_5 wLoc04_3425;
	wLoc04_3425.u0 = 0x00;
	Eq_5 v14_49;
	Eq_5 si_3326;
	do
	{
		ss->*((fp - 122) + wLoc04_3425) = (word16) 0x00;
		(Mem44[ds_175:22062:selector]->*((word32) wLoc04_3425 + 0x0078)).u5 = 0x00;
		v14_49.u5 = (word32) wLoc04_3425 + 1;
		si_3326 = wLoc04_3425;
		wLoc04_3425 = v14_49;
	} while (v14_49 < 0x18);
	while (ss->*((word16) bp_3153 - 4) < 0x0C)
	{
		if (Mem56[ds_175:0x5630:selector]->w014A != 0x00)
		{
			ss->*((word16) bp_3153 - 0x0044) = 0x00;
			if (ss->*((word16) bp_3153 - 4) == 0x00)
				ss->*((word16) bp_3153 - 0x0044) = 0x01;
			ss->*((word16) bp_3153 - 2) = 0x00;
			do
			{
				Eq_5 si_73;
				si_73.u5 = ss->*((word16) bp_3153 - 2);
				if (Mem72[ds_175:22066:selector]:0x406A[si_73 *16 0x02] != 0x00)
				{
					Eq_5 bx_79;
					bx_79.u5 = ss->*((word16) bp_3153 - 2);
					int16 ax_82 = (int16) (Mem72[ds_175:22062:selector]->*((word32) bx_79 + 0x0078));
					ss->*((word16) bp_3153 - 32) = ax_82;
					di_174 = (ax_82 << 0x01) + bx_79 *s16 0x18;
					selector es_90 = Mem83[ds_175:22068:selector];
					ss->*((word16) bp_3153 - 0x0E) = (int16) (es_90->*((word32) di_174 + 0x000040B4));
					Eq_5 ax_95;
					ax_95.u2 = (int16) (es_90->*((word32) di_174 + 16565));
					ss->*((word16) bp_3153 - 20) = ax_95;
					if (ss->*((word16) bp_3153 - 0x0E) != 0x02 && (ax_95 != 0x02 && (ss->*((word16) bp_3153 - 0x0E) | ss->*((word16) bp_3153 - 20)) != 0x00))
					{
						ss->*((word16) bp_3153 - 36) = Mem96[ds_175:22058:selector]->tA44B;
						ss->*((word16) bp_3153 - 46) = Mem109[ds_175:22060:selector]->tA44D;
						struct Eq_73059 Eq_72746::* sp_116 = sp_30 - 2;
						Mem117[ss:sp_116 + 0x00:word16] = Mem112[ds_175:22070:selector]:0x4036[si_73 *16 0x02];
						Mem121[ss:sp_116 + -2:word16] = Mem117[ds_175:22072:selector]:0x4004[si_73 *16 0x02];
						Eq_5 si_130 = fn0800_186F(si_73 << 0x01, di_174, ds_175, (ss->*sp_116).tFFFFFFFE.u0, (ss->*sp_116).w0000, out di_126, out ds_127);
						(ss->*sp_116).w0000 = (word16) (ss->*((word16) bp_3153 - 20));
						(ss->*sp_116).tFFFFFFFE.u0 = (wchar_t) (ss->*((word16) bp_3153 - 0x0E));
						Eq_5 si_151 = fn0800_191B(si_130, di_126, ds_127, (ss->*sp_116).tFFFFFFFE.u0, (ss->*sp_116).w0000, out di_147, out ds_148);
						(ss->*sp_116).w0000 = 0x01;
						(ss->*sp_116).tFFFFFFFE.u0 = (wchar_t) (ss->*((word16) bp_3153 - 20));
						(ss->*sp_116).tFFFFFFFC.u0 = (wchar_t) (ss->*((word16) bp_3153 - 0x0E));
						(ss->*sp_116).tFFFFFFFA.u0 = (wchar_t) (ss->*((word16) bp_3153 - 2));
						if (fn1631_16AB(si_151, di_147, ds_148, (ss->*sp_116).tFFFFFFFA.u0, (ss->*sp_116).w0000, out di_174, out ds_175) == 0x00)
						{
							ss->*((word16) bp_3153 - 0x0044) = 0x01;
							Eq_5 bx_191;
							bx_191.u5 = ss->*((word16) bp_3153 - 2);
							selector es_192 = Mem190[ds_175:22062:selector];
							(es_192->*((word32) bx_191 + 0x0078)).u5 = (word32) (es_192->*((word32) bx_191 + 0x0078)) + 1;
							Eq_5 si_195;
							si_195.u5 = ss->*((word16) bp_3153 - 2);
							Mem194[ds_175:22072:selector]:0x4004[si_195 *16 0x02] = Mem194[Mem194[ds_175:22058:selector]:0xA44B:word16];
							Mem200[ds_175:22070:selector]:0x4036[si_195 *16 0x02] = Mem200[Mem200[ds_175:22060:selector]:0xA44D:word16];
							ss->*((word16) bp_3153 - 64) = (int16) (Mem204[ds_175:22074:selector]->*((word16) ((ss->*((word16) bp_3153 - 20) << 0x02) + ss->*((word16) bp_3153 - 0x0E)) + 11985));
							if (ss->*((word16) bp_3153 - 0x0E) != 0x00 || ss->*((word16) bp_3153 - 20) != 0x00)
							{
								Eq_5 si_220;
								si_220.u5 = ss->*((word16) bp_3153 - 2);
								ss->*((bp_3153 - 0x0078) + si_220) = (word16) (ss->*((bp_3153 - 0x0078) + si_220) + 0x01);
								Eq_5 bx_223;
								bx_223.u5 = ss->*((word16) bp_3153 - 2);
								if ((int16) (Mem222[ds_175:22076:selector]->*((word32) bx_223 + 14700)) != ss->*((word16) bp_3153 - 64))
								{
									if (bx_223 >= 0x04 && bx_223 < 0x0C || bx_223 >= 0x10)
										ss->*((word16) bp_3153 - 64) = (word16) (ss->*((word16) bp_3153 - 64)) + 8;
									int16 bx_249 = (int16) (ss->*((word16) bp_3153 - 64));
									struct Eq_73710 * es_255 = Mem248[ds_175:22078:selector];
									word16 dx_257 = (word16) es_255->a025A[0].w0002[bx_249];
									Eq_5 bx_258;
									bx_258.u5 = ss->*((word16) bp_3153 - 2);
									struct Eq_73725 * es_262 = Mem248[ds_175:22080:selector];
									es_262->a01F6[0].w0000[bx_258].w0000 = es_255->a025A[0].w0000[bx_249].w0000;
									es_262->a01F6[0].w0002[bx_258] = (Eq_108405) dx_257;
								}
								(ss->*sp_116).w0000 = (word16) (ss->*((word16) bp_3153 - 2));
								Eq_5 ds_295;
								word16 si_3726;
								Mem275[ds_295:22082:selector]->*((word16) (ss->*((word16) bp_3153 - 2)) + 0x0000409A) = (byte) fn0800_1732(si_220, di_174, ds_175, (ss->*sp_116).w0000, out si_3726, out di_174, out ds_295);
								Eq_5 bx_310;
								bx_310.u5 = ss->*((word16) bp_3153 - 2);
								Mem309[ds_295:0x5644:selector]->*((word32) bx_310 + 14624) = Mem309[ds_295:22076:selector]->*((word32) bx_310 + 14700);
								ds_175 = ds_295;
							}
						}
						Mem316[ds_175:22058:selector]->tA44B.u5 = ss->*((word16) bp_3153 - 36);
						Mem321[ds_175:22060:selector]->tA44D.u5 = ss->*((word16) bp_3153 - 46);
					}
				}
				ss->*((word16) bp_3153 - 2) = (word16) (ss->*((word16) bp_3153 - 2)) + 1;
			} while (ss->*((word16) bp_3153 - 2) < 0x18);
			if (ss->*((word16) bp_3153 - 0x0044) != 0x00 && Mem329[ds_175:0x5646:selector]->w2E3A != 0x00)
			{
				ss->*((word16) bp_3153 - 76) = 0x04;
				selector es_339 = Mem338[ds_175:22088:selector];
				if (es_339->bC620 < 0x08)
					ss->*((word16) bp_3153 - 76) = (int16) es_339->bC620;
				int16 si_348 = (int16) (ss->*((word16) bp_3153 - 76));
				Mem358[ss:sp_30 + -2:word16] = Mem347[ds_175:22070:selector]:0x4036[si_348 * 0x02];
				Mem362[ss:sp_30 + -4:word16] = Mem358[ds_175:22072:selector]:0x4004[si_348 * 0x02];
				Eq_5 si_377 = fn0800_17BB(si_348 << 0x01, di_174, ds_175, ss->*((word32) sp_30 - 4), ss->*((word32) sp_30 - 2), out di_373, out ds_374);
				ss->*((word32) sp_30 - 2) = Mem362[ds_374:22060:selector]->tA44D;
				ss->*((word32) sp_30 - 4) = Mem388[ds_374:22058:selector]->tA44B;
				fn207F_1314(ss->*((word32) sp_30 - 4), ss->*((word32) sp_30 - 2));
				ss->*((word16) bp_3153 - 16) = Mem392[ds_374:22058:selector]->tA44B;
				ss->*((word16) bp_3153 - 26) = Mem405[ds_374:22060:selector]->tA44D;
				(ss->*((word32) sp_30 - 2)).u5 = 0x00;
				(ss->*((word32) sp_30 - 4)).u0 = 0x3092;
				(ss->*((word32) sp_30 - 6)).u5 = 17172;
				fn207F_1ECE(ss->*((word32) sp_30 - 6), ss->*((word32) sp_30 - 4), ss->*((word32) sp_30 - 2));
				Eq_5 si_436 = fn0800_240B(si_377, di_373, ds_374, out di_432, out ds_433);
				fn207F_18EF();
				Eq_5 di_455;
				Eq_5 ds_456;
				fn1F3D_06C3(bp_3153, fn0800_0E4B(si_436, di_432, ds_433, out di_455, out ds_456), di_455, ds_456, out di_174, out ds_175);
			}
			ss->*((word16) bp_3153 - 2) = 0x00;
			while (ss->*((word16) bp_3153 - 2) < 0x18)
			{
				if (Mem483[ds_175:0x5630:selector]->w014A != 0x00 && Mem483[ds_175:22066:selector]:0x406A[Mem483[ss:bp_3153 + -2:word16] * 0x02] != 0x00)
				{
					ss->*((word16) bp_3153 - 66) = 0x00;
					while (ss->*((word16) bp_3153 - 66) < 0x0C)
					{
						selector es_602 = Mem598[ds_175:22090:selector];
						ss->*((word16) bp_3153 - 58) = 0x00;
						ss->*((word16) bp_3153 - 44) = 0x00;
						ss->*((word16) bp_3153 - 6) = 0x00;
						es_602->wE484 = 0x00;
						Mem607[ds_175:22092:selector]->w4586 = 0x00;
						ss->*((word16) bp_3153 - 40) = (int16) (Mem609[ds_175:22094:selector]->*((word16) (ss->*((word16) bp_3153 - 2) *s 0x0C + ss->*((word16) bp_3153 - 66)) + 0x00003800));
						if (ss->*((word16) bp_3153 - 2) < 0x04 && Mem618[ds_175:0x5650:selector]->*((word16) (ss->*((word16) bp_3153 - 2)) + 110) >= 0x1E)
							ss->*((word16) bp_3153 - 40) = ~0x00;
						if (ss->*((word16) bp_3153 - 2) >= 0x0C && (ss->*((word16) bp_3153 - 2) < 0x10 && Mem628[ds_175:0x5650:selector]->*((word16) (ss->*((word16) bp_3153 - 2)) + 0x0066) >= 0x1E))
							ss->*((word16) bp_3153 - 40) = ~0x00;
						if ((ss->*((word16) bp_3153 - 40) & 0x80) == 0x00)
						{
							ss->*((word16) bp_3153 - 42) = Mem641[ds_175:22058:selector]->tA44B;
							ss->*((word16) bp_3153 - 54) = Mem649[ds_175:22060:selector]->tA44D;
							Eq_5 si_653;
							si_653.u5 = ss->*((word16) bp_3153 - 2);
							Mem658[Mem652[ds_175:22058:selector]:0xA44B:word16] = Mem652[ds_175:22072:selector]:0x4004[si_653 *16 0x02];
							Mem662[Mem658[ds_175:22060:selector]:0xA44D:word16] = Mem658[ds_175:22070:selector]:0x4036[si_653 *16 0x02];
							Eq_5 si_678;
							if (ss->*((word16) bp_3153 - 2) >= 0x04 && ss->*((word16) bp_3153 - 2) < 0x0C || ss->*((word16) bp_3153 - 2) >= 0x10)
							{
								Eq_5 ax_677 = ss->*((word16) bp_3153 - 2) *s 0x11;
								struct Eq_73025 * es_681 = Mem662[ds_175:22088:selector];
								ss->*((word16) bp_3153 - 72) = (int16) es_681->aC5DB[0].b0000[ss->*((word16) bp_3153 - 2)].b0000;
								si_678 = ax_677;
								if (ss->*((word16) bp_3153 - 2) >= 0x10)
									ss->*((word16) bp_3153 - 72) = (int16) es_681->aC597[0].b0000[ss->*((word16) bp_3153 - 2)].b0000;
							}
							else if (ss->*((word16) bp_3153 - 66) == 11)
							{
								Eq_5 ax_754;
								ax_754.u5 = ss->*((word16) bp_3153 - 2);
								ss->*((word16) bp_3153 - 72) = ax_754;
								if (ax_754 >= 0x0C)
									ss->*((word16) bp_3153 - 72) = ax_754 - 0x08;
								Eq_5 ax_766 = ss->*((word16) bp_3153 - 72) *s 0x7D;
								si_678 = ax_766;
								struct Eq_73025 * es_769 = Mem764[ds_175:22088:selector];
								if ((es_769->aC748[0].b0000[ss->*((word16) bp_3153 - 72)].b0000 & 0x08) != 0x00 && ((((es_769->aC748))[0].b0001)[ss->*((word16) bp_3153 - 72)] & 0x08) != 0x00)
									ss->*((word16) bp_3153 - 72) = 0x20;
								else
								{
									ss->*((word16) bp_3153 - 72) = 0x80;
									Mem780[ds_175:22094:selector]:0x380B[Mem780[ss:bp_3153 + -2:word16] * 0x0C] = ~0x00;
								}
							}
							else
							{
								if (ss->*((word16) bp_3153 - 2) < 0x04)
								{
									struct Eq_73983 Eq_72746::* sp_707 = sp_30 - 2;
									(ss->*sp_707).w0000 = (word16) (ss->*((word16) bp_3153 - 66));
									(ss->*sp_707).wFFFFFFFE = (word16) (ss->*((word16) bp_3153 - 2));
								}
								else
								{
									struct Eq_73962 Eq_72746::* sp_699 = sp_30 - 2;
									(ss->*sp_699).w0000 = (word16) (ss->*((word16) bp_3153 - 66));
									(ss->*sp_699).wFFFFFFFE = ss->*((word16) bp_3153 - 2) - 0x08;
								}
								struct Eq_74002 Eq_72746::* sp_726 = sp_30 - 4;
								Eq_5 ax_728 = fn1631_10A2(si_653 << 0x01, di_174, ds_175, (ss->*sp_726).w0000, sp_726[1], out si_678, out di_174, out ds_175);
								ss->*((word16) bp_3153 - 72) = ax_728;
								if (ax_728 == 0xFF)
									Mem743[ds_175:22094:selector]->*((word16) (ss->*((word16) bp_3153 - 2) *s 0x0C + ss->*((word16) bp_3153 - 66)) + 0x00003800) = (word16) ~0x00;
							}
							if ((ss->*((word16) bp_3153 - 72) & 0x80) != 0x00)
							{
l1AE8_0DC4:
								Mem3287[ds_175:22058:selector]->tA44B.u5 = ss->*((word16) bp_3153 - 42);
								Mem3292[ds_175:22060:selector]->tA44D.u5 = ss->*((word16) bp_3153 - 54);
								goto l1AE8_0DDA;
							}
							if (Mem793[ds_175:22066:selector]:0x406A[Mem793[ss:bp_3153 + -40:word16] * 0x02] == 0x00)
							{
								Mem793[ds_175:22094:selector]->*((word16) (ss->*((word16) bp_3153 - 2) *s 0x0C + ss->*((word16) bp_3153 - 66)) + 0x00003800) = (word16) ~0x00;
								goto l1AE8_0DC4;
							}
							struct Eq_74062 Eq_72746::* sp_809 = sp_30 - 2;
							(ss->*sp_809).w0000 = (word16) (ss->*((word16) bp_3153 - 72));
							(ss->*sp_809).wFFFFFFFE = (word16) (ss->*((word16) bp_3153 - 40));
							int16 ax_824 = fn1631_0F24(si_678, di_174, ds_175, (ss->*sp_809).wFFFFFFFE, (ss->*sp_809).w0000, out si_3727, out di_174, out ds_175);
							ss->*((word16) bp_3153 - 92) = ax_824;
							sp_30.u5 = sp_809 + 1;
							if (ax_824 >= 0x03)
								goto l1AE8_0DC4;
							Eq_5 si_841;
							si_841.u5 = ss->*((word16) bp_3153 - 40);
							Mem847[ss:sp_809 + 0x00:word16] = Mem838[ds_175:22070:selector]:0x4036[si_841 *16 0x02];
							Mem851[ss:sp_809 + -2:word16] = Mem847[ds_175:22072:selector]:0x4004[si_841 *16 0x02];
							(ss->*sp_809).wFFFFFFFC = (word16) Mem851[ds_175:22060:selector]->tA44D;
							(ss->*sp_809).wFFFFFFFA = (word16) Mem855[ds_175:22058:selector]->tA44B;
							Eq_5 ax_860 = fn207F_0971((ss->*sp_809).wFFFFFFFA, (ss->*sp_809).wFFFFFFFC, (ss->*sp_809).wFFFFFFFE, (ss->*sp_809).w0000);
							ss->*((word16) bp_3153 - 96) = ax_860;
							if (ax_860 == ~0x00)
								ss->*((word16) bp_3153 - 96) = 0x00;
							ss->*((word16) bp_3153 - 88) = ss->*((word16) bp_3153 - 96);
							Mem877[ds_175:22058:selector]->tA44B.u5 = ss->*((word16) bp_3153 - 42);
							Mem881[ds_175:22060:selector]->tA44D.u5 = ss->*((word16) bp_3153 - 54);
							Eq_5 si_885;
							si_885.u5 = ss->*((word16) bp_3153 - 2);
							Mem892[ss:sp_809 + 0x00:word16] = Mem884[ds_175:22070:selector]:0x4036[si_885 *16 0x02];
							Mem896[ss:sp_809 + -2:word16] = Mem892[ds_175:22072:selector]:0x4004[si_885 *16 0x02];
							Eq_5 di_902;
							Eq_5 ds_903;
							fn0800_17BB(si_885 << 0x01, di_174, ds_175, (ss->*sp_809).wFFFFFFFE, (ss->*sp_809).w0000, out di_902, out ds_903);
							Eq_5 si_913;
							si_913.u5 = ss->*((word16) bp_3153 - 40);
							Mem919[ss:sp_809 + 0x00:word16] = Mem896[ds_903:22070:selector]:0x4036[si_913 *16 0x02];
							Mem923[ss:sp_809 + -2:word16] = Mem919[ds_903:22072:selector]:0x4004[si_913 *16 0x02];
							(ss->*sp_809).wFFFFFFFC = (word16) (ss->*((word16) bp_3153 - 40));
							(ss->*sp_809).wFFFFFFFA = (word16) (ss->*((word16) bp_3153 - 2));
							struct Eq_74334 Eq_72746::* sp_3125 = (struct Eq_74334 Eq_72746::*) (sp_809 + 1);
							Eq_5 si_3227;
							Eq_5 di_1111;
							Eq_5 ds_1112;
							if (fn1631_1BFE(si_913 << 0x01, di_902, ds_903, (ss->*sp_809).wFFFFFFFC, (ss->*sp_809).wFFFFFFFE, (ss->*sp_809).w0000, out si_3227, out di_1111, out ds_1112) != 0x00)
							{
								if (ss->*((word16) bp_3153 - 2) >= 0x04 && ss->*((word16) bp_3153 - 2) < 0x0C)
								{
									Mem962[ss:bp_3153 + -0x0022:word16] = CONVERT(Mem929[ds_1112:0x5652:selector]:0x2EE8[Mem929[ss:bp_3153 + -72:word16] * 0x11], uint8, uint16);
									Eq_5 bx_963;
									bx_963.u5 = ss->*((word16) bp_3153 - 2);
									selector es_964 = Mem962[ds_1112:22088:selector];
									if ((int16) (es_964->*((word32) bx_963 + 54112)) == ss->*((word16) bp_3153 - 0x0022))
									{
										byte v62_975 = (byte) ((word32) (es_964->*((word32) bx_963 + 54104)) + 1);
										(es_964->*((word32) bx_963 + 54104)).u5 = v62_975;
										if (v62_975 == 0x00)
										{
											ss->*((word16) bp_3153 - 0x0080) = (word16) (ss->*((word16) bp_3153 - 0x0022)) + ss->*((word16) bp_3153 - 2) *s 0x11 + 50644;
											ss->*((word16) bp_3153 - 0x007E) = 0x3092;
											Eq_74502 es_bx_986;
											es_bx_986.u2 = ss->*((word16) bp_3153 - 0x0080);
											if (*es_bx_986.u2 < 0x04)
												++*es_bx_986.u2;
										}
									}
									else
									{
										selector es_971 = Mem962[ds_1112:22088:selector];
										es_971->*((word16) (ss->*((word16) bp_3153 - 2)) + 54112) = ss->*((word16) bp_3153 - 0x0022);
										es_971->*((word16) (ss->*((word16) bp_3153 - 2)) + 54104) = 0x00;
									}
								}
								if (ss->*((word16) bp_3153 - 2) < 0x04 && ss->*((word16) bp_3153 - 66) < 11)
								{
									ss->*((word16) bp_3153 - 0x0080) = (word16) (ss->*((word16) bp_3153 - 66)) + ss->*((word16) bp_3153 - 2) *s 0x7D + 51019;
									ss->*((word16) bp_3153 - 0x007E) = 0x3092;
									Eq_74502 es_bx_1008;
									es_bx_1008.u2 = ss->*((word16) bp_3153 - 0x0080);
									if (*es_bx_1008.u2 != ~0x00)
										--*es_bx_1008.u2;
								}
								if (ss->*((word16) bp_3153 - 2) >= 0x0C && (ss->*((word16) bp_3153 - 2) < 0x10 && ss->*((word16) bp_3153 - 66) < 11))
								{
									ss->*((word16) bp_3153 - 0x0080) = (word16) (ss->*((word16) bp_3153 - 66)) + ss->*((word16) bp_3153 - 2) *s 0x7D + 0xC363;
									ss->*((word16) bp_3153 - 0x007E) = 0x3092;
									Eq_74502 es_bx_1032;
									es_bx_1032.u2 = ss->*((word16) bp_3153 - 0x0080);
									if (*es_bx_1032.u2 != ~0x00)
										--*es_bx_1032.u2;
								}
								ss->*((word16) bp_3153 - 48) = (ss->*((word16) bp_3153 - 92) << 0x01) + 0x04;
								if (ss->*((word16) bp_3153 - 72) == 0x20)
								{
									ss->*((word16) bp_3153 - 48) = 0x03;
									Eq_5 ax_1050;
									ax_1050.u5 = ss->*((word16) bp_3153 - 2);
									ss->*((word16) bp_3153 - 122) = ax_1050;
									if (ax_1050 >= 0x0C)
										ss->*((word16) bp_3153 - 122) -= 0x08;
									(ss->*sp_809).w0000 = 0x24;
									(ss->*sp_809).wFFFFFFFE = (word16) (ss->*((word16) bp_3153 - 2));
									Eq_5 si_1092;
									Eq_5 di_1088;
									Eq_5 ds_1089;
									ss->*((word16) bp_3153 - 48) = (word16) (ss->*((word16) bp_3153 - 48)) + fn1631_1B44(si_3227, di_1111, ds_1112, (ss->*sp_809).wFFFFFFFE, (ss->*sp_809).w0000, out si_1092, out di_1088, out ds_1089);
									(ss->*sp_809).w0000 = 0x25;
									(ss->*sp_809).wFFFFFFFE = (word16) (ss->*((word16) bp_3153 - 2));
									word16 si_3728;
									ss->*((word16) bp_3153 - 48) = (word16) (ss->*((word16) bp_3153 - 48)) + fn1631_1B44(si_1092, di_1088, ds_1089, (ss->*sp_809).wFFFFFFFE, (ss->*sp_809).w0000, out si_3728, out di_1111, out ds_1112);
								}
								Mem1138[ss:bp_3153 + -48:word16] = Mem1128[ss:bp_3153 + -48:word16] + (CONVERT(Mem1128[ds_1112:22100:selector]:12998[Mem1128[ss:bp_3153 + -2:word16] * 0x30], int8, int16) + 0x01);
								Eq_5 si_1139;
								si_1139.u5 = ss->*((word16) bp_3153 - 40);
								ss->*((word16) bp_3153 - 48) = (word16) (ss->*((word16) bp_3153 - 48)) + (int16) (&Mem1138[ds_1112:22102:selector]->b2D1A)[(int16) (ss->*((bp_3153 - 0x0078) + si_1139))];
								Eq_5 sp_1314 = sp_30;
								if (ss->*((word16) bp_3153 - 2) >= 0x04 && ss->*((word16) bp_3153 - 2) < 0x0C)
									ss->*((word16) bp_3153 - 38) = ss->*((word16) bp_3153 - 2) - 0x04;
								if (ss->*((word16) bp_3153 - 2) >= 0x10)
									ss->*((word16) bp_3153 - 38) = ss->*((word16) bp_3153 - 2) - 0x08;
								if (ss->*((word16) bp_3153 - 2) < 0x04)
								{
									Eq_5 ax_1172 = ss->*((word16) bp_3153 - 2) *s 0x7D;
									struct Eq_73025 * es_1176 = Mem1167[ds_1112:22088:selector];
									ss->*((word16) bp_3153 - 38) = (uint16) es_1176->aC748[0].b0055[ss->*((word16) bp_3153 - 2)];
									si_1139 = ax_1172;
									if (es_1176->aC748[0].b0053[ss->*((word16) bp_3153 - 2)] != 0x00)
										ss->*((word16) bp_3153 - 48) = (word16) (ss->*((word16) bp_3153 - 48)) + 2;
									Eq_5 bx_1197;
									bx_1197.u5 = ss->*((word16) bp_3153 - 2);
									selector es_1198 = Mem1189[ds_1112:0x5658:selector];
									Mem1200[es_1198:bx_1197 + 0x92:byte] = Mem1189[es_1198:bx_1197 + 0x92:byte] + (Mem1189[ds_1112:0x5652:selector]:0x2EE5[Mem1189[ss:bp_3153 + -72:word16] * 0x11] & 0x0F);
									Eq_5 bx_1201;
									bx_1201.u5 = ss->*((word16) bp_3153 - 2);
									selector es_1202 = Mem1200[ds_1112:0x5650:selector];
									if (es_1202->*((word32) bx_1201 + 110) >= 0x08)
									{
										ss->*((word16) bp_3153 - 48) = (word16) (ss->*((word16) bp_3153 - 48)) + 1;
										if (es_1202->*((word32) bx_1201 + 110) >= 0x0D)
											ss->*((word16) bp_3153 - 48) = (word16) (ss->*((word16) bp_3153 - 48)) + 1;
										if (es_1202->*((word32) bx_1201 + 110) >= 0x11)
											ss->*((word16) bp_3153 - 48) = (word16) (ss->*((word16) bp_3153 - 48)) + 1;
										if (es_1202->*((word32) bx_1201 + 110) >= 0x18)
											ss->*((word16) bp_3153 - 48) = (word16) (ss->*((word16) bp_3153 - 48)) + 1;
									}
								}
								if (ss->*((word16) bp_3153 - 2) >= 0x0C && ss->*((word16) bp_3153 - 2) < 0x10)
								{
									Eq_5 ax_1241 = ss->*((word16) bp_3153 - 2) *s 0x7D;
									struct Eq_73025 * es_1246 = Mem1234[ds_1112:22088:selector];
									ss->*((word16) bp_3153 - 38) = (uint16) es_1246->aC3B3[0].b0002[ss->*((word16) bp_3153 - 2)];
									si_1139 = ax_1241;
									if (es_1246->aC3B3[0].b0000[ss->*((word16) bp_3153 - 2)].b0000 != 0x00)
										ss->*((word16) bp_3153 - 48) = (word16) (ss->*((word16) bp_3153 - 48)) + 2;
									Eq_5 bx_1267;
									bx_1267.u5 = ss->*((word16) bp_3153 - 2);
									selector es_1268 = Mem1259[ds_1112:0x5658:selector];
									Mem1270[es_1268:bx_1267 + 0x8A:byte] = Mem1259[es_1268:bx_1267 + 0x8A:byte] + (Mem1259[ds_1112:0x5652:selector]:0x2EE5[Mem1259[ss:bp_3153 + -72:word16] * 0x11] & 0x0F);
									Eq_5 bx_1271;
									bx_1271.u5 = ss->*((word16) bp_3153 - 2);
									selector es_1272 = Mem1270[ds_1112:0x5650:selector];
									if (es_1272->*((word32) bx_1271 + 0x0066) >= 0x08)
									{
										ss->*((word16) bp_3153 - 48) = (word16) (ss->*((word16) bp_3153 - 48)) + 1;
										if (es_1272->*((word32) bx_1271 + 0x0066) >= 0x0D)
											ss->*((word16) bp_3153 - 48) = (word16) (ss->*((word16) bp_3153 - 48)) + 1;
										if (es_1272->*((word32) bx_1271 + 0x0066) >= 0x11)
											ss->*((word16) bp_3153 - 48) = (word16) (ss->*((word16) bp_3153 - 48)) + 1;
										if (es_1272->*((word32) bx_1271 + 0x0066) >= 0x18)
											ss->*((word16) bp_3153 - 48) = (word16) (ss->*((word16) bp_3153 - 48)) + 1;
									}
								}
								if (Mem1305[ds_1112:0x565A:selector]->w2E38 != 0x00)
								{
									struct Eq_75358 Eq_72746::* sp_1321 = sp_30 - 2;
									(ss->*sp_1321).w0000 = 0x04;
									Eq_5 di_1359;
									Eq_5 ds_1360;
									si_1139 = fn1E56_0388(bp_3153, fn1E56_0281(si_1139, di_1111, ds_1112, (ss->*sp_1321).w0000, out di_1359, out ds_1360), di_1359, ds_1360, out di_1111, out ds_1112);
									sp_1314.u0 = <invalid>;
								}
								selector es_1388 = Mem1387[ds_1112:0x565C:selector];
								es_1388->w37FE = 0x0F;
								if (ss->*((word16) bp_3153 - 2) >= 0x0C)
									es_1388->w37FE = 0x0E;
								Eq_5 sp_1459;
								word16 ax_1454;
								word16 ax_1518;
								if (ss->*((word16) bp_3153 - 2) >= 0x0C)
								{
									if (Mem1397[ds_1112:0x565A:selector]->w2E38 == 0x02)
									{
										struct Eq_75497 Eq_72746::* sp_1523 = sp_1314 - 2;
										(ss->*sp_1523).w0000 = (word16) ds_1112;
										(ss->*sp_1523).wFFFFFFFE = 15977;
										si_1139 = fn1631_1DAB(si_1139, di_1111, ds_1112, (ss->*sp_1523).wFFFFFFFE, out di_1111, out ds_1112);
									}
									sp_1459 = sp_1314;
									if (ss->*((word16) bp_3153 - 2) >= 0x10)
									{
										if (Mem1544[ds_1112:0x565A:selector]->w2E38 != 0x02)
											goto l1AE8_05BF;
										ax_1454 = 0x3E73;
										goto l1AE8_0501;
									}
									if (Mem1544[ds_1112:0x565A:selector]->w2E38 == 0x02)
									{
										struct Eq_75816 Eq_72746::* sp_1553 = sp_1314 - 2;
										(ss->*sp_1553).w0000 = (word16) ds_1112;
										(ss->*sp_1553).wFFFFFFFE = 16001;
										si_1139 = fn1631_1DAB(si_1139, di_1111, ds_1112, (ss->*sp_1553).wFFFFFFFE, out di_1111, out ds_1112);
									}
									sp_1459 = sp_1314;
									if (ss->*((word16) bp_3153 - 72) != 0x20)
									{
										if (Mem1577[ds_1112:0x565A:selector]->w2E38 != 0x02)
											goto l1AE8_05BF;
										ax_1454 = 16007;
										goto l1AE8_0501;
									}
									struct Eq_75850 Eq_72746::* sp_1582 = sp_1314 - 2;
									(ss->*sp_1582).w0000 = (word16) ds_1112;
									(ss->*sp_1582).wFFFFFFFE = 16015;
									(ss->*sp_1582).wFFFFFFFC = 0x3092;
									(ss->*sp_1582).wFFFFFFFA = 0x12;
									fn207F_3B68((ss->*sp_1582).wFFFFFFFA, (ss->*sp_1582).wFFFFFFFE);
									if (Mem1592[ds_1112:0x565A:selector]->w2E38 != 0x01)
										goto l1AE8_05AF;
									ax_1518 = 16021;
									goto l1AE8_059D;
								}
								if (Mem1397[ds_1112:0x565A:selector]->w2E38 == 0x02)
								{
									int16 ax_1410 = CONVERT(Mem1397[ds_1112:22088:selector]:50708[Mem1397[ss:bp_3153 + -38:word16] * 0x11], int8, int16);
									struct Eq_75538 * es_1415 = Mem1397[ds_1112:22110:selector];
									struct Eq_75541 Eq_72746::* sp_1419 = sp_1314 - 2;
									(ss->*sp_1419).w0000 = (word16) es_1415->a01CA[0].w0002[ax_1410];
									(ss->*sp_1419).wFFFFFFFE = es_1415->a01CA[0].w0000[ax_1410].w0000;
									si_1139 = fn1631_1DAB(si_1139, di_1111, ds_1112, (ss->*sp_1419).wFFFFFFFE, out di_1111, out ds_1112);
								}
								sp_1459 = sp_1314;
								if (ss->*((word16) bp_3153 - 2) >= 0x04)
								{
									if (Mem1447[ds_1112:0x565A:selector]->w2E38 != 0x02)
										goto l1AE8_05BF;
									ax_1454 = 0x3E60;
									goto l1AE8_0501;
								}
								if (Mem1447[ds_1112:0x565A:selector]->w2E38 == 0x02)
								{
									struct Eq_75623 Eq_72746::* sp_1460 = sp_1314 - 2;
									(ss->*sp_1460).w0000 = (word16) ds_1112;
									(ss->*sp_1460).wFFFFFFFE = 0x3E44;
									si_1139 = fn1631_1DAB(si_1139, di_1111, ds_1112, (ss->*sp_1460).wFFFFFFFE, out di_1111, out ds_1112);
								}
								sp_1459 = sp_1314;
								struct Eq_75594 Eq_72746::* sp_1637;
								if (ss->*((word16) bp_3153 - 72) == 0x20)
								{
									struct Eq_75669 Eq_72746::* sp_1494 = sp_1314 - 2;
									(ss->*sp_1494).w0000 = (word16) ds_1112;
									(ss->*sp_1494).wFFFFFFFE = 15949;
									(ss->*sp_1494).wFFFFFFFC = 0x3092;
									(ss->*sp_1494).wFFFFFFFA = 0x12;
									fn207F_3B68((ss->*sp_1494).wFFFFFFFA, (ss->*sp_1494).wFFFFFFFE);
									if (Mem1503[ds_1112:0x565A:selector]->w2E38 == 0x01)
									{
										ax_1518 = 15955;
l1AE8_059D:
										struct Eq_75717 Eq_72746::* sp_1609 = sp_1314 - 2;
										(ss->*sp_1609).w0000 = (word16) ds_1112;
										(ss->*sp_1609).wFFFFFFFE = ax_1518;
										(ss->*sp_1609).wFFFFFFFC = 0x3092;
										(ss->*sp_1609).wFFFFFFFA = 0x12;
										fn207F_3B68((ss->*sp_1609).wFFFFFFFA, (ss->*sp_1609).wFFFFFFFE);
									}
l1AE8_05AF:
									sp_1637 = sp_1314 - 2;
									(ss->*sp_1637).w0000 = 0x3092;
									ax_1454 = 0x12;
									goto l1AE8_05B6;
								}
								if (Mem1484[ds_1112:0x565A:selector]->w2E38 == 0x02)
								{
									ax_1454 = 0x3E58;
l1AE8_0501:
									sp_1637 = sp_1314 - 2;
									(ss->*sp_1637).w0000 = (word16) ds_1112;
l1AE8_05B6:
									struct Eq_75643 Eq_72746::* sp_1654 = sp_1637 - 2;
									(ss->*sp_1654).w0000 = ax_1454;
									si_1139 = fn1631_1DAB(si_1139, di_1111, ds_1112, (ss->*sp_1654).w0000, out di_1111, out ds_1112);
									sp_1459.u5 = sp_1654 + 2;
								}
l1AE8_05BF:
								if (ss->*((word16) bp_3153 - 72) != 0x20)
								{
									int16 ax_1706 = ss->*((word16) bp_3153 - 72) *s 0x11;
									struct Eq_75763 Eq_72746::* sp_1712 = sp_1459 - 2;
									(ss->*sp_1712).w0000 = 16091;
									(ss->*sp_1712).wFFFFFFFE = ax_1706 + 11992;
									si_1139 = fn1631_1DAB(si_1139, di_1111, ds_1112, (ss->*sp_1712).wFFFFFFFE, out di_1111, out ds_1112);
								}
								if (Mem1736[ds_1112:0x565A:selector]->w2E38 == 0x02)
								{
									struct Eq_75790 Eq_72746::* sp_1742 = sp_1459 - 2;
									(ss->*sp_1742).w0000 = (word16) ds_1112;
									(ss->*sp_1742).wFFFFFFFE = 16026;
									si_1139 = fn1631_1DAB(si_1139, di_1111, ds_1112, (ss->*sp_1742).wFFFFFFFE, out di_1111, out ds_1112);
								}
								struct Eq_76017 Eq_72746::* sp_1901;
								word16 ax_1899;
								if (ss->*((word16) bp_3153 - 40) >= 0x0C)
								{
									if (Mem1768[ds_1112:0x565A:selector]->w2E38 != 0x02)
										goto l1AE8_071B;
									if (Mem1768[ds_1112:22112:selector]->wE48E == 0x00 || ss->*((word16) bp_3153 - 40) != 0x0D)
									{
										struct Eq_75949 Eq_72746::* sp_1913 = sp_1459 - 2;
										(ss->*sp_1913).w0000 = (word16) ds_1112;
										(ss->*sp_1913).wFFFFFFFE = 16041;
										Eq_5 si_1932 = fn1631_1DAB(si_1139, di_1111, ds_1112, (ss->*sp_1913).wFFFFFFFE, out di_1928, out ds_1929);
										word16 ax_1942;
										if (ss->*((word16) bp_3153 - 40) < 0x10)
											ax_1942 = 0x3EB3;
										else
											ax_1942 = 0x3EB9;
										(ss->*sp_1913).w0000 = (word16) ds_1929;
										(ss->*sp_1913).wFFFFFFFE = ax_1942;
										si_1139 = fn1631_1DAB(si_1932, di_1928, ds_1929, (ss->*sp_1913).wFFFFFFFE, out di_1111, out ds_1112);
									}
									if (Mem1971[ds_1112:22112:selector]->wE48E == 0x00 || ss->*((word16) bp_3153 - 40) != 0x0D)
										goto l1AE8_071B;
									sp_1901 = sp_1459 - 2;
									(ss->*sp_1901).w0000 = (word16) ds_1112;
									ax_1899 = 0x3EC0;
									goto l1AE8_0712;
								}
								if (ss->*((word16) bp_3153 - 40) >= 0x04)
								{
									int16 ax_1841 = CONVERT(Mem1768[ds_1112:22088:selector]:0xC5D0[Mem1768[ss:bp_3153 + -40:word16] * 0x11], int8, int16);
									struct Eq_75538 * es_1846 = Mem1768[ds_1112:22110:selector];
									struct Eq_77710 Eq_72746::* sp_1848 = sp_1459 - 2;
									(ss->*sp_1848).w0000 = es_1846->a01CA[0].w0002[ax_1841].w0000;
									(ss->*sp_1848).wFFFFFFFE = es_1846->a01CA[0].w0000[ax_1841].w0000;
									(ss->*sp_1848).wFFFFFFFC = 0x3092;
									(ss->*sp_1848).wFFFFFFFA = 0x12;
									fn207F_3B68((ss->*sp_1848).wFFFFFFFA, (ss->*sp_1848).wFFFFFFFE);
								}
								else
								{
									struct Eq_73025 * es_1778 = Mem1768[ds_1112:22088:selector];
									int16 ax_1783 = (int16) es_1778->aC614[0].b0000[es_1778->aC748[0].b0055[ss->*((word16) bp_3153 - 40)].b0000].b0000;
									struct Eq_75538 * es_1788 = Mem1768[ds_1112:22110:selector];
									struct Eq_77624 Eq_72746::* sp_1791 = sp_1459 - 2;
									(ss->*sp_1791).w0000 = es_1788->a01CA[0].w0002[ax_1783].w0000;
									(ss->*sp_1791).wFFFFFFFE = es_1788->a01CA[0].w0000[ax_1783].w0000;
									(ss->*sp_1791).wFFFFFFFC = 0x3092;
									(ss->*sp_1791).wFFFFFFFA = 0x12;
									fn207F_3B68((ss->*sp_1791).wFFFFFFFA, (ss->*sp_1791).wFFFFFFFE);
									(ss->*sp_1791).w0000 = (word16) ds_1112;
									(ss->*sp_1791).wFFFFFFFE = 16031;
									(ss->*sp_1791).wFFFFFFFC = 0x3092;
									(ss->*sp_1791).wFFFFFFFA = 0x12;
									fn207F_3B22((ss->*sp_1791).wFFFFFFFA, (ss->*sp_1791).wFFFFFFFE);
								}
								struct Eq_77750 Eq_72746::* sp_1869 = sp_1459 - 8;
								sp_1869[3] = (struct Eq_77750) ds_1112;
								sp_1869[2] = (struct Eq_77750) 0x3EA7;
								sp_1869[1] = (struct Eq_77750) 0x3092;
								(ss->*sp_1869).w0000 = 0x12;
								fn207F_3B22((ss->*sp_1869).w0000, sp_1869[2]);
								if (Mem1884[ds_1112:0x565A:selector]->w2E38 == 0x02)
								{
									sp_1869[3] = (struct Eq_77750) 0x3092;
									ax_1899 = 0x12;
									sp_1901 = (struct Eq_76017 Eq_72746::*) (sp_1869 + 3);
l1AE8_0712:
									struct Eq_77795 Eq_72746::* sp_1985 = sp_1901 - 2;
									(ss->*sp_1985).w0000 = ax_1899;
									si_1139 = fn1631_1DAB(si_1139, di_1111, ds_1112, (ss->*sp_1985).w0000, out di_1111, out ds_1112);
								}
l1AE8_071B:
								Mem2036[ss:bp_3153 + -48:word16] = Mem2019[ss:bp_3153 + -48:word16] - CONVERT(Mem2019[Mem2019[ds_1112:22088:selector]:(CONVERT(Mem2019[ds_1112:0x5652:selector]:0x2EE8[Mem2019[ss:bp_3153 + -72:word16] * 0x11], uint8, uint16) + Mem2019[ss:bp_3153 + -38:word16] *s 0x11) + 0xC618:byte], int8, int16);
								Eq_5 si_2186;
								Eq_5 di_2182;
								Eq_5 ds_2183;
								Eq_5 sp_2429;
								if (ss->*((word16) bp_3153 - 40) >= 0x04 && ss->*((word16) bp_3153 - 40) < 0x0C || ss->*((word16) bp_3153 - 40) >= 0x10)
								{
									Eq_5 ax_2049;
									ax_2049.u5 = ss->*((word16) bp_3153 - 40);
									ss->*((word16) bp_3153 - 0x0C) = ax_2049 - 0x04;
									if (ax_2049 >= 0x10)
										ss->*((word16) bp_3153 - 0x0C) -= 0x04;
									ss->*((word16) bp_3153 - 48) = (word16) (ss->*((word16) bp_3153 - 48)) + ((int16) (Mem2059[ds_1112:22114:selector]->*((word16) (ss->*((word16) bp_3153 - 40)) + 0x000032AE)) >> 0x01);
									ss->*((word16) bp_3153 - 0x007C) = 0x7F;
									Eq_5 ax_2073 = ss->*((word16) bp_3153 - 72) *s 0x11;
									struct Eq_74418 * es_2075 = Mem2070[ds_1112:0x5652:selector];
									ss->*((word16) bp_3153 - 52) = (uint16) es_2075->a2EE3[0].b0001[ss->*((word16) bp_3153 - 72)];
									Eq_5 si_2074 = ax_2073;
									if ((ss->*((word16) bp_3153 - 52) & 0x80) != 0x00)
									{
										Eq_76201 ax_2085;
										ax_2085.u1 = (uint16) es_2075->a2EE3[0].b0000[ss->*((word16) bp_3153 - 72)].b0000;
										ss->*((word16) bp_3153 - 50) = ax_2085;
										ss->*((word16) bp_3153 - 0x007C) = ax_2085 & 0x0F;
										ss->*((word16) bp_3153 - 50) = ss->*((word16) bp_3153 - 50) >> 0x04 & 0x0F;
										while (true)
										{
											Eq_76201 ax_2100 = ss->*((word16) bp_3153 - 50);
											--ss->*((word16) bp_3153 - 50);
											if (ax_2100 == 0x00)
												break;
											struct Eq_5398 * ds_ax_3730 = fn0800_19F3(si_2074, di_1111, ds_1112, out si_2074, out di_1111);
											ss->*((word16) bp_3153 - 0x007C) = (word16) (ss->*((word16) bp_3153 - 0x007C)) + (word16) ds_ax_3730;
											ds_1112.u5 = SLICE(ds_ax_3730, selector, 16);
										}
									}
									ss->*((word16) bp_3153 - 52) &= 0x7F;
									if (ss->*((word16) bp_3153 - 0x007C) == 0x00)
										ss->*((word16) bp_3153 - 0x007C) = (word16) (ss->*((word16) bp_3153 - 0x007C)) + 1;
									Eq_5 sp_2165;
									sp_2165.u0 = <invalid>;
									Eq_5 si_2164;
									Eq_5 di_2160;
									Eq_5 ds_2161;
									if (fn0800_19DD(bp_3153, si_2074, di_1111, ds_1112, out si_2164, out di_2160, out ds_2161) < ss->*((word16) bp_3153 - 48))
									{
										ss->*((word32) sp_2165 - 2) = ds_2161;
										(ss->*((word32) sp_2165 - 4)).u0 = 16077;
										si_2186 = fn1631_1DAB(si_2164, di_2160, ds_2161, ss->*((word32) sp_2165 - 4), out di_2182, out ds_2183);
										ss->*((word16) bp_3153 - 86) = 0x00;
										ss->*((word16) bp_3153 - 52) = 0x00;
										Eq_5 bx_2216;
										bx_2216.u5 = ss->*((word16) bp_3153 - 40);
										if (Mem2215[ds_2183:22114:selector]->*((word32) bx_2216 + 0x000032AE) != 0x00 && (ss->*((word16) bp_3153 - 72) >= 0x10 && ss->*((word16) bp_3153 - 72) <= 0x12 || ss->*((word16) bp_3153 - 72) == 11))
										{
											selector es_2232 = Mem2215[ds_2183:22116:selector];
											if (es_2232->*((word32) bx_2216 + 14160) >= 0x10 && es_2232->*((word32) bx_2216 + 14160) <= 0x3F)
											{
												(ss->*((word32) sp_2165 - 2)).u0 = 0x00;
												(ss->*((word32) sp_2165 - 4)).u0 = ~0x00;
												ss->*((word32) sp_2165 - 6) = bx_2216;
												si_2186 = fn1AE8_1E46(si_2186, di_2182, ds_2183, ss->*((word32) sp_2165 - 6), ss->*((word32) sp_2165 - 4), ss->*((word32) sp_2165 - 2), out di_2182, out ds_2183);
											}
										}
									}
									else
									{
										ss->*((word32) sp_2165 - 2) = ds_2161;
										(ss->*((word32) sp_2165 - 4)).u0 = 16086;
										si_2186 = fn1631_1DAB(si_2164, di_2160, ds_2161, ss->*((word32) sp_2165 - 4), out di_2182, out ds_2183);
									}
									while (true)
									{
										Eq_76128 ax_2275 = ss->*((word16) bp_3153 - 52);
										--ss->*((word16) bp_3153 - 52);
										sp_2429 = sp_2165;
										if (ax_2275 == 0x00)
											break;
										ss->*((word16) bp_3153 - 86) = 0x01;
										ss->*((word16) bp_3153 - 6) = 0x01;
										struct Eq_73025 * es_2299 = Mem2294[ds_2183:22088:selector];
										Eq_74502 al_2300;
										al_2300.u2 = (&es_2299->bC620)[2][ss->*((word16) bp_3153 - 0x0C)];
										ss->*((word16) bp_3153 - 0x0080) = al_2300;
										if (al_2300 != 0x00)
										{
											if ((int16) al_2300 >= ss->*((word16) bp_3153 - 0x007C) >> 0x01)
											{
												ss->*((word16) bp_3153 - 0x007C) >>= 0x01;
												(&es_2299->bC620)[2][ss->*((word16) bp_3153 - 0x0C)].b0000 = (&es_2299->bC620)[2][ss->*((word16) bp_3153 - 0x0C)].b0000 - ss->*((word16) bp_3153 - 0x007C);
											}
											else
											{
												ss->*((word16) bp_3153 - 0x007C) -= (int16) (&es_2299->bC620)[2][ss->*((word16) bp_3153 - 0x0C)].b0000;
												(&es_2299->bC620)[2][ss->*((word16) bp_3153 - 0x0C)].b0000 = 0x00;
											}
										}
										if ((int16) (&es_2299->bC620)[3][ss->*((word16) bp_3153 - 0x0C)] <= ss->*((word16) bp_3153 - 0x007C))
											(&es_2299->bC620)[3][ss->*((word16) bp_3153 - 0x0C)].b0000 = 0x00;
										else
											(&es_2299->bC620)[3][ss->*((word16) bp_3153 - 0x0C)].b0000 = (&es_2299->bC620)[3][ss->*((word16) bp_3153 - 0x0C)].b0000 - ss->*((word16) bp_3153 - 0x007C);
									}
									if (Mem2277[ds_2183:22088:selector]:0xC623[Mem2277[ss:bp_3153 + -0x0C:word16] * 0x11] == 0x00)
										ss->*((word16) bp_3153 - 44) = 0x01;
								}
								else
								{
									Eq_5 bx_2372;
									bx_2372.u5 = ss->*((word16) bp_3153 - 40);
									ss->*((word16) bp_3153 - 48) = (word16) (ss->*((word16) bp_3153 - 48)) + ((int16) (Mem2036[ds_1112:22114:selector]->*((word32) bx_2372 + 0x000032AE)) >> 0x03);
									ss->*((word16) bp_3153 - 0x0C) = bx_2372;
									if (bx_2372 >= 0x0C)
										ss->*((word16) bp_3153 - 0x0C) -= 0x08;
									Eq_76159 ax_2392;
									ax_2392.u0 = (int16) (Mem2388[ds_1112:22076:selector]->*((word32) bx_2372 + 14700));
									ss->*((word16) bp_3153 - 70) = ax_2392;
									if (ax_2392 == ~0x00)
										ss->*((word16) bp_3153 - 70) = (int16) (Mem2395[ds_1112:0x5666:selector]->*((word32) bx_2372 + 0x000045B6));
									ss->*((word16) bp_3153 - 84) = (int16) (Mem2404[ds_1112:22120:selector]->*(ss->*((word16) bp_3153 - 70) - ss->*((word16) bp_3153 - 96))).b2D11;
									Eq_5 ds_2425;
									word16 si_3729;
									ss->*((word16) bp_3153 - 96) = (uint16) (Mem2412[ds_2425:22122:selector]->*((word16) (ss->*((word16) bp_3153 - 84) *s 11 + fn0800_19DD(bp_3153, si_1139, di_1111, ds_1112, out si_3729, out di_2182, out ds_2425)) + 11840));
									sp_2429.u0 = <invalid>;
									if (ss->*((word16) bp_3153 - 72) == 0x20)
									{
										uint8 al_2457;
										if (ss->*((word16) bp_3153 - 2) < 0x04)
											al_2457 = Mem2445[ds_2425:22088:selector]:50996[Mem2445[ss:bp_3153 + -2:word16] * 0x7D];
										else
											al_2457 = Mem2445[ds_2425:22088:selector]:49996[Mem2445[ss:bp_3153 + -2:word16] * 0x7D];
										Eq_76104 ax_2468;
										ax_2468.u1 = (uint16) al_2457;
										ss->*((word16) bp_3153 - 0x007C) = ax_2468;
										ss->*((word16) bp_3153 - 0x007C) = (word32) ax_2468 /16 0x05;
										Mem2480[ds_2425:0x5652:selector]->t3103 = ss->*((word16) bp_3153 - 0x007C);
										ss->*((word16) bp_3153 - 96) = (uint16) (Mem2484[ds_2425:22122:selector]->*((word16) (fn207F_0BC0() & 0x08) + 11843));
									}
									Eq_5 ax_2503 = ss->*((word16) bp_3153 - 72) *s 0x11;
									si_2186 = ax_2503;
									struct Eq_74418 * es_2506 = Mem2501[ds_2425:0x5652:selector];
									if ((es_2506->a2EE3[0].b0001[ss->*((word16) bp_3153 - 72)].b0000 & 0x80) != 0x00)
										ds_2183 = ds_2425;
									else
									{
										ss->*((word16) bp_3153 - 0x007C) = (uint16) es_2506->a2EE3[0].b0000[ss->*((word16) bp_3153 - 72)].b0000;
										Eq_5 ds_2553 = ds_2425;
										if (es_2506->a2EE3[0].b0001[ss->*((word16) bp_3153 - 72)].b0000 > 0x01)
										{
											Eq_5 ds_2525;
											Eq_5 si_2528;
											ss->*((word16) bp_3153 - 0x007C) *= (uint16) (Mem2514[ds_2525:22124:selector]->*((word16) ((word16) (fn0800_19DD(bp_3153, ax_2503, di_2182, ds_2425, out si_2528, out di_2182, out ds_2525) *s 0x07) + (uint16) (Mem2514[ds_2525:0x5652:selector]->*((word32) si_2528 + 0x00002EE4))) + 0x00002E5E));
											ds_2553 = ds_2525;
											si_2186 = si_2528;
										}
										Eq_5 sp_2566;
										sp_2566.u0 = <invalid>;
										Eq_5 si_2565;
										Eq_5 di_2561;
										Eq_5 ds_2562;
										if (fn0800_19DD(bp_3153, si_2186, di_2182, ds_2553, out si_2565, out di_2561, out ds_2562) >= ss->*((word16) bp_3153 - 48))
										{
											ss->*((word16) bp_3153 - 86) = 0x01;
											ss->*((word32) sp_2566 - 2) = ds_2562;
											(ss->*((word32) sp_2566 - 4)).u0 = 0x3EE7;
											Eq_5 si_2753 = fn1631_1DAB(si_2565, di_2561, ds_2562, ss->*((word32) sp_2566 - 4), out di_2749, out ds_2750);
											(ss->*((word32) sp_2566 - 2)).u5 = ss->*((word16) bp_3153 - 96);
											si_2186 = fn1631_1B8F(si_2753, di_2749, ds_2750, ss->*((word32) sp_2566 - 2), out di_2182, out ds_2183);
										}
										else
										{
											ss->*((word32) sp_2566 - 2) = ds_2562;
											(ss->*((word32) sp_2566 - 4)).u0 = 0x3EDE;
											si_2186 = fn1631_1DAB(si_2565, di_2561, ds_2562, ss->*((word32) sp_2566 - 4), out di_2182, out ds_2183);
											ss->*((word16) bp_3153 - 86) = 0x00;
											ss->*((word16) bp_3153 - 0x007C) = 0x00;
											Eq_5 bx_2597;
											bx_2597.u5 = ss->*((word16) bp_3153 - 40);
											if (Mem2596[ds_2183:22114:selector]->*((word32) bx_2597 + 0x000032AE) != 0x00 && (ss->*((word16) bp_3153 - 72) >= 0x10 && ss->*((word16) bp_3153 - 72) <= 0x12 || ss->*((word16) bp_3153 - 72) == 11))
											{
												selector es_2613 = Mem2596[ds_2183:22116:selector];
												if (es_2613->*((word32) bx_2597 + 14160) >= 0x10 && es_2613->*((word32) bx_2597 + 14160) <= 0x3F)
												{
													(ss->*((word32) sp_2566 - 2)).u0 = ~0x00;
													(ss->*((word32) sp_2566 - 4)).u0 = 0x00;
													ss->*((word32) sp_2566 - 6) = bx_2597;
													si_2186 = fn1AE8_1E46(si_2186, di_2182, ds_2183, ss->*((word32) sp_2566 - 6), ss->*((word32) sp_2566 - 4), ss->*((word32) sp_2566 - 2), out di_2182, out ds_2183);
												}
											}
											if (ss->*((word16) bp_3153 - 40) < 0x04 || ss->*((word16) bp_3153 - 40) >= 0x0C && ss->*((word16) bp_3153 - 40) < 0x10)
											{
												Eq_5 bx_2666;
												bx_2666.u5 = ss->*((word16) bp_3153 - 40);
												if ((uint16) (Mem2656[ds_2183:22126:selector]->*((word32) bx_2666 + 17870)) >= Mem2656[ds_2183:22128:selector]->w0150)
												{
													Eq_5 bx_2679;
													bx_2679.u5 = ss->*((word16) bp_3153 - 40);
													Mem2686[ss:bp_3153 + -24:word16] = Mem2656[ds_2183:22070:selector]:0x4036[bx_2666 *16 0x02] - CONVERT(Mem2656[Mem2656[ds_2183:22130:selector]:bx_2679 + 0x4554:byte], uint8, uint16) - 0x01;
													if ((ss->*((word16) bp_3153 - 24) & 0x80) != 0x00)
														ss->*((word16) bp_3153 - 24) &= ~0x0F80;
													(ss->*((word32) sp_2566 - 2)).u5 = ss->*((word16) bp_3153 - 24);
													Mem2712[ss:sp_2566 + -4:word16] = Mem2704[ds_2183:22072:selector]:0x4004[bx_2679 *16 0x02];
													(ss->*((word32) sp_2566 - 6)).u0 = 0x7F;
													si_2186 = fn183B_27C9(si_2186, di_2182, ds_2183, ss->*((word32) sp_2566 - 6), ss->*((word32) sp_2566 - 4), ss->*((word32) sp_2566 - 2), out di_2182, out ds_2183);
												}
											}
										}
										while (true)
										{
											sp_2429 = sp_2566;
											if (ss->*((word16) bp_3153 - 0x007C) == 0x00 || Mem2781[ds_2183:22088:selector]:50980[Mem2781[ss:bp_3153 + -0x0C:word16] * 0x7D] == ~0x00)
												break;
											if (ss->*((word16) bp_3153 - 72) == 11)
											{
												Mem2781[ds_2183:22132:selector]->*((word16) (ss->*((word16) bp_3153 - 0x0C)) + 54646) = 0x03;
												ss->*((word16) bp_3153 - 52) = 0x00;
												ss->*((word16) bp_3153 - 0x007C) = 0x00;
											}
											Eq_76104 ax_2813;
											ax_2813.u1 = (uint16) (Mem2804[ds_2183:22088:selector]->*((word16) (ss->*((word16) bp_3153 - 0x0C) *s 0x7D + ss->*((word16) bp_3153 - 96)) + 50980));
											ss->*((word16) bp_3153 - 82) = ax_2813;
											if (ss->*((word16) bp_3153 - 0x007C) > ax_2813)
											{
												ss->*((word16) bp_3153 - 0x007C) -= ss->*((word16) bp_3153 - 82);
												Mem2955[ds_2183:22088:selector]->*((word16) (ss->*((word16) bp_3153 - 0x0C) *s 0x7D + ss->*((word16) bp_3153 - 96)) + 50980) = (word16) 0x00;
												if (ss->*((word16) bp_3153 - 82) != 0x00 && (ss->*((word16) bp_3153 - 96) == 0x1C || ss->*((word16) bp_3153 - 96) == 33))
													Mem2962[ds_2183:0x5676:selector]->b3986 = 0x01;
												if (ss->*((word16) bp_3153 - 96) >= 0x1C && ss->*((word16) bp_3153 - 96) <= 0x23)
												{
													(ss->*((word32) sp_2566 - 2)).u5 = ss->*((word16) bp_3153 - 96);
													(ss->*((word32) sp_2566 - 4)).u5 = ss->*((word16) bp_3153 - 0x0C);
													si_2186 = fn1631_11AB(si_2186, di_2182, ds_2183, ss->*((word32) sp_2566 - 4), ss->*((word32) sp_2566 - 2), out di_2182, out ds_2183);
												}
												(ss->*((word32) sp_2566 - 2)).u5 = ss->*((word16) bp_3153 - 96);
												ss->*((word16) bp_3153 - 96) = fn1631_1122(si_2186, di_2182, ds_2183, ss->*((word32) sp_2566 - 2), out si_2186, out di_2182, out ds_2183);
												if (Mem3037[ds_2183:22090:selector]->wE484 != 0x00)
												{
													(ss->*((word32) sp_2566 - 2)).u5 = ss->*((word16) bp_3153 - 40);
													si_2186 = fn1543_0A35(si_2186, di_2182, ds_2183, ss->*((word32) sp_2566 - 2), out di_2182, out ds_2183);
													ss->*((word16) bp_3153 - 58) = 0x01;
													Mem3059[ds_2183:22092:selector]->w4586 = 0x00;
												}
											}
											else
											{
												if (ss->*((word16) bp_3153 - 0x007C) == ax_2813 && (ss->*((word16) bp_3153 - 96) == 0x1C || ss->*((word16) bp_3153 - 96) == 33))
													Mem2814[ds_2183:0x5676:selector]->b3986 = 0x01;
												Eq_77550 bx_2840 = (word16) (ss->*((word16) bp_3153 - 96)) + ss->*((word16) bp_3153 - 0x0C) *s 0x7D;
												selector es_2842 = Mem2830[ds_2183:22088:selector];
												es_2842->*((word16) bx_2840 + 50980) -= ss->*((word16) bp_3153 - 0x007C);
												ss->*((word16) bp_3153 - 0x007C) = 0x00;
												if (ss->*((word16) bp_3153 - 96) >= 0x1C && ss->*((word16) bp_3153 - 96) <= 0x23)
												{
													(ss->*((word32) sp_2566 - 2)).u5 = ss->*((word16) bp_3153 - 96);
													(ss->*((word32) sp_2566 - 4)).u5 = ss->*((word16) bp_3153 - 0x0C);
													si_2186 = fn1631_11AB(si_2186, di_2182, ds_2183, ss->*((word32) sp_2566 - 4), ss->*((word32) sp_2566 - 2), out di_2182, out ds_2183);
												}
												if ((ss->*((word16) bp_3153 - 96) == 0x1F || ss->*((word16) bp_3153 - 96) == 0x20) && Mem2890[ds_2183:22088:selector]->*((word16) (ss->*((word16) bp_3153 - 0x0C) *s 0x7D + ss->*((word16) bp_3153 - 96)) + 50980) == 0x00)
												{
													(ss->*((word32) sp_2566 - 2)).u5 = ss->*((word16) bp_3153 - 40);
													si_2186 = fn1543_0A35(si_2186, di_2182, ds_2183, ss->*((word32) sp_2566 - 2), out di_2182, out ds_2183);
													ss->*((word16) bp_3153 - 58) = 0x01;
													Mem2933[ds_2183:22092:selector]->w4586 = 0x00;
													if (ss->*((word16) bp_3153 - 40) == 0x00 && ss->*((word16) bp_3153 + 6) != 0x00)
														si_2186 = fn1467_0D7E(si_2186, di_2182, ds_2183, out di_2182, out ds_2183);
												}
											}
										}
									}
								}
								struct Eq_76758 Eq_72746::* sp_3069 = sp_2429 - 2;
								(ss->*sp_3069).t0000.u0 = 0x3092;
								(ss->*sp_3069).tFFFFFFFE.u0 = 17172;
								(ss->*sp_3069).tFFFFFFFC.u0 = (wchar_t) (ss->*((word16) bp_3153 - 86));
								(ss->*sp_3069).tFFFFFFFA.u0 = (wchar_t) (ss->*((word16) bp_3153 - 0x0C));
								(ss->*sp_3069).wFFFFFFF8 = (word16) (ss->*((word16) bp_3153 - 58));
								(ss->*sp_3069).wFFFFFFF6 = (word16) (ss->*((word16) bp_3153 - 44));
								(ss->*sp_3069).wFFFFFFF4 = (word16) (ss->*((word16) bp_3153 - 6));
								(ss->*sp_3069).tFFFFFFF2.u0 = (wchar_t) (ss->*((word16) bp_3153 - 88));
								(ss->*sp_3069).tFFFFFFF0.u0 = (wchar_t) (ss->*((word16) bp_3153 - 72));
								(ss->*sp_3069).tFFFFFFEE.u0 = (wchar_t) (ss->*((word16) bp_3153 - 40));
								(ss->*sp_3069).tFFFFFFEC.u0 = (wchar_t) (ss->*((word16) bp_3153 - 2));
								Eq_5 si_3119 = fn1AE8_12C7(si_2186, di_2182, ds_2183, (ss->*sp_3069).tFFFFFFEC.u0, (ss->*sp_3069).tFFFFFFEE.u0, (ss->*sp_3069).tFFFFFFF0.u0, (ss->*sp_3069).tFFFFFFF2.u0, (ss->*sp_3069).wFFFFFFF4, (ss->*sp_3069).tFFFFFFFC.u0, (ss->*sp_3069).tFFFFFFFE.u0, (ss->*sp_3069).t0000.u0, out di_3115, out ds_3116);
								sp_3125 = (struct Eq_74334 Eq_72746::*) ((char *) &sp_3069->t0000 + 2);
								if (Mem3101[ds_3116:0x5676:selector]->b3986 != 0x00)
								{
									Mem3101[ds_3116:22092:selector]->w4586 = 0x00;
									if (Mem3130[ds_3116:0x5646:selector]->w2E3A != 0x00 && (ss->*((word16) bp_3153 - 40) != 0x0D || Mem3130[ds_3116:22112:selector]->wE48E == 0x00))
									{
										(ss->*sp_3069).t0000.u0 = 0x00;
										(ss->*sp_3069).tFFFFFFFE.u0 = 0x10;
										Eq_5 sp_3161;
										sp_3161.u0 = <invalid>;
										bp_3153 = fn0800_48B7(si_3119, di_3115, ds_3116, (ss->*sp_3069).tFFFFFFFE.u0, out si_3119, out di_3115, out ds_3116);
										sp_3125 = (struct Eq_74334 Eq_72746::*) ((word32) sp_3161 + 4);
									}
								}
								if (Mem3171[ds_3116:22092:selector]->w4586 != 0x00 && ((int16) Mem3171[ds_3116:22088:selector]->bC620 == ss->*((word16) bp_3153 - 0x0C) && Mem3171[ds_3116:0x5646:selector]->w2E3A != 0x00))
								{
									struct Eq_77182 Eq_72746::* sp_3188 = sp_3125 - 2;
									(ss->*sp_3188).w0000 = 0x00;
									(ss->*sp_3188).wFFFFFFFE = 0x05;
									Eq_5 sp_3205;
									sp_3205.u0 = <invalid>;
									bp_3153 = fn0800_48B7(si_3119, di_3115, ds_3116, (ss->*sp_3188).wFFFFFFFE, out si_3119, out di_3115, out ds_3116);
									sp_3125 = (struct Eq_74334 Eq_72746::*) ((word32) sp_3205 + 4);
								}
								si_3227 = fn1631_1DCC(bp_3153, si_3119, di_3115, ds_3116, out di_1111, out ds_1112);
								Eq_77133 bx_3238 = (word16) (ss->*((word16) bp_3153 - 66)) + ss->*((word16) bp_3153 - 2) *s 0x0C;
								selector es_3239 = Mem3234[ds_1112:22094:selector];
								es_3239->*((word16) bx_3238 + 0x00003800) |= 0x80;
								ss->*((word16) bp_3153 - 66) = 0x0C;
								Mem3245[ds_1112:0x5676:selector]->b3986 = 0x00;
							}
							struct Eq_74372 Eq_72746::* sp_3254 = sp_3125 - 2;
							(ss->*sp_3254).w0000 = (word16) (ss->*((word16) bp_3153 - 54));
							(ss->*sp_3254).wFFFFFFFE = (word16) (ss->*((word16) bp_3153 - 42));
							fn0800_17BB(si_3227, di_1111, ds_1112, (ss->*sp_3254).wFFFFFFFE, (ss->*sp_3254).w0000, out di_174, out ds_175);
							sp_30.u5 = sp_3254 + 1;
							goto l1AE8_0DC4;
						}
l1AE8_0DDA:
						ss->*((word16) bp_3153 - 66) = (word16) (ss->*((word16) bp_3153 - 66)) + 1;
					}
				}
				ss->*((word16) bp_3153 - 2) = (word16) (ss->*((word16) bp_3153 - 2)) + 1;
			}
			ss->*((word16) bp_3153 - 90) = 0x00;
			do
			{
				Eq_5 ax_492 = ss->*((word16) bp_3153 - 90) *s 0x30;
				si_3326 = ax_492;
				if (Mem490[ds_175:22100:selector]:12998[Mem490[ss:bp_3153 + -90:word16] * 0x30] != ~0x00)
				{
					int16 di_498 = (int16) (ss->*((word16) bp_3153 - 90));
					Mem508[ss:bp_3153 + -80:word16] = CONVERT(Mem490[ds_175:22072:selector]:0x4005[di_498 * 0x02] | Mem490[ds_175:22070:selector]:0x4037[di_498 * 0x02], uint8, uint16);
					Mem512[ss:bp_3153 + -0x0A:word16] = Mem508[ds_175:22072:selector]:0x4004[di_498 * 0x02] & 0x7F;
					Mem516[ss:bp_3153 + -18:word16] = Mem512[ds_175:22070:selector]:0x4036[di_498 * 0x02] & 0x7F;
					struct Eq_74586 * es_517 = Mem516[ds_175:22100:selector];
					di_174 = di_498 << 0x01;
					if ((uint16) es_517->a32C7[0].b0000[ss->*((word16) bp_3153 - 90)].b0000 == ss->*((word16) bp_3153 - 80) && ((int16) (((es_517->a32C7))[0].b0001)[ss->*((word16) bp_3153 - 90)] == ss->*((word16) bp_3153 - 0x0A) && (int16) (((es_517->a32C7))[0].b0002)[ss->*((word16) bp_3153 - 90)] == ss->*((word16) bp_3153 - 18)))
					{
						ss->*((word16) bp_3153 - 94) = 0x00;
						do
						{
							Eq_5 ax_537 = ss->*((word16) bp_3153 - 90) *s 0x30;
							struct Eq_74804 Eq_74586::* di_540 = ss->*((word16) bp_3153 - 94) + ax_537;
							(es_517->*di_540).b32C6 = (es_517->*di_540).b32CA;
							ss->*((word16) bp_3153 - 94) = (word16) (ss->*((word16) bp_3153 - 94)) + 1;
							struct Eq_74828 Eq_74586::* di_547 = ss->*((word16) bp_3153 - 94) + ax_537;
							(es_517->*di_547).b32C6 = (es_517->*di_547).b32CA;
							ss->*((word16) bp_3153 - 94) = (word16) (ss->*((word16) bp_3153 - 94)) + 1;
							struct Eq_74852 Eq_74586::* di_553 = ss->*((word16) bp_3153 - 94) + ax_537;
							(es_517->*di_553).b32C6 = (es_517->*di_553).b32CA;
							ss->*((word16) bp_3153 - 94) = (word16) (ss->*((word16) bp_3153 - 94)) + 1;
							di_174.u5 = ss->*((word16) bp_3153 - 94) + ax_537;
							es_517->*((word32) di_174 + 12998) = es_517->*((word32) di_174 + 13002);
							ss->*((word16) bp_3153 - 94) = (word16) (ss->*((word16) bp_3153 - 94)) + 1;
							si_3326 = ax_537;
						} while (ss->*((word16) bp_3153 - 94) < 44);
						es_517->a32C7[0].b002B[ss->*((word16) bp_3153 - 90)] = (Eq_108453) ~0x00;
					}
				}
				ss->*((word16) bp_3153 - 90) = (word16) (ss->*((word16) bp_3153 - 90)) + 1;
			} while (ss->*((word16) bp_3153 - 90) < 0x0C);
		}
		ss->*((word16) bp_3153 - 4) = (word16) (ss->*((word16) bp_3153 - 4)) + 1;
	}
	if (Mem56[ds_175:0x5630:selector]->w014A != 0x00)
	{
		struct Eq_72844 Eq_72746::* sp_3321 = sp_30 - 2;
		(ss->*sp_3321).t0000.u0 = (wchar_t) (ss->*((word16) bp_3153 - 74));
		(ss->*sp_3321).tFFFFFFFE.u0 = (wchar_t) (ss->*((word16) bp_3153 - 62));
		si_3326 = fn0800_17BB(si_3326, di_174, ds_175, (ss->*sp_3321).tFFFFFFFE.u0, (ss->*sp_3321).t0000.u0, out di_174, out ds_175);
	}
	if (Mem3362[ds_175:0x5630:selector]->w014A != 0x00)
	{
		struct Eq_72952 Eq_72746::* sp_3369 = sp_30 - 2;
		(ss->*sp_3369).w0000 = ss;
		(ss->*sp_3369).tFFFFFFFE.u0 = (wchar_t) (bp_3153 - 0x0078);
		ds_175 = fn1631_0C63(si_3326, di_174, ds_175, (ss->*sp_3369).tFFFFFFFE.u5);
	}
	Eq_5 si_3395;
	si_3395.u5 = (ss->*sp_30.u7).t0000.u1;
	diOut = (ss->*sp_30.u7).w0002;
	dsOut = ds_175;
	return si_3395;
}

// 1AE8:12C7: Register Eq_5 fn1AE8_12C7(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Stack Eq_5 wArg06, Stack Eq_5 wArg08, Stack Eq_5 wArg0A, Stack word16 wArg0C, Stack Eq_5 wArg14, Stack Eq_5 wArg16, Stack Eq_5 wArg18, Register out Eq_5 diOut, Register out Eq_5 dsOut)
// Called from:
//      fn1AE8_000C
Eq_5 fn1AE8_12C7(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, Eq_5 wArg06, Eq_5 wArg08, Eq_5 wArg0A, word16 wArg0C, Eq_5 wArg14, Eq_5 wArg16, Eq_5 wArg18, union Eq_5 & diOut, union Eq_5 & dsOut)
{
	Eq_5 ds_1133;
	Eq_5 di_1132;
	Eq_5 ds_1380;
	Eq_5 di_1379;
	Eq_5 ds_1357;
	Eq_5 di_1356;
	Eq_5 si_1360;
	Eq_5 ds_303;
	Eq_5 di_302;
	Eq_5 ds_287;
	Eq_5 di_286;
	Eq_5 ds_1988;
	Eq_5 di_1987;
	Eq_5 ds_1975;
	Eq_5 di_1974;
	Eq_5 ds_1962;
	Eq_5 di_1961;
	Eq_5 ds_1939;
	Eq_5 di_1938;
	Eq_5 ds_1886;
	Eq_5 di_1885;
	Eq_5 ds_1830;
	Eq_5 di_1829;
	Eq_5 ds_1812;
	Eq_5 di_1811;
	Eq_5 ds_1767;
	Eq_5 di_1766;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_1300;
	Eq_5 di_1063;
	Eq_5 ds_1059;
	fn207F_2FDC(0x32, fp - 2, si, di, ds, wLoc06, wLoc04, out si_1300, out di_1063, out ds_1059);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	selector ss;
	ss->*((word32) sp_18 - 2) = si_1300;
	Eq_36 bp_1457 = fp - 2;
	Eq_5 sp_1306 = sp_18 - 2;
	Eq_5 wLoc26_2225;
	wLoc26_2225.u0 = 0x00;
	if (Mem30[ds_1059:0x5646:selector]->w2E3A == 0x00 || Mem30[ds_1059:0x5630:selector]->w014A == 0x00)
	{
l1AE8_1B0C:
		if (ss->*((word16) bp_1457 + 16) != 0x00)
		{
			struct Eq_78075 Eq_78029::* sp_1526 = sp_1306 - 2;
			(ss->*sp_1526).t0000.u0 = (wchar_t) ds_1059;
			(ss->*sp_1526).tFFFFFFFE.u0 = 0x41FC;
			Eq_5 di_1546;
			Eq_5 ds_1547;
			fn1631_1DAB(si_1300, di_1063, ds_1059, (ss->*sp_1526).tFFFFFFFE.u5, out di_1546, out ds_1547);
			Eq_78099 si_1557 = ss->*((word16) bp_1457 + 8);
			Mem1530[ds_1547:22168:selector]:0x393C[si_1557 * 0x02] = 0x01;
			Mem1560[ds_1547:22066:selector]:0x406A[si_1557 * 0x02] = 0x00;
			Mem1562[ds_1547:22088:selector]:50708[Mem1562[ss:bp_1457 + 20:word16] * 0x11] = ~0x00;
			Mem1570[ds_1547:22082:selector]->*((word16) (ss->*((word16) bp_1457 + 8)) + 0x0000409A) = 0x7E;
			Mem1573[ds_1547:22138:selector]->*((word16) (ss->*((word16) bp_1457 + 8)) + 0x0000D55E) = 0x00;
			Mem1580[ss:sp_1526 + 0x00:word16] = Mem1576[ds_1547:22070:selector]:0x4036[si_1557 * 0x02];
			Mem1584[ss:sp_1526 + -2:word16] = Mem1580[ds_1547:22072:selector]:0x4004[si_1557 * 0x02];
			(ss->*sp_1526).tFFFFFFFC.u0 = 0x7E;
			fn183B_27C9(si_1557 << 0x01, di_1546, ds_1547, (ss->*sp_1526).tFFFFFFFC.u1, (ss->*sp_1526).tFFFFFFFE.u0, (ss->*sp_1526).t0000.u0, out di_1063, out ds_1059);
			ss->*((word16) bp_1457 - 30) = 0x00;
			while (ss->*((word16) bp_1457 - 30) < 0x18)
			{
				ss->*((word16) bp_1457 - 0x0022) = 0x00;
				while (ss->*((word16) bp_1457 - 0x0022) < 0x0C)
				{
					ss->*((word16) bp_1457 - 50) = (word16) (ss->*((word16) bp_1457 - 0x0022)) + ss->*((word16) bp_1457 - 30) *s 0x0C + 0x3800;
					ss->*((word16) bp_1457 - 48) = 0x3092;
					uint8 * es_bx_1642 = (uint8 *) (ss->*((word16) bp_1457 - 50));
					if (((uint16) *es_bx_1642 & 0x7F) == ss->*((word16) bp_1457 + 8))
						*es_bx_1642 = ~0x00;
					ss->*((word16) bp_1457 - 0x0022) = (word16) (ss->*((word16) bp_1457 - 0x0022)) + 1;
				}
				ss->*((word16) bp_1457 - 30) = (word16) (ss->*((word16) bp_1457 - 30)) + 1;
			}
			if (ss->*((word16) bp_1457 + 20) < 0x02)
				Mem1606[ds_1059:0x5630:selector]->w014A = 0x00;
			Eq_78099 si_1617 = ss->*((word16) bp_1457 + 8);
			Mem1616[ds_1059:22070:selector]:0x4036[si_1617 * 0x02] = ~0x00;
			Mem1623[ds_1059:22072:selector]:0x4004[si_1617 * 0x02] = ~0x00;
			si_1300 = si_1617 << 0x01;
		}
		Eq_5 sp_1726 = sp_1306;
		if (ss->*((word16) bp_1457 + 18) != 0x00)
		{
			if (Mem1660[ds_1059:22112:selector]->wE48E == 0x00 || ss->*((word16) bp_1457 + 8) != 0x0D)
			{
				ss->*((word16) bp_1457 + 18) = 0x80;
				Eq_78099 bx_1672 = ss->*((word16) bp_1457 + 8);
				if (Mem1671[ds_1059:22138:selector]->*((word16) bx_1672 + 0x0000D55E) != 0x00)
					ss->*((word16) bp_1457 + 18) = (word16) (ss->*((word16) bp_1457 + 18)) + 1;
				Mem1689[ss:bp_1457 + -30:word16] = Mem1683[ds_1059:22072:selector]:0x4004[bx_1672 * 0x02] - 0x01;
				if ((ss->*((word16) bp_1457 - 30) & 0x80) != 0x00)
					ss->*((word16) bp_1457 - 30) &= 0x0F7F;
				Mem1708[ss:bp_1457 + -0x0022:word16] = Mem1701[ds_1059:22070:selector]:0x4036[Mem1701[ss:bp_1457 + 8:word16] * 0x02] - 0x01;
				if ((ss->*((word16) bp_1457 - 0x0022) & 0x80) != 0x00)
					ss->*((word16) bp_1457 - 0x0022) &= ~0x0F80;
				struct Eq_79083 Eq_78029::* sp_1731 = sp_1306 - 2;
				(ss->*sp_1731).t0000.u0 = (wchar_t) (ss->*((word16) bp_1457 - 0x0022));
				(ss->*sp_1731).tFFFFFFFE.u0 = (wchar_t) (ss->*((word16) bp_1457 - 30));
				(ss->*sp_1731).tFFFFFFFC.u0 = (wchar_t) (ss->*((word16) bp_1457 + 18));
				Eq_5 si_1770 = fn183B_27C9(si_1300, di_1063, ds_1059, (ss->*sp_1731).tFFFFFFFC.u1, (ss->*sp_1731).tFFFFFFFE.u0, (ss->*sp_1731).t0000.u0, out di_1766, out ds_1767);
				(ss->*sp_1731).t0000.u0 = 0x08;
				si_1300 = fn0800_19BF(si_1770, di_1766, ds_1767, (ss->*sp_1731).t0000.u0, out di_1063, out ds_1059);
			}
			sp_1726 = sp_1306;
			if (Mem1797[ds_1059:22112:selector]->wE48E != 0x00 && ss->*((word16) bp_1457 + 8) == 0x0D)
			{
				Eq_5 si_1815 = fn1CD3_17C6(bp_1457, si_1300, di_1063, ds_1059, out di_1811, out ds_1812);
				Eq_5 sp_1816;
				sp_1816.u0 = <invalid>;
				(ss->*((word32) sp_1816 - 2)).u0 = 0x07;
				Eq_5 si_1833 = fn0800_19BF(si_1815, di_1811, ds_1812, ss->*((word32) sp_1816 - 2), out di_1829, out ds_1830);
				ss->*((word32) sp_1816 - 2) = ds_1830;
				(ss->*((word32) sp_1816 - 4)).u0 = 0x4209;
				Eq_5 di_1849;
				Eq_5 ds_1850;
				Eq_5 si_1868;
				Eq_5 di_1864;
				Eq_5 ds_1865;
				fn1F3D_0259(fn1CD3_17EA(si_1833, di_1829, ds_1830, ss->*((word32) sp_1816 - 4), ss->*((word32) sp_1816 - 2), out di_1849, out ds_1850), di_1849, ds_1850, out si_1868, out di_1864, out ds_1865);
				ss->*((word32) sp_1816 - 2) = Mem1845[ds_1865:22070:selector]->t4036;
				ss->*((word32) sp_1816 - 4) = Mem1877[ds_1865:22072:selector]->t4004;
				Eq_5 si_1889 = fn0800_17BB(si_1868, di_1864, ds_1865, ss->*((word32) sp_1816 - 4), ss->*((word32) sp_1816 - 2), out di_1885, out ds_1886);
				ss->*((word32) sp_1816 - 2) = Mem1881[ds_1886:22060:selector]->tA44D;
				ss->*((word32) sp_1816 - 4) = Mem1900[ds_1886:22058:selector]->tA44B;
				fn207F_1314(ss->*((word32) sp_1816 - 4), ss->*((word32) sp_1816 - 2));
				(ss->*((word32) sp_1816 - 2)).u0 = 0x00;
				(ss->*((word32) sp_1816 - 4)).u5 = ss->*((word16) bp_1457 + 26);
				(ss->*((word32) sp_1816 - 6)).u5 = ss->*((word16) bp_1457 + 24);
				fn207F_1ECE(ss->*((word32) sp_1816 - 6), ss->*((word32) sp_1816 - 4), ss->*((word32) sp_1816 - 2));
				Eq_5 si_1942 = fn0800_240B(si_1889, di_1885, ds_1886, out di_1938, out ds_1939);
				fn207F_18EF();
				Eq_5 si_1991 = fn1CD3_17C6(bp_1457, fn1F3D_06C3(bp_1457, fn0800_0E4B(si_1942, di_1938, ds_1939, out di_1961, out ds_1962), di_1961, ds_1962, out di_1974, out ds_1975), di_1974, ds_1975, out di_1987, out ds_1988);
				Eq_5 sp_1992;
				sp_1992.u0 = <invalid>;
				ss->*((word32) sp_1992 - 2) = ds_1988;
				(ss->*((word32) sp_1992 - 4)).u0 = 16949;
				Eq_5 di_2007;
				Eq_5 ds_2008;
				Eq_5 si_2026;
				Eq_5 di_2022;
				Eq_5 ds_2023;
				fn1F3D_0259(fn1CD3_17EA(si_1991, di_1987, ds_1988, ss->*((word32) sp_1992 - 4), ss->*((word32) sp_1992 - 2), out di_2007, out ds_2008), di_2007, ds_2008, out si_2026, out di_2022, out ds_2023);
				ss->*((word16) bp_1457 - 30) = 0x00;
				do
				{
					Eq_5 bx_2036;
					bx_2036.u5 = ss->*((word16) bp_1457 - 30);
					byte al_2039 = (byte) (Mem2035[ds_2023:22170:selector]->*((word32) bx_2036 + 0x065B));
					selector es_2040 = Mem2035[ds_2023:22088:selector];
					(es_2040->*((word32) bx_2036 + 51855)).u5 = al_2039;
					es_2040->*((word16) (ss->*((word16) bp_1457 - 30)) + 0x0000CA12) = al_2039;
					ss->*((word16) bp_1457 - 30) = (word16) (ss->*((word16) bp_1457 - 30)) + 1;
				} while (ss->*((word16) bp_1457 - 30) < 0x7D);
				selector es_2048 = Mem2045[ds_2023:22082:selector];
				es_2048->b40A9 = 0x00;
				es_2048->b40A8 = 0x00;
				selector es_2052 = Mem2051[ds_2023:22138:selector];
				es_2052->bD56D = 0x00;
				es_2052->bD56C = 0x00;
				Mem2054[ds_2023:0x5644:selector]->b392E = 0x04;
				Mem2057[ds_2023:22076:selector]->b397A = 0x04;
				Mem2059[ds_2023:0x5644:selector]->b392F = 0x00;
				Mem2063[ds_2023:22076:selector]->b397B = 0x00;
				selector es_2066 = Mem2065[ds_2023:22080:selector];
				es_2066->w0232 = 0x02A0;
				es_2066->t0234.u0 = 12264;
				es_2066->w022E = 0x02A0;
				es_2066->t0230.u0 = 12264;
				selector es_2073 = Mem2072[ds_2023:22066:selector];
				es_2073->w4088 = 0x01;
				es_2073->w4086 = 0x01;
				Mem2076[ds_2023:22112:selector]->wE48E = 0x00;
				Mem2078[ds_2023:22088:selector]->bD32F = 0x01;
				selector es_2081 = Mem2080[ds_2023:22072:selector];
				es_2081->w4022 = 2429;
				es_2081->w4020 = 2429;
				selector es_2085 = Mem2084[ds_2023:22070:selector];
				es_2085->w4052 = 0x8030;
				es_2085->w4054 = 0x8070;
				(ss->*((word32) sp_1992 - 2)).u0 = 0x04;
				fn1E56_0281(si_2026, di_2022, ds_2023, ss->*((word32) sp_1992 - 2), out di_1063, out ds_1059);
				sp_1726 = sp_1992;
			}
			Eq_78099 si_2113 = ss->*((word16) bp_1457 + 8);
			Mem2112[ds_1059:22070:selector]:0x4036[si_2113 * 0x02] = ~0x00;
			Mem2119[ds_1059:22072:selector]:0x4004[si_2113 * 0x02] = ~0x00;
			Mem2121[ds_1059:22066:selector]:0x406A[si_2113 * 0x02] = 0x00;
		}
		if (Mem2125[ds_1059:0x5646:selector]->w2E3A != 0x00)
			Mem2125[ds_1059:22076:selector]->*((word16) (ss->*((word16) bp_1457 + 6)) + 14700) = ~0x00;
		Eq_5 si_2140;
		si_2140.u5 = (ss->*sp_1726.u7).t0000.u1;
		diOut = di_1063;
		dsOut = ds_1059;
		return si_2140;
	}
	int16 ax_39 = (int16) Mem30[ds_1059:22088:selector]->bC620;
	int16 wLoc1A_2226 = ax_39;
	if (ax_39 >= 0x08)
		wLoc1A_2226 = 0x04;
	Eq_5 ax_51 = Mem46[ds_1059:22072:selector]:0x4004[wLoc1A_2226 * 0x02];
	Eq_5 ax_54 = Mem52[ds_1059:22070:selector]:0x4036[wLoc1A_2226 * 0x02];
	selector es_57 = Mem55[ds_1059:22076:selector];
	if (es_57->*((word32) wArg04 + 14700) != ~0x00)
		Mem55[ds_1059:0x5666:selector]->*((word32) wArg04 + 0x000045B6) = es_57->*((word32) wArg04 + 14700);
	Eq_5 si_105;
	word16 ax_101;
	word16 dx_102;
	if (wArg04 >= 0x04 && (wArg04 < 0x0C || wArg04 >= 0x10))
	{
		si_105 = wArg08 << 0x05;
		ax_101 = ((word16) (wArg0A << 0x02) + 0x00003FF8)[wArg08].w0000;
		dx_102 = ((word16) (wArg0A << 0x02) + 0x00003FFA)[wArg08].w0000;
	}
	else if (wArg08 != 0x20)
	{
		struct Eq_78899 * es_106 = Mem82[ds_1059:22136:selector];
		word16 dx_108 = (word16) es_106->a2D58[0].w0002[wArg0A];
		struct Eq_73725 * es_111 = Mem82[ds_1059:22080:selector];
		es_111->a01F6[0].w0000[wArg04].w0000 = es_106->a2D58[0].w0000[wArg0A].w0000;
		es_111->a01F6[0].w0002[wArg04].w0000 = dx_108;
		si_105 = wArg0A << 0x02;
		if (Mem113[ds_1059:22138:selector]->*((word32) wArg04 + 0x0000D55E) == 0x00)
			goto l1AE8_142F;
		struct Eq_78899 * es_118 = Mem113[ds_1059:22136:selector];
		ax_101 = es_118->a2D78[0].w0000[wArg0A].w0000;
		dx_102 = (word16) es_118->a2D78[0].w0002[wArg0A];
	}
	else
	{
		struct Eq_78859 * es_88 = Mem82[ds_1059:22140:selector];
		word16 dx_90 = (word16) es_88->a2D98[0].w0002[wArg0A];
		struct Eq_73725 * es_93 = Mem82[ds_1059:22080:selector];
		es_93->a01F6[0].w0000[wArg04].w0000 = es_88->a2D98[0].w0000[wArg0A].w0000;
		es_93->a01F6[0].w0002[wArg04].w0000 = dx_90;
		si_105 = wArg0A << 0x02;
		if (Mem95[ds_1059:22138:selector]->*((word32) wArg04 + 0x0000D55E) == 0x00)
			goto l1AE8_142F;
		struct Eq_78859 * es_100 = Mem95[ds_1059:22140:selector];
		ax_101 = es_100->a2DB8[0].w0000[wArg0A].w0000;
		dx_102 = (word16) es_100->a2DB8[0].w0002[wArg0A];
	}
	struct Eq_73725 * es_141 = Mem140[ds_1059:22080:selector];
	es_141->a01F6[0].w0000[wArg04].w0000 = ax_101;
	es_141->a01F6[0].w0002[wArg04].w0000 = dx_102;
l1AE8_142F:
	if (wArg08 == 0x0A || wArg08 == 11)
	{
		wArg0C = 0x00;
		if (wArg06 < 0x04 || wArg06 >= 0x0C && wArg06 < 0x10)
			wLoc26_2225.u0 = 0x01;
	}
	if (wArg08 >= 0x19 && wArg08 <= 0x1F)
		wArg0C = 0x00;
	if (wArg0C != 0x00)
	{
		selector es_186 = Mem177[ds_1059:22076:selector];
		if (es_186->*((word32) wArg06 + 14700) != ~0x00)
			Mem177[ds_1059:0x5666:selector]->*((word32) wArg06 + 0x000045B6) = es_186->*((word32) wArg06 + 14700);
		struct Eq_73725 * es_200 = Mem194[ds_1059:22080:selector];
		es_200->a01F6[0].w0000[wArg06].w0000 = 11836;
		es_200->a01F6[0].w0002[wArg06].u0 = 16091;
	}
	while (Mem205[Mem205[ds_1059:22080:selector]:0x01F6[wArg04 *16 0x04] + 0x00:byte] != ~0x00)
	{
		ss->*((word32) sp_18 - 4) = wArg04;
		Eq_5 ds_227;
		(Mem219[ds_227:22082:selector]->*((word32) wArg04 + 0x0000409A)).u5 = (byte) fn0800_1732(si_105, di_1063, ds_1059, ss->*((word32) sp_18 - 4), out si_105, out di_1063, out ds_227);
		ds_1059 = ds_227;
		if (wArg0C != 0x00)
		{
			ss->*((word32) sp_18 - 4) = wArg06;
			Eq_5 ds_250;
			(Mem245[ds_250:22082:selector]->*((word32) wArg06 + 0x0000409A)).u5 = (byte) fn0800_1732(si_105, di_1063, ds_227, ss->*((word32) sp_18 - 4), out si_105, out di_1063, out ds_250);
			ds_1059 = ds_250;
		}
		if (Mem267[ds_1059:22142:selector]->*((word32) wArg04 + 17142) != 0x00)
		{
			ss->*((word32) sp_18 - 4) = wArg18;
			ss->*((word32) sp_18 - 6) = wArg16;
			Eq_5 si_306 = fn1F3D_06C3(fp - 2, fn1631_1F09(si_105, di_1063, ds_1059, ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4), out di_286, out ds_287), di_286, ds_287, out di_302, out ds_303);
			(ss->*((word32) sp_18 - 4)).u0 = 0x05;
			si_105 = fn1F3D_0006(si_306, di_302, ds_303, ss->*((word32) sp_18 - 4), out di_1063, out ds_1059);
		}
	}
	if (wArg08 < 0x03)
	{
		(ss->*((word32) sp_18 - 4)).u0 = 0x0D;
		si_105 = fn0800_19BF(si_105, di_1063, ds_1059, ss->*((word32) sp_18 - 4), out di_1063, out ds_1059);
	}
	if (wArg08 == 0x17 || (wArg08 == 0x09 || wArg08 >= 0x13 && wArg08 <= 22))
	{
		(ss->*((word32) sp_18 - 4)).u0 = 0x03;
		si_105 = fn0800_19BF(si_105, di_1063, ds_1059, ss->*((word32) sp_18 - 4), out di_1063, out ds_1059);
	}
	if (wArg08 == 0x03)
	{
		(ss->*((word32) sp_18 - 4)).u0 = 0x05;
		si_105 = fn0800_19BF(si_105, di_1063, ds_1059, ss->*((word32) sp_18 - 4), out di_1063, out ds_1059);
	}
	if (wArg08 == 0x07 || wArg08 == 0x08)
	{
		(ss->*((word32) sp_18 - 4)).u0 = 0x06;
		si_105 = fn0800_19BF(si_105, di_1063, ds_1059, ss->*((word32) sp_18 - 4), out di_1063, out ds_1059);
	}
	if (wArg08 >= 0x04 && wArg08 <= 0x06)
	{
		(ss->*((word32) sp_18 - 4)).u0 = 11;
		si_105 = fn0800_19BF(si_105, di_1063, ds_1059, ss->*((word32) sp_18 - 4), out di_1063, out ds_1059);
	}
	word16 wLoc1A_2295 = 0x00;
	if (wArg08 == 0x0A || wArg08 == 11)
		wLoc1A_2295 = 0x01;
	if (wArg08 >= 0x19 && wArg08 <= 0x1F)
		wLoc1A_2295 = 0x01;
	word16 wLoc0A_2301 = 0x00;
	Eq_5 wLoc2E;
	if (wArg08 == 0x0C || wArg08 == 0x0D)
	{
		wLoc1A_2295 = 0x02;
		wLoc2E.u0 = 0x0E;
		if (wArg04 >= 0x10)
			wLoc2E.u0 = 0x0A;
		if (Mem524[ds_1059:22144:selector]->w4FBA == 0x00)
			wLoc2E.u0 = 0x03;
		wLoc0A_2301 = 0x01;
	}
	if (wArg08 >= 0x0F && wArg08 <= 0x12)
	{
		wLoc1A_2295 = 0x03;
		wLoc2E.u0 = 0x0C;
		if (wArg04 >= 0x0C)
		{
			wLoc2E.u0 = 0x05;
			if (wArg06 == 0x00 && Mem553[ds_1059:22138:selector]->*((word32) wArg04 + 0x0000D55E) != 0x00)
				wLoc26_2225.u0 = 0x03;
		}
		else if (Mem542[ds_1059:22138:selector]->*((word32) wArg04 + 0x0000D55E) == 0x00)
			wLoc26_2225.u0 = 0x04;
		else
			wLoc26_2225.u0 = 0x07;
		if (Mem562[ds_1059:22144:selector]->w4FBA == 0x00)
			wLoc2E.u0 = 0x02;
	}
	if (wLoc1A_2295 == 0x00)
	{
l1AE8_1A07:
		Eq_5 sp_1465;
		if (wArg14 == 0x00)
		{
			ss->*((word32) sp_18 - 4) = wArg18;
			ss->*((word32) sp_18 - 6) = wArg16;
			sp_1465 = sp_18 - 6;
			si_1300 = fn1631_1F09(si_105, di_1063, ds_1059, ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4), out di_1063, out ds_1059);
		}
		else
		{
			(ss->*((word32) sp_18 - 4)).u0 = 0x04;
			si_1300 = fn0800_19BF(si_105, di_1063, ds_1059, ss->*((word32) sp_18 - 4), out di_1063, out ds_1059);
			sp_1306 = sp_18 - 0x02;
			if (wArg08 < 0x07 || Mem1287[ds_1059:22142:selector]->*((word32) wArg06 + 17142) == 0x00)
				goto l1AE8_1AEB;
			selector es_1313 = Mem1287[ds_1059:22080:selector];
			es_1313->t0256.u0 = 16856;
			es_1313->t0258 = ds_1059;
			Eq_5 ax_1323 = Mem1321[ds_1059:22148:selector]:12924[wArg06 *16 0x02];
			Eq_5 si_1318 = wArg06 << 0x01;
			Eq_5 ax_1320 = Mem1316[ds_1059:22146:selector]:0x324C[wArg06 *16 0x02];
			Eq_5 wLoc24_2777 = ax_1323;
			if (wArg06 < 0x04 || wArg06 >= 0x0C && wArg06 < 0x10)
				wLoc24_2777 = ax_1323 - 0x08;
			while (*Mem1338[ds_1059:22080:selector]->t0256.u1 != ~0x00)
			{
				(ss->*((word32) sp_18 - 4)).u0 = 0x18;
				word16 ax_1353 = fn0800_1732(si_1318, di_1063, ds_1059, ss->*((word32) sp_18 - 4), out si_1360, out di_1356, out ds_1357);
				ss->*((word32) sp_18 - 4) = wArg18;
				ss->*((word32) sp_18 - 6) = wArg16;
				Eq_5 si_1383 = fn1631_1F09(si_1360, di_1356, ds_1357, ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4), out di_1379, out ds_1380);
				ss->*((word32) sp_18 - 4) = wLoc24_2777;
				ss->*((word32) sp_18 - 6) = ax_1320;
				ss->*((word32) sp_18 - 8) = ax_1353 + 0xFA;
				Eq_5 di_1405;
				Eq_5 ds_1406;
				si_1318 = fn1F3D_06C3(fp - 2, fn1631_1F73(si_1383, di_1379, ds_1380, ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4), out di_1405, out ds_1406), di_1405, ds_1406, out di_1063, out ds_1059);
			}
			(ss->*((word32) sp_18 - 4)).u0 = 0x05;
			si_1300 = fn1F3D_0006(si_1318, di_1063, ds_1059, ss->*((word32) sp_18 - 4), out di_1063, out ds_1059);
			sp_1306 = sp_18 - 0x02;
			if (wLoc26_2225 == 0x00)
			{
l1AE8_1AEB:
				if (ss->*((word16) bp_1457 + 6) < 0x04 || ss->*((word16) bp_1457 + 6) >= 0x0C && ss->*((word16) bp_1457 + 6) < 0x10)
					Mem1499[ds_1059:22082:selector]->*((word16) (ss->*((word16) bp_1457 + 6)) + 0x0000409A) = ss->*((word16) bp_1457 - 0x0C);
				goto l1AE8_1B0C;
			}
			(ss->*((word32) sp_18 - 4)).u0 = 0x00;
			ss->*((word32) sp_18 - 6) = wLoc26_2225;
			bp_1457 = fn0800_48B7(si_1300, di_1063, ds_1059, ss->*((word32) sp_18 - 6), out si_1300, out di_1063, out ds_1059);
			sp_1465.u0 = <invalid>;
		}
		sp_1306.u5 = (word32) sp_1465 + 4;
		goto l1AE8_1AEB;
	}
	if (wLoc1A_2295 == 0x01)
	{
		(ss->*((word32) sp_18 - 4)).u0 = 0x01;
		si_105 = fn0800_19BF(si_105, di_1063, ds_1059, ss->*((word32) sp_18 - 4), out di_1063, out ds_1059);
	}
	selector es_640 = Mem637[ds_1059:22142:selector];
	if (es_640->*((word32) wArg04 + 17142) == 0x00 && es_640->*((word32) wArg06 + 17142) == 0x00)
		goto l1AE8_1A07;
	Eq_5 wLoc20_2421;
	Eq_5 ax_698;
	if (es_640->*((word32) wArg04 + 17142) != 0x00)
	{
		wLoc20_2421 = Mem637[ds_1059:22146:selector]:0x324C[wArg04 *16 0x02];
		ax_698 = Mem705[ds_1059:22148:selector]:12924[wArg04 *16 0x02];
	}
	else
	{
		Mem662[ss:sp_18 + -4:word16] = Mem637[ds_1059:22070:selector]:0x4036[wArg04 *16 0x02];
		Mem666[ss:sp_18 + -6:word16] = Mem662[ds_1059:22072:selector]:0x4004[wArg04 *16 0x02];
		ss->*((word32) sp_18 - 8) = ax_54;
		ss->*((word32) sp_18 - 0x0A) = ax_51;
		fn1631_1DF8(wArg04 << 0x01, di_1063, ds_1059, ss->*((word32) sp_18 - 0x0A), ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4), out di_1063, out ds_1059);
		wLoc20_2421 = Mem672[ds_1059:0x5686:selector]->wE486 << 0x03;
		ax_698 = Mem695[ds_1059:22152:selector]->wE488 << 0x03;
	}
	Eq_5 wLoc24_2423 = ax_698;
	Eq_5 wLoc22_2428;
	Eq_5 ax_758;
	if (Mem711[ds_1059:22142:selector]->*((word32) wArg06 + 17142) != 0x00)
	{
		si_105 = wArg06 << 0x01;
		wLoc22_2428 = Mem711[ds_1059:22146:selector]:0x324C[wArg06 *16 0x02];
		ax_758 = Mem765[ds_1059:22148:selector]:12924[wArg06 *16 0x02];
	}
	else
	{
		Mem724[ss:sp_18 + -4:word16] = Mem711[ds_1059:22070:selector]:0x4036[wArg06 *16 0x02];
		Mem728[ss:sp_18 + -6:word16] = Mem724[ds_1059:22072:selector]:0x4004[wArg06 *16 0x02];
		ss->*((word32) sp_18 - 8) = ax_54;
		ss->*((word32) sp_18 - 0x0A) = ax_51;
		si_105 = fn1631_1DF8(wArg06 << 0x01, di_1063, ds_1059, ss->*((word32) sp_18 - 0x0A), ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4), out di_1063, out ds_1059);
		wLoc22_2428 = Mem734[ds_1059:0x5686:selector]->wE486 << 0x03;
		ax_758 = Mem755[ds_1059:22152:selector]->wE488 << 0x03;
	}
	Eq_5 wLoc2A_2430 = ax_758;
	if (wArg06 < 0x04 || wArg06 >= 0x0C && wArg06 < 0x10)
		wLoc2A_2430 = ax_758 - 0x08;
	if (wLoc1A_2295 != 0x01)
	{
		wLoc22_2428.u5 = (word32) wLoc22_2428 + 3;
		wLoc2A_2430.u5 = (word32) wLoc2A_2430 + 3;
		int8 al_814;
		if (wArg04 >= 0x04 && (wArg04 < 0x0C || wArg04 >= 0x10))
		{
			wLoc20_2421.u5 = (word16) wLoc20_2421.u2 + (int16) (Mem792[ds_1059:22162:selector]->*((word32) wArg0A + 11592));
			al_814 = (int8) (Mem811[ds_1059:22164:selector]->*((word32) wArg0A + 11600));
		}
		else if (Mem792[ds_1059:22138:selector]->*((word32) wArg04 + 0x0000D55E) == 0x00)
		{
			wLoc20_2421.u5 = (word16) wLoc20_2421.u2 + (int16) (Mem792[ds_1059:22154:selector]->*((word32) wArg0A + 0x00002D28));
			al_814 = (int8) (Mem837[ds_1059:22156:selector]->*((word32) wArg0A + 11568));
		}
		else
		{
			wLoc20_2421.u5 = (word16) wLoc20_2421.u2 + (int16) (Mem792[ds_1059:22158:selector]->*((word32) wArg0A + 11576));
			al_814 = (int8) (Mem828[ds_1059:0x5690:selector]->*((word32) wArg0A + 11584));
		}
		wLoc24_2423.u5 = ax_698.u5 + (int16) al_814;
	}
	struct Eq_79980 * es_857 = Mem851[ds_1059:22166:selector];
	Eq_5 dx_859;
	dx_859.u0 = es_857->a2DDA[0].u5[wArg0A].u0;
	selector es_860 = Mem851[ds_1059:22080:selector];
	es_860->t0256.u0 = es_857->a2DD8[0].u1[wArg0A].u0;
	es_860->t0258 = dx_859;
	ss->*((word32) sp_18 - 4) = wLoc20_2421 - wLoc22_2428;
	if (fn207F_3C6C(ss->*((word32) sp_18 - 4)) <= 0x08)
	{
		ss->*((word32) sp_18 - 4) = wLoc24_2423 - wLoc2A_2430;
		if (fn207F_3C6C(ss->*((word32) sp_18 - 4)) <= 0x08)
			goto l1AE8_19EA;
	}
	Eq_5 ax_900 = wLoc24_2423 - wLoc2A_2430;
	ss->*((word32) sp_18 - 4) = ax_900;
	int16 ax_910 = fn207F_3C6C(ss->*((word32) sp_18 - 4));
	Eq_5 ax_903 = wLoc22_2428 - wLoc20_2421;
	ss->*((word32) sp_18 - 4) = ax_903;
	int16 ax_921 = fn207F_3C6C(ss->*((word32) sp_18 - 4));
	int16 wLoc28_2519 = ax_910;
	int16 wLoc2C_2520 = ax_921;
	if (ax_921 > ax_910)
	{
		wLoc2C_2520 = ax_910;
		wLoc28_2519 = ax_921;
	}
	ss->*((word32) sp_18 - 4) = ax_903;
	ss->*((word32) sp_18 - 6) = ax_900;
	struct Eq_80150 * ds_ax_3343 = fn1631_1EA2(si_105, di_1063, ds_1059, ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4), out si_105, out di_1063);
	int16 ax_996 = (int16) ds_ax_3343->b41DC;
	int16 ax_999 = (int16) ds_ax_3343->b41E4;
	int16 ax_1002 = (int16) ds_ax_3343->b41EC;
	int16 ax_1005 = (int16) ds_ax_3343->b41F4;
	ds_1059.u5 = SLICE(ds_ax_3343, selector, 16);
	int16 wLoc1C_2528 = wLoc28_2519 >> 0x01;
	int16 wLoc30_2529 = ax_996;
	int16 wLoc04_2530 = ax_999;
	int16 wLoc08_2531 = ax_1002;
	int16 wLoc0C_2532 = ax_1005;
	if (wLoc1A_2295 == 0x01)
	{
		wLoc30_2529 = ax_996 << 0x02;
		wLoc04_2530 = ax_999 << 0x02;
		wLoc08_2531 = ax_1002 << 0x02;
		wLoc0C_2532 = ax_1005 << 0x02;
	}
	while (true)
	{
		byte bLoc06_2555 = (byte) wLoc06;
		if (wLoc20_2421 == wLoc22_2428 && wLoc24_2423 == wLoc2A_2430)
			break;
		if (wLoc1A_2295 == 0x01)
		{
			(ss->*((word32) sp_18 - 4)).u0 = 0x18;
			word16 ax_1084 = fn0800_1732(si_105, di_1063, ds_1059, ss->*((word32) sp_18 - 4), out si_105, out di_1063, out ds_1059);
			if (wLoc20_2421 >= 0x68 && (wLoc20_2421 < 0x0140 && (wLoc24_2423 >= 0x00 && wLoc24_2423 < 200)))
			{
				if (Mem1099[ds_1059:22144:selector]->w4FBA != 0x01 || (bLoc06_2555 & 0x03) == 0x00)
				{
					ss->*((word32) sp_18 - 4) = wArg18;
					ss->*((word32) sp_18 - 6) = wArg16;
					Eq_5 si_1136 = fn1631_1F09(si_105, di_1063, ds_1059, ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4), out di_1132, out ds_1133);
					ss->*((word32) sp_18 - 4) = wLoc24_2423;
					ss->*((word32) sp_18 - 6) = wLoc20_2421;
					ss->*((word32) sp_18 - 8) = ax_1084 + 0x68;
					Eq_5 di_1157;
					Eq_5 ds_1158;
					si_105 = fn1F3D_06C3(fp - 2, fn1631_1F73(si_1136, di_1132, ds_1133, ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4), out di_1157, out ds_1158), di_1157, ds_1158, out di_1063, out ds_1059);
				}
				wLoc06 = SEQ(SLICE(wLoc06 + 0x01, byte, 8), bLoc06_2555 + 0x01);
			}
		}
		else if (wLoc20_2421 >= 0x68 && (wLoc20_2421 < 0x0140 && (wLoc24_2423 >= 0x00 && wLoc24_2423 < 200)))
		{
			ss->*((word32) sp_18 - 4) = wLoc2E;
			ss->*((word32) sp_18 - 6) = wLoc24_2423;
			ss->*((word32) sp_18 - 8) = wLoc20_2421;
			ss->*((word32) sp_18 - 0x0A) = wLoc24_2423;
			ss->*((word32) sp_18 - 0x0C) = wLoc20_2421;
			si_105 = fn1F3D_031C(si_105, di_1063, ds_1059, ss->*((word32) sp_18 - 0x0C), ss->*((word32) sp_18 - 0x0A), ss->*((word32) sp_18 - 8), ss->*((word32) sp_18 - 6), ss->*((word32) sp_18 - 4), out di_1063, out ds_1059);
		}
		if (wLoc20_2421 != wLoc22_2428)
			wLoc20_2421.u5 = (word16) wLoc20_2421.u2 + wLoc30_2529;
		if (wLoc24_2423 != wLoc2A_2430)
			wLoc24_2423.u5 = (word16) wLoc24_2423.u2 + wLoc04_2530;
		int16 v91_1212 = wLoc1C_2528 - wLoc2C_2520;
		wLoc1C_2528 = v91_1212;
		if (v91_1212 < 0x00)
		{
			if (wLoc20_2421 != wLoc22_2428)
				wLoc20_2421.u5 = (word16) wLoc20_2421.u2 + wLoc08_2531;
			if (wLoc24_2423 != wLoc2A_2430)
				wLoc24_2423.u5 = (word16) wLoc24_2423.u2 + wLoc0C_2532;
			wLoc1C_2528 = v91_1212 + wLoc28_2519;
		}
	}
l1AE8_19EA:
	if (wLoc1A_2295 != 0x01)
	{
		Eq_5 ax_1247;
		if (wLoc0A_2301 == 0x00)
			ax_1247.u0 = 0x02;
		else
			ax_1247.u0 = 0x09;
		ss->*((word32) sp_18 - 4) = ax_1247;
		si_105 = fn0800_19BF(si_105, di_1063, ds_1059, ss->*((word32) sp_18 - 4), out di_1063, out ds_1059);
	}
	goto l1AE8_1A07;
}

// 1AE8:1E46: Register Eq_5 fn1AE8_1E46(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Stack Eq_5 wArg06, Stack Eq_5 wArg08, Register out Eq_5 diOut, Register out Eq_5 dsOut)
// Called from:
//      fn1AE8_000C
Eq_5 fn1AE8_1E46(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, Eq_5 wArg06, Eq_5 wArg08, union Eq_5 & diOut, union Eq_5 & dsOut)
{
	Eq_5 ds_113;
	Eq_5 di_112;
	word16 si_185;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	Eq_5 di_19;
	Eq_5 ds_20;
	fn207F_2FDC(0x06, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	selector ss;
	ss->*((word32) sp_18 - 2) = si_22;
	Eq_27220 ax_30 = fn0800_19DD(fp - 2, si_22, di_19, ds_20, out si_185, out di_112, out ds_113);
	Eq_5 sp_38;
	sp_38.u0 = <invalid>;
	if (ax_30 < 0x05 || ax_30 > 0x09)
	{
		Eq_5 ax_57 = Mem44[ds_113:22072:selector]:0x4004[wArg04 *16 0x02] + wArg06;
		Eq_5 ax_61 = Mem58[ds_113:22070:selector]:0x4036[wArg04 *16 0x02] + wArg08;
		Eq_5 wLoc06_140 = ax_57;
		byte bLoc08_147 = (byte) ax_61;
		if (((byte) ax_57 & 0x80) != 0x00)
			wLoc06_140 = ax_57 & 0x0F7F;
		Eq_5 wLoc08_150 = ax_61;
		if ((bLoc08_147 & 0x80) != 0x00)
			wLoc08_150 = ax_61 & ~0x0F80;
		ss->*((word32) sp_38 - 2) = wLoc08_150;
		ss->*((word32) sp_38 - 4) = wLoc06_140;
		(ss->*((word32) sp_38 - 6)).u0 = 0x7C;
		fn183B_27C9(wArg04 << 0x01, di_112, ds_113, ss->*((word32) sp_38 - 6), ss->*((word32) sp_38 - 4), ss->*((word32) sp_38 - 2), out di_112, out ds_113);
	}
	Eq_5 si_127;
	si_127.u5 = (ss->*sp_38.u7).t0000.u1;
	diOut = di_112;
	dsOut = ds_113;
	return si_127;
}

