// UNBTECH_1467.c
// Generated by decompiling UNBTECH.exe
// using Reko decompiler version 0.12.2.0.

#include "UNBTECH.h"

// 1467:0002: Register Eq_5 fn1467_0002(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Register out word16 diOut, Register out Eq_5 dsOut)
// Called from:
//      fn0800_4D57
//      fn1CD3_0004
Eq_5 fn1467_0002(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, word16 & diOut, union Eq_5 & dsOut)
{
	Eq_5 ds_753;
	Eq_5 di_752;
	Eq_5 ds_734;
	Eq_5 di_733;
	Eq_5 ds_687;
	Eq_5 di_686;
	Eq_5 ds_558;
	Eq_5 di_557;
	Eq_5 ds_543;
	Eq_5 di_542;
	Eq_5 ds_1529;
	Eq_5 di_1528;
	Eq_5 ds_1455;
	Eq_5 di_1454;
	Eq_5 ds_1321;
	Eq_5 di_1320;
	word16 si_2254;
	Eq_5 ds_1058;
	Eq_5 di_1057;
	Eq_5 ds_1042;
	Eq_5 di_1041;
	Eq_5 si_492;
	Eq_5 ds_151;
	Eq_5 di_150;
	Eq_5 ds_135;
	Eq_5 di_134;
	Eq_49538 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	Eq_5 di_129;
	Eq_5 ds_127;
	fn207F_2FDC(0x32, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_129, out ds_127);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	Eq_5 ss;
	ss->*((word32) sp_18 - 2) = di_129;
	ss->*((word32) sp_18 - 4) = si_22;
	Eq_5 sp_123 = sp_18 - 4;
	if (wArg04 != 0x00)
	{
		int16 wLoc28_1934 = 0x00;
		struct Eq_49571 * es_96;
		int16 v15_98;
		do
		{
			es_96 = Mem91[ds_127:0x5528:selector];
			es_96->aC614[0].b000C[wLoc28_1934] = (Eq_107529) 0x08;
			v15_98 = wLoc28_1934 + 0x01;
			wLoc28_1934 = v15_98;
		} while (v15_98 < 0x08);
		int16 wLoc28_1937;
		for (wLoc28_1937 = 0x00; wLoc28_1937 < 0x04; ++wLoc28_1937)
		{
			es_96->aC724[0].b007A[wLoc28_1937].b0000 = ~0x00;
			es_96->aC724[0].b0079[wLoc28_1937].b0000 = ~0x00;
		}
	}
	else
	{
		int16 wLoc28_1922 = 0x00;
		int16 v23_83;
		do
		{
			byte bLoc28_1924 = (byte) wLoc28_1922;
			struct Eq_49571 * es_43 = Mem38[ds_127:0x5528:selector];
			if (es_43->aC724[0].b0000[wLoc28_1922].b0000 != ~0x00)
			{
				byte bLoc28_1929 = (byte) wLoc28_1922;
				if (es_43->aC724[0].b0079[wLoc28_1922] != ~0x00)
					es_43->aC614[0].b000C[es_43->aC724[0].b0079[wLoc28_1922].b0000].b0000 = bLoc28_1924;
				bui8 al_66 = (bui8) es_43->aC724[0].b007A[wLoc28_1922];
				if (al_66 != ~0x00)
					es_43->aC614[0].b000C[al_66].b0000 = bLoc28_1929;
			}
			v23_83 = wLoc28_1922 + 0x01;
			wLoc28_1922 = v23_83;
		} while (v23_83 < 0x04);
	}
	int16 wLoc28_1939 = 0x00;
	int16 v22_117;
	Eq_5 si_115;
	do
	{
		(&&(ss->*(ss->*(fp - 26)).u0))[wLoc28_1939].u1 = ~0x00;
		v22_117 = wLoc28_1939 + 0x01;
		si_115 = wLoc28_1939 << 0x01;
		wLoc28_1939 = v22_117;
	} while (v22_117 < 0x08);
	word16 wLoc20_1942 = 0x00;
	do
	{
		struct Eq_50609 Eq_5::* sp_124 = sp_123 - 2;
		(ss->*sp_124).t0000.u0 = 0x06;
		Eq_5 si_154 = fn1E56_0388(fp - 2, fn1E56_0281(si_115, di_129, ds_127, (ss->*sp_124).t0000.u0, out di_134, out ds_135), di_134, ds_135, out di_150, out ds_151);
		Eq_5 sp_155;
		sp_155.u0 = <invalid>;
		(ss->*((word32) sp_155 - 2)).u0 = 0x00;
		Eq_5 di_168;
		Eq_5 ds_169;
		Eq_5 si_188;
		Eq_5 di_184;
		Eq_5 ds_185;
		fn0800_28A2(fp - 2, fn1E56_0004(si_154, di_150, ds_151, ss->*((word32) sp_155 - 2), out di_168, out ds_169), di_168, ds_169, out si_188, out di_184, out ds_185);
		ss->*((word32) sp_155 - 2) = ds_185;
		(ss->*((word32) sp_155 - 4)).u0 = 0x2622;
		Eq_5 si_1838;
		Eq_5 di_1834;
		Eq_5 ds_1835;
		fn1E56_03F5(si_188, di_184, ds_185, ss->*((word32) sp_155 - 4), out si_1838, out di_1834, out ds_1835);
		Mem198[ds_1835:0x552C:selector]->w0202 = Mem198[ds_1835:0x552A:selector]->w374E;
		Eq_5 wLoc22_1943;
		wLoc22_1943.u0 = 0x00;
		Eq_5 wLoc28_1944;
		wLoc28_1944.u0 = 0x00;
		while (wLoc28_1944 < 0x08)
		{
			int8 al_1663 = Mem223[ds_1835:0x5528:selector]:50708[wLoc28_1944 *16 0x11];
			if (al_1663 != ~0x00)
			{
				(&&(ss->*(ss->*(fp - 26)).u0))[wLoc22_1943].u1 = (struct Eq_109213 *) wLoc28_1944;
				int16 ax_1674 = (int16) al_1663;
				struct Eq_49738 * es_1679 = Mem1672[ds_1835:0x552E:selector];
				(ss->*((word32) sp_155 - 2)).u0 = es_1679->a01CC[0].u5[ax_1674].u0;
				(ss->*((word32) sp_155 - 4)).u0 = es_1679->a01CA[0].u5[ax_1674].u0;
				Eq_5 si_1693;
				Eq_5 di_1689;
				Eq_5 ds_1690;
				fn1E56_03F5(wLoc22_1943 << 0x01, di_1834, ds_1835, ss->*((word32) sp_155 - 4), out si_1693, out di_1689, out ds_1690);
				wLoc22_1943.u5 = (word32) wLoc22_1943 + 1;
				int16 ax_1706 = CONVERT(Mem1685[ds_1690:0x5528:selector]:0xC620[wLoc28_1944 *16 0x11], int8, int16);
				Eq_5 ax_1710;
				if (ax_1706 != 0x08)
				{
					Mem1707[ds_1690:0x5530:selector]->b0012 = 0x20;
					(ss->*((word32) sp_155 - 2)).u0 = 0x3092;
					ss->*((word32) sp_155 - 4) = ax_1706 *s 0x7D + 50980;
					(ss->*((word32) sp_155 - 6)).u0 = 0x3092;
					(ss->*((word32) sp_155 - 8)).u0 = 0x13;
					fn207F_3B68(ss->*((word32) sp_155 - 8), ss->*((word32) sp_155 - 4));
					(ss->*((word32) sp_155 - 2)).u0 = 0x3092;
					(ss->*((word32) sp_155 - 4)).u0 = 0x12;
					struct Eq_49842 Eq_49791::* wLoc2C_2110;
					for (wLoc2C_2110 = fn207F_3B9E(ss->*((word32) sp_155 - 4)) - 0x01; wLoc2C_2110 != &Eq_49791::t0000; --wLoc2C_2110)
					{
						selector es_1769 = Mem1764[ds_1690:0x5530:selector];
						if (wLoc2C_2110[18] == 0x20)
							wLoc2C_2110[18] = (struct Eq_49842) 0x00;
						else
							wLoc2C_2110 = &Eq_49791::t0001;
					}
					(ss->*((word32) sp_155 - 2)).u0 = 0x3092;
					(ss->*((word32) sp_155 - 4)).u0 = 0x12;
					fn1E56_03F5(si_1693, di_1689, ds_1690, ss->*((word32) sp_155 - 4), out si_1693, out di_1689, out ds_1690);
					if (CONVERT(Mem1787[ds_1690:0x5528:selector]:51101[ax_1706 * 0x7D], uint8, uint16) == wLoc28_1944)
						ax_1710.u0 = 0x264D;
					else
						ax_1710.u0 = 0x2655;
				}
				else
					ax_1710.u0 = 9795;
				ss->*((word32) sp_155 - 2) = ds_1690;
				ss->*((word32) sp_155 - 4) = ax_1710;
				fn1E56_03F5(si_1693, di_1689, ds_1690, ss->*((word32) sp_155 - 4), out si_1838, out di_1834, out ds_1835);
			}
			wLoc28_1944.u5 = (word16) wLoc28_1944.u2 + 1;
		}
		ss->*((word32) sp_155 - 2) = ds_1835;
		(ss->*((word32) sp_155 - 4)).u0 = 0x265D;
		Eq_5 si_1903;
		Eq_5 di_1904;
		Eq_5 ds_1901;
		fn1E56_03F5(si_1838, di_1834, ds_1835, ss->*((word32) sp_155 - 4), out si_1903, out di_1904, out ds_1901);
		Mem232[ds_1901:0x552C:selector]->t0206 = (word32) wLoc22_1943 + 1;
		Mem255[ds_1901:0x552A:selector]->w374E = 0x0A;
		Eq_5 sp_1902 = sp_155;
		int16 wLoc28_1947;
		for (wLoc28_1947 = 0x00; wLoc28_1947 < 0x04; ++wLoc28_1947)
		{
			if (Mem261[ds_1901:0x5528:selector]:50980[wLoc28_1947 * 0x7D] != ~0x00)
			{
				if (Mem261[ds_1901:0x5532:selector]->w4FBA == 0x00)
					Mem261[ds_1901:21812:selector]->w37FE = 0x01;
				struct Eq_49956 Eq_5::* sp_290 = sp_1902 - 2;
				(ss->*sp_290).t0000.u0 = 0x3092;
				(ss->*sp_290).tFFFFFFFE.u0 = (wchar_t) (wLoc28_1947 *s 0x7D + 50980);
				Eq_5 si_308;
				Eq_5 di_304;
				Eq_5 ds_305;
				fn1E56_03F5(si_1903, di_1904, ds_1901, (ss->*sp_290).tFFFFFFFE.u5, out si_308, out di_304, out ds_305);
				(ss->*sp_290).t0000.u0 = (wchar_t) ds_305;
				(ss->*sp_290).tFFFFFFFE.u0 = 0x2663;
				Eq_5 si_328;
				Eq_5 di_324;
				Eq_5 ds_325;
				fn1E56_03F5(si_308, di_304, ds_305, (ss->*sp_290).tFFFFFFFE.u5, out si_328, out di_324, out ds_325);
				struct Eq_49571 * es_339 = Mem320[ds_325:0x5528:selector];
				bui8 al_340 = es_339->aC724[0].b0079[wLoc28_1947].b0000;
				if (al_340 == ~0x00)
				{
					(ss->*sp_290).t0000.u0 = (wchar_t) ds_325;
					(ss->*sp_290).tFFFFFFFE.u0 = 0x2670;
				}
				else
				{
					int16 ax_348 = (int16) es_339->aC614[0].b0000[al_340].b0000;
					struct Eq_49738 * es_353 = Mem341[ds_325:0x552E:selector];
					(ss->*sp_290).t0000.u0 = es_353->a01CC[0].u5[ax_348].u0;
					(ss->*sp_290).tFFFFFFFE.u0 = es_353->a01CA[0].u5[ax_348].u0;
				}
				struct Eq_50310 Eq_5::* sp_370 = sp_1902 - 4;
				Eq_5 si_379;
				Eq_5 di_375;
				Eq_5 ds_376;
				fn1E56_03F5(si_328, di_324, ds_325, (ss->*sp_370).t0000.u5, out si_379, out di_375, out ds_376);
				(ss->*sp_370).t0002.u0 = (wchar_t) ds_376;
				(ss->*sp_370).t0000.u0 = 0x2675;
				Eq_5 si_399;
				Eq_5 di_395;
				Eq_5 ds_396;
				fn1E56_03F5(si_379, di_375, ds_376, (ss->*sp_370).t0000.u5, out si_399, out di_395, out ds_396);
				struct Eq_49571 * es_411 = Mem391[ds_396:0x5528:selector];
				bui8 al_412 = es_411->aC724[0].b007A[wLoc28_1947].b0000;
				if (al_412 != ~0x00)
				{
					int16 ax_425 = (int16) es_411->aC614[0].b0000[al_412].b0000;
					struct Eq_49738 * es_430 = Mem413[ds_396:0x552E:selector];
					(ss->*sp_370).t0002.u0 = es_430->a01CC[0].u5[ax_425].u0;
					(ss->*sp_370).t0000.u0 = es_430->a01CA[0].u5[ax_425].u0;
				}
				else
				{
					(ss->*sp_370).t0002.u0 = (wchar_t) ds_396;
					(ss->*sp_370).t0000.u0 = 0x2682;
				}
				Eq_5 si_451;
				Eq_5 di_447;
				Eq_5 ds_448;
				fn1E56_03F5(si_399, di_395, ds_396, (ss->*sp_370).t0000.u5, out si_451, out di_447, out ds_448);
				Mem443[ds_448:21812:selector]->w37FE = 0x0F;
				si_1903 = fn1CD3_181E(fp - 2, si_451, di_447, ds_448, out di_1904, out ds_1901);
				sp_1902.u0 = <invalid>;
			}
		}
		struct Eq_49916 Eq_5::* sp_483 = sp_1902 - 2;
		(ss->*sp_483).t0000.u0 = 0x17;
		Eq_5 ax_485 = fn1E56_0B5E(si_1903, di_1904, ds_1901, (ss->*sp_483).t0000.u0, out si_492, out di_129, out ds_127);
		sp_123.u5 = (char *) &sp_483->t0000 + 2;
		Eq_5 di_1290;
		Eq_5 ds_1291;
		Eq_5 si_1562;
		if (ax_485 != wLoc22_1943)
		{
			(ss->*sp_483).t0000.u0 = 0x04;
			Eq_5 di_879;
			Eq_5 ds_880;
			Eq_5 di_894;
			Eq_5 ds_895;
			fn1E56_0388(fp - 2, fn1E56_0281(si_492, di_129, ds_127, (ss->*sp_483).t0000.u0, out di_879, out ds_880), di_879, ds_880, out di_894, out ds_895);
			Mem875[ds_895:21812:selector]->w37FE = 0x0F;
			int16 ax_915 = CONVERT(Mem906[ds_895:0x5528:selector]:50708[ss:fp - 26[ax_485 *16 0x02] * 0x11], int8, int16);
			struct Eq_49738 * es_920 = Mem906[ds_895:0x552E:selector];
			Eq_5 sp_899;
			sp_899.u0 = <invalid>;
			(ss->*((word32) sp_899 - 2)).u0 = es_920->a01CC[0].u5[ax_915].u0;
			(ss->*((word32) sp_899 - 4)).u0 = es_920->a01CA[0].u5[ax_915].u0;
			Eq_5 si_934;
			Eq_5 di_930;
			Eq_5 ds_931;
			fn1E56_03F5(ax_485 << 0x01, di_894, ds_895, ss->*((word32) sp_899 - 4), out si_934, out di_930, out ds_931);
			ss->*((word32) sp_899 - 2) = ds_931;
			(ss->*((word32) sp_899 - 4)).u0 = 10038;
			word16 si_2250;
			Eq_5 di_1018;
			Eq_5 ds_1012;
			fn1E56_03F5(si_934, di_930, ds_931, ss->*((word32) sp_899 - 4), out si_2250, out di_1018, out ds_1012);
			Eq_5 si_1001 = ax_485 << 0x01;
			int16 ax_969 = CONVERT(Mem946[ds_1012:0x5528:selector]:0xC61C[ss:fp - 26[ax_485 *16 0x02] * 0x11], int8, int16);
			if (ax_969 == 0x00)
			{
				Eq_5 si_983;
				Eq_5 di_979;
				Eq_5 ds_980;
				fn0800_28A2(fp - 2, ax_485 << 0x01, di_1018, ds_1012, out si_983, out di_979, out ds_980);
				ss->*((word32) sp_899 - 2) = ds_980;
				(ss->*((word32) sp_899 - 4)).u0 = 10043;
				fn1E56_03F5(si_983, di_979, ds_980, ss->*((word32) sp_899 - 4), out si_1001, out di_1018, out ds_1012);
			}
			ss->*((word32) sp_899 - 2) = ds_1012;
			(ss->*((word32) sp_899 - 4)).u0 = 0x2740;
			Eq_5 si_1027;
			Eq_5 di_1023;
			Eq_5 ds_1024;
			fn1E56_03F5(si_1001, di_1018, ds_1012, ss->*((word32) sp_899 - 4), out si_1027, out di_1023, out ds_1024);
			(ss->*((word32) sp_899 - 2)).u0 = 0x03;
			Eq_5 si_1061 = fn1E56_0388(fp - 2, fn1E56_0281(si_1027, di_1023, ds_1024, ss->*((word32) sp_899 - 2), out di_1041, out ds_1042), di_1041, ds_1042, out di_1057, out ds_1058);
			Eq_5 sp_1062;
			sp_1062.u0 = <invalid>;
			ss->*((word32) sp_1062 - 2) = ds_1058;
			(ss->*((word32) sp_1062 - 4)).u0 = 10075;
			word16 si_2251;
			Eq_5 di_1076;
			Eq_5 ds_1077;
			fn1E56_03F5(si_1061, di_1057, ds_1058, ss->*((word32) sp_1062 - 4), out si_2251, out di_1076, out ds_1077);
			Mem1072[ds_1077:0x552C:selector]->w00C2 = Mem1072[ds_1077:0x552A:selector]->w374E;
			int16 wLoc28_1997 = 0x00;
			int16 v38_1099;
			Eq_5 si_1097;
			do
			{
				(&&(ss->*(ss->*(fp - 0x0A)).u0))[wLoc28_1997].u1 = ~0x00;
				v38_1099 = wLoc28_1997 + 0x01;
				si_1097 = wLoc28_1997 << 0x01;
				wLoc28_1997 = v38_1099;
			} while (v38_1099 < 0x04);
			Eq_5 wLoc26_2000;
			wLoc26_2000.u0 = 0x00;
			Eq_5 wLoc28_2001;
			wLoc28_2001.u0 = 0x00;
			while (wLoc28_2001 < 0x04)
			{
				if (Mem1109[ds_1077:0x5528:selector]:50980[wLoc28_2001 *16 0x7D] != ~0x00)
				{
					(ss->*((word32) sp_1062 - 2)).u0 = 0x3092;
					ss->*((word32) sp_1062 - 4) = wLoc28_2001 *s16 0x7D + 50980;
					(ss->*((word32) sp_1062 - 6)).u0 = 0x3092;
					(ss->*((word32) sp_1062 - 8)).u0 = 0x12;
					fn207F_3B68(ss->*((word32) sp_1062 - 8), ss->*((word32) sp_1062 - 4));
					Mem1138[ds_1077:0x5530:selector]->b001D = 0x00;
					(ss->*((word32) sp_1062 - 2)).u0 = 0x3092;
					ss->*((word32) sp_1062 - 4) = wLoc28_2001 *s16 0x7D + 50980;
					word16 si_2253;
					fn1E56_03F5(si_1097, di_1076, ds_1077, ss->*((word32) sp_1062 - 4), out si_2253, out di_1076, out ds_1077);
					(&&(ss->*(ss->*(fp - 0x0A)).u0))[wLoc26_2000].u1 = (struct Eq_109213 *) wLoc28_2001;
					wLoc26_2000.u5 = (word32) wLoc26_2000 + 1;
					si_1097 = wLoc26_2000 << 0x01;
				}
				wLoc28_2001.u5 = (word16) wLoc28_2001.u2 + 1;
			}
			ss->*((word32) sp_1062 - 2) = ds_1077;
			(ss->*((word32) sp_1062 - 4)).u0 = 10101;
			word16 si_2252;
			Eq_5 di_1202;
			Eq_5 ds_1203;
			fn1E56_03F5(si_1097, di_1076, ds_1077, ss->*((word32) sp_1062 - 4), out si_2252, out di_1202, out ds_1203);
			Mem1198[ds_1203:0x552C:selector]->w00C6 = (word16) ((word32) wLoc26_2000 + 1);
			int16 wLoc2C_2007 = 0x00;
			int16 v41_1268;
			do
			{
				struct Eq_49571 * es_1228 = Mem1223[ds_1203:0x5528:selector];
				if ((uint16) es_1228->aC724[0].b0079[wLoc2C_2007].b0000 == ((&(&(ss->*(ss->*(fp - 26)).u0))))[ax_485].u1)
					es_1228->aC724[0].b0079[wLoc2C_2007].b0000 = ~0x00;
				if ((uint16) es_1228->aC724[0].b007A[wLoc2C_2007].b0000 == ((&(&(ss->*(ss->*(fp - 26)).u0))))[ax_485].u1)
					es_1228->aC724[0].b007A[wLoc2C_2007].b0000 = ~0x00;
				v41_1268 = wLoc2C_2007 + 0x01;
				wLoc2C_2007 = v41_1268;
			} while (v41_1268 < 0x04);
			(ss->*((word32) sp_1062 - 2)).u0 = 0x03;
			Eq_5 ax_1287 = fn1E56_0B5E(ax_485 << 0x01, di_1202, ds_1203, ss->*((word32) sp_1062 - 2), out si_2254, out di_1290, out ds_1291);
			if (ax_1287 == wLoc26_2000)
			{
				Mem1301[ds_1291:0x5528:selector]:0xC620[ss:fp - 26[ax_485 *16 0x02] * 0x11] = 0x08;
				si_1562 = ax_485 << 0x01;
				goto l1467_0873;
			}
			Eq_50727 wLoc1E_2018;
			wLoc1E_2018.u0 = 122;
			if (ax_969 != 0x00)
			{
				if (Mem1305[ds_1291:0x5528:selector]:51101[ss:fp - 0x0A[ax_1287 *16 0x02] * 0x7D] != ~0x00)
				{
					Eq_5 si_1324 = fn1E56_0388(fp - 2, ax_1287 << 0x01, di_1290, ds_1291, out di_1320, out ds_1321);
					Eq_5 sp_1325;
					sp_1325.u0 = <invalid>;
					ss->*((word32) sp_1325 - 2) = ds_1321;
					(ss->*((word32) sp_1325 - 4)).u0 = 10106;
					Eq_5 si_1343;
					Eq_5 di_1339;
					Eq_5 ds_1340;
					fn1E56_03F5(si_1324, di_1320, ds_1321, ss->*((word32) sp_1325 - 4), out si_1343, out di_1339, out ds_1340);
					(ss->*((word32) sp_1325 - 2)).u0 = 0x01;
					word16 si_2255;
					word16 di_2256;
					if (fn0800_1A13(si_1343, di_1339, ds_1340, ss->*((word32) sp_1325 - 2), out si_2255, out di_2256, out ds_1291) != 0x00)
						goto l1467_0751;
				}
				else
				{
l1467_0751:
					wLoc1E_2018.u0 = 121;
				}
			}
			int16 ax_1383 = (&&(ss->*(ss->*(fp - 0x0A)).u0))[ax_1287].u1 *s 0x7D;
			struct Eq_49571 * es_1389 = Mem1378[ds_1291:0x5528:selector];
			uint8 al_1390 = (uint8) (es_1389->*((word16) ((word16) wLoc1E_2018 + ax_1383) + 50980));
			uint16 ax_1392 = (uint16) al_1390;
			if (ax_1392 != 0xFF)
			{
				if (wLoc1E_2018 == 121)
				{
					if (es_1389->aC724[0].b007A[(&&(ss->*(ss->*(fp - 0x0A)).u0))[ax_1287].u1].b0000 != ~0x00)
						es_1389->aC614[0].b000C[es_1389->aC724[0].b007A[(&&(ss->*(ss->*(fp - 0x0A)).u0))[ax_1287].u1].b0000].b0000 = 0x08;
					es_1389->aC724[0].b007A[(&&(ss->*(ss->*(fp - 0x0A)).u0))[ax_1287].u1].b0000 = al_1390;
				}
				else
					es_1389->aC614[0].b000C[ax_1392].b0000 = 0x08;
			}
			if (es_1389->bD333 != 0x00 && ((fp - 26))[ax_485].u1 == (int16) es_1389->bD331)
			{
				Eq_5 si_1458 = fn1CD3_17C6(fp - 2, ax_485 << 0x01, ax_1287 << 0x01, ds_1291, out di_1454, out ds_1455);
				Eq_5 sp_1459;
				sp_1459.u0 = <invalid>;
				ss->*((word32) sp_1459 - 2) = ds_1455;
				(ss->*((word32) sp_1459 - 4)).u0 = 10141;
				word16 si_2257;
				Eq_5 di_1474;
				Eq_5 ds_1475;
				fn1E56_03F5(si_1458, di_1454, ds_1455, ss->*((word32) sp_1459 - 4), out si_2257, out di_1474, out ds_1475);
				int16 ax_1493 = CONVERT(Mem1470[ds_1475:0x5528:selector]:50708[ss:fp - 26[ax_485 *16 0x02] * 0x11], int8, int16);
				struct Eq_49738 * es_1498 = Mem1470[ds_1475:0x552E:selector];
				(ss->*((word32) sp_1459 - 2)).u0 = es_1498->a01CC[0].u5[ax_1493].u0;
				(ss->*((word32) sp_1459 - 4)).u0 = es_1498->a01CA[0].u5[ax_1493].u0;
				Eq_5 si_1512;
				Eq_5 di_1508;
				Eq_5 ds_1509;
				fn1E56_03F5(ax_485 << 0x01, di_1474, ds_1475, ss->*((word32) sp_1459 - 4), out si_1512, out di_1508, out ds_1509);
				ss->*((word32) sp_1459 - 2) = ds_1509;
				(ss->*((word32) sp_1459 - 4)).u0 = 10158;
				Eq_5 si_1532 = fn1CD3_17EA(si_1512, di_1508, ds_1509, ss->*((word32) sp_1459 - 4), ss->*((word32) sp_1459 - 2), out di_1528, out ds_1529);
				Mem1524[ds_1529:0x5536:selector]->w374A = 0x01;
				word16 si_2258;
				word16 di_2259;
				fn1F3D_0259(si_1532, di_1528, ds_1529, out si_2258, out di_2259, out ds_1291);
			}
			si_1562.u5 = ds_1291->*((word16) ((ax_485 << 0x01) + (fp - 2)) - 24);
			di_1290.u5 = ds_1291->*((word16) ((ax_1287 << 0x01) + (fp - 2)) - 8);
			struct Eq_49571 * es_1574 = Mem1557[ds_1291:0x5528:selector];
			es_1574->*((word16) (di_1290 *s16 0x7D + wLoc1E_2018) + 50980) = (word16) (byte) si_1562;
			es_1574->aC614[0].b000C[si_1562].b0000 = (byte) di_1290;
			goto l1467_0873;
		}
		wLoc20_1942 = 0x01;
		int16 wLoc28_1963 = 0x00;
		Eq_5 ax_510;
		int16 v39_522;
		do
		{
			ax_510 = wLoc28_1963 *s 0x7D;
			si_115 = ax_510;
			struct Eq_49571 * es_513 = Mem508[ds_127:0x5528:selector];
			if (es_513->aC724[0].b0000[wLoc28_1963].b0000 != ~0x00 && ((((es_513->aC724))[0].b0079))[wLoc28_1963].b0000 == ~0x00)
				wLoc20_1942 = 0x00;
			v39_522 = wLoc28_1963 + 0x01;
			wLoc28_1963 = v39_522;
		} while (v39_522 < 0x04);
		if (wLoc20_1942 == 0x00)
		{
			(ss->*sp_483).t0000.u0 = 0x04;
			Eq_5 si_561 = fn1E56_0388(fp - 2, fn1E56_0281(ax_510, di_129, ds_127, (ss->*sp_483).t0000.u0, out di_542, out ds_543), di_542, ds_543, out di_557, out ds_558);
			Eq_5 sp_562;
			sp_562.u0 = <invalid>;
			ss->*((word32) sp_562 - 2) = ds_558;
			(ss->*((word32) sp_562 - 4)).u0 = 0x2687;
			Eq_5 si_580;
			Eq_5 di_576;
			Eq_5 ds_577;
			fn1E56_03F5(si_561, di_557, ds_558, ss->*((word32) sp_562 - 4), out si_580, out di_576, out ds_577);
			ci16 wLoc2A_1970 = 0x00;
			int16 wLoc28_1971;
			for (wLoc28_1971 = 0x00; wLoc28_1971 < 0x08; ++wLoc28_1971)
			{
				Eq_5 ax_598 = wLoc28_1971 *s 0x11;
				si_580 = ax_598;
				struct Eq_49571 * es_601 = Mem593[ds_577:0x5528:selector];
				if (es_601->aC614[0].b0000[wLoc28_1971].b0000 != ~0x00 && (((es_601->aC614))[0].b0008)[wLoc28_1971] != 0x00)
					++wLoc2A_1970;
			}
			ci16 wLoc32_1977 = 0x00;
			int16 wLoc28_1978;
			for (wLoc28_1978 = 0x00; wLoc28_1978 < 0x04; ++wLoc28_1978)
			{
				if (Mem621[ds_577:0x5528:selector]:50980[wLoc28_1978 * 0x7D] != ~0x00)
					++wLoc32_1977;
			}
			if (wLoc2A_1970 >= wLoc32_1977)
			{
				ss->*((word32) sp_562 - 2) = ds_577;
				(ss->*((word32) sp_562 - 4)).u0 = 10014;
				Eq_5 di_848;
				Eq_5 ds_849;
				fn1F3D_0259(fn1CD3_17EA(si_580, di_576, ds_577, ss->*((word32) sp_562 - 4), ss->*((word32) sp_562 - 2), out di_848, out ds_849), di_848, ds_849, out si_1562, out di_1290, out ds_1291);
			}
			else
			{
				Eq_5 di_659;
				Eq_5 ds_660;
				Eq_5 si_677;
				Eq_5 di_673;
				Eq_5 ds_674;
				fn1F3D_0259(fn1F3D_086A(fp - 2, si_580, di_576, ds_577, out di_659, out ds_660), di_659, ds_660, out si_677, out di_673, out ds_674);
				Eq_5 si_690 = fn1E56_0388(fp - 2, si_677, di_673, ds_674, out di_686, out ds_687);
				Eq_5 sp_691;
				sp_691.u0 = <invalid>;
				ss->*((word32) sp_691 - 2) = ds_687;
				(ss->*((word32) sp_691 - 4)).u0 = 9903;
				Eq_5 di_705;
				Eq_5 ds_706;
				Eq_5 si_724;
				Eq_5 di_720;
				Eq_5 ds_721;
				fn1F3D_0259(fn1CD3_17EA(si_690, di_686, ds_687, ss->*((word32) sp_691 - 4), ss->*((word32) sp_691 - 2), out di_705, out ds_706), di_705, ds_706, out si_724, out di_720, out ds_721);
				Eq_5 si_737 = fn1E56_0388(fp - 2, si_724, di_720, ds_721, out di_733, out ds_734);
				Eq_5 sp_738;
				sp_738.u0 = <invalid>;
				ss->*((word32) sp_738 - 2) = ds_734;
				(ss->*((word32) sp_738 - 4)).u0 = 9965;
				Eq_5 si_756 = fn1CD3_17EA(si_737, di_733, ds_734, ss->*((word32) sp_738 - 4), ss->*((word32) sp_738 - 2), out di_752, out ds_753);
				(ss->*((word32) sp_738 - 2)).u0 = 0x00;
				if (fn0800_1A13(si_756, di_752, ds_753, ss->*((word32) sp_738 - 2), out si_1562, out di_1290, out ds_1291) != 0x00)
				{
					int16 wLoc28_1986 = 0x00;
					int16 v53_832;
					do
					{
						Eq_5 ax_792 = wLoc28_1986 *s 0x7D;
						si_1562 = ax_792;
						struct Eq_49571 * es_795 = Mem790[ds_1291:0x5528:selector];
						if (es_795->aC724[0].b0000[wLoc28_1986].b0000 != ~0x00 && ((((es_795->aC724))[0].b0079))[wLoc28_1986].b0000 == ~0x00)
						{
							es_795->aC724[0].b0000[wLoc28_1986].b0000 = ~0x00;
							int16 wLoc32_1988 = 0x00;
							int16 v52_825;
							do
							{
								struct Eq_49571 * es_810 = Mem805[ds_1291:0x5528:selector];
								if ((int16) es_810->aC614[0].b000C[wLoc32_1988].b0000 == wLoc28_1986)
									es_810->aC614[0].b000C[wLoc32_1988].b0000 = 0x08;
								v52_825 = wLoc32_1988 + 0x01;
								wLoc32_1988 = v52_825;
							} while (v52_825 < 0x08);
						}
						v53_832 = wLoc28_1986 + 0x01;
						wLoc28_1986 = v53_832;
					} while (v53_832 < 0x04);
				}
			}
l1467_0873:
			si_115 = fn1E56_0388(fp - 2, si_1562, di_1290, ds_1291, out di_129, out ds_127);
			sp_123.u0 = <invalid>;
		}
	} while (wLoc20_1942 == 0x00);
	Eq_50606 wLoc28_2073;
	wLoc28_2073.u0 = 54354;
	selector es_1643;
	Eq_50606 v42_1645;
	do
	{
		es_1643 = Mem1640[ds_127:0x5528:selector];
		es_1643->*wLoc28_2073 = ~0x00;
		v42_1645 = (word16) wLoc28_2073 + 1;
		wLoc28_2073 = v42_1645;
	} while (v42_1645 < 11186);
	es_1643->bD324 = 0x00;
	Eq_5 si_1652;
	si_1652.u5 = (ss->*sp_123.u7).t0000.u1;
	diOut = (ss->*sp_123.u7).w0002;
	dsOut = ds_127;
	return si_1652;
}

// 1467:08A8: Register word16 fn1467_08A8(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Register out (memptr Eq_5 Eq_32704) bpOut, Register out word16 siOut, Register out word16 diOut, Register out Eq_5 dsOut)
// Called from:
//      fn0FDC_0008
word16 fn1467_08A8(Eq_5 si, Eq_5 di, Eq_5 ds, struct Eq_32704 & bpOut, word16 & siOut, word16 & diOut, union Eq_5 & dsOut)
{
	Eq_5 ds_778;
	Eq_5 di_777;
	Eq_5 ds_757;
	Eq_5 di_756;
	Eq_5 ds_739;
	Eq_5 di_738;
	Eq_5 ds_724;
	Eq_5 di_723;
	Eq_5 ds_705;
	Eq_5 di_704;
	Eq_5 ds_688;
	Eq_5 di_687;
	Eq_5 si_691;
	Eq_5 ds_640;
	Eq_5 di_639;
	Eq_5 ds_606;
	Eq_5 di_605;
	Eq_5 ds_544;
	Eq_5 di_543;
	Eq_5 ds_353;
	Eq_5 di_352;
	Eq_5 ds_338;
	Eq_5 di_337;
	Eq_5 ds_320;
	Eq_5 di_319;
	Eq_5 ds_285;
	Eq_5 di_284;
	Eq_5 ds_202;
	Eq_5 di_201;
	Eq_5 ds_184;
	Eq_5 di_183;
	Eq_5 ds_167;
	Eq_5 di_166;
	Eq_5 ds_122;
	Eq_5 di_121;
	Eq_5 ds_42;
	Eq_5 di_41;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_115;
	Eq_5 di_116;
	Eq_5 ds_20;
	fn207F_2FDC(0x18, fp - 2, si, di, ds, wLoc06, wLoc04, out si_115, out di_116, out ds_20);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	struct Eq_51381 * ss;
	ss->*((word32) sp_18 - 2) = di_116;
	ss->*((word32) sp_18 - 4) = si_115;
	Eq_36 bp_179 = fp - 2;
	struct Eq_51393 Eq_51381::* sp_30 = sp_18 - 4;
	if (Mem31[ds_20:0x5538:selector]->w4594 == 0x00)
	{
		(ss->*((word32) sp_18 - 6)).u0 = 0x01;
		Eq_5 si_45 = fn0800_28CC(si_115, di_116, ds_20, ss->*((word32) sp_18 - 6), out di_41, out ds_42);
		(ss->*((word32) sp_18 - 6)).u0 = 0x3092;
		(ss->*((word32) sp_18 - 8)).u0 = 0xA0;
		ss->*((word32) sp_18 - 0x0A) = ds_42;
		(ss->*((word32) sp_18 - 0x0C)).u0 = 10214;
		Eq_5 sp_73;
		sp_73.u0 = <invalid>;
		bp_179 = fn1F3D_063B(si_45, di_41, ds_42, out si_115, out di_116, out ds_20);
		sp_30 = (struct Eq_51393 Eq_51381::*) &sp_73.u7->t0008.u0;
	}
	Mem82[ds_20:21818:selector]->w4FBC = 0x00;
	struct Eq_51411 Eq_51381::* sp_88 = sp_30 - 2;
	(ss->*sp_88).t0000.u0 = 0x3056;
	(ss->*sp_88).tFFFFFFFE.u0 = 0x00;
	fn207F_00D1((ss->*sp_88).tFFFFFFFE.u0, (ss->*sp_88).t0000.u0);
	(ss->*sp_88).t0000.u0 = 0x246C;
	(ss->*sp_88).tFFFFFFFE.u0 = 0x244B;
	(ss->*sp_88).tFFFFFFFC.u0 = 0x3092;
	(ss->*sp_88).tFFFFFFFA.u0 = 0xA0;
	Eq_5 si_125 = fn1F3D_049D(si_115, di_116, ds_20, (ss->*sp_88).tFFFFFFFA.u5, (ss->*sp_88).tFFFFFFFE.u0, (ss->*sp_88).t0000.u0, out di_121, out ds_122);
	if (Mem114[ds_122:0x5532:selector]->w4FBA == 0x02)
	{
		(ss->*sp_88).t0000.u0 = 0xA800;
		(ss->*sp_88).tFFFFFFFE.u0 = 0x246C;
		(ss->*sp_88).tFFFFFFFC.u0 = 0x244B;
		fn207F_0260((ss->*sp_88).tFFFFFFFC.u0, (ss->*sp_88).tFFFFFFFE.u0, (ss->*sp_88).t0000.u0);
	}
	struct Eq_51520 Eq_51381::* sp_156 = sp_30 - 2;
	(ss->*sp_156).t0000.u0 = 0x06;
	Eq_5 si_187 = fn1E56_0388(bp_179, fn1E56_0281(si_125, di_121, ds_122, (ss->*sp_156).t0000.u0, out di_166, out ds_167), di_166, ds_167, out di_183, out ds_184);
	Eq_5 sp_188;
	sp_188.u0 = <invalid>;
	(ss->*((word32) sp_188 - 2)).u0 = 0x00;
	Eq_5 si_205 = fn1E56_0004(si_187, di_183, ds_184, ss->*((word32) sp_188 - 2), out di_201, out ds_202);
	ss->*((word32) sp_188 - 2) = ds_202;
	(ss->*((word32) sp_188 - 4)).u0 = 0x27F2;
	Eq_5 di_222;
	Eq_5 ds_223;
	Eq_5 si_241;
	Eq_5 di_237;
	Eq_5 ds_238;
	fn1F3D_0259(fn1CD3_17EA(si_205, di_201, ds_202, ss->*((word32) sp_188 - 4), ss->*((word32) sp_188 - 2), out di_222, out ds_223), di_222, ds_223, out si_241, out di_237, out ds_238);
	ss->*((word16) bp_179 - 18) = 0x00;
	ss->*((word16) bp_179 - 8) = ~0x00;
	ss->*((word16) bp_179 - 0x0A) = ~0x00;
	ss->*((word16) bp_179 - 0x0C) = ~0x00;
	ss->*((word16) bp_179 - 0x0E) = 0x00;
	Eq_5 sp_232 = sp_188;
	while (ss->*((word16) bp_179 - 0x0E) < 0x03)
	{
		struct Eq_51653 Eq_51381::* sp_260 = sp_232 - 2;
		(ss->*sp_260).t0000.u0 = 200;
		(ss->*sp_260).tFFFFFFFE.u0 = 0x28;
		(ss->*sp_260).tFFFFFFFC.u0 = 0x00;
		(ss->*sp_260).tFFFFFFFA.u0 = 0x00;
		(ss->*sp_260).tFFFFFFF8.u0 = 0x246C;
		(ss->*sp_260).tFFFFFFF6.u0 = 0x244B;
		Eq_5 si_288 = fn1F3D_0086(si_241, di_237, ds_238, (ss->*sp_260).tFFFFFFF6.u0, (ss->*sp_260).tFFFFFFF8.u0, (ss->*sp_260).tFFFFFFFA.u0, (ss->*sp_260).tFFFFFFFC.u0, (ss->*sp_260).tFFFFFFFE.u0, (ss->*sp_260).t0000.u0, out di_284, out ds_285);
		(ss->*sp_260).t0000.u0 = (wchar_t) ((word16) (Mem276[ds_285:0x5532:selector]->w4FBA < 0x01) + 0x09);
		(ss->*sp_260).tFFFFFFFE.u0 = 0xC0;
		(ss->*sp_260).tFFFFFFFC.u0 = 0x80;
		(ss->*sp_260).tFFFFFFFA.u0 = 0x00;
		(ss->*sp_260).tFFFFFFF8.u0 = 0x80;
		Eq_5 si_323 = fn1F3D_031C(si_288, di_284, ds_285, (ss->*sp_260).tFFFFFFF8.u0, (ss->*sp_260).tFFFFFFFA.u0, (ss->*sp_260).tFFFFFFFC.u0, (ss->*sp_260).tFFFFFFFE.u0, (ss->*sp_260).t0000.u0, out di_319, out ds_320);
		(ss->*sp_260).t0000.u0 = 0x08;
		Eq_5 si_356 = fn1E56_0388(bp_179, fn1E56_0281(si_323, di_319, ds_320, (ss->*sp_260).t0000.u0, out di_337, out ds_338), di_337, ds_338, out di_352, out ds_353);
		Eq_5 sp_357;
		sp_357.u0 = <invalid>;
		ss->*((word32) sp_357 - 2) = ds_353;
		(ss->*((word32) sp_357 - 4)).u0 = 0x286C;
		Eq_5 si_375;
		Eq_5 di_371;
		Eq_5 ds_372;
		fn1E56_03F5(si_356, di_352, ds_353, ss->*((word32) sp_357 - 4), out si_375, out di_371, out ds_372);
		ss->*((word16) bp_179 - 16) = 0x00;
		do
		{
			(ss->*((word32) sp_357 - 2)).u0 = 0x00;
			(ss->*((word32) sp_357 - 4)).u0 = 0x0F;
			(ss->*((word32) sp_357 - 6)).u5 = (word16) (ss->*((word16) bp_179 - 16)) + 4;
			(ss->*((word32) sp_357 - 8)).u0 = 0x00;
			int16 bx_400 = (int16) (ss->*((word16) bp_179 - 16));
			struct Eq_51895 * es_405 = Mem399[ds_372:0x553C:selector];
			(ss->*((word32) sp_357 - 0x0A)).u0 = es_405->a4DE4[0].u5[bx_400].u0;
			(ss->*((word32) sp_357 - 0x0C)).u0 = es_405->a4DE2[0].u5[bx_400].u0;
			fn1F3D_00D5(si_375, di_371, ds_372, ss->*((word32) sp_357 - 0x0C), ss->*((word32) sp_357 - 8), ss->*((word32) sp_357 - 6), ss->*((word32) sp_357 - 4), ss->*((word32) sp_357 - 2), out si_375, out di_371, out ds_372);
			ss->*((word16) bp_179 - 16) = (word16) (ss->*((word16) bp_179 - 16)) + 1;
		} while (ss->*((word16) bp_179 - 16) < 0x14);
		int16 ax_454;
		do
		{
			ss->*((word16) bp_179 - 22) = 0x00;
			ss->*((word16) bp_179 - 24) = (int32) fn207F_0BC0() % 0x0A;
			ss->*((word16) bp_179 - 20) = 0x00;
			while (true)
			{
				ax_454 = (int16) (ss->*((word16) bp_179 - 0x0E));
				if (ss->*((word16) bp_179 - 20) >= ax_454)
					break;
				if ((ss->*(bp_179 - 0x0C)).a0000[ss->*((word16) bp_179 - 20)] == ss->*((word16) bp_179 - 24))
					ss->*((word16) bp_179 - 22) = 0x01;
				ss->*((word16) bp_179 - 20) = (word16) (ss->*((word16) bp_179 - 20)) + 1;
			}
		} while (ss->*((word16) bp_179 - 22) != 0x00);
		(ss->*(bp_179 - 0x0C)).a0000[ax_454] = (struct Eq_32704 Eq_5::*) (ss->*((word16) bp_179 - 24));
		int16 si_475 = (int16) (ss->*((word16) bp_179 - 24));
		ss->*((word16) bp_179 - 4) = (*((word32) ds_372 + 0x000028C4))[si_475] - 0x03;
		ss->*((word16) bp_179 - 6) = (*((word32) ds_372 + 0x000028D8))[si_475] - 0x03;
		(ss->*((word32) sp_357 - 2)).u0 = 0x0F;
		(ss->*((word32) sp_357 - 4)).u5 = ss->*((word16) bp_179 - 6);
		(ss->*((word32) sp_357 - 6)).u5 = (word16) (ss->*((word16) bp_179 - 4)) + 8;
		(ss->*((word32) sp_357 - 8)).u5 = ss->*((word16) bp_179 - 6);
		(ss->*((word32) sp_357 - 0x0A)).u5 = ss->*((word16) bp_179 - 4);
		Eq_5 di_512;
		Eq_5 ds_513;
		fn1F3D_031C(si_475 << 0x01, ax_454 << 0x01, ds_372, ss->*((word32) sp_357 - 0x0A), ss->*((word32) sp_357 - 8), ss->*((word32) sp_357 - 6), ss->*((word32) sp_357 - 4), ss->*((word32) sp_357 - 2), out di_512, out ds_513);
		Eq_5 si_523;
		si_523.u5 = ss->*((word16) bp_179 - 6);
		(ss->*((word32) sp_357 - 2)).u0 = 0x0F;
		(ss->*((word32) sp_357 - 4)).u5 = &si_523.u7->t0008.u0;
		(ss->*((word32) sp_357 - 6)).u5 = (word16) (ss->*((word16) bp_179 - 4)) + 8;
		(ss->*((word32) sp_357 - 8)).u5 = &si_523.u7->t0008.u0;
		(ss->*((word32) sp_357 - 0x0A)).u5 = ss->*((word16) bp_179 - 4);
		Eq_5 si_547 = fn1F3D_031C(&si_523.u7->t0008.u0, di_512, ds_513, ss->*((word32) sp_357 - 0x0A), ss->*((word32) sp_357 - 8), ss->*((word32) sp_357 - 6), ss->*((word32) sp_357 - 4), ss->*((word32) sp_357 - 2), out di_543, out ds_544);
		(ss->*((word32) sp_357 - 2)).u0 = 0x0F;
		(ss->*((word32) sp_357 - 4)).u5 = (word16) (ss->*((word16) bp_179 - 6)) + 8;
		(ss->*((word32) sp_357 - 6)).u5 = ss->*((word16) bp_179 - 4);
		(ss->*((word32) sp_357 - 8)).u5 = ss->*((word16) bp_179 - 6);
		(ss->*((word32) sp_357 - 0x0A)).u5 = ss->*((word16) bp_179 - 4);
		Eq_5 di_574;
		Eq_5 ds_575;
		fn1F3D_031C(si_547, di_543, ds_544, ss->*((word32) sp_357 - 0x0A), ss->*((word32) sp_357 - 8), ss->*((word32) sp_357 - 6), ss->*((word32) sp_357 - 4), ss->*((word32) sp_357 - 2), out di_574, out ds_575);
		Eq_5 si_585;
		si_585.u5 = ss->*((word16) bp_179 - 4);
		(ss->*((word32) sp_357 - 2)).u0 = 0x0F;
		(ss->*((word32) sp_357 - 4)).u5 = (word16) (ss->*((word16) bp_179 - 6)) + 8;
		(ss->*((word32) sp_357 - 6)).u5 = &si_585.u7->t0008.u0;
		(ss->*((word32) sp_357 - 8)).u5 = ss->*((word16) bp_179 - 6);
		(ss->*((word32) sp_357 - 0x0A)).u5 = &si_585.u7->t0008.u0;
		Eq_5 si_609 = fn1F3D_031C(&si_585.u7->t0008.u0, di_574, ds_575, ss->*((word32) sp_357 - 0x0A), ss->*((word32) sp_357 - 8), ss->*((word32) sp_357 - 6), ss->*((word32) sp_357 - 4), ss->*((word32) sp_357 - 2), out di_605, out ds_606);
		(ss->*((word32) sp_357 - 2)).u0 = 0x0F;
		(ss->*((word32) sp_357 - 4)).u5 = (word16) (ss->*((word16) bp_179 - 6)) + 6;
		(ss->*((word32) sp_357 - 6)).u5 = ss->*((word16) bp_179 - 4);
		(ss->*((word32) sp_357 - 8)).u5 = (word16) (ss->*((word16) bp_179 - 6)) + 2;
		(ss->*((word32) sp_357 - 0x0A)).u0 = 0x80;
		Eq_5 si_643 = fn1F3D_01FB(si_609, di_605, ds_606, ss->*((word32) sp_357 - 0x0A), ss->*((word32) sp_357 - 8), ss->*((word32) sp_357 - 6), ss->*((word32) sp_357 - 4), ss->*((word32) sp_357 - 2), out di_639, out ds_640);
		(ss->*((word32) sp_357 - 2)).u0 = 0x25;
		fn1E56_0B5E(si_643, di_639, ds_640, ss->*((word32) sp_357 - 2), out si_241, out di_237, out ds_238);
		sp_232 = sp_357;
		ss->*((word16) bp_179 - 0x0E) = (word16) (ss->*((word16) bp_179 - 0x0E)) + 1;
	}
	fn207F_1FBE();
	struct Eq_51829 Eq_51381::* sp_681 = sp_232 - 2;
	(ss->*sp_681).t0000.u0 = 0x01;
	Eq_36 bp_684 = fn0800_4CAC(si_241, di_237, ds_238, (ss->*sp_681).t0000.u0, out si_691, out di_687, out ds_688);
	Eq_5 si_708 = fn1E56_0388(bp_684, si_691, di_687, ds_688, out di_704, out ds_705);
	Eq_5 sp_709;
	sp_709.u0 = <invalid>;
	if (ss->*((word16) bp_684 - 18) != 0x00)
	{
		(ss->*((word32) sp_709 - 2)).u0 = 0x06;
		Eq_5 si_742 = fn1E56_0388(bp_684, fn1E56_0281(si_708, di_704, ds_705, ss->*((word32) sp_709 - 2), out di_723, out ds_724), di_723, ds_724, out di_738, out ds_739);
		Eq_5 sp_743;
		sp_743.u0 = <invalid>;
		(ss->*((word32) sp_743 - 2)).u0 = 0x00;
		Eq_5 si_760 = fn1E56_0004(si_742, di_738, ds_739, ss->*((word32) sp_743 - 2), out di_756, out ds_757);
		ss->*((word32) sp_743 - 2) = ds_757;
		(ss->*((word32) sp_743 - 4)).u0 = 0x2886;
		Eq_5 si_781 = fn1CD3_17EA(si_760, di_756, ds_757, ss->*((word32) sp_743 - 4), ss->*((word32) sp_743 - 2), out di_777, out ds_778);
		Mem773[ds_778:0x5528:selector]->bD320 = ~0x00;
		word16 si_844;
		word16 di_845;
		fn1F3D_0259(si_781, di_777, ds_778, out si_844, out di_845, out ds_705);
		sp_709 = sp_743;
	}
	word16 ax_807 = (word16) (ss->*((word16) bp_684 - 18));
	word16 si_809 = (ss->*sp_709.u7).t0000.u1;
	word16 di_811 = (ss->*sp_709.u7).w0002;
	bpOut = (struct Eq_32704 Eq_5::*) (ss->*bp_684);
	siOut = si_809;
	diOut = di_811;
	dsOut = ds_705;
	return ax_807;
}

// 1467:0B98: Register Eq_5 fn1467_0B98(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Register out word16 diOut, Register out (ptr16 Eq_13692) dsOut)
// Called from:
//      fn0800_378D
//      fn0FDC_1A26
//      fn11B8_0002
//      fn11B8_080A
//      fn11B8_1762
Eq_5 fn1467_0B98(Eq_5 si, Eq_5 di, Eq_5 ds, word16 & diOut, struct Eq_13692 & dsOut)
{
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_127;
	Eq_5 di_128;
	Eq_5 ds_102;
	fn207F_2FDC(0x04, fp - 2, si, di, ds, wLoc06, wLoc04, out si_127, out di_128, out ds_102);
	Eq_5 sp_121;
	sp_121.u0 = <invalid>;
	Eq_52526 wLoc06_337;
	wLoc06_337.u0 = 0xD558;
	Eq_52526 v10_36;
	do
	{
		Mem31[ds_102:21822:selector]->*wLoc06_337 = 0x00;
		v10_36 = (word16) wLoc06_337 + 1;
		wLoc06_337 = v10_36;
	} while (v10_36 < 0x2AAC);
	Mem37[ds_102:0x5540:selector]->t0068.u0 = 0x00;
	Eq_49698 wLoc04_340;
	wLoc04_340.u0 = 0x00;
	if (Mem43[ds_102:0x5528:selector]->bD324 != 0x00)
	{
		Eq_52560 wLoc06_350;
		wLoc06_350.u0 = 0x00;
		while (true)
		{
			byte bLoc06_364 = (byte) wLoc06_350;
			if (wLoc06_350 >= 0x04)
				break;
			if (Mem76[ds_102:0x5528:selector]->*((word16) wLoc06_350 + 54354) != ~0x00)
			{
				Mem299[ds_102:21822:selector]->*((word16) wLoc04_340 + 0x0000D558) = bLoc06_364;
				wLoc04_340 = (word16) wLoc04_340 + 1;
			}
			wLoc06_350 = (word16) wLoc06_350 + 1;
		}
	}
	else
	{
		int16 wLoc06_341 = 0x00;
		int16 v20_69;
		do
		{
			byte bLoc06_343 = (byte) wLoc06_341;
			if (Mem51[ds_102:0x5528:selector]:50980[wLoc06_341 * 0x7D] != ~0x00)
			{
				Mem62[ds_102:21822:selector]->*((word16) wLoc04_340 + 0x0000D558) = bLoc06_343;
				wLoc04_340 = (word16) wLoc04_340 + 1;
			}
			v20_69 = wLoc06_341 + 0x01;
			wLoc06_341 = v20_69;
		} while (v20_69 < 0x04);
	}
	Mem82[ds_102:0x5540:selector]->t0068.u0 = (int16) Mem82[ds_102:21822:selector]->bD558;
	Mem87[ds_102:0x552C:selector]->w0202 = Mem87[ds_102:0x552A:selector]->w374E;
	Eq_49698 wLoc06_352;
	wLoc06_352.u0 = 0xD558;
	selector ss;
	while (wLoc06_352 < wLoc04_340)
	{
		selector es_106 = Mem97[ds_102:0x5540:selector];
		es_106->t0068.u0 = (int16) (Mem97[ds_102:21822:selector]->*wLoc06_352);
		uint16 bx_115 = CONVERT(Mem107[ds_102:0x5528:selector]:51101[Mem107[es_106:0x68:word16] * 0x7D], uint8, uint16);
		struct Eq_49738 * es_119 = Mem107[ds_102:0x552E:selector];
		struct Eq_52662 Eq_52669::* sp_122 = sp_121 - 2;
		(ss->*sp_122).t0000.u0 = es_119->a01CC[0].u5[bx_115].u0;
		(ss->*sp_122).tFFFFFFFE.u0 = es_119->a01CA[0].u5[bx_115].u0;
		Eq_5 si_137;
		Eq_5 di_133;
		Eq_5 ds_134;
		fn1E56_03F5(si_127, di_128, ds_102, (ss->*sp_122).tFFFFFFFE.u5, out si_137, out di_133, out ds_134);
		(ss->*sp_122).t0000.u0 = (wchar_t) ds_134;
		(ss->*sp_122).tFFFFFFFE.u0 = 0x2900;
		Eq_5 si_157;
		Eq_5 di_153;
		Eq_5 ds_154;
		fn1E56_03F5(si_137, di_133, ds_134, (ss->*sp_122).tFFFFFFFE.u5, out si_157, out di_153, out ds_154);
		Eq_5 ax_204;
		if (Mem149[ds_154:0x5528:selector]->bD324 == 0x00)
			ax_204 = Mem149[ds_154:0x5540:selector]->t0068 *s 0x7D + 50980;
		else
		{
			Eq_52541 bx_168 = Mem149[ds_154:0x5540:selector]->t0068;
			Mem149[ds_154:0x5530:selector]->b0012 = (byte) (Mem149[ds_154:0x5528:selector]->*((word16) bx_168 + 54354));
			(ss->*sp_122).t0000.u0 = 0x3092;
			(ss->*sp_122).tFFFFFFFE.u0 = (wchar_t) (bx_168 *s 0x7D + 0xC725);
			(ss->*sp_122).tFFFFFFFC.u0 = 0x3092;
			(ss->*sp_122).tFFFFFFFA.u0 = 0x13;
			fn207F_3B68((ss->*sp_122).tFFFFFFFA.u5, (ss->*sp_122).tFFFFFFFE.u5);
			ax_204.u0 = 0x12;
		}
		struct Eq_52851 Eq_52669::* sp_216 = sp_121 - 2;
		(ss->*sp_216).t0000.u0 = 0x3092;
		(ss->*sp_216).tFFFFFFFE.u0 = (wchar_t) ax_204;
		Eq_5 si_234;
		Eq_5 di_230;
		Eq_5 ds_231;
		fn1E56_03F5(si_157, di_153, ds_154, (ss->*sp_216).tFFFFFFFE.u5, out si_234, out di_230, out ds_231);
		si_127 = fn1CD3_181E(fp - 2, si_234, di_230, ds_231, out di_128, out ds_102);
		sp_121.u0 = <invalid>;
		wLoc06_352 = (word16) wLoc06_352 + 1;
	}
	selector es_260 = Mem97[ds_102:0x552C:selector];
	es_260->t0206 = wLoc04_340;
	es_260->w0208 = 0x00;
	union Eq_5 Eq_52669::* sp_265 = sp_121 - 2;
	(ss->*sp_265).u0 = 0x17;
	struct Eq_13692 * ds_271;
	Eq_5 si_274;
	word16 di_270;
	Mem266[ds_271:0x5540:selector]->w0068 = (int16) (Mem266[ds_271:21822:selector]->*((word16) fn1E56_0B5E(si_127, di_128, ds_102, (ss->*sp_265).u0, out si_274, out di_270, out ds_271) + 0x0000D558));
	Mem285[ds_271:0x552C:selector]->w0202 = 0x01;
	diOut = di_270;
	dsOut = ds_271;
	return si_274;
}

// 1467:0D7E: Register Eq_5 fn1467_0D7E(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Register out word16 diOut, Register out (ptr16 Eq_52894) dsOut)
// Called from:
//      fn1AE8_000C
Eq_5 fn1467_0D7E(Eq_5 si, Eq_5 di, Eq_5 ds, word16 & diOut, struct Eq_52894 & dsOut)
{
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	word16 di_19;
	struct Eq_52894 * ds_20;
	fn207F_2FDC(0x04, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	int16 wLoc04_62;
	for (wLoc04_62 = 0x00; wLoc04_62 < 0x18; ++wLoc04_62)
	{
		Eq_52903 wLoc06_65;
		wLoc06_65.u0 = 0x00;
		while (wLoc06_65 < 0x18)
		{
			Mem40[ds_20:0x5542:selector]->*((word16) (wLoc04_62 *s 0x18 + wLoc06_65) + 0x000040B4) = (word16) 0x00;
			wLoc06_65 = (word16) wLoc06_65 + 1;
		}
	}
	diOut = di_19;
	dsOut = ds_20;
	return si_22;
}

