// UNBTECH_1431.c
// Generated by decompiling UNBTECH.exe
// using Reko decompiler version 0.12.2.0.

#include "UNBTECH.h"

// 1431:000A: Register Eq_28 fn1431_000A(Register Eq_5 si, Register Eq_5 di, Register Eq_5 ds, Stack Eq_5 wArg04, Register out Eq_5 siOut, Register out word16 diOut, Register out Eq_5 dsOut)
// Called from:
//      fn0800_2C50
//      fn183B_000A
//      fn1CD3_0004
Eq_28 fn1431_000A(Eq_5 si, Eq_5 di, Eq_5 ds, Eq_5 wArg04, union Eq_5 & siOut, word16 & diOut, union Eq_5 & dsOut)
{
	Eq_5 ds_660;
	Eq_5 di_659;
	Eq_5 ds_620;
	Eq_5 di_619;
	Eq_5 ds_606;
	Eq_5 di_605;
	Eq_5 ds_438;
	Eq_5 di_437;
	Eq_5 ds_132;
	Eq_5 di_131;
	Eq_5 ds_116;
	Eq_5 di_115;
	Eq_5 ds_98;
	Eq_5 di_97;
	mp16 fp;
	word16 wLoc06;
	cup16 wLoc04;
	Eq_5 si_22;
	Eq_5 di_19;
	Eq_5 ds_20;
	fn207F_2FDC(0x1A, fp - 2, si, di, ds, wLoc06, wLoc04, out si_22, out di_19, out ds_20);
	Eq_5 sp_18;
	sp_18.u0 = <invalid>;
	selector ss;
	ss->*((word32) sp_18 - 2) = di_19;
	ss->*((word32) sp_18 - 4) = si_22;
	Eq_36 bp_635 = fp - 2;
	Eq_5 si_698;
	Eq_5 di_694;
	Eq_5 ds_695;
	Eq_5 sp_650;
	if (Mem31[ds_20:0x5522:selector]->bD335 != 0x00)
	{
		Eq_5 di_707;
		Eq_5 ds_708;
		fn1CD3_17C6(fp - 2, si_22, di_19, ds_20, out di_707, out ds_708);
		Eq_5 sp_712;
		sp_712.u0 = <invalid>;
		word16 wLoc04_897 = 0x00;
		int16 wLoc18_898 = 0x00;
		Eq_5 ax_726;
		int16 v17_743;
		do
		{
			ax_726 = wLoc18_898 *s 0x11;
			struct Eq_48827 * es_729 = Mem724[ds_708:0x5522:selector];
			if (es_729->aC614[0].b0000[wLoc18_898].b0000 != ~0x00 && (((es_729->aC614))[0].b0001)[wLoc18_898] *s16 0x0A != (int16) (((es_729->aC614))[0].b000F)[wLoc18_898])
				wLoc04_897 = 0x01;
			v17_743 = wLoc18_898 + 0x01;
			wLoc18_898 = v17_743;
		} while (v17_743 < 0x08);
		Eq_5 ax_749;
		if (wLoc04_897 != 0x00)
			ax_749.u0 = 9636;
		else
			ax_749.u0 = 9679;
		ss->*((word32) sp_712 - 2) = ds_708;
		ss->*((word32) sp_712 - 4) = ax_749;
		si_698 = fn1CD3_17EA(ax_726, di_707, ds_708, ss->*((word32) sp_712 - 4), ss->*((word32) sp_712 - 2), out di_694, out ds_695);
		sp_650 = sp_712;
	}
	else
	{
		Eq_5 wLoc0E_831;
		wLoc0E_831.u0 = 0x00;
		int16 wLoc08_832 = 0x00;
		int16 wLoc18_833 = 0x00;
		Eq_5 ax_46;
		int16 v19_63;
		do
		{
			ax_46 = wLoc18_833 *s 0x11;
			struct Eq_48827 * es_49 = Mem44[ds_20:0x5522:selector];
			if (es_49->aC614[0].b0000[wLoc18_833].b0000 != ~0x00)
			{
				Eq_5 ax_53;
				ax_53.u2 = (int16) es_49->aC614[0].b000A[wLoc18_833];
				di_19 = ax_53;
				if (wLoc0E_831 < ax_53)
				{
					wLoc08_832 = wLoc18_833;
					wLoc0E_831 = ax_53;
				}
			}
			v19_63 = wLoc18_833 + 0x01;
			wLoc18_833 = v19_63;
		} while (v19_63 < 0x08);
		(ss->*((word32) sp_18 - 6)).u5 = 0x17;
		// Failed to bind call argument.
		// Please report this issue at https://github.com/uxmal/reko
		Eq_5 stackArg4;
		stackArg4.u0 = <invalid>;
		word16 si_963;
		word16 di_964;
		selector ds_965;
		fn1CD3_0004(ax_46, di_19, ds_20, stackArg4, out si_963, out di_964, out ds_965);
		Eq_5 sp_80;
		sp_80.u0 = <invalid>;
		sp_650.u5 = &sp_80.u7->w0002;
		if (Mem71[ds_20:0x5522:selector]->bD325 != 0x00)
		{
			(ss->*sp_80.u7).t0000.u1 = 0x01;
			Eq_5 si_101 = fn1E56_0281(ax_46, di_19, ds_20, (ss->*sp_80.u7).t0000.u1, out di_97, out ds_98);
			(ss->*sp_80.u7).t0000.u1 = 0x01;
			Eq_5 si_135 = fn1E56_0388(fp - 2, fn1E56_0004(si_101, di_97, ds_98, (ss->*sp_80.u7).t0000.u1, out di_115, out ds_116), di_115, ds_116, out di_131, out ds_132);
			Eq_5 sp_136;
			sp_136.u0 = <invalid>;
			Eq_49001 wLoc0A_841;
			wLoc0A_841.u0 = 0x01;
			selector es_143 = Mem142[ds_132:0x5522:selector];
			if (es_143->bD450 != 0x00)
				wLoc0A_841.u0 = 0x02;
			if (wLoc0E_831 >= 0x03 && es_143->bD451 != 0x00)
				wLoc0A_841.u0 = 0x03;
			Eq_5 si_198;
			Eq_5 di_194;
			Eq_5 ds_195;
			if (wArg04 != 0x00)
			{
				wLoc0A_841.u0 = 0x02;
				if (wArg04 > 0x02)
					wLoc0A_841.u0 = 0x04;
				ss->*((word32) sp_136 - 2) = ds_132;
				(ss->*((word32) sp_136 - 4)).u0 = 0x252D;
				fn1E56_03F5(si_135, di_131, ds_132, ss->*((word32) sp_136 - 4), out si_198, out di_194, out ds_195);
				wLoc0E_831 = wArg04;
			}
			else
			{
				int16 ax_171 = CONVERT(Mem160[ds_132:0x5522:selector]:50708[wLoc08_832 * 0x11], int8, int16);
				struct Eq_49093 * es_176 = Mem160[ds_132:0x5524:selector];
				(ss->*((word32) sp_136 - 2)).u0 = es_176->a01CC[0].u5[ax_171].u0;
				(ss->*((word32) sp_136 - 4)).u0 = es_176->a01CA[0].u5[ax_171].u0;
				fn1E56_03F5(si_135, di_131, ds_132, ss->*((word32) sp_136 - 4), out si_198, out di_194, out ds_195);
			}
			if (wLoc0E_831 != 0x00)
			{
				ss->*((word32) sp_136 - 2) = ds_195;
				(ss->*((word32) sp_136 - 4)).u0 = 0x2538;
				Eq_5 si_266;
				Eq_5 di_262;
				Eq_5 ds_263;
				fn1E56_03F5(si_198, di_194, ds_195, ss->*((word32) sp_136 - 4), out si_266, out di_262, out ds_263);
				if (wLoc0E_831 < 0x05)
				{
					if (wLoc0E_831 < 0x03)
					{
						(ss->*((word32) sp_136 - 2)).u0 = (*((word32) ds_263 + 9696))[wLoc0E_831].u0;
						(ss->*((word32) sp_136 - 4)).u0 = (*((word32) ds_263 + 9694))[wLoc0E_831].u0;
					}
					else
					{
						(ss->*((word32) sp_136 - 2)).u0 = (*((word32) ds_263 + 9692))[wLoc0E_831].u0;
						(ss->*((word32) sp_136 - 4)).u0 = (*((word32) ds_263 + 9690))[wLoc0E_831].u0;
					}
				}
				else
				{
					Mem277[ss:sp_136 + -2:word16] = Mem255[ds_263:0x25F0:word16];
					Mem280[ss:sp_136 + -4:word16] = Mem277[ds_263:0x25EE:word16];
				}
				Eq_5 si_317;
				Eq_5 di_313;
				Eq_5 ds_314;
				fn1E56_03F5(si_266, di_262, ds_263, ss->*((word32) sp_136 - 4), out si_317, out di_313, out ds_314);
				ss->*((word32) sp_136 - 2) = ds_314;
				(ss->*((word32) sp_136 - 4)).u0 = 9539;
				fn1E56_03F5(si_317, di_313, ds_314, ss->*((word32) sp_136 - 4), out si_198, out di_194, out ds_195);
				(ss->*((word32) sp_136 - 2)).u0 = (*((word32) ds_195 + 9712))[wLoc0A_841].u0;
				(ss->*((word32) sp_136 - 4)).u0 = (*((word32) ds_195 + 0x000025EE))[wLoc0A_841].u0;
			}
			else
			{
				ss->*((word32) sp_136 - 2) = ds_195;
				(ss->*((word32) sp_136 - 4)).u0 = 9555;
			}
			Eq_5 si_369;
			Eq_5 di_365;
			Eq_5 ds_366;
			fn1E56_03F5(si_198, di_194, ds_195, ss->*((word32) sp_136 - 4), out si_369, out di_365, out ds_366);
			ss->*((word32) sp_136 - 2) = ds_366;
			(ss->*((word32) sp_136 - 4)).u0 = 0x256F;
			Eq_5 si_389;
			Eq_5 di_385;
			Eq_5 ds_386;
			fn1E56_03F5(si_369, di_365, ds_366, ss->*((word32) sp_136 - 4), out si_389, out di_385, out ds_386);
			Eq_5 si_405;
			Eq_5 di_401;
			Eq_5 ds_402;
			fn0800_28A2(fp - 2, si_389, di_385, ds_386, out si_405, out di_401, out ds_402);
			int16 wLoc18_866;
			for (wLoc18_866 = 0x00; wLoc18_866 < 0x08; ++wLoc18_866)
			{
				Eq_5 ax_419 = wLoc18_866 *s 0x11;
				si_405 = ax_419;
				struct Eq_48827 * es_422 = Mem414[ds_402:0x5522:selector];
				if (es_422->aC614[0].b0000[wLoc18_866].b0000 != ~0x00)
				{
					int16 ax_426 = es_422->aC614[0].b0001[wLoc18_866].b0000 *s16 0x0A;
					if ((int16) es_422->aC614[0].b000F[wLoc18_866].b0000 != ax_426)
					{
						Eq_5 si_441 = fn1CD3_181E(fp - 2, ax_419, di_401, ds_402, out di_437, out ds_438);
						int16 ax_454 = CONVERT(Mem427[ds_438:0x5522:selector]:50708[wLoc18_866 * 0x11], int8, int16);
						struct Eq_49093 * es_459 = Mem427[ds_438:0x5524:selector];
						Eq_5 sp_442;
						sp_442.u0 = <invalid>;
						(ss->*((word32) sp_442 - 2)).u0 = es_459->a01CC[0].u5[ax_454].u0;
						(ss->*((word32) sp_442 - 4)).u0 = es_459->a01CA[0].u5[ax_454].u0;
						Eq_5 si_473;
						Eq_5 di_469;
						Eq_5 ds_470;
						fn1E56_03F5(si_441, di_437, ds_438, ss->*((word32) sp_442 - 4), out si_473, out di_469, out ds_470);
						ss->*((word32) sp_442 - 2) = ds_470;
						(ss->*((word32) sp_442 - 4)).u0 = 0x2587;
						word16 di_970;
						fn1E56_03F5(si_473, di_469, ds_470, ss->*((word32) sp_442 - 4), out si_405, out di_970, out ds_402);
						int8 al_504 = ((word16) wLoc0A_841 + 9729)[wLoc0E_831].b0000;
						int16 ax_505 = (int16) al_504;
						di_401 = wLoc0E_831 << 0x02;
						int16 wLoc0C_871 = ax_505;
						int16 wLoc14_872 = 0x01;
						if ((al_504 & 0xF0) != 0x00)
						{
							wLoc14_872 = ax_505 >> 0x04 & 0x0F;
							wLoc0C_871 = ax_505 & 0x0F;
						}
						int16 wLoc04_876 = 0x00;
						while (true)
						{
							--wLoc0C_871;
							if (wLoc0C_871 == 0x00)
								break;
							struct Eq_5398 * ds_ax_971 = fn0800_19F3(si_405, di_401, ds_402, out si_405, out di_401);
							ds_402.u5 = SLICE(ds_ax_971, selector, 16);
							wLoc04_876 += (word16) ds_ax_971;
						}
						struct Eq_48827 * es_563 = Mem558[ds_402:0x5522:selector];
						int16 v41_568 = (int16) es_563->aC614[0].b000F[wLoc18_866].b0000 + wLoc04_876 *s wLoc14_872;
						byte bLoc12_891 = (byte) v41_568;
						if (v41_568 > ax_426)
							bLoc12_891 = (byte) ax_426;
						es_563->aC614[0].b000F[wLoc18_866].b0000 = bLoc12_891;
					}
				}
			}
			Mem414[ds_402:0x5526:selector]->w37FE = 0x0F;
			Eq_5 si_623 = fn0800_2A4F(fp - 2, fn1F3D_086A(fp - 2, si_405, di_401, ds_402, out di_605, out ds_606), di_605, ds_606, out di_619, out ds_620);
			Eq_5 sp_624;
			sp_624.u0 = <invalid>;
			(ss->*((word32) sp_624 - 2)).u0 = 0x00;
			word16 si_968;
			word16 di_969;
			bp_635 = fn0800_4CAC(si_623, di_619, ds_620, ss->*((word32) sp_624 - 2), out si_968, out di_969, out ds_20);
			Mem633[ds_20:0x5522:selector]->bD335 = 0x3F;
			Eq_5 sp_643;
			sp_643.u0 = <invalid>;
			sp_650.u5 = &sp_643.u7->w0002;
l1431_035C:
			word16 di_810 = (ss->*sp_650.u7).w0002;
			Eq_28 bp_815 = ss->*bp_635;
			siOut.u5 = (ss->*sp_650.u7).t0000.u1;
			diOut = di_810;
			dsOut = ds_20;
			return bp_815;
		}
		if (wArg04 != 0x00)
			goto l1431_035C;
		Eq_5 si_663 = fn1CD3_17C6(fp - 2, ax_46, di_19, ds_20, out di_659, out ds_660);
		Eq_5 sp_664;
		sp_664.u0 = <invalid>;
		ss->*((word32) sp_664 - 2) = ds_660;
		(ss->*((word32) sp_664 - 4)).u0 = 0x2591;
		Eq_5 si_683;
		Eq_5 di_679;
		Eq_5 ds_680;
		fn1E56_03F5(si_663, di_659, ds_660, ss->*((word32) sp_664 - 4), out si_683, out di_679, out ds_680);
		sp_650 = sp_664;
		si_698 = fn0800_2A2B(fp - 2, si_683, di_679, ds_680, out di_694, out ds_695);
	}
	word16 si_966;
	word16 di_967;
	fn1F3D_0259(si_698, di_694, ds_695, out si_966, out di_967, out ds_20);
	goto l1431_035C;
}

