[sdl]
fullscreen=false
fulldouble=false
fullresolution=640x480
windowresolution=640x480
output=surface
autolock=false
sensitivity=100
waitonerror=true
priority=higher,normal
usescancodes=true

[dosbox]
machine=svga_s3
memsize=16

[render]
frameskip=0
aspect=false
scaler=normal2x

[cpu]
core=auto
cputype=auto
cycles=auto
cycleup=10
cycledown=20

[mixer]
rate=44100
nosound=true

[speaker]
pcspeaker=false

[debug]
debug=high
logfile=/tmp/dosbox_debug_out.log

[autoexec]
@echo off
mount c /home/velteyn/projects/Reversing/AIATTEMPT
c:
UNBTECH.exe
