package com.btech;

import java.util.ArrayList;
import java.util.List;

public class GameStrings {
    public static final List<String> STRINGS = new ArrayList<>();

    static {
        STRINGS.add("Unskilled");
        STRINGS.add("Amateur");
        STRINGS.add("Adequate");
        STRINGS.add("Good");
        STRINGS.add("Excellent");
        STRINGS.add("North");
        STRINGS.add("Northeast");
        STRINGS.add("East");
        STRINGS.add("Southeast");
        STRINGS.add("South");
        STRINGS.add("Southwest");
        STRINGS.add("West");
        STRINGS.add("Northwest");
        STRINGS.add("Jason");
        STRINGS.add("Edward");
        STRINGS.add("Russ");
        STRINGS.add("Rick");
        STRINGS.add("Zeke");
        STRINGS.add("Possum");
        STRINGS.add("Marco");
        STRINGS.add("Rusty");
        STRINGS.add("Hunter");
        STRINGS.add("Hawk");
        STRINGS.add("Jason");
        STRINGS.add(" has died.  You cannot finish the game without him.");
        STRINGS.add("Do you want to play again?");
        STRINGS.add("Game0");
        STRINGS.add("The water is too deep that way.");
        STRINGS.add("Put the BattleTech ");
        STRINGS.add("Game Disk");
        STRINGS.add("Disk 2");
        STRINGS.add(" in ");
        STRINGS.add("the drive");
        STRINGS.add("drive A:");
        STRINGS.add("Press a key.");
        STRINGS.add("Change game settings");
        STRINGS.add("Allocate men in 'Mechs");
        STRINGS.add("Save Game");
        STRINGS.add("Show Overhead Map");
        STRINGS.add(".MTP");
        STRINGS.add("DESTRUCT.ICN");
        STRINGS.add("ANIMATE.ICN");
        STRINGS.add("Cancel");
        STRINGS.add("INFOCOM.CMP");
        STRINGS.add("Game saved is invalid. Use only games saved from this version.");
        STRINGS.add("Load game failed! File ");
        STRINGS.add(" not found. Press a key.");
        STRINGS.add("Cancel");
        STRINGS.add("INFOCOM.CMP");
        STRINGS.add("You can't save the game inside the map room.");
        STRINGS.add("You can inspect a man or a 'Mech.  Do you want to inspect a 'Mech?");
        STRINGS.add("Field Surgery Kit:");
        STRINGS.add("You don't like the way he's acting.  He makes you uneasy.");
        STRINGS.add("Armor ");
        STRINGS.add("has not been injured.");
        STRINGS.add("has lost ");
        STRINGS.add(" of its ");
        STRINGS.add(" protective points.");
        STRINGS.add("Turn Sound O");
        STRINGS.add("Cancel");
        STRINGS.add("Four steps");
        STRINGS.add("Keypress");
        STRINGS.add("Infrequently");
        STRINGS.add("Quitting will exit the game and return you to the system.  ");
        STRINGS.add("Are you sure you want to quit?");
        STRINGS.add(".MTP");
        STRINGS.add("Arrows to move, space to exit.");
        STRINGS.add("Press any key to return to game.");
        STRINGS.add("BTTLTECH.ICN");
        STRINGS.add("BTTITLE.CMP");
        STRINGS.add("WWOODBT.SIF");
        STRINGS.add(".ANM");
        STRINGS.add("It would be dangerous to dismount so close to a populated area.");
        STRINGS.add("\"BattleTech\" is a registered trademark of FASA corporation,  ");
        STRINGS.add("Board game, design, ");
        STRINGS.add("Is this your first time playing BattleTech?");
        STRINGS.add("You can load a previously saved game, or start a new game.  Do you want to load an old game?");
        STRINGS.add("DEMOFILE");
        STRINGS.add("INFOCOM.CMP");
        STRINGS.add("BTBORDER.CMP");
        STRINGS.add("TINYLAND.CMP");
        STRINGS.add("MECHSHAP.CMP");
        STRINGS.add("save games onto.");
        STRINGS.add("All files from both BattleTech disks should be in the current directory.");
        STRINGS.add("Your Saved Games will be saved onto your hard disk.");
        STRINGS.add(" and heat sinks");
        STRINGS.add(", heat sinks and weapons");
        STRINGS.add(", heat sinks, weapons and structure");
        STRINGS.add(" uses his tech training to scavenge armor");
        STRINGS.add(" from the enemy 'Mechs.");
        STRINGS.add("You are able to scrounge together ");
        STRINGS.add(" C-bills worth of scrap metal from the destroyed 'Mech");
        STRINGS.add("> is a qualified pilot without a 'Mech. Do you want to salvage one of the wrecks?");
        STRINGS.add(" is salvaging a X");
        STRINGS.add("No chance to salvage this X");
        STRINGS.add("There are no more salvageable 'Mechs on the battlefield.");
        STRINGS.add("You dig through the soldiers' pockets and find ");
        STRINGS.add(" C-bills in cash");
        STRINGS.add(", and confiscate their weapons");
        STRINGS.add("Do you want to drop your ");
        STRINGS.add(" in exchange for a ");
        STRINGS.add("Do you want the computer to fight for you?");
        STRINGS.add("Enemy human");
        STRINGS.add("Detail Scan");
        STRINGS.add("Done");
        STRINGS.add("None");
        STRINGS.add("Gone");
        STRINGS.add("BTSTATS.CMP");
        STRINGS.add("Armament   Loc");
        STRINGS.add("None");
        STRINGS.add("Unknown");
        STRINGS.add("Actuators");
        STRINGS.add("Right Arm");
        STRINGS.add("When you get outside, you decide to use your new ");
        STRINGS.add("holoviewer to watch your father's holodisk.");
        STRINGS.add("Other cadets snicker as you leave the training center.");
        STRINGS.add("Don't come back here until you complete your mission!");
        STRINGS.add("You've made it to the southeast corner.  Now get back to the training center!");
        STRINGS.add("You realize your Locust has no hands and can't pick it up.");
        STRINGS.add("You use your 'Mech's hands to retrieve the rubble.");
        STRINGS.add("You quickly scramble up the boarding ladders of this 'Mech, ");
        STRINGS.add("hoping that it will function when you get to the cockpit.");
        STRINGS.add("You flip the activation switch...");
        STRINGS.add("and the 'Mech starts up!");
        STRINGS.add("but this 'Mech refuses to start.");
        STRINGS.add("Give ");
        STRINGS.add("Armor points left: ");
        STRINGS.add("He already has that type of armor.");
        STRINGS.add("Give ");
        STRINGS.add("Drop it");
        STRINGS.add("He already has that weapon.");
        STRINGS.add("Nobody here seems interested in talking to you.");
        STRINGS.add("Done");
        STRINGS.add("Hi, Jason, how are you?  I just stopped in here to ");
        STRINGS.add("  After I'm done here, I'm going over to the ");
        STRINGS.add(" nothing this time.");
        STRINGS.add("engine.");
        STRINGS.add("gyro.");
        STRINGS.add("sensors.");
        STRINGS.add("Our facility doesn't have the equipment to fix your damaged ");
        STRINGS.add("That 'Mech looks shiny new to me.  It doesn't need anything fixed.");
        STRINGS.add("You don't have any C-bills.  ");
        STRINGS.add("Looks like this 'Mech has lost about ");
        STRINGS.add(" pieces of armor.  If you want those replaced, it's going to cost ");
        STRINGS.add(" C-bills.  You've got ");
        STRINGS.add("  Want it fixed?");
        STRINGS.add("We fixed as much as you could afford, but you ran out of cash before the job was done.");
        STRINGS.add("This 'Mech has had some of its internal structure damaged.");
        STRINGS.add("  If you want to fix any weapons or heat sinks, you have to have structure to mount them on.");
        STRINGS.add(" If you want the structure fixed, it's going to cost ");
        STRINGS.add(" C-bills.  You've got ");
        STRINGS.add("  Want it fixed?");
        STRINGS.add("We fixed as much as you could afford, but you ran out of cash before the job was done.");
        STRINGS.add("You've had ");
        STRINGS.add(" heat sink");
        STRINGS.add("   damaged.  We have a special on heat sinks this month: only 800 C-bills each!  You've got ");
        STRINGS.add("  Want to fix some heat sinks?");
        STRINGS.add("The job's not complete.  You need to come up with some cash before we can finish.");
        STRINGS.add("Here's your weapons estimate:");
        STRINGS.add("At 300 C-bills per item, what do you want to fix?");
        STRINGS.add("C-bills: ");
        STRINGS.add("All your weapons are fixed.");
        STRINGS.add("You're out of cash.");
        STRINGS.add("You've got some damaged actuators.  ");
        STRINGS.add("For 200 C-bills, we'll patch them all.");
        STRINGS.add("Is it a deal?");
        STRINGS.add("They're all patched up, good as new.");
        STRINGS.add("However, you don't have the 200 C-bills it takes to get them fixed.");
        STRINGS.add("Hey, that thing is already pretty powerful.  We can't modify that any further.");
        STRINGS.add("C-bills: ");
        STRINGS.add("All for the incredibly low price of only ");
        STRINGS.add(" C-bills.  Want to modify your 'Mech?");
        STRINGS.add("Your 'Mech is done.  It's waiting for you outside.");
        STRINGS.add("His name is ");
        STRINGS.add(" and he will be ");
        STRINGS.add("on foot.");
        STRINGS.add("riding as a passenger in ");
        STRINGS.add("'s 'Mech.");
        STRINGS.add("O0.ANM");
        STRINGS.add("Your ");
        STRINGS.add(" has maximum ammunition right now.");
        STRINGS.add(" could use some ammunition.  You've expended ");
        STRINGS.add("Reloads cost ");
        STRINGS.add(" C-bills each.  How many do you want to buy? ");
        STRINGS.add("That's more than you can carry for that weapon.  We'll max out your ammo.");
        STRINGS.add("You ran out of money before the ammo bay was full.");
        STRINGS.add("You don't have any functional weapons that require ammunition.");
        STRINGS.add("Some of your weaponry is damaged, so selling you ammunition for it would be a waste.");
        STRINGS.add("STARLEAG.ICN");
        STRINGS.add("Part of the hallway here crumbles away, revealing a secret passageway!");
        STRINGS.add("These boxes are full of 'Mech gyros!  The cache must be around here!");
        STRINGS.add("You have turned on the power to the Hyperpulse Generator.");
        STRINGS.add("BLUE");
        STRINGS.add("YELLOW");
        STRINGS.add("You've already used this terminal's code.");
        STRINGS.add("Do you want to imprint ");
        STRINGS.add(" code ");
        STRINGS.add(">It seems the power to these terminals is turned off.");
        STRINGS.add("Incorrect WHITE code.");
        STRINGS.add("You want to radio Katrina, but you haven't found the cache.");
        STRINGS.add("You already have the WHITE code.");
        STRINGS.add("You peer down the hole and see a huge map painted on the floor.");
        STRINGS.add("You climb down the ladder to investigate it.");
        STRINGS.add("MAP.ICN");
        STRINGS.add("MAP15.MTP");
        STRINGS.add("You easily scale the ladder back up to the Star League cache.");
        STRINGS.add("STARLEAG.ICN");
        STRINGS.add("You can trigger the HyperPulse Generator now.");
        STRINGS.add("Incorrect password.");
        STRINGS.add("Incorrect YELLOW code.");
        STRINGS.add("z{|}vwxyt");
        STRINGS.add("First Aid");
        STRINGS.add("Adv. First Aid");
        STRINGS.add("Field Surgery");
        STRINGS.add("Hospital Surgery");
        STRINGS.add("torn cloth strips");
        STRINGS.add("MedKit");
        STRINGS.add("Field Surgery Kit");
        STRINGS.add("Hospital Facilities");
        STRINGS.add("The doctor");
        STRINGS.add(" uses his ");
        STRINGS.add(" skill and his ");
        STRINGS.add(" fumbles with some bandages");
        STRINGS.add(" to assist the wounded.");
        STRINGS.add(" healing.");
        STRINGS.add("Nobody is wounded.");
        STRINGS.add("Your characters need more time to recover.");
        STRINGS.add("Nobody is wounded.");
        STRINGS.add("None");
        STRINGS.add("None");
        STRINGS.add("Not all of your 'Mechs have pilots.  ");
        STRINGS.add("You'll have to abandon any 'Mech that doesn't have a pilot.");
        STRINGS.add("Are you ready to abandon your nonpiloted 'Mechs?");
        STRINGS.add("Assign a pilot to each.");
        STRINGS.add(" is ");
        STRINGS.add("not ");
        STRINGS.add("a qualified 'Mech pilot.");
        STRINGS.add("None");
        STRINGS.add("Assign to this 'Mech as the pilot?");
        STRINGS.add("Something about ");
        STRINGS.add(" makes you uneasy about putting him in a 'Mech cockpit.");
        STRINGS.add("BTSTATS.CMP");
        STRINGS.add("Before you can go on a training mission, you will have to pass the written quiz.  Hopefully, you have studied your books.");
        STRINGS.add("Identify this 'Mech part:");
        STRINGS.add("That was miserable.  Study up before coming back here again.");
        STRINGS.add("This 'Mech has overheated and shut down.");
        STRINGS.add("This Mech's sensors are damaged. Accuracy is impaired.");
        STRINGS.add("This Mech's sensors are destroyed. It cannot fire its weapons.");
        STRINGS.add("Select the weapon to fire.");
        STRINGS.add("Ammo Target  Range");
        STRINGS.add("Destroyed");
        STRINGS.add("Full");
        STRINGS.add("Human");
        STRINGS.add("None");
        STRINGS.add("Done");
        STRINGS.add("Choose a different one.");
        STRINGS.add("Choose a different one.");
        STRINGS.add("That weapon is already going to be fired. Override?");
        STRINGS.add("Choose the enemy to shoot at:");
        STRINGS.add("You are using your ");
        STRINGS.add(" against a ");
        STRINGS.add("Human");
        STRINGS.add(" at ");
        STRINGS.add("Override?");
        STRINGS.add("against:");
        STRINGS.add("Target here Next enemy Cancel");
        STRINGS.add("Human      ");
        STRINGS.add("Mech is destroyed!");
        STRINGS.add("Men eject!");
        STRINGS.add("PBS@0T");
        STRINGS.add("@TOP@B");
        STRINGS.add("S looks like Death himself.");
        STRINGS.add(" amazingly, is still standing.");
        STRINGS.add(" can't take another hit.");
        STRINGS.add(" is bleeding pretty hard.");
        STRINGS.add(" has definitely been injured.");
        STRINGS.add(" is grimacing in pain.");
        STRINGS.add(" is showing some wear and tear.");
        STRINGS.add(" could use some bandages.");
        STRINGS.add(" is starting to get mad.");
        STRINGS.add(" is just getting warmed up.");
        STRINGS.add(" is the picture of health.");
        STRINGS.add("Short");
        STRINGS.add("Long");
        STRINGS.add("Cudgel");
        STRINGS.add("Knife");
        STRINGS.add("Sword");
        STRINGS.add("VibroBlade");
        STRINGS.add("Shortbow");
        STRINGS.add("Longbow");
        STRINGS.add("Crossbow");
        STRINGS.add("Pistol");
        STRINGS.add("Rifle");
        STRINGS.add("MachineGun");
        STRINGS.add("SR Missile");
        STRINGS.add("Inferno");
        STRINGS.add("LaserPistl");
        STRINGS.add("LaserRifle");
        STRINGS.add("Flamer");
        STRINGS.add("SmallLaser");
        STRINGS.add("Med Laser");
        STRINGS.add("LargeLaser");
        STRINGS.add("AutoCann/2");
        STRINGS.add("AutoCann/5");
        STRINGS.add("AutoCann10");
        STRINGS.add("AutoCann20");
        STRINGS.add("MachineGun");
        STRINGS.add("Flamer");
        STRINGS.add("LRMissile5");
        STRINGS.add("LRMissil10");
        STRINGS.add("LRMissil15");
        STRINGS.add("LRMissil20");
        STRINGS.add("SRMissile2");
        STRINGS.add("SRMissile4");
        STRINGS.add("SRMissile6");
        STRINGS.add("Kick      ");
        STRINGS.add("Critical!");
        STRINGS.add("Enemy human");
        STRINGS.add(" is squashed underfoot.");
        STRINGS.add("Left Torso");
        STRINGS.add("Left Leg");
        STRINGS.add("Left Arm");
        STRINGS.add("Left Rear Torso");
        STRINGS.add("Right Torso");
        STRINGS.add("Right Leg");
        STRINGS.add("Right Arm");
        STRINGS.add("Right Rear Torso");
        STRINGS.add("Center Torso");
        STRINGS.add("Head");
        STRINGS.add("Rear Center Torso");
        STRINGS.add("They're trying to actually kill you!  This is no training mission!");
        STRINGS.add("Those are Kurita 'Mechs!  You can see the Dragon symbol on them!");
        STRINGS.add("You look around and see the citadel has been destroyed!");
        STRINGS.add("Kuritans must have raided Pacifica and destroyed your army!");
        STRINGS.add("They broke down the southeast wall!");
        STRINGS.add(" 'Mech");
        STRINGS.add(" human");
        STRINGS.add("Engage in combat?");
        STRINGS.add("You did not evade them!");
        STRINGS.add("These 'Mechs are unlike any you've fought against.  You feel uneasy.");
        STRINGS.add("You cannot escape these Jenners!");
        STRINGS.add("You do not escape! The enemies engage in combat.");
        STRINGS.add("You watched ");
        STRINGS.add(" carefully, and saw that ");
        STRINGS.add(" the Dracos didn't shoot at him at all.  Under Rex's interrogation, ");
        STRINGS.add("which involved fists, it turns out that he was a Kurita ");
        STRINGS.add("double agent!  You put an end to that situation, to say the least.");
        STRINGS.add(" tried to turn and fire on you!  He's a Kurita double agent!  ");
        STRINGS.add("You were able to stop him, but it involved destroying the Mech he ");
        STRINGS.add("was piloting also.");
        STRINGS.add(" was able to stop him, but in the process he destroyed the Mech's ");
        STRINGS.add("cockpit.  He was able to eject in time, but the doublecrossing pilot didn't.");
        STRINGS.add(" was able to overcome him and throw him out the cockpit.  ");
        STRINGS.add("Then he took command of the Mech, but in the process he must have ");
        STRINGS.add("jolted the controls, because the Mech stepped on the doublecrosser.");
        STRINGS.add(" knew you were suspicious of him, and he tried to sabotage the Mech ");
        STRINGS.add("he was riding in.  He was a Kurita double agent!  ");
        STRINGS.add(" was able to overcome him, and threw the doublecrosser out the cockpit.  ");
        STRINGS.add("Then he \"accidentally\" stepped on him, to rid you of the problem.");
        STRINGS.add("Some of the enemy humans have fled!");
        STRINGS.add("The enemy humans have fled!");
        STRINGS.add("After an invigorating scuffle, you defeated the Kuritans.");
        STRINGS.add("You have eluded your enemies!");
        STRINGS.add("You return to where you were before combat took place.");
        STRINGS.add("You should return to base now.");
        STRINGS.add("Congratulations!  You have won!");
        STRINGS.add("The crowd boos resoundingly.  You have lost.");
        STRINGS.add("You have eluded your enemies!");
        STRINGS.add("The computer is currently moving this unit.");
        STRINGS.add("Begin Fight");
        STRINGS.add("Begin Fight");
        STRINGS.add("walk");
        STRINGS.add("jump");
        STRINGS.add("This mech is now ");
        STRINGS.add("ing.");
        STRINGS.add("Do you wish to ");
        STRINGS.add(" instead?");
        STRINGS.add("All your current movement orders have been deleted.");
        STRINGS.add("Press a key to enter new moves.");
        STRINGS.add("This 'Mech has no jump jets.");
        STRINGS.add("This 'Mech has overheated and shut down.");
        STRINGS.add("Movement is inhibited by ");
        STRINGS.add("this 'Mech's heat level.");
        STRINGS.add("You can't ");
        STRINGS.add("move");
        STRINGS.add(" any further this turn.");
        STRINGS.add("You might move farther if you tried running.");
        STRINGS.add("You have ");
        STRINGS.add(" movement points left.  Move the cursor to where you want to go.");
        STRINGS.add(">Choose the enemy to kick:");
        STRINGS.add("This 'Mech can't kick because it has damaged hips. Press a key.");
        STRINGS.add("Verbose");
        STRINGS.add("See combat graphics:");
        STRINGS.add("Cancel");
        STRINGS.add("Press a key.");
        STRINGS.add("Press a key.");
        STRINGS.add("There are no enemy humans in this battle.");
        STRINGS.add("'s Mech ");
        STRINGS.add("kicks");
        STRINGS.add("Kick");
        STRINGS.add("uses a ");
        STRINGS.add(" uses a ");
        STRINGS.add("An enemy ");
        STRINGS.add("human uses a ");
        STRINGS.add("Mech ");
        STRINGS.add("uses a ");
        STRINGS.add("kicks");
        STRINGS.add("Kick");
        STRINGS.add(" on ");
        STRINGS.add("'s Mech");
        STRINGS.add("an enemy ");
        STRINGS.add("Mech.");
        STRINGS.add("human.");
        STRINGS.add("a spectator.");
        STRINGS.add("Missed!");
        STRINGS.add("Hit!");
        STRINGS.add("Missed!");
        STRINGS.add("Hit ");
        STRINGS.add("Killed him!");
        STRINGS.add("Your 'Mech has destroyed part of the Arena!");
        STRINGS.add("Some Kurita UrbanMechs have been dispatched to kill you!");
        STRINGS.add("Intercooler");
        STRINGS.add("Hip Unit");
        STRINGS.add("Foot Unit");
        STRINGS.add("Weather Seal");
        STRINGS.add("Foot Casting");
        STRINGS.add("Foot Actuator");
        STRINGS.add("Shoulder Joint");
        STRINGS.add("Leg Mainshaft");
        STRINGS.add("Balance Strut");
        STRINGS.add("Armor Plating");
        STRINGS.add("Elbow Actuator");
        STRINGS.add("Myomer Bundle");
        STRINGS.add("Antennae Mount");
        STRINGS.add("Collective Strut");
        STRINGS.add("Stabilizer");
        STRINGS.add("Torso Mainframe");
        STRINGS.add("Jump Jet Intake");
        STRINGS.add("Heat Sink");
        STRINGS.add("Gyro Housing");
        STRINGS.add("Venting");
        STRINGS.add("go on a training mission.  Hey, you see that fool?  He took a Locust out on mission two!");
        STRINGS.add("hone some of my weapon skills in the combat class.");
        STRINGS.add("buy me some of that Baker stock.  I'll make a fortune if they don't go broke.");
        STRINGS.add("buy a new pistol.");
        STRINGS.add("get me one of those flak vests.");
        STRINGS.add("watch the men work, and see if I can't learn something.");
        STRINGS.add("catch up on my sleep.");
        STRINGS.add("boogie.");
        STRINGS.add("buy a MedKit.");
        STRINGS.add("watch some good 'Mech combat.");
        STRINGS.add("Go away, kid, you bother me.");
        STRINGS.add("Wait your turn.  I'll be done soon.  Kids these days...");
        STRINGS.add("Back offa me or I'll knock your block off.");
        STRINGS.add("Excuse me, but I'm trying to do something here.  Please go away.");
        STRINGS.add("I don't have time to chat about the weather.");
        STRINGS.add("What's the big idea, bumpin' into me like that?");
        STRINGS.add("Whatcha lookin' for, buried treasure?");
        STRINGS.add("Know what you need?  A good, swift kick... hey!  Come back here!");
        STRINGS.add("None");
        STRINGS.add("Flak Vest");
        STRINGS.add("Flak Suit");
        STRINGS.add("Lt Env Suit");
        STRINGS.add("Hv Env Suit");
        STRINGS.add("Ablative");
        STRINGS.add("completely unskilled");
        STRINGS.add("an amateur");
        STRINGS.add("competent");
        STRINGS.add("a whiz");
        STRINGS.add("a grand master");
        STRINGS.add(" in the use of bows and blades.  ");
        STRINGS.add(" when it comes to pistols and handguns.  ");
        STRINGS.add(" with a rifle or submachinegun.  ");
        STRINGS.add("TRAINING.BLD");
        STRINGS.add("CITADEL.BLD");
        STRINGS.add("COMSTAR.BLD");
        STRINGS.add("WEAPON.BLD");
        STRINGS.add("ARMOR.BLD");
        STRINGS.add("REPAIR.BLD");
        STRINGS.add("BARRACKS.BLD");
        STRINGS.add("LOUNGE.BLD");
        STRINGS.add("GARAGE.BLD");
        STRINGS.add("HOSPITAL.BLD");
        STRINGS.add("ARENA.BLD");
        STRINGS.add("PARTY.BLD");
        STRINGS.add("CLOTHES.BLD");
        STRINGS.add("JAIL.BLD");
        STRINGS.add("MAYOR.BLD");
        STRINGS.add("WEAPON2.BLD");
        STRINGS.add("THEATER.BLD");
        STRINGS.add("FROB.BLD");
        STRINGS.add("VIEWDISK.BLD");
        STRINGS.add("BARRACK2.BLD");
        STRINGS.add("ENTRANCE.BLD");
        STRINGS.add("HUT.BLD");
        STRINGS.add("ENDMECH.BLD");
        STRINGS.add("INSTRUCT.BLD");
        STRINGS.add("FINDIT.BLD");
        STRINGS.add("WINSCENE.BLD");
        STRINGS.add("Locust, the results are hardly surprising. ");
        STRINGS.add("Wasp");
        STRINGS.add("Chameleon");
        STRINGS.add(", the results are all the more impressive. ");
        STRINGS.add("By looking at your transcript, I see you are ");
        STRINGS.add("I'm afraid that we here can't possibly teach you any more than you already know.");
        STRINGS.add("I'm afraid you don't have enough C-bills for tuition.  ");
        STRINGS.add("None");
        STRINGS.add("You have no stock to sell.");
        STRINGS.add("Sell how much?  ");
        STRINGS.add("Stock account:");
        STRINGS.add("You don't have that much, but you sell all that you do have.");
        STRINGS.add("You have sold a total of ");
        STRINGS.add(" of ");
        STRINGS.add("stock, bringing your balance in that stock to ");
        STRINGS.add("You sell");
        STRINGS.add("You can't sell any stock you don't own!");
        STRINGS.add("You need some cash in your C-bill account before you can buy stock.");
        STRINGS.add("Invest in which stock?");
        STRINGS.add("Invest how much?  ");
        STRINGS.add("C-bill account:");
        STRINGS.add("You don't have that much, but you invest all that you do have.");
        STRINGS.add("You have invested a total of ");
        STRINGS.add(" in ");
        STRINGS.add("bringing your balance in that stock to ");
        STRINGS.add("You invest");
        STRINGS.add("Why, this armor looks brand new to me!  It doesn't need any repair.");
        STRINGS.add("This armor has lost ");
        STRINGS.add(" points");
        STRINGS.add(" of its protective capacity.  It would cost ");
        STRINGS.add(" C-bills to repair it, and you have ");
        STRINGS.add("  Do you want it repaired?");
        STRINGS.add("You did not have enough C-bills to ");
        STRINGS.add("finish the job, but we repaired all that you could afford.");
        STRINGS.add("get your armor patched.");
        STRINGS.add("There you are, sir, good as new!");
        STRINGS.add("Do you want to drop your ");
        STRINGS.add(" and take the Laser Rifle?");
        STRINGS.add("ENDMECH.CMP");
        STRINGS.add("STARLEAG.ICN");
        STRINGS.add("Come back when you can afford it.");
        STRINGS.add("Alloc too big!");
        STRINGS.add("Alloc: Null pointer return!");
        STRINGS.add("R;C_FILE_INFO");
        STRINGS.add("0<<NMSG>>");
        STRINGS.add("run-time error ");
    }

    // Categorized lists (heuristically detected)
    public static final String[] MECH_PARTS = {
        "Actuators",
        "Foot Actuator",
        "Shoulder Joint",
        "Balance Strut",
        "Armor Plating",
        "Elbow Actuator",
        "Myomer Bundle",
        "Antennae Mount",
        "Collective Strut",
        "Heat Sink",
        "Gyro Housing",
    };
}
