package com.btech;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;

public class StartupSequence extends JPanel {

    private enum State {
        BOOT_TEXT,
        SPLASH_INFOCOM,
        SPLASH_TITLE,
        FINISHED
    }

    private State currentState = State.BOOT_TEXT;
    private final Runnable onComplete;
    
    // Text Mode properties
    private List<String> textLines = new ArrayList<>();
    private int currentLineIndex = 0;
    private Timer textTimer;
    
    // Splash Screens
    private BufferedImage infocomImage;
    private BufferedImage titleImage;
    private Timer splashTimer;
    
    // Paths to assets (relative to project root usually, but we use absolute for dev)
    // Assuming running from C:\Reversing\AIATTEMPT
    private static final String ASSET_PATH = "Assets/";

    public StartupSequence(Runnable onComplete) {
        this.onComplete = onComplete;
        this.setBackground(Color.BLACK);
        this.setDoubleBuffered(true);
        this.setFocusable(true); // For key listener if we wanted to skip
        
        loadAssets();
        startBootSequence();
    }

    private void loadAssets() {
        try {
            // Using standard ImageIO to read BMPs generated by the C# tool
            File infocomFile = new File(ASSET_PATH + "INFOCOM.bmp");
            File titleFile = new File(ASSET_PATH + "BTTITLE.bmp");
            
            if (infocomFile.exists()) {
                infocomImage = ImageIO.read(infocomFile);
            } else {
                System.err.println("INFOCOM.bmp not found at " + infocomFile.getAbsolutePath());
            }
            
            if (titleFile.exists()) {
                titleImage = ImageIO.read(titleFile);
            } else {
                System.err.println("BTTITLE.bmp not found at " + titleFile.getAbsolutePath());
            }
            
        } catch (IOException e) {
            System.err.println("Failed to load splash screens: " + e.getMessage());
        }
    }

    private void startBootSequence() {
        // Simulate DOS boot messages
        textLines.add("Crescent Hawks Inception Loader v1.0");
        textLines.add("Copyright (c) 2025 AI Recreation Team");
        textLines.add("");
        textLines.add("System Check .................... OK");
        textLines.add("Memory Test ..................... 640K OK");
        textLines.add("");
        textLines.add("Select Graphics Adapter:");
        textLines.add("  1. CGA");
        textLines.add("  2. EGA");
        textLines.add("  3. Tandy");
        textLines.add("");
        textLines.add("Selection > 2"); // Auto-select EGA
        textLines.add("");
        textLines.add("Initializing EGA Graphics Mode...");
        textLines.add("Loading BATTLETECH.EXE...");
        
        // Timer to add lines one by one
        textTimer = new Timer(300, e -> {
            currentLineIndex++;
            repaint();
            
            if (currentLineIndex >= textLines.size()) {
                textTimer.stop();
                // Delay before switching to splash
                Timer delay = new Timer(1500, evt -> {
                    currentState = State.SPLASH_INFOCOM;
                    repaint();
                    startSplashTimer();
                });
                delay.setRepeats(false);
                delay.start();
            }
        });
        textTimer.start();
    }
    
    private void startSplashTimer() {
        // Show INFOCOM for 3 seconds
        splashTimer = new Timer(3000, e -> {
            if (currentState == State.SPLASH_INFOCOM) {
                currentState = State.SPLASH_TITLE;
                repaint();
                // Reset timer for Title screen (4 seconds)
                splashTimer.setInitialDelay(4000);
                splashTimer.restart();
            } else if (currentState == State.SPLASH_TITLE) {
                splashTimer.stop();
                currentState = State.FINISHED;
                if (onComplete != null) {
                    onComplete.run();
                }
            }
        });
        splashTimer.setRepeats(false);
        splashTimer.start();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        Graphics2D g2d = (Graphics2D) g;
        
        // Scale to window size (keep aspect ratio?)
        int w = getWidth();
        int h = getHeight();

        if (currentState == State.BOOT_TEXT) {
            g2d.setColor(Color.WHITE);
            g2d.setFont(new Font("Monospaced", Font.PLAIN, 16));
            
            int y = 30;
            for (int i = 0; i <= currentLineIndex && i < textLines.size(); i++) {
                g2d.drawString(textLines.get(i), 20, y);
                y += 20;
            }
            
            // Blinking cursor
            if (currentLineIndex < textLines.size()) {
                 // Simulate cursor?
            }
            
        } else if (currentState == State.SPLASH_INFOCOM) {
            drawScaledImage(g2d, infocomImage, w, h);
        } else if (currentState == State.SPLASH_TITLE) {
            drawScaledImage(g2d, titleImage, w, h);
        }
    }
    
    private void drawScaledImage(Graphics2D g2d, BufferedImage img, int w, int h) {
        if (img == null) {
            g2d.setColor(Color.RED);
            g2d.drawString("Image missing", w/2, h/2);
            return;
        }
        
        // Keep aspect ratio 320x200
        double scaleX = (double) w / 320.0;
        double scaleY = (double) h / 200.0;
        double scale = Math.min(scaleX, scaleY);
        
        int drawW = (int) (320 * scale);
        int drawH = (int) (200 * scale);
        int x = (w - drawW) / 2;
        int y = (h - drawH) / 2;
        
        g2d.drawImage(img, x, y, drawW, drawH, null);
    }
}
